### ISSUE TITLE
Question: Deepstream source code

### ISSUE THREAD

**Issue by ishangupta3** [marcoslucianops/DeepStream-Yolo#1]
Thanks for creating this repo; I was under the impression that the Nvidia deepstream sdk has to be edited in a c++ file. Here it seems that is not how the interaction with deep stream taking place. Any information to clear up my misconception will be helpful.

**Comment by marcoslucianops** [comment]
You can use DeepStream with [C++](https://docs.nvidia.com/metropolis/deepstream/dev-guide/index.html#page/DeepStream%2520Development%2520Guide%2Fdeepstream_quick_start.html%23wwpID0E2HA) or [Python](https://github.com/NVIDIA-AI-IOT/deepstream_python_apps). My repo shows how to compile DeepStream to use Yolo models. You need edit deepstream apps code (deepstream-test1, deepstream-test2, etc.) as you needed and use compiled files.

**Comment by ishangupta3** [comment]
If I use deepstream with Python, will that effect the performance issues compared to c++?

**Comment by ishangupta3** [comment]
Do you know where I can access the deepstream apps code (deepstream-test1, deepstream-2)files?

**Comment by marcoslucianops** [comment]
> If I use deepstream with Python, will that effect the performance issues compared to c++?

Is the same performance, but Python is more sintax friendly than C++.
In this video, I'm using Python: https://www.youtube.com/watch?v=n3uYS550PDo

> Do you know where I can access the deepstream apps code (deepstream-test1, deepstream-2)files?

C code is located in /opt/nvidia/deepstream/deepstream-4.0/sources/apps/sample_apps/
Python you need install from link: https://github.com/NVIDIA-AI-IOT/deepstream_python_apps

**Comment by ishangupta3** [comment]
Thank you Marcos for your help.
