### ISSUE TITLE
Yolov3-tiny-prn failing at launch of custom app

### ISSUE THREAD

**Issue by telemarketer** [marcoslucianops/DeepStream-Yolo#10]
I keep getting this error.
deepstream-app: yolo.cpp:141: NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&): Assertion `m_ConfigBlocks.at(i).at("activation") == "linear"' failed.
Aborted

Things i have done :
1) My weights and cfg files are prn and have been correctly labeled in the "infer config files.txt" file .
2) I have change the yolo.cpp file to the one in your repo.
3) I have installed deepstream 5.0 correctly as i have run other default apps by nvidia on it.
4) My camera is CSI and its working.

**Comment by marcoslucianops** [comment]
Hi,

> 2\. I have change the yolo.cpp file to the one in your repo.

I think you don't put yolo.cpp file in correct folder. Try put it again and recopile nvdsinfer_custom_impl_Yolo.
My yolo.cpp file doesn't have this assertion.
