### ISSUE TITLE
RAM is out of memory with Jetson Nano

### ISSUE THREAD

**Issue by SimonRenu** [marcoslucianops/DeepStream-Yolo#101]
When I run : 
`deepstream-app -c deepstream_app_config.txt`
Ram is out of memory and the Jetson crash...

**Comment by marcoslucianops** [comment]
Are you using batch-size > 1?

**Comment by SimonRenu** [comment]
> Are you using batch-size > 1?

No, I haven't change the batch-size...

**Comment by marcoslucianops** [comment]
This error is related to GPU memory. Are you using the 2GB Nano board?

**Comment by SimonRenu** [comment]
> This error is related to GPU memory. Are you using the 2GB Nano board?

No it is 4GB

**Comment by SimonRenu** [comment]
> This error is related to GPU memory. Are you using the 2GB Nano board?

I don't know how to check it but I think yes it is 2GB

**Comment by marcoslucianops** [comment]
Jetson boards use shared memory for CPU and GPU. Please run ```sudo tegrastats``` command and check the memory available.

**Comment by marcoslucianops** [comment]
You need to close the background processes to free the memory.
