### ISSUE TITLE
Error for  custom yolov3

### ISSUE THREAD

**Issue by SharathTUdelft** [marcoslucianops/DeepStream-Yolo#102]
I am using a custom yolov3 in deepstream 6. This is the error I get. The number of classes in my yolo is 5

WARNING: Num classes mismatch. Configured: 5, detected by network: 0
python3: nvdsparsebbox_Yolo.cpp:342: bool NvDsInferParseYoloV2(const std::vector<NvDsInferLayerInfo>&, const NvDsInferNetworkInfo&, const NvDsInferParseDetectionParams&, std::vector<NvDsInferObjectDetectionInfo>&, std::vector<float>&, const uint&): Assertion `layer.inferDims.numDims == 3' failed.
Aborted

**Comment by marcoslucianops** [comment]
can you send me the files to test?

**Comment by SharathTUdelft** [comment]
I unfortunately cant share the files. But the yolo we are working on is based on https://github.com/ultralytics/yolov3. Any we are suing the deepstream python apps to run it

**Comment by marcoslucianops** [comment]
This repo supports only Darknet based model for now.

**Comment by SharathTUdelft** [comment]
For the previous versions of deepstream this method worked for YOLO from ultralytics. When can we expect support for ultralytic YOLO models for deepstream6?

**Comment by marcoslucianops** [comment]
I'm working on native support for PyTorch models. I think it will be available untill January.

**Comment by marcoslucianops** [comment]
Repo updated with native support for ultralytics YOLOv5 model.

**Comment by SharathTUdelft** [comment]
It works!! Thank you for the update to custom yolov5]
