### ISSUE TITLE
Issue in nvdsinfer_impl_Yolo/layers/activation_layer.cpp

### ISSUE THREAD

**Issue by gherodes** [marcoslucianops/DeepStream-Yolo#103]
When running the command `CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo` on the Jetson platform an error is raised by **nvdsinfer_impl_Yolo/layers/activation_layer.cpp** 
It seems that adding `#include <iostream>`  fixed it though

**Comment by marcoslucianops** [comment]
Fixed, thank you.
