### ISSUE TITLE
Unable to Compile Deepstream-yolo on Jetson with Deepstream 6.0 container

### ISSUE THREAD

**Issue by vpramo** [marcoslucianops/DeepStream-Yolo#104]
Hi , 

I followed the instructions mentioned in the readme, I installed the deepstream 6.0 l4t sample container and then cloned your repo and tried to build , i get the following error

/opt/nvidia/deepstream/deepstream-6.0/DeepStream-Yolo# CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo
make: Entering directory '/opt/nvidia/deepstream/deepstream-6.0/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'
g++ -c  -o nvdsinfer_yolo_engine.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsinfer_yolo_engine.cpp
In file included from nvdsinfer_yolo_engine.cpp:28:0:
yoloPlugins.h:81:9: error: 'int YoloLayer::enqueue(int, const void* const*, void* const*, void*, cudaStream_t)' marked 'override', but does not override
     int enqueue (
         ^~~~~~~
yoloPlugins.h: In member function 'virtual nvinfer1::IPluginV2* YoloLayerPluginCreator::deserializePlugin(const char*, const void*, size_t)':
yoloPlugins.h:137:54: error: invalid new-expression of abstract class type 'YoloLayer'
         return new YoloLayer(serialData, serialLength);
                                                      ^
yoloPlugins.h:55:7: note:   because the following virtual functions are pure within 'YoloLayer':
 class YoloLayer : public nvinfer1::IPluginV2
       ^~~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInferRuntime.h:59:0,
                 from /usr/include/aarch64-linux-gnu/NvInfer.h:53,
                 from /usr/include/aarch64-linux-gnu/NvCaffeParser.h:53,
                 from /opt/nvidia/deepstream/deepstream/sources/includes/nvdsinfer_custom_impl.h:126,
                 from nvdsinfer_yolo_engine.cpp:26:
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:492:17: note: 	virtual int nvinfer1::IPluginV2::enqueue(int, const void* const*, void**, void*, cudaStream_t)
     virtual int enqueue(int batchSize, const void* const* inputs, void** outputs, void* workspace, cudaStream_t stream) TRTNOEXCEPT = 0;
                 ^~~~~~~
Makefile:80: recipe for target 'nvdsinfer_yolo_engine.o' failed
make: *** [nvdsinfer_yolo_engine.o] Error 1
make: Leaving directory '/opt/nvidia/deepstream/deepstream-6.0/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'

**Comment by marcoslucianops** [comment]
Hi, please test with development container: nvcr.io/nvidia/deepstream:6.0-devel

**Comment by vpramo** [comment]
But There is no devel container for l4t , i.e jetson

**Comment by vpramo** [comment]
I was able to install deepstream natively on jetson, and that worked , Thanks so much

**Comment by marcoslucianops** [comment]
For Jetson, I think you should use the nvcr.io/nvidia/deepstream-l4t:6.0-samples container if you want to use docker.
