### ISSUE TITLE
CUDA failure: too many resources requested for launch in file yoloPlugins.cpp at line 149

### ISSUE THREAD

**Issue by znawaz** [marcoslucianops/DeepStream-Yolo#105]
I am having a Nvidia Jetson Nano with 4GB. I have used your repository successfully with out any problem on my device. The latest update has broken the working on my device. I am using YoloV4-tiny on the current update and its error. I have installed DeepStream 6.0. The error is as follows:

`**PERF:  FPS 0 (Avg)	
**PERF:  0.00 (0.00)	
** INFO: <bus_callback:194>: Pipeline ready

Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
** INFO: <bus_callback:180>: Pipeline running

CUDA failure: too many resources requested for launch in file yoloPlugins.cpp at line 149
Aborted (core dumped)
`

Luckily, I have kept the last version of your repository and it is still working with out any issue.

**Comment by marcoslucianops** [comment]
Hi, I updated the repo, please check if it will fix the problem.

**Comment by znawaz** [comment]
Thanks, it is working again
