### ISSUE TITLE
libnvdsgst_meta.so

### ISSUE THREAD

**Issue by ONNONS** [marcoslucianops/DeepStream-Yolo#106]
Help

The libnvdsgst_meta.so file exists in the lib folder. But when I run deepstream-app it doesn't find it

**Comment by marcoslucianops** [comment]
Are you using Jetson or x86 platform?

**Comment by ONNONS** [comment]
Jetson  nano!

**Comment by ONNONS** [comment]
"./install.sh" It was solved by doing so, but this error occurred.

** ERROR: <parse_config_file:536>: parse_config_file failed
** ERROR: main:630: Failed to parse config file

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/issues/107
