### ISSUE TITLE
help..........

### ISSUE THREAD

**Issue by ONNONS** [marcoslucianops/DeepStream-Yolo#107]
sorry..;;

** ERROR: <parse_config_file:536>: parse_config_file failed
** ERROR: <main:630>: Failed to parse config file '

**Comment by marcoslucianops** [comment]
you are using the command incorrectly

**Comment by ONNONS** [comment]
I'm really sorry, but please explain it a little easier.

**Comment by marcoslucianops** [comment]
Send the full log from terminal, please

**Comment by ONNONS** [comment]
![Screenshot from 2021-12-13 09-55-20](https://user-images.githubusercontent.com/65228677/145737067-02b2027c-da58-4023-a534-ef4275a43eee.png)

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo#basic-usage

**Comment by ONNONS** [comment]
ok i did as you described but i still get the erro
![Screenshot from 2021-12-13 10-31-07](https://user-images.githubusercontent.com/65228677/145739179-9652cde5-c4ef-4643-a989-740b444aadd9.png)
r

**Comment by marcoslucianops** [comment]
Please attach your deepstream_app_config.txt and config_infer_primary_yoloV5.txt files.
