### ISSUE TITLE
How to integrate a generated yolov4 engine in Deepstream 6 samples (deepstream-preprocess-test for example)

### ISSUE THREAD

**Issue by SimonRenu** [marcoslucianops/DeepStream-Yolo#109]
I have some difficulties to incorporate the engine in the sample mentioned above. 
I think I need to integrate libs but don't know how...
Could you help?
Thank you !

**Comment by marcoslucianops** [comment]
For the deepstream-preprocess-test sample it won't able to work because it uses a tensor meta model as primary inference.

For others samples, you just need to use


C:
```
g_object_set(G_OBJECT(pgie), "config-file-path", "path_to_the_config_infer_file", NULL);
```

Python:
```
pgie.set_property("config-file-path", "path_to_the_config_infer_file")
```

**Comment by Xinxinatg** [comment]
By any chance do you know whether I need add dynamic link library compiled through nvdsinfer_custom_impl_Yolo apart from this setting?

**Comment by Xinxinatg** [comment]
in this [issue](https://github.com/zhouyuchong/yolov5-deepstream-python/issues/2), it seems like libmyplugins.so needs to be generated using https://github.com/wang-xinyu/tensorrtx

**Comment by chengzihencai** [comment]
Hi, I am the author of the issue you mentioned, and I recommend that when you use different deployment methods to operate according to the project author's operating procedures.

**Comment by Xinxinatg** [comment]
> Hi, I am the author of the issue you mentioned, and I recommend that when you use different deployment methods to operate according to the project author's operating procedures.

thanks! I followed the instruction in current repo and succeded to run the program in deepstream:)
