### ISSUE TITLE
Yolov5 FP16 engine TensorRT model was not faster than FP32

### ISSUE THREAD

**Issue by BTVinh0409** [marcoslucianops/DeepStream-Yolo#112]
Hi,
I tried converting yolov5l.pt model to FP32 TensorRT engine. It works well and the FPS is around 60. But when I try to convert to FP16 it doesn't seem to increase the FPS any further. And both exported models have the same size. Maybe I did something wrong?

**Comment by mfoglio** [comment]
Is it possible that your GPU does not support FP16 inference?

**Comment by juanfeyero** [comment]
I have the same issue with Yolov4, when I change to FP16, the file size is the same like FP32 and the FPS are the same on both.

**Comment by mfoglio** [comment]
What GPU are you using?

**Comment by juanfeyero** [comment]
I am using the Jetson AGX Xavier.

**Comment by BTVinh0409** [comment]
hi @mfoglio, I am using RTX 2080 and it supports FP16 inference. Can you provide the FPS when you inference FP32 and FP16 models? Thank you so much

**Comment by marcoslucianops** [comment]
I will check it

**Comment by juanfeyero** [comment]
I noticed that the same issue happens when you already have the calib.table and you build the engine on INT8.

**Comment by DavidBaldsiefen** [comment]
Any update? I have the same issue here, but maybe I am missing something. I am running a custom yolor-csp model and get around 20fps on the Jetson AGX Xavier. Changing `network-mode` from 0 to 1 does not change the fps at all

**Comment by marcoslucianops** [comment]
I need more days to check, I'm full of work these days.

**Comment by pakike** [comment]
I fixed this bug by following the link below:

https://forums.developer.nvidia.com/t/deepstream-6-yolo-performance-issue/194238/22

Mainly you have to modify this files:
yolo.cpp
yolo.h
nvdsinfer_yolo_engine.cpp

**Comment by pakike** [comment]
Just only put the new line in the file, for example for yolo.cpp you need delete this line and put the new line.

- nvinfer1::ICudaEngine *Yolo::createEngine (nvinfer1::IBuilder* builder)
+nvinfer1::ICudaEngine *Yolo::createEngine (
+   nvinfer1::IBuilder* builder, nvinfer1::IBuilderConfig* config)

**Comment by georgetsu** [comment]
I confirm, after steps mentioned by Pakike engine model size for FP16 decreased which caused FPS increased to normal like in DS5.1 version.

**Comment by marcoslucianops** [comment]
Thank you @pakike, I confirmed the issue and updated the repo.
