### ISSUE TITLE
Error to generate wts file

### ISSUE THREAD

**Issue by juanfeyero** [marcoslucianops/DeepStream-Yolo#113]
I followed the step. I installed PyTorch 1.7.0. But, it showed me the following error when I run :
`python3 gen_wts_yolor.py -w yolor_csp.pt -c cfg/yolor_csp.cfg`
Traceback (most recent call last):
  File "gen_wts_yolor.py", line 5, in <module>
    from utils.torch_utils import select_device
ModuleNotFoundError: No module named 'utils'

Please help me.

**Comment by marcoslucianops** [comment]
you need to copy the gen_wts_yolor.py to the yolor folder
