### ISSUE TITLE
Custom metadata

### ISSUE THREAD

**Issue by SashaAlderson** [marcoslucianops/DeepStream-Yolo#115]
I am using YOLOv5 example that takes camera as input and ouputs inference results as rtsp stream. If i want to use my custom metadata and print it out in OSD, i need to go to the ../apps-common/src and change /deepstream_osd_bin.c ? Is there another way to display my data on the rtsp stream using your example? All examples that i found suggested to run custom deepstream_test_app.

**Comment by marcoslucianops** [comment]
About metadata, I recommend you to search in NVIDIA forums or DeepStream documentation.

**Comment by SashaAlderson** [comment]
Thanks. Seems like, custom DS is a more suitable way of solving this problem.
