### ISSUE TITLE
Not utilizing tensor cores

### ISSUE THREAD

**Issue by IvensaMDH** [marcoslucianops/DeepStream-Yolo#117]
Hi,

I'm using DS6 with Yolov5 and am unable to see any tensor core activity using either FP16 or 32.
Tested on RTX3060 and T4.

sample pipeline:

`gst-launch-1.0 uridecodebin uri="file://test.mp4" ! nvvideoconvert ! "video/x-raw(memory:NVMM), format=NV12, width=640, height=640" ! m.sink_0 nvstreammux name="m" batch-size=1 ! nvinfer config-file-path="config_infer_primary_yoloV5.txt" ! fakesink`

Is this a known limitation or have I missed something..?

Thanks,

/M

**Comment by marcoslucianops** [comment]
The Tensor Cores isn't related to FP16/FP32 mode.

**Comment by IvensaMDH** [comment]
> The Tensor Cores isn't related to FP16/FP32 mode.

I see - do you have any suggestions as to why the tensor cores are not utilized? Could it be related to the FPS issues discussed in #114 ?

Thanks,

/M

**Comment by marcoslucianops** [comment]
I think the Tensor Cores are used only in model training.
