### ISSUE TITLE
How can i access object and save to jpg file in deepstream-test5-app

### ISSUE THREAD

**Issue by phonPtan** [marcoslucianops/DeepStream-Yolo#12]
in deepstream-test5-app i can't find tiler_src_pad_buffer_probe() so in bbox_generated_probe_after_analytics() can do it

**Comment by marcoslucianops** [comment]
deepstream-test5-app uses deepstream-app code. It's different from the others test-apps (is more difficult than the others). Your code need be implemented in deepstream-app code.

**Comment by phonPtan** [comment]
hi,  in deepstream-app code how can i save frame has object detection in analytics_done_buf_prob() function

**Comment by marcoslucianops** [comment]
deepstream-app doesn't have analytics_done_buf_prob(). You need add your function after image processing with metadata calls.

If you only want to save images, you better use [dsexample](https://forums.developer.nvidia.com/t/how-to-crop-the-image-and-save/80174#5375174).

**Comment by phonPtan** [comment]
i want to save image in deepstream-app, and put path of this image to label metada, in deepstream test5app i will custom event metadata for build json message kalka

**Comment by phonPtan** [comment]
i have seen analytics_done_buf_prob() in deepstream_app.c

**Comment by phonPtan** [comment]
> deepstream-app doesn't have analytics_done_buf_prob(). You need add your function after image processing with metadata calls.
> 
> If you only want to save images, you better use [dsexample](https://forums.developer.nvidia.com/t/how-to-crop-the-image-and-save/80174#5375174).

are you give me an example, thank so much

**Comment by marcoslucianops** [comment]
> i have seen analytics_done_buf_prob() in deepstream_app.c

I think you can't get image in deeepstream_app.c because it doesn't have an image return function.

> are you give me an example, thank so much

dsexample can be used in deepstream-app. You need edit and compile it, and add in deepstream_config.txt.
dsexample uses opencv to convert image, and, in this function, you can add save image function.

/opt/nvidia/deepstream/deepstream-5.0/sources/gst-plugins/gst-dsexample/gstdsexample.cpp
```
...
cv::cvtColor (in_mat, *dsexample->cvmat, cv::COLOR_RGBA2BGR);
...
```
