### ISSUE TITLE
Can be used with Deepstram v5.1

### ISSUE THREAD

**Issue by leviethung2103** [marcoslucianops/DeepStream-Yolo#121]
Hello, 

I just found this new repo. I am wondering if the Yolov5 can be used with Deepstream v5.1? 

Thank you in advance.

**Comment by marcoslucianops** [comment]
For YOLOv5 support, using this repo, it should use DeepStream 6.0.

**Comment by marcoslucianops** [comment]
Added support for DeepStream 5.1
