### ISSUE TITLE
"deepstream-app -c deepstream_app_config.txt" Error

### ISSUE THREAD

**Issue by ToNi981004** [marcoslucianops/DeepStream-Yolo#122]
0:00:55.834807440 18287 0x55a793990680 WARN                 nvinfer gstnvinfer.cpp:2288:gst_nvinfer_output_loop:<primary_gie> error: Internal data stream error.
0:00:55.834842482 18287 0x55a793990680 WARN                 nvinfer gstnvinfer.cpp:2288:gst_nvinfer_output_loop:<primary_gie> error: streaming stopped, reason not-negotiated (-4)
ERROR from primary_gie: Internal data stream error.
Debug info: gstnvinfer.cpp(2288): gst_nvinfer_output_loop (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
streaming stopped, reason not-negotiated (-4)
Quitting
ERROR from sink_bin_queue: Internal data stream error.
Debug info: gstqueue.c(988): gst_queue_handle_sink_event (): /GstPipeline:pipeline/GstBin:processing_bin_0/GstBin:sink_bin/GstQueue:sink_bin_queue:
streaming stopped, reason not-negotiated (-4)
ERROR from qtdemux0: Internal data stream error.
Debug info: qtdemux.c(6073): gst_qtdemux_loop (): /GstPipeline:pipeline/GstBin:multi_src_bin/GstBin:src_sub_bin0/GstURIDecodeBin:src_elem/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0:
streaming stopped, reason not-negotiated (-4)
App run failed

**Comment by marcoslucianops** [comment]
This error seems related to your source stream.
