### ISSUE TITLE
I got error in make

### ISSUE THREAD

**Issue by kks-bakaneko** [marcoslucianops/DeepStream-Yolo#123]
Hi, when I execute make I got error how can I solve it?
here's full log

g++ -c -o yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I../includes -I/usr/local/cuda-10.2/include yolo.cpp
In file included from yolo.cpp:24:0:
yoloPlugins.h:74:9: error: ‘int YoloLayerV3::enqueue(int, const void* const*, void* const*, void*, cudaStream_t)’ marked override’, but does not override
     int enqueue (
         ^~~~~~~
yoloPlugins.h: In member function ‘virtual nvinfer1::IPluginV2* YoloLayerV3PluginCreator::deserializePlugin(const char*, const void*, size_t)’:
yoloPlugins.h:122:56: error: invalid new-expression of abstract class type ‘YoloLayerV3’
         return new YoloLayerV3(serialData, serialLength);
                                                        ^
yoloPlugins.h:50:7: note:   because the following virtual functions are pure within ‘YoloLayerV3’:
 class YoloLayerV3 : public nvinfer1::IPluginV2
       ^~~~~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInferRuntime.h:59:0,
                 from /usr/include/aarch64-linux-gnu/NvInfer.h:53,
                 from yolo.h:31,
                 from yolo.cpp:23:
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:492:17: note: 	virtual int nvinfer1::IPluginV2::enqueue(int, const void* const*, void**, void*, cudaStream_t)
     virtual int enqueue(int batchSize, const void* const* inputs, void** outputs, void* workspace, cudaStream_t stream) TRTNOEXCEPT = 0;
                 ^~~~~~~
yolo.cpp: In member function ‘nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*)’:
yolo.cpp:72:12: error: ‘virtual nvinfer1::IBuilderConfig::~IBuilderConfig()’ is protected within this context
     delete config;
            ^~~~~~
In file included from yolo.h:31:0,
                 from yolo.cpp:23:
/usr/include/aarch64-linux-gnu/NvInfer.h:6692:13: note: declared protected here
     virtual ~IBuilderConfig()
             ^
yolo.cpp: In member function ‘NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&)’:
yolo.cpp:178:81: error: invalid new-expression of abstract class type ‘YoloLayerV3’
                                   m_OutputTensors.at(outputTensorCount).gridSize);
                                                                                 ^
Makefile:50: recipe for target 'yolo.o' failed
make: *** [yolo.o] Error 1

**Comment by DavidBaldsiefen** [comment]
Same here on a Jetson with JetPack 4.5.1, did you get it fixed? What is your TensorRT version?

**Comment by marcoslucianops** [comment]
This repo works only with JetPack 4.6 and DeepStream 6.0.

**Comment by youngjae-avikus** [comment]
I'm curious why this project relies on jetpack 4.6. What code or package is it dependent on?

**Comment by marcoslucianops** [comment]
#### For Jetson boards

CUDA 10.2
TensorRT 8.0.1 / 8.2.1
cuDNN 8.2.1
DeepStream SDK 6.0 / 6.1

**Comment by JasonChao-yue** [comment]
> Hi, when I execute make I got error how can I solve it? here's full log
> 
> g++ -c -o yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I../includes -I/usr/local/cuda-10.2/include yolo.cpp In file included from yolo.cpp:24:0: yoloPlugins.h:74:9: error: ‘int YoloLayerV3::enqueue(int, const void* const*, void* const*, void*, cudaStream_t)’ marked override’, but does not override int enqueue ( ^~~~~~~ yoloPlugins.h: In member function ‘virtual nvinfer1::IPluginV2* YoloLayerV3PluginCreator::deserializePlugin(const char*, const void*, size_t)’: yoloPlugins.h:122:56: error: invalid new-expression of abstract class type ‘YoloLayerV3’ return new YoloLayerV3(serialData, serialLength); ^ yoloPlugins.h:50:7: note: because the following virtual functions are pure within ‘YoloLayerV3’: class YoloLayerV3 : public nvinfer1::IPluginV2 ^~~~~~~~~~~ In file included from /usr/include/aarch64-linux-gnu/NvInferRuntime.h:59:0, from /usr/include/aarch64-linux-gnu/NvInfer.h:53, from yolo.h:31, from yolo.cpp:23: /usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:492:17: note: virtual int nvinfer1::IPluginV2::enqueue(int, const void* const*, void**, void*, cudaStream_t) virtual int enqueue(int batchSize, const void* const* inputs, void** outputs, void* workspace, cudaStream_t stream) TRTNOEXCEPT = 0; ^~~~~~~ yolo.cpp: In member function ‘nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*)’: yolo.cpp:72:12: error: ‘virtual nvinfer1::IBuilderConfig::~IBuilderConfig()’ is protected within this context delete config; ^~~~~~ In file included from yolo.h:31:0, from yolo.cpp:23: /usr/include/aarch64-linux-gnu/NvInfer.h:6692:13: note: declared protected here virtual ~IBuilderConfig() ^ yolo.cpp: In member function ‘NvDsInferStatus Yolo::buildYoloNetwork(std::vector&, nvinfer1::INetworkDefinition&)’: yolo.cpp:178:81: error: invalid new-expression of abstract class type ‘YoloLayerV3’ m_OutputTensors.at(outputTensorCount).gridSize); ^ Makefile:50: recipe for target 'yolo.o' failed make: *** [yolo.o] Error 1

Hello, has this problem been solved?

**Comment by marcoslucianops** [comment]
> Hello, has this problem been solved?

The repo is updated, please check with the new files.
