### ISSUE TITLE
cuda 10.2  error: ‘int YoloLayer::enqueue(int, const void* const*, void* const*, void*, cudaStream_t)’ marked ‘override’, but does not override

### ISSUE THREAD

**Issue by nowaylv** [marcoslucianops/DeepStream-Yolo#127]
g++ -c  -o nvdsinfer_yolo_engine.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsinfer_yolo_engine.cpp
In file included from nvdsinfer_yolo_engine.cpp:28:0:
yoloPlugins.h:81:9: error: ‘int YoloLayer::enqueue(int, const void* const*, void* const*, void*, cudaStream_t)’ marked ‘override’, but does not override
     int enqueue (
         ^~~~~~~
yoloPlugins.h: In member function ‘virtual nvinfer1::IPluginV2* YoloLayerPluginCreator::deserializePlugin(const char*, const void*, size_t)’:
yoloPlugins.h:137:54: error: invalid new-expression of abstract class type ‘YoloLayer’
         return new YoloLayer(serialData, serialLength);
                                                      ^
yoloPlugins.h:55:7: note:   because the following virtual functions are pure within ‘YoloLayer’:
 class YoloLayer : public nvinfer1::IPluginV2
       ^~~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInferRuntime.h:59:0,
                 from /usr/include/aarch64-linux-gnu/NvInfer.h:53,
                 from /usr/include/aarch64-linux-gnu/NvCaffeParser.h:53,
                 from /opt/nvidia/deepstream/deepstream/sources/includes/nvdsinfer_custom_impl.h:128,
                 from nvdsinfer_yolo_engine.cpp:26:
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:492:17: note:     virtual int nvinfer1::IPluginV2::enqueue(int, const void* const*, void**, void*, cudaStream_t)
     virtual int enqueue(int batchSize, const void* const* inputs, void** outputs, void* workspace, cudaStream_t stream) TRTNOEXCEPT = 0;
                 ^~~~~~~
Makefile:83: recipe for target 'nvdsinfer_yolo_engine.o' failed
make: *** [nvdsinfer_yolo_engine.o] Error 1

**Comment by marcoslucianops** [comment]
are you using Jetson or x86 platform?

**Comment by nowaylv** [comment]
> are you using Jetson or x86 platform?

usign agx

**Comment by marcoslucianops** [comment]
Are you using JetPack 4.6? I'm without Jetson boards to test here.
