### ISSUE TITLE
pipeline error

### ISSUE THREAD

**Issue by seungyong0313** [marcoslucianops/DeepStream-Yolo#129]
help me plz

Using winsys: x11 
ERROR: Could not open lib: /home/iisl/Desktop/deepstream-6.0/sources/DeepStream-Yolo-master/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so, error string: /home/iisl/Desktop/deepstream-6.0/sources/DeepStream-Yolo-master/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so: cannot open shared object file: No such file or directory
0:00:00.232566051 12720     0x33f3aa10 ERROR                nvinfer gstnvinfer.cpp:632:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1248> [UID = 1]: Could not open custom lib: (null)
0:00:00.232649231 12720     0x33f3aa10 WARN                 nvinfer gstnvinfer.cpp:841:gst_nvinfer_start:<primary_gie> error: Failed to create NvDsInferContext instance
0:00:00.232674284 12720     0x33f3aa10 WARN                 nvinfer gstnvinfer.cpp:841:gst_nvinfer_start:<primary_gie> error: Config file path: /home/iisl/Desktop/deepstream-6.0/sources/DeepStream-Yolo-master/config_infer_primary_yoloV5.txt, NvDsInfer Error: NVDSINFER_CUSTOM_LIB_FAILED
** ERROR: <main:658>: Failed to set pipeline to PAUSED
Quitting
ERROR from primary_gie: Failed to create NvDsInferContext instance
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvinfer/gstnvinfer.cpp(841): gst_nvinfer_start (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
Config file path: /home/iisl/Desktop/deepstream-6.0/sources/DeepStream-Yolo-master/config_infer_primary_yoloV5.txt, NvDsInfer Error: NVDSINFER_CUSTOM_LIB_FAILED
App run failed

**Comment by marcoslucianops** [comment]
Please install DeepStream in default location /opt/nvidia or change the include path in Makefile before compile it.

**Comment by seungyong0313** [comment]
T_T

default location /opt/nvidia 

Using winsys: x11 
ERROR: Could not open lib: /nvdsinfer_custom_impl_Yolo, error string: /nvdsinfer_custom_impl_Yolo: cannot open shared object file: No such file or directory
0:00:00.240395870  9557     0x1ba8a640 ERROR                nvinfer gstnvinfer.cpp:632:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1248> [UID = 1]: Could not open custom lib: (null)
0:00:00.240476236  9557     0x1ba8a640 WARN                 nvinfer gstnvinfer.cpp:841:gst_nvinfer_start:<primary_gie> error: Failed to create NvDsInferContext instance
0:00:00.240500664  9557     0x1ba8a640 WARN                 nvinfer gstnvinfer.cpp:841:gst_nvinfer_start:<primary_gie> error: Config file path: /opt/nvidia/deepstream/deepstream-6.0/sources/wf6_yolov5/config_infer_primary_yoloV5.txt, NvDsInfer Error: NVDSINFER_CUSTOM_LIB_FAILED
** ERROR: <main:658>: Failed to set pipeline to PAUSED
Quitting
ERROR from primary_gie: Failed to create NvDsInferContext instance
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvinfer/gstnvinfer.cpp(841): gst_nvinfer_start (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
Config file path: /opt/nvidia/deepstream/deepstream-6.0/sources/wf6_yolov5/config_infer_primary_yoloV5.txt, NvDsInfer Error: NVDSINFER_CUSTOM_LIB_FAILED
App run failed
root@iisl-desktop:/opt/nvidia/deepstream/deepstream-6.0/sources/wf6_yolov5#

**Comment by chengzihencai** [comment]
hi，have you solved this problem?I have the problem too。

**Comment by marcoslucianops** [comment]
Please send the output log related to your issue.

**Comment by chengzihencai** [comment]
I've fixed the issue and it seems that something went wrong with some of my versions that caused the error.And auout issue 215,you said I can send you my model and common file vim email.My email is caiOrange@outlook.com.
