### ISSUE TITLE
Do I need to add parse function when I deal with other yolov5 models?

### ISSUE THREAD

**Issue by theiot** [marcoslucianops/DeepStream-Yolo#13]
Hi,

From your yolov5 FAQ,  I'm aware something need to be changed with the config files. My question is, do I need to add functions to parse the model's data in nvdsparsebbox_Yolo.cpp? And how to do so? 

Thanks,

**Comment by marcoslucianops** [comment]
Hi, I didn't understand what you need. Do you want know how to run model or how to get processed metada?

**Comment by theiot** [comment]
> Hi, I didn't understand what you need. Do you want know how to run model or how to get processed metada?



> Hi, I didn't understand what you need. Do you want know how to run model or how to get processed metada?

Hi, 

Thank you for your prompt replay.

In your /examples/yolov5s/nvdsinfer_custom_impl_Yolo/nvdsparsebbox_Yolo.cpp file, there is a function named：NvDsInferParseCustomYoloV5(), I think it can parse yolov5s meta data. If I want to parse v5m or v5x, can I just use this function or I need create a new one specific for v5m/v5x?

**Comment by marcoslucianops** [comment]
Do you need only TensorRT converted model to use with other yolov5 model, the nvdsparsebbox_Yolo.cpp file is the same of yolov5s.

Metadata is processed stream/video data. It's location of bbox, label of detected object, etc. To get this data, you need knowledge to edit deepstream code (Python or C).

**Comment by theiot** [comment]
Got it, thank you for your confirmation.

**Comment by marcoslucianops** [comment]
@theiot, I updated and simplified [YOLOv5.md](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/YOLOv5.md).
