### ISSUE TITLE
Building the TensorRT Engine error for yolov5 p6.is something error in my step?

### ISSUE THREAD

**Issue by tms2003** [marcoslucianops/DeepStream-Yolo#132]
I run yolov5 p6 version's deepstream. and I get this error:
```
Loading pre-trained weights
Loading weights of yolov5m6 complete
Total weights read: 35785980
Building YOLO network

      layer                        input               output         weightPtr
(0)   conv_silu                  3 x1280 x1280      48 x 640 x 640    5376   
(1)   conv_silu                 48 x 640 x 640      96 x 320 x 320    47232  
(2)   conv_silu                 96 x 320 x 320      48 x 320 x 320    52032  
(3)   route                           -             96 x 320 x 320    52032  
(4)   conv_silu                 96 x 320 x 320      48 x 320 x 320    56832  
(5)   conv_silu                 48 x 320 x 320      48 x 320 x 320    59328  
(6)   conv_silu                 48 x 320 x 320      48 x 320 x 320    80256  
(7)   shortcut_linear: 4              -             48 x 320 x 320        -  
(8)   conv_silu                 48 x 320 x 320      48 x 320 x 320    82752  
(9)   conv_silu                 48 x 320 x 320      48 x 320 x 320    103680 
(10)  shortcut_linear: 7              -             48 x 320 x 320        -  
(11)  route                           -             96 x 320 x 320    103680 
(12)  conv_silu                 96 x 320 x 320      96 x 320 x 320    113280 
(13)  conv_silu                 96 x 320 x 320     192 x 160 x 160    279936 
(14)  conv_silu                192 x 160 x 160      96 x 160 x 160    298752 
(15)  route                           -            192 x 160 x 160    298752 
(16)  conv_silu                192 x 160 x 160      96 x 160 x 160    317568 
(17)  conv_silu                 96 x 160 x 160      96 x 160 x 160    327168 
(18)  conv_silu                 96 x 160 x 160      96 x 160 x 160    410496 
(19)  shortcut_linear: 16             -             96 x 160 x 160        -  
(20)  conv_silu                 96 x 160 x 160      96 x 160 x 160    420096 
(21)  conv_silu                 96 x 160 x 160      96 x 160 x 160    503424 
(22)  shortcut_linear: 19             -             96 x 160 x 160        -  
(23)  conv_silu                 96 x 160 x 160      96 x 160 x 160    513024 
(24)  conv_silu                 96 x 160 x 160      96 x 160 x 160    596352 
(25)  shortcut_linear: 22             -             96 x 160 x 160        -  
(26)  conv_silu                 96 x 160 x 160      96 x 160 x 160    605952 
(27)  conv_silu                 96 x 160 x 160      96 x 160 x 160    689280 
(28)  shortcut_linear: 25             -             96 x 160 x 160        -  
(29)  route                           -            192 x 160 x 160    689280 
(30)  conv_silu                192 x 160 x 160     192 x 160 x 160    726912 
(31)  conv_silu                192 x 160 x 160     384 x  80 x  80    1392000
(32)  conv_silu                384 x  80 x  80     192 x  80 x  80    1466496
(33)  route                           -            384 x  80 x  80    1466496
(34)  conv_silu                384 x  80 x  80     192 x  80 x  80    1540992
(35)  conv_silu                192 x  80 x  80     192 x  80 x  80    1578624
(36)  conv_silu                192 x  80 x  80     192 x  80 x  80    1911168
(37)  shortcut_linear: 34             -            192 x  80 x  80        -  
(38)  conv_silu                192 x  80 x  80     192 x  80 x  80    1948800
(39)  conv_silu                192 x  80 x  80     192 x  80 x  80    2281344
(40)  shortcut_linear: 37             -            192 x  80 x  80        -  
(41)  conv_silu                192 x  80 x  80     192 x  80 x  80    2318976
(42)  conv_silu                192 x  80 x  80     192 x  80 x  80    2651520
(43)  shortcut_linear: 40             -            192 x  80 x  80        -  
(44)  conv_silu                192 x  80 x  80     192 x  80 x  80    2689152
(45)  conv_silu                192 x  80 x  80     192 x  80 x  80    3021696
(46)  shortcut_linear: 43             -            192 x  80 x  80        -  
(47)  conv_silu                192 x  80 x  80     192 x  80 x  80    3059328
(48)  conv_silu                192 x  80 x  80     192 x  80 x  80    3391872
(49)  shortcut_linear: 46             -            192 x  80 x  80        -  
(50)  conv_silu                192 x  80 x  80     192 x  80 x  80    3429504
(51)  conv_silu                192 x  80 x  80     192 x  80 x  80    3762048
(52)  shortcut_linear: 49             -            192 x  80 x  80        -  
(53)  route                           -            384 x  80 x  80    3762048
(54)  conv_silu                384 x  80 x  80     384 x  80 x  80    3911040
(55)  conv_silu                384 x  80 x  80     768 x  40 x  40    6568320
(56)  conv_silu                768 x  40 x  40     384 x  40 x  40    6864768
(57)  route                           -            768 x  40 x  40    6864768
(58)  conv_silu                768 x  40 x  40     384 x  40 x  40    7161216
(59)  conv_silu                384 x  40 x  40     384 x  40 x  40    7310208
(60)  conv_silu                384 x  40 x  40     384 x  40 x  40    8638848
(61)  shortcut_linear: 58             -            384 x  40 x  40        -  
(62)  conv_silu                384 x  40 x  40     384 x  40 x  40    8787840
(63)  conv_silu                384 x  40 x  40     384 x  40 x  40    10116480
(64)  shortcut_linear: 61             -            384 x  40 x  40        -  
(65)  route                           -            768 x  40 x  40    10116480
(66)  conv_silu                768 x  40 x  40     768 x  40 x  40    10709376
(67)  conv_silu                768 x  40 x  40     384 x  40 x  40    11005824
(68)  maxpool                  384 x  40 x  40     384 x  40 x  40    11005824
(69)  route                           -            384 x  40 x  40    11005824
(70)  maxpool                  384 x  40 x  40     384 x  40 x  40    11005824
(71)  route                           -            384 x  40 x  40    11005824
(72)  maxpool                  384 x  40 x  40     384 x  40 x  40    11005824
(73)  route                           -           1536 x  40 x  40    11005824
(74)  conv_silu               1536 x  40 x  40     768 x  40 x  40    12188544
(75)  conv_silu                768 x  40 x  40     384 x  40 x  40    12484992
(76)  upsample                 384 x  40 x  40     384 x  80 x  80        -  
(77)  route                           -            768 x  80 x  80    12484992
(78)  conv_silu                768 x  80 x  80     192 x  80 x  80    12633216
(79)  route                           -            768 x  80 x  80    12633216
(80)  conv_silu                768 x  80 x  80     192 x  80 x  80    12781440
(81)  conv_silu                192 x  80 x  80     192 x  80 x  80    12819072
(82)  conv_silu                192 x  80 x  80     192 x  80 x  80    13151616
(83)  conv_silu                192 x  80 x  80     192 x  80 x  80    13189248
(84)  conv_silu                192 x  80 x  80     192 x  80 x  80    13521792
(85)  route                           -            384 x  80 x  80    13521792
(86)  conv_silu                384 x  80 x  80     384 x  80 x  80    13670784
(87)  conv_silu                384 x  80 x  80     192 x  80 x  80    13745280
(88)  upsample                 192 x  80 x  80     192 x 160 x 160        -  
(89)  route                           -            384 x 160 x 160    13745280
(90)  conv_silu                384 x 160 x 160      96 x 160 x 160    13782528
(91)  route                           -            384 x 160 x 160    13782528
(92)  conv_silu                384 x 160 x 160      96 x 160 x 160    13819776
(93)  conv_silu                 96 x 160 x 160      96 x 160 x 160    13829376
(94)  conv_silu                 96 x 160 x 160      96 x 160 x 160    13912704
(95)  conv_silu                 96 x 160 x 160      96 x 160 x 160    13922304
(96)  conv_silu                 96 x 160 x 160      96 x 160 x 160    14005632
(97)  route                           -            192 x 160 x 160    14005632
(98)  conv_silu                192 x 160 x 160     192 x 160 x 160    14043264
(99)  conv_silu                192 x 160 x 160     192 x  80 x  80    14375808
(100) route                           -            384 x  80 x  80    14375808
(101) conv_silu                384 x  80 x  80     192 x  80 x  80    14450304
(102) route                           -            384 x  80 x  80    14450304
(103) conv_silu                384 x  80 x  80     192 x  80 x  80    14524800
(104) conv_silu                192 x  80 x  80     192 x  80 x  80    14562432
(105) conv_silu                192 x  80 x  80     192 x  80 x  80    14894976
(106) conv_silu                192 x  80 x  80     192 x  80 x  80    14932608
(107) conv_silu                192 x  80 x  80     192 x  80 x  80    15265152
(108) route                           -            384 x  80 x  80    15265152
(109) conv_silu                384 x  80 x  80     384 x  80 x  80    15414144
(110) conv_silu                384 x  80 x  80     384 x  40 x  40    16742784
(111) route                           -            768 x  40 x  40    16742784
(112) conv_silu                768 x  40 x  40     384 x  40 x  40    17039232
(113) route                           -            768 x  40 x  40    17039232
(114) conv_silu                768 x  40 x  40     384 x  40 x  40    17335680
(115) conv_silu                384 x  40 x  40     384 x  40 x  40    17484672
(116) conv_silu                384 x  40 x  40     384 x  40 x  40    18813312
(117) conv_silu                384 x  40 x  40     384 x  40 x  40    18962304
(118) conv_silu                384 x  40 x  40     384 x  40 x  40    20290944
(119) route                           -            768 x  40 x  40    20290944
(120) conv_silu                768 x  40 x  40     768 x  40 x  40    20883840
(121) route                           -            192 x 160 x 160    20883840
(122) conv_logistic            192 x 160 x 160     255 x 160 x 160    20933055
(123) yolo                     255 x 160 x 160     255 x 160 x 160    20933055
(124) route                           -            384 x  80 x  80    20933055
(125) conv_logistic            384 x  80 x  80     255 x  80 x  80    21031230
(126) yolo                     255 x  80 x  80     255 x  80 x  80    21031230
(127) route                           -            768 x  40 x  40    21031230
(128) conv_logistic            768 x  40 x  40     255 x  40 x  40    21227325
(129) yolo                     255 x  40 x  40     255 x  40 x  40    21227325
Number of unused weights left: 14558655
deepstream-app: yolo.cpp:421: NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&): Assertion `0' failed.
Aborted (core dumped)
```

My deepstream's version is 6.0,and the Deepstream-Yolo is ok for yolov5 p5(640).

I generate cfg and wts file like this:
python3 gen_wts_yoloV5.py  -w /root/source/third/yolov5/weights/yolov5m6.pt -c ./models/yolov5m.yaml --p6

[yolov5m6.cfg.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/7939407/yolov5m6.cfg.txt)

Is something error in my steps?

**Comment by seungyong0313** [comment]
> I run yolov5 p6 version's deepstream. and I get this error:
> 
> ```
> Loading pre-trained weights
> Loading weights of yolov5m6 complete
> Total weights read: 35785980
> Building YOLO network
> 
>       layer                        input               output         weightPtr
> (0)   conv_silu                  3 x1280 x1280      48 x 640 x 640    5376   
> (1)   conv_silu                 48 x 640 x 640      96 x 320 x 320    47232  
> (2)   conv_silu                 96 x 320 x 320      48 x 320 x 320    52032  
> (3)   route                           -             96 x 320 x 320    52032  
> (4)   conv_silu                 96 x 320 x 320      48 x 320 x 320    56832  
> (5)   conv_silu                 48 x 320 x 320      48 x 320 x 320    59328  
> (6)   conv_silu                 48 x 320 x 320      48 x 320 x 320    80256  
> (7)   shortcut_linear: 4              -             48 x 320 x 320        -  
> (8)   conv_silu                 48 x 320 x 320      48 x 320 x 320    82752  
> (9)   conv_silu                 48 x 320 x 320      48 x 320 x 320    103680 
> (10)  shortcut_linear: 7              -             48 x 320 x 320        -  
> (11)  route                           -             96 x 320 x 320    103680 
> (12)  conv_silu                 96 x 320 x 320      96 x 320 x 320    113280 
> (13)  conv_silu                 96 x 320 x 320     192 x 160 x 160    279936 
> (14)  conv_silu                192 x 160 x 160      96 x 160 x 160    298752 
> (15)  route                           -            192 x 160 x 160    298752 
> (16)  conv_silu                192 x 160 x 160      96 x 160 x 160    317568 
> (17)  conv_silu                 96 x 160 x 160      96 x 160 x 160    327168 
> (18)  conv_silu                 96 x 160 x 160      96 x 160 x 160    410496 
> (19)  shortcut_linear: 16             -             96 x 160 x 160        -  
> (20)  conv_silu                 96 x 160 x 160      96 x 160 x 160    420096 
> (21)  conv_silu                 96 x 160 x 160      96 x 160 x 160    503424 
> (22)  shortcut_linear: 19             -             96 x 160 x 160        -  
> (23)  conv_silu                 96 x 160 x 160      96 x 160 x 160    513024 
> (24)  conv_silu                 96 x 160 x 160      96 x 160 x 160    596352 
> (25)  shortcut_linear: 22             -             96 x 160 x 160        -  
> (26)  conv_silu                 96 x 160 x 160      96 x 160 x 160    605952 
> (27)  conv_silu                 96 x 160 x 160      96 x 160 x 160    689280 
> (28)  shortcut_linear: 25             -             96 x 160 x 160        -  
> (29)  route                           -            192 x 160 x 160    689280 
> (30)  conv_silu                192 x 160 x 160     192 x 160 x 160    726912 
> (31)  conv_silu                192 x 160 x 160     384 x  80 x  80    1392000
> (32)  conv_silu                384 x  80 x  80     192 x  80 x  80    1466496
> (33)  route                           -            384 x  80 x  80    1466496
> (34)  conv_silu                384 x  80 x  80     192 x  80 x  80    1540992
> (35)  conv_silu                192 x  80 x  80     192 x  80 x  80    1578624
> (36)  conv_silu                192 x  80 x  80     192 x  80 x  80    1911168
> (37)  shortcut_linear: 34             -            192 x  80 x  80        -  
> (38)  conv_silu                192 x  80 x  80     192 x  80 x  80    1948800
> (39)  conv_silu                192 x  80 x  80     192 x  80 x  80    2281344
> (40)  shortcut_linear: 37             -            192 x  80 x  80        -  
> (41)  conv_silu                192 x  80 x  80     192 x  80 x  80    2318976
> (42)  conv_silu                192 x  80 x  80     192 x  80 x  80    2651520
> (43)  shortcut_linear: 40             -            192 x  80 x  80        -  
> (44)  conv_silu                192 x  80 x  80     192 x  80 x  80    2689152
> (45)  conv_silu                192 x  80 x  80     192 x  80 x  80    3021696
> (46)  shortcut_linear: 43             -            192 x  80 x  80        -  
> (47)  conv_silu                192 x  80 x  80     192 x  80 x  80    3059328
> (48)  conv_silu                192 x  80 x  80     192 x  80 x  80    3391872
> (49)  shortcut_linear: 46             -            192 x  80 x  80        -  
> (50)  conv_silu                192 x  80 x  80     192 x  80 x  80    3429504
> (51)  conv_silu                192 x  80 x  80     192 x  80 x  80    3762048
> (52)  shortcut_linear: 49             -            192 x  80 x  80        -  
> (53)  route                           -            384 x  80 x  80    3762048
> (54)  conv_silu                384 x  80 x  80     384 x  80 x  80    3911040
> (55)  conv_silu                384 x  80 x  80     768 x  40 x  40    6568320
> (56)  conv_silu                768 x  40 x  40     384 x  40 x  40    6864768
> (57)  route                           -            768 x  40 x  40    6864768
> (58)  conv_silu                768 x  40 x  40     384 x  40 x  40    7161216
> (59)  conv_silu                384 x  40 x  40     384 x  40 x  40    7310208
> (60)  conv_silu                384 x  40 x  40     384 x  40 x  40    8638848
> (61)  shortcut_linear: 58             -            384 x  40 x  40        -  
> (62)  conv_silu                384 x  40 x  40     384 x  40 x  40    8787840
> (63)  conv_silu                384 x  40 x  40     384 x  40 x  40    10116480
> (64)  shortcut_linear: 61             -            384 x  40 x  40        -  
> (65)  route                           -            768 x  40 x  40    10116480
> (66)  conv_silu                768 x  40 x  40     768 x  40 x  40    10709376
> (67)  conv_silu                768 x  40 x  40     384 x  40 x  40    11005824
> (68)  maxpool                  384 x  40 x  40     384 x  40 x  40    11005824
> (69)  route                           -            384 x  40 x  40    11005824
> (70)  maxpool                  384 x  40 x  40     384 x  40 x  40    11005824
> (71)  route                           -            384 x  40 x  40    11005824
> (72)  maxpool                  384 x  40 x  40     384 x  40 x  40    11005824
> (73)  route                           -           1536 x  40 x  40    11005824
> (74)  conv_silu               1536 x  40 x  40     768 x  40 x  40    12188544
> (75)  conv_silu                768 x  40 x  40     384 x  40 x  40    12484992
> (76)  upsample                 384 x  40 x  40     384 x  80 x  80        -  
> (77)  route                           -            768 x  80 x  80    12484992
> (78)  conv_silu                768 x  80 x  80     192 x  80 x  80    12633216
> (79)  route                           -            768 x  80 x  80    12633216
> (80)  conv_silu                768 x  80 x  80     192 x  80 x  80    12781440
> (81)  conv_silu                192 x  80 x  80     192 x  80 x  80    12819072
> (82)  conv_silu                192 x  80 x  80     192 x  80 x  80    13151616
> (83)  conv_silu                192 x  80 x  80     192 x  80 x  80    13189248
> (84)  conv_silu                192 x  80 x  80     192 x  80 x  80    13521792
> (85)  route                           -            384 x  80 x  80    13521792
> (86)  conv_silu                384 x  80 x  80     384 x  80 x  80    13670784
> (87)  conv_silu                384 x  80 x  80     192 x  80 x  80    13745280
> (88)  upsample                 192 x  80 x  80     192 x 160 x 160        -  
> (89)  route                           -            384 x 160 x 160    13745280
> (90)  conv_silu                384 x 160 x 160      96 x 160 x 160    13782528
> (91)  route                           -            384 x 160 x 160    13782528
> (92)  conv_silu                384 x 160 x 160      96 x 160 x 160    13819776
> (93)  conv_silu                 96 x 160 x 160      96 x 160 x 160    13829376
> (94)  conv_silu                 96 x 160 x 160      96 x 160 x 160    13912704
> (95)  conv_silu                 96 x 160 x 160      96 x 160 x 160    13922304
> (96)  conv_silu                 96 x 160 x 160      96 x 160 x 160    14005632
> (97)  route                           -            192 x 160 x 160    14005632
> (98)  conv_silu                192 x 160 x 160     192 x 160 x 160    14043264
> (99)  conv_silu                192 x 160 x 160     192 x  80 x  80    14375808
> (100) route                           -            384 x  80 x  80    14375808
> (101) conv_silu                384 x  80 x  80     192 x  80 x  80    14450304
> (102) route                           -            384 x  80 x  80    14450304
> (103) conv_silu                384 x  80 x  80     192 x  80 x  80    14524800
> (104) conv_silu                192 x  80 x  80     192 x  80 x  80    14562432
> (105) conv_silu                192 x  80 x  80     192 x  80 x  80    14894976
> (106) conv_silu                192 x  80 x  80     192 x  80 x  80    14932608
> (107) conv_silu                192 x  80 x  80     192 x  80 x  80    15265152
> (108) route                           -            384 x  80 x  80    15265152
> (109) conv_silu                384 x  80 x  80     384 x  80 x  80    15414144
> (110) conv_silu                384 x  80 x  80     384 x  40 x  40    16742784
> (111) route                           -            768 x  40 x  40    16742784
> (112) conv_silu                768 x  40 x  40     384 x  40 x  40    17039232
> (113) route                           -            768 x  40 x  40    17039232
> (114) conv_silu                768 x  40 x  40     384 x  40 x  40    17335680
> (115) conv_silu                384 x  40 x  40     384 x  40 x  40    17484672
> (116) conv_silu                384 x  40 x  40     384 x  40 x  40    18813312
> (117) conv_silu                384 x  40 x  40     384 x  40 x  40    18962304
> (118) conv_silu                384 x  40 x  40     384 x  40 x  40    20290944
> (119) route                           -            768 x  40 x  40    20290944
> (120) conv_silu                768 x  40 x  40     768 x  40 x  40    20883840
> (121) route                           -            192 x 160 x 160    20883840
> (122) conv_logistic            192 x 160 x 160     255 x 160 x 160    20933055
> (123) yolo                     255 x 160 x 160     255 x 160 x 160    20933055
> (124) route                           -            384 x  80 x  80    20933055
> (125) conv_logistic            384 x  80 x  80     255 x  80 x  80    21031230
> (126) yolo                     255 x  80 x  80     255 x  80 x  80    21031230
> (127) route                           -            768 x  40 x  40    21031230
> (128) conv_logistic            768 x  40 x  40     255 x  40 x  40    21227325
> (129) yolo                     255 x  40 x  40     255 x  40 x  40    21227325
> Number of unused weights left: 14558655
> deepstream-app: yolo.cpp:421: NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&): Assertion `0' failed.
> Aborted (core dumped)
> ```
> 
> My deepstream's version is 6.0,and the Deepstream-Yolo is ok for yolov5 p5(640).
> 
> I generate cfg and wts file like this: python3 gen_wts_yoloV5.py -w /root/source/third/yolov5/weights/yolov5m6.pt -c ./models/yolov5m.yaml --p6
> 
> [yolov5m6.cfg.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/7939407/yolov5m6.cfg.txt)
> 
> Is something error in my steps?

**I also get the same error. I haven't been able to find the cause for a week...**

**Comment by alex7smart** [comment]
Use the appropriate yaml `-c ./models/hub/yolov5m6.yaml`

**Comment by ONNONS** [comment]
> Use the appropriate yaml `-c ./models/hub/yolov5m6.yaml`

I did it your way but it still fails. I think it's a make file creation error.

**Comment by marcoslucianops** [comment]
This repo works for YOLOv5 6.0 version (latest version of ultralytics YOLOv5). Please check your model and use the correct yaml file during conversion.

**Comment by tms2003** [comment]
> This repo works for YOLOv5 6.0 version (latest version of ultralytics YOLOv5). Please check your model and use the correct yaml file during conversion.

ok,hub/yolov5m6.yaml can work for me ,thanks!it's can closed!
