### ISSUE TITLE
Do I need to modify the code ?

### ISSUE THREAD

**Issue by ONNONS** [marcoslucianops/DeepStream-Yolo#135]
python3 gen_wts_yoloV5.py -w yolov5n.pt -c ./models/hub/yolov5-p34.yaml
YOLOv5 🚀 2022-2-11 torch 1.9.0 CPU

Traceback (most recent call last):
  File "gen_wts_yoloV5.py", line 131, in <module>
    for v in f[l]:
TypeError: 'int' object is not iterable

**Comment by marcoslucianops** [comment]
There's something wrong in yolov5-p34.yaml file. Can you share it?

**Comment by marcoslucianops** [comment]
Please use the new utils/gen_wts_yoloV5.py to convert your model. I saw that your model has 2 classes, please change the yolov5-p34.yaml file before conversion

```
nc: 80
```

to

```
nc: 2
```

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/issues/136
