### ISSUE TITLE
Does DS support Windows and consumer GTX, RTX cards?

### ISSUE THREAD

**Issue by haquocviet** [marcoslucianops/DeepStream-Yolo#139]
Thanks for your work.
I am curious if the DeepStream supports Windows and consumer Nvidia cards.

**Comment by marcoslucianops** [comment]
It doesn't support Windows, but it supports consumer Nvidia cards. See the requirements:

### Requirements

* [Ubuntu 18.04](https://releases.ubuntu.com/18.04.6/)
* [CUDA 11.4.3](https://developer.nvidia.com/cuda-toolkit)
* [TensorRT 8.0 GA (8.0.1)](https://developer.nvidia.com/tensorrt)
* [cuDNN >= 8.2](https://developer.nvidia.com/cudnn)
* [NVIDIA Driver >= 470.63.01](https://www.nvidia.com.br/Download/index.aspx)

**Comment by haquocviet** [comment]
Thanks @marcoslucianops
