### ISSUE TITLE
How can I get NMS_THRESH and CONF_THRESH inferenced from config files

### ISSUE THREAD

**Issue by theiot** [marcoslucianops/DeepStream-Yolo#14]
@marcoslucianops 

Hi, I want to make nvdsparsebbox_Yolo more flexible by remove：

static const int NUM_CLASSES_YOLO = 80; 
#define NMS_THRESH 0.45
#define CONF_THRESH 0.25

Right now I just cannot get  NMS_THRESH from config file "config_infer_primary_yoloV5s.txt:
[class-attrs-all]
nms-iou-threshold=0.45
pre-cluster-threshold=0.25

Do you have any suggestion?

Thanks,

**Comment by marcoslucianops** [comment]
Hi, i'm working on it now (parse some fuctions based on cfg and config.txt file) and I will update the repo soon.

I tested the mAP and FPS in some YOLO models, and I recommend you see my readme.md. YOLOv4 performs better when compared to YOLOv5 on TensorRT/DeepStream.

**Comment by theiot** [comment]
> Hi, i'm working on it now (parse some fuctions based on cfg and config.txt file) and I will update the repo soon.
> 
> I tested the mAP and FPS in some YOLO models, and I recommend you see my readme.md. YOLOv4 performs better when compared to YOLOv5 on TensorRT/DeepStream.
> 
> With my files, you can directly convert YOLOv4 to DeepStream TensorRT model.

Glad to hear and looking forward to it.

**Comment by marcoslucianops** [comment]
CONF_THRESH (pre-cluster-threshold)
```
const float kCONF_THRESH = detectionParams.perClassThreshold[0];
```

NUM_CLASSES_YOLO (num-detected-classes)
```
const uint kNUM_CLASSES = detectionParams.numClassesConfigured;
```

NMS_THRESH cannot be obtained from config.txt file in current DeepStream code.
