### ISSUE TITLE
Benchmarks up to date? Comparison with YOLOR/YOLOv5 official repositories

### ISSUE THREAD

**Issue by remi-sh** [marcoslucianops/DeepStream-Yolo#144]
Hi,

Are the YOLOR and YOLOv5 benchmarks (in the ReadMe) up to date?

Performance seems still several percents lower than the official repositories (e.g. AP at 0.478 vs 0.541 for YOLOR-P6 and 0.492 vs 0.537 for YOLOv5l6).

Also, should there be a significant speed improvement with FP16 on dGPU? I'm getting less than 10% speedup (RTX 3090).

**Comment by marcoslucianops** [comment]
> Are the YOLOR and YOLOv5 benchmarks (in the ReadMe) up to date?

No, I will update them in next days, but the mAP should be similar as it is now.

> Performance seems still several percents lower than the official repositories (e.g. AP at 0.478 vs 0.541 for YOLOR-P6 and 0.492 vs 0.537 for YOLOv5l6).

Yes, there's a degradation. I think it's normal in model conversion, but if you check the results are very similar comparing YOLOv5 models in DeepStream and PyTorch (ultralytics) even the mAP being lower. Maybe my evaluation code isn't precise, I will check in the next days too.

> Also, should there be a significant speed improvement with FP16 on dGPU? I'm getting less than 10% speedup (RTX 3090).

I don't have available x86 GPU with FP16 support for now. In next days I will try to use an RTX 3080 to do the tests.

**Comment by remi-sh** [comment]
Thanks for your answers.

>Yes, there's a degradation. I think it's normal in model conversion, but if you check the results are very similar comparing YOLOv5 models in DeepStream and PyTorch (ultralytics) even the mAP being lower.

True that visually, the COCO pretrained models give very similar results. 
Actually I'm using a custom dataset and DeepStream results are much worse (both YOLOv5 and YOLOR). I don't have this issue with Ultralitics' TensorRT converted model by the way.

**Comment by marcoslucianops** [comment]
Please change the yolo.cpp file (line 178) from

```
eps = 1.0e-3;

```

to

```
eps = 1.0e-5;

```

Recompile, remove the old engine file, and check the results again with your custom model.

**Comment by remi-sh** [comment]
No visible improvement, unfortunately.

Any reason for this change especially?

**Comment by marcoslucianops** [comment]
TensorRTx repo uses ```eps = 1.0e-3``` and ultralytics repo uses ```eps = 1.0e-5```.

**Comment by marcoslucianops** [comment]
I'm adding the benchmarks with the new updates: https://github.com/marcoslucianops/DeepStream-Yolo#benchmarks

**Comment by remi-sh** [comment]
Thanks for the update. Will there be YOLOR benchmarks too?

**Comment by marcoslucianops** [comment]
Yes, I will add soon.
