### ISSUE TITLE
Fps

### ISSUE THREAD

**Issue by ONNONS** [marcoslucianops/DeepStream-Yolo#146]
I use jetsonnano

How many fps do you need for yolov5 nano version? I have yolov5n = 19fps, yolov5_custom = 9fps, is that right?

**Comment by marcoslucianops** [comment]
> yolov5n = 19fps

It's correct for Jetson Nano.

**Comment by cudanexus** [comment]
@marcoslucianops  any idea on the fps on t4 gpu

**Comment by marcoslucianops** [comment]
I will check it this week in AWS.

**Comment by marcoslucianops** [comment]
YOLOv5n in T4 (g4dn.8xlarge)

| | DeepStream | Ultralytics |
|:-:|:-:|:-:|
| FP16 | 133.80 | 63.32 |
| FP32 | 133.62 | 74.60 |

I think the T4 has bad FP16 support because the results aren't good.

**Comment by marcoslucianops** [comment]
I don't have available Jetson Nano to test it, sorry.

**Comment by ONNONS** [comment]
For mp4 files, where can I check the accuracy?

**Comment by marcoslucianops** [comment]
What do you mean with check accuracy?
