### ISSUE TITLE
Could not compute dimensions for (Unnamed Layer* 214) [Convolution]_output, because the network is not valid.

### ISSUE THREAD

**Issue by hejun888** [marcoslucianops/DeepStream-Yolo#15]
hi,
When I execute 'sudo ./yolov5 -s', the following error occurs
![1](https://user-images.githubusercontent.com/28728850/102951351-9f9ebc80-4507-11eb-8002-6c60ebe8795a.png)

**Comment by marcoslucianops** [comment]
> hi,
> 
> When I execute 'sudo ./yolov5 -s', the following error occurs
> 
> ![1](https://user-images.githubusercontent.com/28728850/102951351-9f9ebc80-4507-11eb-8002-6c60ebe8795a.png)
> 
> 

Do you using custom model?

**Comment by hejun888** [comment]
I use my own training network, also yolov5s, classify two categories

**Comment by marcoslucianops** [comment]
> I use my own training network, also yolov5s, classify two categories

Edit class_num in yololayer.h in tensorrtx folder

**Comment by hejun888** [comment]
thank you very much
