### ISSUE TITLE
High CPU usage for yolov5 postprocessing

### ISSUE THREAD

**Issue by HoangTienDuc** [marcoslucianops/DeepStream-Yolo#151]
Hi @marcoslucianops . Thank for your yolov5 post-postprocessing, I can make my yolov5-deepstream (python-version) run.
Everything is the same as your work. 

However, The CPU usage is **very high** even my CPU is very strong.
Could you pls give me some advice to reduce CPU usage?

![Screenshot from 2022-03-09 18-45-38](https://user-images.githubusercontent.com/53229746/157436384-87fb2872-ca20-49e8-a046-fe397509c56a.png)

**Comment by marcoslucianops** [comment]
Is this GPU usage when you run the deepstream-app or your code? How many streams are you running?

**Comment by HoangTienDuc** [comment]
Hi @marcoslucianops 
I run in my code (python). But it's no different from your code.

CPU usage increases as the number of objects in the frame increases (even when running only 1 stream).

I tried running from 1 to 8 streams (rtx 2080ti). I set batch-size pgie/streamux = 8. With the first 4 streams reaching 25fps, the Fps decreases as the number of streams increases

**Comment by HoangTienDuc** [comment]
Hi @marcoslucianops It is my fault. The high CPU is due to my custom post-processing.
