### ISSUE TITLE
Multiple inferences

### ISSUE THREAD

**Issue by amish25** [marcoslucianops/DeepStream-Yolo#152]
Hi, I'm using this library with two separate GST pipelines (both PGIEs). This works great if both .engines have the same numbers of classes but if not, I get an error telling me that the classes are different.

**Comment by marcoslucianops** [comment]
Hi, you need to use 2 DeepStream-Yolo folders (like pgie1, pgie2) and change the YOLOLAYER_PLUGIN_VERSION in one of the folders when the model is different.

Please change the yoloPlugins.h (line 51):

```
const char* YOLOLAYER_PLUGIN_VERSION {"1"};
```

to 

```
const char* YOLOLAYER_PLUGIN_VERSION {"2"};
```

in one of the models, recompile and try to run again (remove the old engine file too).

**Comment by amish25** [comment]
Ah I had another folder but I didn't recompile the engine file for the second pgie so it was still referencing the first pgie. All working as expected now! Thanks!
