### ISSUE TITLE
deepstream:6.0.1-triton

### ISSUE THREAD

**Issue by AIJIA000** [marcoslucianops/DeepStream-Yolo#154]
Hello
Using (deepstream:6.0.1-triton) this docker to compile will report an error, how should I modify it? Because I don't want to use the gRPC function, I may need to use trition, but I don't know if I choose to use trition is correct, I hope you can help me, thank you

**Comment by marcoslucianops** [comment]
Hi, comment the lines 314 to 329 in yolo.cpp file before compile.

**Comment by AIJIA000** [comment]
Can I use gRPC in trition?

**Comment by AIJIA000** [comment]
Thank you very much

**Comment by marcoslucianops** [comment]
> Can I use gRPC in trition?

I don't know.

**Comment by AIJIA000** [comment]
Thanks a lot
