### ISSUE TITLE
Dynamic batch-size

### ISSUE THREAD

**Issue by momohuangsha** [marcoslucianops/DeepStream-Yolo#155]
@marcoslucianops   Thanks for your work   Looking forward to updating Dynamic batch-size

**Comment by anywo** [comment]
Expect it!

**Comment by NIKHILDUGAR** [comment]
Any update on this?

**Comment by marcoslucianops** [comment]
Not yet.

**Comment by marcoslucianops** [comment]
Dynamic batch-size for ONNX exported models (YOLO-NAS, PPYOLOE+, PPYOLOE, DAMO-YOLO, YOLOX, YOLOR, YOLOv8, YOLOv7, YOLOv6 and YOLOv5)

The `opt` = `max` batch-size, and it's set in the config_infer_primary file

Example: 

```
...
batch-size=8
...
```
