### ISSUE TITLE
WARNING: Num classes mismatch. Configured: 6, detected by network: 80

### ISSUE THREAD

**Issue by DuyguBulut** [marcoslucianops/DeepStream-Yolo#156]
Hello sir! Thanks for your work.

I'm trying to run Yolov4-tiny from DeepStream 6.0.1 using your repository on Jetson Nano. I started with [this](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/customModels.md). Everything went okay. However, when the stream starts, the terminal displays this message:

WARNING: Num classes mismatch. Configured: 6, detected by network: 80
I followed your instructions for custom models. I have 6 classes and I changed labels.txt according to my classes.

My system's info:

CUDA 10.2
JetPack 4.6.1
DeepStream 6.0.1
TensorRT 8.0.1

Please help me. Thank you. 
![mismatch warning](https://user-images.githubusercontent.com/12576898/161010136-fa42a7d2-cf98-45f1-b13c-269100bff1a3.PNG)

**Comment by JWLee89** [comment]
Off the top of my head, in the generated `.cfg` file, if you go to the end of the file to the output layers, change the value `classes=80` to `classes=6`.  The warning should then disappear.

**Comment by DuyguBulut** [comment]
> Off the top of my head, in the generated `.cfg` file, if you go to the end of the file to the output layers, change the value `classes=80` to `classes=6`. The warning should then disappear.

I used my own custom .cfg file and I've already changed classes value for the output layers.  And I also changed num-detected-classes in config_infer_primary.txt. But unfortunately warning did not dissappear.

![class_num_in_config_infer](https://user-images.githubusercontent.com/12576898/161484323-
![class_num_in_config_infer](https://user-images.githubusercontent.com/12576898/161484653-50b8049a-c84a-44e5-b78f-d120549b3ec3.PNG)
9f0d888b-539a-4f7f-86cd-c53e9f9cd047.PNG)

**Comment by JWLee89** [comment]
Did you delete the existing engine prior to running DeepStream? If you don't delete the existing engine file, DeepStream will use the old TensorRT engine specified under `model_b1_gpu_0_fp32.txt`, which will have classes=80. And also note that YOLO has more than one output, meaning you have to update classes=6 for each of the output specifications.

**Comment by DuyguBulut** [comment]
> existing engine prior to running DeepStream

Thank you for reminding. I already updated classes=6 for each of the output specifications but I didn't know I had to delete the existing engine file. That's why I didn't delete the existing engine file before. After deleting the existing engine file and running it again, the warning disappeared. Thank you for your help. I wish you good work
