### ISSUE TITLE
question about FPS metric

### ISSUE THREAD

**Issue by youngjae-avikus** [marcoslucianops/DeepStream-Yolo#159]
Hello
I checked deepstream FPS indicators based on FP32 in README file

https://github.com/marcoslucianops/DeepStream-Yolo#yolov5n-performance-comparison

Did you not use the tracker when measuring in DeepStream?
If you used it, can you tell me the tracker type and interval value?
Thank you.

**Comment by youngjae-avikus** [comment]
And is `TensorRTx `a pure TensorRT API on the index?
I wonder why the FPS is dropping compared to the ultralytics
Thank you.

**Comment by marcoslucianops** [comment]
I didn't use a tracker. About the TensorRTx, you need to check on their repo.
