### ISSUE TITLE
WARNING: Num classes mismatch. Configured: 80, detected by network: 0

### ISSUE THREAD

**Issue by beybars1** [marcoslucianops/DeepStream-Yolo#16]
Hello sir! Thanks for your work. 

I am trying to run YoloV4 from DeepStream 5.0.1 using your repository on my Jetson Nano. I started with [this](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/customModels.md). Everything went okay, I successfully compiled with CUDA and tested the TRT inference. However, when the stream starts, the terminal displays this message:

**WARNING: Num classes mismatch. Configured: 80, detected by network: 0**
I followed your instructions, but got this. Number of classes in my labels.txt is 80.

My system's info:

- CUDA 10.2
- JetPack 4.4.1
- DeepStream 5.0.1
- TensorRT 7.1.3
- cuDNN 8.0
- OpenCV 4.1.1

Please help me!

![image](https://user-images.githubusercontent.com/29370622/103031438-0663ba80-4588-11eb-8098-bb7b82871f4b.png)

**Comment by marcoslucianops** [comment]
Can you send me your config_infer.txt and yolo.cfg?

**Comment by beybars1** [comment]
> Can you send me your config_infer.txt and yolo.cfg?

Files are attached below. Note that I intentionally make .cfg file to be .txt extension, GitHub doesn't support .cfg files.

[yolov4.cfg.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/5738639/yolov4.cfg.txt)
[config_infer_primary.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/5738625/config_infer_primary.txt)

**Comment by marcoslucianops** [comment]
Are you using my nvdsinfer_custom_impl_Yolo folder?

**Comment by beybars1** [comment]
> Are you using my nvdsinfer_custom_impl_Yolo folder? Did you edit anything from code?

yes, I use your folder. Nothing was introduced to the code.

**Comment by marcoslucianops** [comment]
> > Are you using my nvdsinfer_custom_impl_Yolo folder? Did you edit anything from code?
> 
> 
> 
> yes, I use your folder. Nothing was introduced to the code.

Strange, because I tested recently in my Jetson Nano and yesterday on dGPU without this error. Can you clone repo and recompile all again?

**Comment by beybars1** [comment]
> > > Are you using my nvdsinfer_custom_impl_Yolo folder? Did you edit anything from code?
> > 
> > 
> > yes, I use your folder. Nothing was introduced to the code.
> 
> Strange, because I tested recently in my Jetson Nano and yesterday on dGPU without this error. Can you clone repo and recompile all again?

ok, I will try.

**Comment by beybars1** [comment]
Do I need to do anything in the nvdsinfer_impl_Yolo folder? Edit something? By the way, I did everything again, the result is same.

**Comment by XiangjiBU** [comment]
this may be a permission problem, use "sudo deepstream <config......>"

**Comment by beybars1** [comment]
> this may be a permission problem, use "sudo deepstream-app -c <config......>"

Thanks sir! It works now! We can close this issue.

**Comment by marcoslucianops** [comment]
> this may be a permission problem, use "sudo deepstream-app -c  <config......>"

I will update repo with this info.

**Comment by ctslick** [comment]
I've encountered the same problem, but running using "sudo deepstream-app -c <config_file>" is not the solution for me (I'm able to run other sample Deepstream configuration files using sudo though).  

I'm using a custom YoloV5 model, which detects 3 classes (it was provided to me by a coworker, but runs fine using the Ultralytics detect.py function in their repository).  
I have only the 3 classes listed in "labels_yolov5.txt".  

Attached is my config_infer_primary__yolov5.txt file.

Note that I created the .cfg & .weights files (pointed to in config_infer_primary__yolov5.txt) from .pt & .yaml files using code from this repository:
https://github.com/adrianosantospb/yolov5_ultralytics_to_darnet_format

As above, I have not edited anything in your "nvdsinfer_custom_impl_Yolo"
[config_infer_primary__yolov5.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/9570475/config_infer_primary__yolov5.txt)
 folder.

Any assistance would be greatly appreciated.
