### ISSUE TITLE
Will the nvdsparsebbox_Yolo.cpp in bbi.classId = maxIndex; Is it the class of the object?

### ISSUE THREAD

**Issue by AIJIA000** [marcoslucianops/DeepStream-Yolo#161]
![image](https://user-images.githubusercontent.com/16066503/164382766-a7fe4ba2-4e9b-4647-8028-b30bc210179f.png)

**Comment by marcoslucianops** [comment]
Yes, but it's the class number (0, 1, etc).

**Comment by AIJIA000** [comment]
![image](https://user-images.githubusercontent.com/16066503/166426644-57b70051-8697-46b0-bd54-d4878d58856b.png)

**Comment by AIJIA000** [comment]
But addBBoxProposal(bx, by, bw, bh, netW, netH, maxIndex, maxProb, binfo) is run three layers of for loop, then bbi.classId = maxIndex; will produce many values in each frame, so how do I determine Category ID index?

**Comment by AIJIA000** [comment]
thanks～

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/issues/167#issuecomment-1117503292
