### ISSUE TITLE
Create a dependencies file

### ISSUE THREAD

**Issue by Emmanuel-Messulam** [marcoslucianops/DeepStream-Yolo#165]
Installing on a Xavier we've had to update `numpy`, `scipy` and install `tqdm`, `seaborn` and a few other dependecies, please add them to a dependencies file.

**Comment by marcoslucianops** [comment]
The requirements are available in model repo.
YOLOv5: https://github.com/ultralytics/yolov5/blob/master/requirements.txt
YOLOR: https://github.com/WongKinYiu/yolor/blob/main/requirements.txt
