### ISSUE TITLE
YOLO v5 INT8 is not faster than FP16 or FP32

### ISSUE THREAD

**Issue by 4399chen** [marcoslucianops/DeepStream-Yolo#166]
Hello.

I used your project and followed your steps.
But INT8 is slower than both FP32 and FP16 in my tests.
Test with a video file(640x480x50FPS)

FP32
![image](https://user-images.githubusercontent.com/56430444/166144256-a3316997-dd67-4266-a0cf-28a8b1585aae.png)

FP16
![image](https://user-images.githubusercontent.com/56430444/166144286-902f26e9-a40f-413c-8d71-c8b1f4dbe95e.png)

INT8
![image](https://user-images.githubusercontent.com/56430444/166144177-8600e216-a905-466e-89e1-9c12c4bca4f9.png)

Jetson Xavier NX, MODE 20W 6CORE
YOLO v5 6.1
yolov5n.pt

**Comment by 4399chen** [comment]
It is obvious that INT8 is not exerting all the ability of NX. Because when I lower the power of NX, THE FPS of FP16 goes down a lot, but the FPS of INT8 doesn't change much.

FP16(MODE 10W 2CORE)
![image](https://user-images.githubusercontent.com/56430444/166144406-3bcd7318-e1f9-4bde-9252-a07163784afb.png)


INT8(MODE 10W 2CORE)
![image](https://user-images.githubusercontent.com/56430444/166144473-12cda81b-6415-40a3-b4e9-ba4cff6539f4.png)

**Comment by marcoslucianops** [comment]
Please use the updated files, there are a lot of improvements on them.
