### ISSUE TITLE
Assertion `layer.inferDims.numDims == 3' Error

### ISSUE THREAD

**Issue by Krokos11** [marcoslucianops/DeepStream-Yolo#172]
I did following steps:

**1. Train model according to the steps from the repository https://github.com/ultralytics/yolov5 (tag 6.1) on Google Colab
2. Model was trained well and had been saved to a file best.pt
3. Tested this model on test dataset and performed well
4. Copy best.pt and dataset.yaml file to my Jetson Nano
5. Convert best.pt to best.egine inside Jetson in yolov5 folder, using**
 `python3 export.py --weights best.pt --data drugs.yaml --include engine --device 0`

**Model was exported with few errors, but finally it was saved with success Note:**

export: data=drugs.yaml, weights=['best.pt'], imgsz=[640, 640], batch_size=1, device=0, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
YOLOv5 🚀 v6.1-0-g3752807 torch 1.8.0 CUDA:0 (NVIDIA Tegra X1, 1972MiB)

Fusing layers... 
Model Summary: 213 layers, 7023610 parameters, 0 gradients, 15.8 GFLOPs

PyTorch: starting from best.pt with output shape (1, 25200, 10) (14.4 MB)
/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
requirements: onnx not found and is required by YOLOv5, attempting auto-update...
Defaulting to user installation because normal site-packages is not writeable
Collecting onnx
  Downloading onnx-1.11.0-cp36-cp36m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (12.7 MB)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/nvj-jetson/.local/lib/python3.6/site-packages (from onnx) (4.1.1)
Requirement already satisfied: numpy>=1.16.6 in /home/nvj-jetson/.local/lib/python3.6/site-packages (from onnx) (1.19.5)
Requirement already satisfied: protobuf>=3.12.2 in /usr/local/lib/python3.6/dist-packages (from onnx) (3.19.4)
Installing collected packages: onnx
Successfully installed onnx-1.11.0

requirements: 1 package updated per ['onnx']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

ONNX: starting export with onnx 1.11.0...
ONNX: export success, saved as best.onnx (28.5 MB)

TensorRT: starting export with TensorRT 8.0.1.6...
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +144, GPU +3, now: CPU 2193, GPU 1947 (MiB)
[TensorRT] INFO: ----------------------------------------------------------------
[TensorRT] INFO: Input filename:   best.onnx
[TensorRT] INFO: ONNX IR version:  0.0.6
[TensorRT] INFO: Opset version:    13
[TensorRT] INFO: Producer name:    pytorch
[TensorRT] INFO: Producer version: 1.8
[TensorRT] INFO: Domain:           
[TensorRT] INFO: Model version:    0
[TensorRT] INFO: Doc string:       
[TensorRT] INFO: ----------------------------------------------------------------
[TensorRT] WARNING: onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
TensorRT: Network Description:
TensorRT:       input "images" with shape (1, 3, 640, 640) and dtype DataType.FLOAT
TensorRT:       output "output" with shape (1, 25200, 10) and dtype DataType.FLOAT
TensorRT:       output "350" with shape (1, 3, 80, 80, 10) and dtype DataType.FLOAT
TensorRT:       output "416" with shape (1, 3, 40, 40, 10) and dtype DataType.FLOAT
TensorRT:       output "482" with shape (1, 3, 20, 20, 10) and dtype DataType.FLOAT
TensorRT: building FP32 engine in best.engine
[TensorRT] INFO: [MemUsageSnapshot] Builder begin: CPU 2221 MiB, GPU 1947 MiB
[TensorRT] INFO: ---------- Layers Running on DLA ----------
[TensorRT] INFO: ---------- Layers Running on GPU ----------
[TensorRT] INFO: [GpuLayer] 361
[TensorRT] INFO: [GpuLayer] 374
[TensorRT] INFO: [GpuLayer] 427
[TensorRT] INFO: [GpuLayer] 440
[TensorRT] INFO: [GpuLayer] 493
[TensorRT] INFO: [GpuLayer] 506
[TensorRT] INFO: [GpuLayer] Conv_0
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_1), Mul_2)
[TensorRT] INFO: [GpuLayer] Conv_3
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_4), Mul_5)
[TensorRT] INFO: [GpuLayer] Conv_6 || Conv_16
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_7), Mul_8)
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_17), Mul_18)
[TensorRT] INFO: [GpuLayer] Conv_9
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_10), Mul_11)
[TensorRT] INFO: [GpuLayer] Conv_12
[TensorRT] INFO: [GpuLayer] PWN(PWN(PWN(Sigmoid_13), Mul_14), Add_15)
[TensorRT] INFO: [GpuLayer] Conv_20
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_21), Mul_22)
[TensorRT] INFO: [GpuLayer] Conv_23
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_24), Mul_25)
[TensorRT] INFO: [GpuLayer] Conv_26 || Conv_43
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_27), Mul_28)
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_44), Mul_45)
[TensorRT] INFO: [GpuLayer] Conv_29
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_30), Mul_31)
[TensorRT] INFO: [GpuLayer] Conv_32
[TensorRT] INFO: [GpuLayer] PWN(PWN(PWN(Sigmoid_33), Mul_34), Add_35)
[TensorRT] INFO: [GpuLayer] Conv_36
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_37), Mul_38)
[TensorRT] INFO: [GpuLayer] Conv_39
[TensorRT] INFO: [GpuLayer] PWN(PWN(PWN(Sigmoid_40), Mul_41), Add_42)
[TensorRT] INFO: [GpuLayer] Conv_47
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_48), Mul_49)
[TensorRT] INFO: [GpuLayer] Conv_50
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_51), Mul_52)
[TensorRT] INFO: [GpuLayer] Conv_53 || Conv_77
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_54), Mul_55)
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_78), Mul_79)
[TensorRT] INFO: [GpuLayer] Conv_56
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_57), Mul_58)
[TensorRT] INFO: [GpuLayer] Conv_59
[TensorRT] INFO: [GpuLayer] PWN(PWN(PWN(Sigmoid_60), Mul_61), Add_62)
[TensorRT] INFO: [GpuLayer] Conv_63
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_64), Mul_65)
[TensorRT] INFO: [GpuLayer] Conv_66
[TensorRT] INFO: [GpuLayer] PWN(PWN(PWN(Sigmoid_67), Mul_68), Add_69)
[TensorRT] INFO: [GpuLayer] Conv_70
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_71), Mul_72)
[TensorRT] INFO: [GpuLayer] Conv_73
[TensorRT] INFO: [GpuLayer] PWN(PWN(PWN(Sigmoid_74), Mul_75), Add_76)
[TensorRT] INFO: [GpuLayer] Conv_81
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_82), Mul_83)
[TensorRT] INFO: [GpuLayer] Conv_84
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_85), Mul_86)
[TensorRT] INFO: [GpuLayer] Conv_87 || Conv_97
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_88), Mul_89)
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_98), Mul_99)
[TensorRT] INFO: [GpuLayer] Conv_90
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_91), Mul_92)
[TensorRT] INFO: [GpuLayer] Conv_93
[TensorRT] INFO: [GpuLayer] PWN(PWN(PWN(Sigmoid_94), Mul_95), Add_96)
[TensorRT] INFO: [GpuLayer] Conv_101
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_102), Mul_103)
[TensorRT] INFO: [GpuLayer] Conv_104
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_105), Mul_106)
[TensorRT] INFO: [GpuLayer] MaxPool_107
[TensorRT] INFO: [GpuLayer] MaxPool_108
[TensorRT] INFO: [GpuLayer] MaxPool_109
[TensorRT] INFO: [GpuLayer] 228 copy
[TensorRT] INFO: [GpuLayer] 229 copy
[TensorRT] INFO: [GpuLayer] 230 copy
[TensorRT] INFO: [GpuLayer] Conv_111
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_112), Mul_113)
[TensorRT] INFO: [GpuLayer] Conv_114
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_115), Mul_116)
[TensorRT] INFO: [GpuLayer] Resize_117
[TensorRT] INFO: [GpuLayer] 243 copy
[TensorRT] INFO: [GpuLayer] Conv_119 || Conv_128
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_120), Mul_121)
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_129), Mul_130)
[TensorRT] INFO: [GpuLayer] Conv_122
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_123), Mul_124)
[TensorRT] INFO: [GpuLayer] Conv_125
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_126), Mul_127)
[TensorRT] INFO: [GpuLayer] Conv_132
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_133), Mul_134)
[TensorRT] INFO: [GpuLayer] Conv_135
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_136), Mul_137)
[TensorRT] INFO: [GpuLayer] Resize_138
[TensorRT] INFO: [GpuLayer] 268 copy
[TensorRT] INFO: [GpuLayer] Conv_140 || Conv_149
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_141), Mul_142)
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_150), Mul_151)
[TensorRT] INFO: [GpuLayer] Conv_143
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_144), Mul_145)
[TensorRT] INFO: [GpuLayer] Conv_146
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_147), Mul_148)
[TensorRT] INFO: [GpuLayer] Conv_153
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_154), Mul_155)
[TensorRT] INFO: [GpuLayer] Conv_156
[TensorRT] INFO: [GpuLayer] Conv_196
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_157), Mul_158)
[TensorRT] INFO: [GpuLayer] 263 copy
[TensorRT] INFO: [GpuLayer] Conv_160 || Conv_169
[TensorRT] INFO: [GpuLayer] Reshape_213 + Transpose_214
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_161), Mul_162)
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_170), Mul_171)
[TensorRT] INFO: [GpuLayer] Conv_163
[TensorRT] INFO: [GpuLayer] PWN(Sigmoid_215)
[TensorRT] INFO: [GpuLayer] Slice_220
[TensorRT] INFO: [GpuLayer] Slice_233
[TensorRT] INFO: [GpuLayer] Slice_244
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_164), Mul_165)
[TensorRT] INFO: [GpuLayer] Conv_166
[TensorRT] INFO: [GpuLayer] PWN(PWN(370 + (Unnamed Layer* 229) [Shuffle] + Mul_235, PWN(372 + (Unnamed Layer* 232) [Shuffle], Pow_237)), Mul_239)
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_167), Mul_168)
[TensorRT] INFO: [GpuLayer] PWN(PWN(PWN(357 + (Unnamed Layer* 217) [Shuffle] + Mul_222, PWN(359 + (Unnamed Layer* 220) [Shuffle], Sub_224)), Add_226), 363 + (Unnamed Layer* 225) [Shuffle] + Mul_228)
[TensorRT] INFO: [GpuLayer] 364 copy
[TensorRT] INFO: [GpuLayer] 375 copy
[TensorRT] INFO: [GpuLayer] 380 copy
[TensorRT] INFO: [GpuLayer] Conv_173
[TensorRT] INFO: [GpuLayer] Reshape_249
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_174), Mul_175)
[TensorRT] INFO: [GpuLayer] Conv_176
[TensorRT] INFO: [GpuLayer] Conv_250
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_177), Mul_178)
[TensorRT] INFO: [GpuLayer] 238 copy
[TensorRT] INFO: [GpuLayer] Conv_180 || Conv_189
[TensorRT] INFO: [GpuLayer] Reshape_267 + Transpose_268
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_181), Mul_182)
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_190), Mul_191)
[TensorRT] INFO: [GpuLayer] Conv_183
[TensorRT] INFO: [GpuLayer] PWN(Sigmoid_269)
[TensorRT] INFO: [GpuLayer] Slice_274
[TensorRT] INFO: [GpuLayer] Slice_287
[TensorRT] INFO: [GpuLayer] Slice_298
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_184), Mul_185)
[TensorRT] INFO: [GpuLayer] Conv_186
[TensorRT] INFO: [GpuLayer] PWN(PWN(436 + (Unnamed Layer* 276) [Shuffle] + Mul_289, PWN(438 + (Unnamed Layer* 279) [Shuffle], Pow_291)), Mul_293)
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_187), Mul_188)
[TensorRT] INFO: [GpuLayer] PWN(PWN(PWN(423 + (Unnamed Layer* 264) [Shuffle] + Mul_276, PWN(425 + (Unnamed Layer* 267) [Shuffle], Sub_278)), Add_280), 429 + (Unnamed Layer* 272) [Shuffle] + Mul_282)
[TensorRT] INFO: [GpuLayer] 430 copy
[TensorRT] INFO: [GpuLayer] 441 copy
[TensorRT] INFO: [GpuLayer] 446 copy
[TensorRT] INFO: [GpuLayer] Conv_193
[TensorRT] INFO: [GpuLayer] Reshape_303
[TensorRT] INFO: [GpuLayer] PWN(PWN(Sigmoid_194), Mul_195)
[TensorRT] INFO: [GpuLayer] Conv_304
[TensorRT] INFO: [GpuLayer] Reshape_321 + Transpose_322
[TensorRT] INFO: [GpuLayer] PWN(Sigmoid_323)
[TensorRT] INFO: [GpuLayer] Slice_328
[TensorRT] INFO: [GpuLayer] Slice_341
[TensorRT] INFO: [GpuLayer] Slice_352
[TensorRT] INFO: [GpuLayer] PWN(PWN(502 + (Unnamed Layer* 323) [Shuffle] + Mul_343, PWN(504 + (Unnamed Layer* 326) [Shuffle], Pow_345)), Mul_347)
[TensorRT] INFO: [GpuLayer] PWN(PWN(PWN(489 + (Unnamed Layer* 311) [Shuffle] + Mul_330, PWN(491 + (Unnamed Layer* 314) [Shuffle], Sub_332)), Add_334), 495 + (Unnamed Layer* 319) [Shuffle] + Mul_336)
[TensorRT] INFO: [GpuLayer] 496 copy
[TensorRT] INFO: [GpuLayer] 507 copy
[TensorRT] INFO: [GpuLayer] 512 copy
[TensorRT] INFO: [GpuLayer] Reshape_357
[TensorRT] INFO: [GpuLayer] 391 copy
[TensorRT] INFO: [GpuLayer] 457 copy
[TensorRT] INFO: [GpuLayer] 523 copy
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU -29, now: CPU 2225, GPU 1920 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +0, GPU +14, now: CPU 2225, GPU 1934 (MiB)
[TensorRT] WARNING: Detected invalid timing cache, setup a local cache instead
[TensorRT] ERROR: Tactic Device request: 538MB Available: 206MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 538 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 538MB Available: 219MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 538 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 531MB Available: 231MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 531 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 531MB Available: 230MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 531 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 533MB Available: 288MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 533 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 534MB Available: 287MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 534 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 554MB Available: 284MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 554 detected for tactic 5.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 547MB Available: 287MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 547 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 549MB Available: 287MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 549 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 1093MB Available: 359MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 1093 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 1066MB Available: 353MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 1066 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] ERROR: Tactic Device request: 507MB Available: 353MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 507 detected for tactic 4.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[TensorRT] INFO: Detected 1 inputs and 7 output network tensors.
[TensorRT] INFO: Total Host Persistent Memory: 144736
[TensorRT] INFO: Total Device Persistent Memory: 44335616
[TensorRT] INFO: Total Scratch Memory: 0
[TensorRT] INFO: [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 7 MiB, GPU 282 MiB
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU -1, now: CPU 2234, GPU 1905 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +1, GPU +0, now: CPU 2235, GPU 1905 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +1, now: CPU 2234, GPU 1906 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 2234, GPU 1896 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] Builder end: CPU 2234 MiB, GPU 1896 MiB
TensorRT: export success, saved as best.engine (48.9 MB)

Export complete (383.20s)
Results saved to /home/nvj-jetson/Desktop/Magisterka/PT_2_TensorRT/yolov5_v6_1_drugie/yolov5
Detect:          python detect.py --weights best.engine
PyTorch Hub:     model = torch.hub.load('ultralytics/yolov5', 'custom', 'best.engine')
Validate:        python val.py --weights best.engine
Visualize:       https://netron.app

**6.After it was created, I copy best.engine to DeepStream-Yolo folder**
**7. Changed config_infer_primary_yoloV5 file appropriately**
**8. Run deepstream-app -c desspstream_app_config.txt**
**9. It started for a secodn and after that has this note:**

Using winsys: x11 
0:00:06.930806168 17214     0x3a392780 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1900> [UID = 1]: deserialized trt engine from :/home/nvj-jetson/Desktop/Magisterka/PT_2_TensorRT/DeepStream-Yolo/best.engine
INFO: [Implicit Engine Info]: layers num: 5
0   INPUT  kFLOAT images          3x640x640       
1   OUTPUT kFLOAT 350             3x80x80x10      
2   OUTPUT kFLOAT 416             3x40x40x10      
3   OUTPUT kFLOAT 482             3x20x20x10      
4   OUTPUT kFLOAT output          25200x10        

0:00:06.931091229 17214     0x3a392780 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2004> [UID = 1]: Use deserialized engine model: /home/nvj-jetson/Desktop/Magisterka/PT_2_TensorRT/DeepStream-Yolo/best.engine
0:00:07.281073068 17214     0x3a392780 INFO                 nvinfer gstnvinfer_impl.cpp:313:notifyLoadModelStatus:<primary_gie> [UID 1]: Load new model:/home/nvj-jetson/Desktop/Magisterka/PT_2_TensorRT/DeepStream-Yolo/config_infer_primary_yoloV5.txt sucessfully

Runtime commands:
	h: Print this help
	q: Quit

	p: Pause
	r: Resume

NOTE: To expand a source in the 2D tiled display and view object details, left-click on the source.
      To go back to the tiled display, right-click anywhere on the window.

**PERF:  FPS 0 (Avg)	
**PERF:  0.00 (0.00)	
** INFO: <bus_callback:194>: Pipeline ready

** INFO: <bus_callback:180>: Pipeline running

deepstream-app: nvdsparsebbox_Yolo.cpp:137: bool NvDsInferParseCustomYolo(const std::vector<NvDsInferLayerInfo>&, const NvDsInferNetworkInfo&, const NvDsInferParseDetectionParams&, std::vector<NvDsInferObjectDetectionInfo>&, const uint&, const uint&): Assertion `layer.inferDims.numDims == 3' failed.
Aborted (core dumped)

**Any suggestion how to fix it?**

**Comment by Krokos11** [comment]
I add, when I tried use only .wts and .cfg files, and did similar steps, I had error from this theme: 
https://github.com/marcoslucianops/DeepStream-Yolo/issues/136

**Comment by marcoslucianops** [comment]
Please see https://github.com/marcoslucianops/DeepStream-Yolo#yolov5-usage

You are doing wrong model conversion.
