### ISSUE TITLE
Show confidence

### ISSUE THREAD

**Issue by Krokos11** [marcoslucianops/DeepStream-Yolo#173]
Is here possibility to show confidence of my detections on screen? Like it was did on dusty-nv tutorial: 

https://www.youtube.com/watch?v=2XMkPW_sIGg&t=1092s&ab_channel=NVIDIADeveloper

![image](https://user-images.githubusercontent.com/51709404/168487547-3ae1e169-e9a2-4212-a25a-90704eba8799.png)

**Comment by marcoslucianops** [comment]
You need to work with custom codes to do that.

**Comment by zardadi** [comment]
@Krokos11 I have the same issue. Did you figure out how to display confidence?

**Comment by marcoslucianops** [comment]
Check the DeepStream Python Apps:
https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps
