### ISSUE TITLE
Why is the fp16 engine file size larger than pt? (yolov5s)

### ISSUE THREAD

**Issue by youngjae-avikus** [marcoslucianops/DeepStream-Yolo#175]
Why is the size of the engine file larger than pt?
Doesn't its bigger size affect inference time?
Also, how can I increase the size of `workspace` when I make an engine?

```txt
-rw-r--r-- 1 root root  32M May 17 10:15 model_b1_gpu0_fp16.engine
```

```txt
-rw-rw-r-- 1 1000 1000  15M May 16 16:28 yolov5s.pt
```

**Comment by marcoslucianops** [comment]
There's no problem on it, it's due to TensorRT conversion.
