### ISSUE TITLE
Problem Running Yolov5 in Deepstream

### ISSUE THREAD

**Issue by franzhd** [marcoslucianops/DeepStream-Yolo#176]
Hello guys, i'm trying to make yolov5 work in deepstream on a jetson AGX xavier, i followed the tutorial, but when i launch the deepstream command it does not work, giving me that error, can you guys help me? 

` deepstream-app -c deepstream_app_config.txt

(deepstream-app:15307): GStreamer-CRITICAL **: 11:33:32.095: passed '0' as denominator for `GstFraction'

(deepstream-app:15307): GStreamer-CRITICAL **: 11:33:32.096: passed '0' as denominator for `GstFraction'
Failed to load config file: No such file or directory
** ERROR: <gst_nvinfer_parse_config_file:1303>: failed

Using winsys: x11 
0:00:00.426919956 15307      0x5439240 WARN                 nvinfer gstnvinfer.cpp:794:gst_nvinfer_start:<primary_gie> error: Configuration file parsing failed
0:00:00.427134238 15307      0x5439240 WARN                 nvinfer gstnvinfer.cpp:794:gst_nvinfer_start:<primary_gie> error: Config file path: /home/auto/DeepStream-Yolo/config_infer_primary_yoloV5.txt 
** ERROR: <main:707>: Failed to set pipeline to PAUSED
Quitting
ERROR from primary_gie: Configuration file parsing failed
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvinfer/gstnvinfer.cpp(794): gst_nvinfer_start (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
Config file path: /home/auto/DeepStream-Yolo/config_infer_primary_yoloV5.txt 
App run failed`

**Comment by youngjae-avikus** [comment]
`deepstream_app_config.txt` Is the route exactly right?

**Comment by marcoslucianops** [comment]
There's something wrong in your config_infer_primary_yoloV5.txt file.
