### ISSUE TITLE
yolov4-tiny deploy

### ISSUE THREAD

**Issue by Adam123wu** [marcoslucianops/DeepStream-Yolo#179]
I actually tried to deploy Yolo4-Tiny on the flame dataset (standard CFG file) but could not generate the.so file. How should I resolve this to solve tiny's deployment in DeepStream?
![6011653551851_ pic](https://user-images.githubusercontent.com/48359834/170446378-37a67877-de60-434b-84e0-4dc091397f7d.jpg)

**Comment by marcoslucianops** [comment]
Please see the requirements. You need to use DeepStream 6.0.1.

**Comment by Adam123wu** [comment]
thank you.Actually,you script perfectly solve the custom yolo deployment
