### ISSUE TITLE
Custom engine model name not changing

### ISSUE THREAD

**Issue by amish25** [marcoslucianops/DeepStream-Yolo#18]
Hi, firstly thanks for your great work. Small issue, when I create an engine with a custom engine name using your native folder, the engine doesn't have the same name as that specified in the config file. 

For example, if I set model-engine-file=model_b1_gpu0_fp32_custom.engine, the engine is saved as model_b1_gpu0_fp32.engine.

**Comment by marcoslucianops** [comment]
> For example, if I set model-engine-file=model_b1_gpu0_fp32_custom.engine, the engine is saved as model_b1_gpu0_fp32.engine. 

This is an implementation of DeepStream. You can change it only by editing and recompiling default DeepStream code (not Yolo model code). The easy way is rename file and edit config_infer path.

**Comment by ntd94** [comment]
> This is an implementation of DeepStream.

Hi, could you provide the reference to this

**Comment by marcoslucianops** [comment]
@ntd94, refer to /opt/nvidia/deepstream/deepstream-6.0/sources/libs/nvdsinfer/nvdsinfer_model_builder.cpp lines 825-827:

```
suggestedPathName =
        modelPath + "_b" + std::to_string(initParams.maxBatchSize) + "_" +
        devId + "_" + networkMode2Str(networkMode) + ".engine";
```
