### ISSUE TITLE
streaming stopped, reason not-negotiated (-4)

### ISSUE THREAD

**Issue by hasantokatlioglu** [marcoslucianops/DeepStream-Yolo#180]
I convert .engine but I cannot use please help me 

my deepstream_app_config.txt is:
![a](https://user-images.githubusercontent.com/93164887/170804967-893b9110-c037-4a96-915d-8c3db750abf3.png)
my config_infer_primary_yoloV5.txt is:  
![b](https://user-images.githubusercontent.com/93164887/170805020-e983c1a2-8754-4ce0-9c2e-5f4260e99c3a.png)

Thank you!

**Comment by marcoslucianops** [comment]
In deepstream-app you need to set the camera parameters according to your usb camera supported formats. The default is `camera-width=640`, `camera-height=480` and `camera-fps-n=30`.

**Comment by hasantokatlioglu** [comment]
I changed values and I get new error.


ws/DeepStream-Yolo/config_infer_primary_yoloV5.txt sucessfully

Runtime commands:
	h: Print this help
	q: Quit

	p: Pause
	r: Resume

NOTE: To expand a source in the 2D tiled display and view object details, left-click on the source.
      To go back to the tiled display, right-click anywhere on the window.

** INFO: <bus_callback:194>: Pipeline ready

** INFO: <bus_callback:180>: Pipeline running

Segmentation fault (core dumped)

**Comment by marcoslucianops** [comment]
Which DeepStream version are you using?

**Comment by hasantokatlioglu** [comment]
6.1

**Comment by marcoslucianops** [comment]
I didn't get this error here. Can you try to debug the error using gdb?

**Comment by arun-kumark** [comment]
Hello,
I am also facing the same issue.
My pipeline is:
gst-launch-1.0 pylonsrc cam::ExposureTime=20000 cam::Gain=10.3 ! "video/x-raw,width=640,height=480,framerate=10/1,format=GRAY8" ! videoconvert ! nvvideoconvert ! m.sink_0 nvstreammux name=m batch-size=1 width=1024 height=768 ! nvinfer config-file-path=/home/arun/DeepStream-Yolo/config_infer_primary_yoloV5.txt batch-size=1 unique-id=1 ! autovideosink

I get the following error:



```
arun@arun:~/DeepStream-Yolo$ gst-launch-1.0 pylonsrc cam::ExposureTime=20000 cam::Gain=10.3 ! "video/x-raw,width=640,height=480,framerate=10/1,format=GRAY8" ! videoconvert ! nvvideoconvert ! m.sink_0 nvstreammux name=m batch-size=1 width=1024 height=768 ! nvinfer config-file-path=/home/arun/DeepStream-Yolo/config_infer_primary_yoloV5.txt batch-size=1 unique-id=1 ! autovideosink
Setting pipeline to PAUSED ...
WARNING: [TRT]: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
0:00:13.592017243 13969 0xaaaaecef4030 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<nvinfer0> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1909> [UID = 1]: deserialized trt engine from :/home/arun/DeepStream-Yolo/model_b1_gpu0_fp32.engine
WARNING: [TRT]: The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
INFO: [Implicit Engine Info]: layers num: 4
0   INPUT  kFLOAT input           3x640x640       
1   OUTPUT kFLOAT boxes           25200x4         
2   OUTPUT kFLOAT scores          25200x1         
3   OUTPUT kFLOAT classes         25200x1         

0:00:13.657445702 13969 0xaaaaecef4030 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<nvinfer0> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2012> [UID = 1]: Use deserialized engine model: /home/arun/DeepStream-Yolo/model_b1_gpu0_fp32.engine
0:00:13.669595896 13969 0xaaaaecef4030 INFO                 nvinfer gstnvinfer_impl.cpp:328:notifyLoadModelStatus:<nvinfer0> [UID 1]: Load new model:/home/arun/DeepStream-Yolo/config_infer_primary_yoloV5.txt sucessfully
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstPylonSrc:pylonsrc0: Internal data stream error.
Additional debug info:
gstbasesrc.c(3072): gst_base_src_loop (): /GstPipeline:pipeline0/GstPylonSrc:pylonsrc0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.307523235
Setting pipeline to NULL ...
Freeing pipeline ...
arun@arun:~/DeepStream-Yolo$ 
```
I am using DeepStream 6.1 and Basler Ace2

thanks
Kind Regards
Arun

**Comment by marcoslucianops** [comment]
Try

If you are runing in a x86 platform

```
gst-launch-1.0 pylonsrc cam::ExposureTime=20000 cam::Gain=10.3 ! "video/x-raw,width=640,height=480,framerate=10/1,format=GRAY8" ! videoconvert ! nvvideoconvert ! m.sink_0 nvstreammux name=m batch-size=1 width=1024 height=768 ! nvinfer config-file-path=/home/arun/DeepStream-Yolo/config_infer_primary_yoloV5.txt batch-size=1 unique-id=1 ! nvvideoconvert ! nvdsosd ! nveglglessink sync=0
```

If you are running in a Jetson platform:

```
gst-launch-1.0 pylonsrc cam::ExposureTime=20000 cam::Gain=10.3 ! "video/x-raw,width=640,height=480,framerate=10/1,format=GRAY8" ! videoconvert ! nvvideoconvert ! m.sink_0 nvstreammux name=m batch-size=1 width=1024 height=768 ! nvinfer config-file-path=/home/arun/DeepStream-Yolo/config_infer_primary_yoloV5.txt batch-size=1 unique-id=1 ! nvvideoconvert ! nvdsosd ! nvegltransform ! nveglglessink sync=0
```

**Comment by arun-kumark** [comment]
Solved with Jetson platform option :+1: 

Thanks!

How can I make this as a Python file ? Any reference Marco ?

**Comment by marcoslucianops** [comment]
> How can I make this as a Python file ? Any reference Marco ?

https://github.com/NVIDIA-AI-IOT/deepstream_python_apps

**Comment by arun-kumark** [comment]
Thanks Marco.
I am searching for Basler specific pylonsrc code. I have a graph from running pipeline, but my python code stalls.
Attaching the graph file for your reference too..

[pipeline_PAUSED_READY.pdf](https://github.com/marcoslucianops/DeepStream-Yolo/files/12165000/pipeline_PAUSED_READY.pdf)
thanks 
Kind Regards
Arun

**Comment by marcoslucianops** [comment]
Can you send the log from the terminal?
