### ISSUE TITLE
Modify generated engine file path

### ISSUE THREAD

**Issue by abdullahhanzalah** [marcoslucianops/DeepStream-Yolo#181]
Wanted to know if we could edit the output path or add the functionality to where the engine files are created after running the deepstream app. Currently it generates in the root directory.

Thanks

**Comment by marcoslucianops** [comment]
@abdullahhanzalah, refer to /opt/nvidia/deepstream/deepstream/sources/libs/nvdsinfer/nvdsinfer_model_builder.cpp lines 825-827:

```
    suggestedPathName =
        modelPath + "_b" + std::to_string(initParams.maxBatchSize) + "_" +
        devId + "_" + networkMode2Str(networkMode) + ".engine";
```

https://github.com/marcoslucianops/DeepStream-Yolo/issues/18#issuecomment-1089533940

**Comment by kalmastenitin** [comment]
can anybody will show ? What to do if i would like to run  detectnet and for yolov on same machine

**Comment by marcoslucianops** [comment]
> can anybody will show ? What to do if i would like to run detectnet and for yolov on same machine

You need to edit the `deepstream_app_config.txt` file adding both models (`[primary-gie]`, `[secondary-gie0]`, etc).
