### ISSUE TITLE
How to generate wts file of other models like YoloX?

### ISSUE THREAD

**Issue by chienhust** [marcoslucianops/DeepStream-Yolo#183]
I want to use other models like YoloX. Can you give me docs about generating wts file and nvdsinfer_custom_impl_Yolo folder? Thank you.

**Comment by marcoslucianops** [comment]
I'm working on implementation for YOLOX and PP-YOLO.

**Comment by marcoslucianops** [comment]
It's already supported.

[YOLOX](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOX.md)
[PPYOLOE](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/PPYOLOE.md)
