### ISSUE TITLE
ERROR: <create_udpsink_bin:603>: Failed to create 'sink_sub_bin_encoder1'

### ISSUE THREAD

**Issue by WangxuP** [marcoslucianops/DeepStream-Yolo#184]
Hello, I am currently using the PTH model of yolov5 version 6.0. When I set sink as 1, the following problems will occur. Could you help me solve the problem? Thank you very much.

ERROR:
sudo deepstream-app -c deepstream_app_config_copy.txt
** ERROR: <create_udpsink_bin:603>: Failed to create 'sink_sub_bin_encoder1'
** ERROR: <create_udpsink_bin:676>: create_udpsink_bin failed
** ERROR: <create_sink_bin:781>: create_sink_bin failed
** ERROR: <create_processing_instance:815>: create_processing_instance failed
** ERROR: <create_pipeline:1326>: create_pipeline failed
** ERROR: <main:688>: Failed to create pipeline
Quitting
App run failed
ENV：
jetson Xavier NX Jetpack 4.6.1
CUDA 10.2

deepstream_app_config_copy.txt:
[application]
enable-perf-measurement=1
perf-measurement-interval-sec=5

[tiled-display]
enable=1
rows=1
columns=1
width=704
height=576
gpu-id=0
nvbuf-memory-type=0

[source0]
enable=1
type=3
#uri=file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4
uri=file:///home/dvadmin/wxp/safeHat/video/show-safetyhelmet.avi
num-sources=1
gpu-id=0
cudadec-memtype=0

[sink0]
enable=0
type=2
sync=0
gpu-id=0
nvbuf-memory-type=0

[osd]
enable=1
gpu-id=0
border-width=5
text-size=15
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Serif
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0

[streammux]
gpu-id=0
live-source=0
batch-size=1
batched-push-timeout=40000
width=704
height=576
enable-padding=0
nvbuf-memory-type=0

[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary_yoloV5.txt

[tests]
file-loop=0

**Comment by marcoslucianops** [comment]
At least one sink needs to be enabled, so you need to keep the `[sink] enable=1`. Check the documentation: https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_ref_app_deepstream.html#sink-group

**Comment by WangxuP** [comment]
> At least one sink needs to be enabled, so you need to keep the `[sink] enable=1`. Check the documentation: https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_ref_app_deepstream.html#sink-group

ok  thank you very much
