### ISSUE TITLE
mAP code for DeepStream-Yolo's .engine

### ISSUE THREAD

**Issue by ahmedalzuhair** [marcoslucianops/DeepStream-Yolo#187]
Hi @marcoslucianops 

I tried to calculate mAP using ultralytics: val.py on the .engine, but it does not seem to be compatible.

How are you calculating mAP?  

Thanks

**Comment by marcoslucianops** [comment]
I created the code to calculate the mAP but it may have errors because the output in DeepStream seems very similar to PyTorch as far I tested.

**Comment by ahmedalzuhair** [comment]
Results seem to be close to PyTorch. Is the code public?

**Comment by marcoslucianops** [comment]
It's not.

**Comment by ahmedalzuhair** [comment]
I'll modify the PyTorch version for now. Thanks!

**Comment by huytranvan2010** [comment]
> It's not. Maybe in the future.

Could you share the code to calculate mAP of Yolo's .engine?

**Comment by marcoslucianops** [comment]
> Could you share the code to calculate mAP of Yolo's .engine?

It's not available for public yet.
