### ISSUE TITLE
How to change the batch size

### ISSUE THREAD

**Issue by javiercalle97** [marcoslucianops/DeepStream-Yolo#188]
I want to change the batch size of the TensorRT model but in the [gen_wts_yoloV5.py] (https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/utils/gen_wts_yoloV5.py) file there is no option to modify this parameter. 

I thought that maybe adding the `batch=16` to the config file the problem would be solved, but the result is the same. How can I modify the batch size?

Thanks!

**Comment by pabsan-0** [comment]
I would add that you need to run `deepstream-app -c <cfg>` for the `.engine` file to be generated. Pipelines built using `gst-launch-1.0` will not spawn it: in addition to updating batch size and engine filename in `config_infer_primary_yoloV5.txt` you need to use the app to generate the engine file first (Jetpack 4.6 & DeepstreamSDK 6.0.0 on Jetson Xavier NX).

**Comment by marcoslucianops** [comment]
The main idea of this plugin is to use in custom DeepStream/GStreamer codes (C/C++ or python).
