### ISSUE TITLE
error on generating the engine file

### ISSUE THREAD

**Issue by kevincao8828** [marcoslucianops/DeepStream-Yolo#189]
@marcoslucianops Thank you very much for creating the great project. I tested it on the original yolov5s.pt, and it worked well. However, when I try to use our custom trained model, it encountered this error. I am totally stucked in here for days. Please help.!
Error Info:
Loading pre-trained weights
Loading weights of yolov5_shenmu_last complete
Total weights read: 7287258
Building YOLO network

      layer                        input               output         weightPtr
(0)   reorgV5                    3 x1280 x1280      12 x 640 x 640    0      
(1)   conv_silu                 12 x 640 x 640      32 x 640 x 640    3584   
(2)   conv_silu                 32 x 640 x 640      64 x 320 x 320    22272  
(3)   conv_silu                 64 x 320 x 320     128 x 160 x 160    96512  
(4)   conv_silu                128 x 160 x 160     256 x  80 x  80    392448 
(5)   conv_silu                256 x  80 x  80     512 x  40 x  40    1574144
(6)   conv_silu                512 x  40 x  40     256 x  40 x  40    1706240
(7)   maxpool                  256 x  40 x  40     256 x  40 x  40    1706240
(8)   route                           -            256 x  40 x  40    1706240
(9)   maxpool                  256 x  40 x  40     256 x  40 x  40    1706240
(10)  route                           -            256 x  40 x  40    1706240
(11)  maxpool                  256 x  40 x  40     256 x  40 x  40    1706240
(12)  route                           -           1024 x  40 x  40    1706240
(13)  conv_silu               1024 x  40 x  40     512 x  40 x  40    2232576
(14)  conv_silu                512 x  40 x  40     256 x  40 x  40    2364672
(15)  upsample                 256 x  40 x  40     256 x  80 x  80        -  
ERROR: [TRT]: 4: [layers.cpp::estimateOutputDims::1944] Error Code 4: Internal Error (route_16: all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at index 1. Input 0 shape: [256,80,80], Input 1 shape: [256,40,40])
deepstream-app: utils.cpp:147: int getNumChannels(nvinfer1::ITensor*): Assertion `d.nbDims == 3' failed.
Aborted (core dumped)

Environment: Jetson Nano, DeepStream 6.0
Yaml file:
# parameters
nc: 5  # number of classes
depth_multiple: 0.67  # model depth multiple
width_multiple: 0.75  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, BottleneckCSP, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, BottleneckCSP, [1024, False]],  # 9
  ]

# YOLOv5 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, BottleneckCSP, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, BottleneckCSP, [256, False]],  # 17

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, BottleneckCSP, [512, False]],  # 20

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, BottleneckCSP, [1024, False]],  # 23

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

**Comment by marcoslucianops** [comment]
You are trying to use YOLOv5 <= 3.1 model and it's not supported yet. It's only supported YOLOv5 >= 4.0 for now.

**Comment by kevincao8828** [comment]
will you add support for Yolov5 3?

**Comment by kevincao8828** [comment]
Thanks a lot! Looking forward to it.

**Comment by kevincao8828** [comment]
Hi, just checking out if YoloV5 3.0 supporting is still in your plan? One of our existing custom trained model is based on 3.0,  so it will be a gaint help if this project supports convert 3.0 model. Thanks again

**Comment by marcoslucianops** [comment]
Yes, I'm changing the code to better support for all YOLOv5 models (and to support new models like PPYOLO , YOLOX and YOLOv6).

**Comment by kevincao8828** [comment]
Great！ Thanks a lot. I am trying it now. It seems it had big change, it removed the gen_wts.py?

**Comment by kevincao8828** [comment]
Thanks a lot! I am trying it now!!!
