### ISSUE TITLE
about main program 

### ISSUE THREAD

**Issue by hejun888** [marcoslucianops/DeepStream-Yolo#19]
hi，could you please tell me where is the main program that links the various plugins

**Comment by marcoslucianops** [comment]
What do you mean by plugins?

**Comment by sameerk1304** [comment]
this repository is a nvidia deepstream plugin, it cant be used standalone, kindly go through deepstream to understand better

**Comment by marcoslucianops** [comment]
This repo is a `nvinfer` plugin. The program is the `deepstream-app` based on GStreamer pipeline.
