### ISSUE TITLE
compiling error on jetson nano: fatal error: cub/cub.cuh: No such file or directory

### ISSUE THREAD

**Issue by jeswin001** [marcoslucianops/DeepStream-Yolo#191]
Hi,
Many thanks for sharing this repo. But when i am trying to build this repo on jetson nano, its is giving error as "fatal error: cub/cub.cuh: No such file or directory". I used   "jetpack 4.6.1 and deepstream 6.0.1" also "jetpack 4.6.1 and deepstream 6.0" [combinations.[](url)]
![cub_files](https://user-images.githubusercontent.com/694503/174783180-73e78fb9-d225-4747-81fc-57a56c5e6ec1.jpg)

**Comment by marcoslucianops** [comment]
I updated the repo, please test with the new files.

**Comment by jeswin001** [comment]
Thank you sir..its working now..Can you please share a sample code to crop the yolo output and save the bounding rectangle only?.

**Comment by marcoslucianops** [comment]
Sorry, but I'm not providing samples, please check the nvidia sample apps.
