### ISSUE TITLE
怎么在运行时添加和删除视频源呢？

### ISSUE THREAD

**Issue by monoloxo** [marcoslucianops/DeepStream-Yolo#194]

**Comment by monoloxo** [comment]
> 需要修改deepstream源码实现和本项目无关

是的，我查资料好像要修改deepstream-app这个主程序，至于到底修改哪里，就不清楚了。

**Comment by sunjun** [comment]
我们修改完了 可以给我发邮件你的联系方式和你交流下思路

**Comment by marcoslucianops** [comment]
You need to use this YOLO plugin (nvinfer) in sample apps provided by NVIDIA. The deepstream-app is the main program and it's used as example.

Please send the messages in english.

**Comment by monoloxo** [comment]
> 我们修改完了 可以给我发邮件你的联系方式和你交流下思路

刚给你发了邮件，请大佬指教呀

**Comment by zoidburg** [comment]
check this the nvidia [deepstream app example](https://github.com/NVIDIA-AI-IOT/deepstream_reference_apps/tree/master/runtime_source_add_delete)

**Comment by monoloxo** [comment]
> check this the nvidia [deepstream app example](https://github.com/NVIDIA-AI-IOT/deepstream_reference_apps/tree/master/runtime_source_add_delete)

it is difficult for me,so i would like to get a easy way,but still thank you .
