### ISSUE TITLE
how to save the serialized engine in custom path?

### ISSUE THREAD

**Issue by thunder95** [marcoslucianops/DeepStream-Yolo#195]
I loaded wts weight file, however, I wish save the serialized engine in other path in order to load it next time efficiently . This path I have tried with the parameter "model-engine-file" also did not work.  Any idea for that, do I need to do some modification in nvinfer plugin?

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/issues/181

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/issues/181#issuecomment-1141464992

**Comment by thunder95** [comment]
@marcoslucianops Thanks for your quick reply, Sir.  So that means I have to modify the source code anyway, where the engine file were saved in the current path. Never mind, I will use another strategy to save this duplicated in your code.
