### ISSUE TITLE
yolov5  v6.1版本转换报错

### ISSUE THREAD

**Issue by LeFuGang** [marcoslucianops/DeepStream-Yolo#196]
Opening in BLOCKING MODE 
ERROR: Deserialize engine failed because file path: /data/lefugang/tensorrt/ai_box/deepstream/DeepStream-Yolo/yolo5s_model_b1_gpu0_fp32.engine open error
0:00:02.029512832 16338   0x7f4c002360 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1889> [UID = 1]: deserialize engine from file :/data/lefugang/tensorrt/ai_box/deepstream/DeepStream-Yolo/yolo5s_model_b1_gpu0_fp32.engine failed
0:00:02.029680544 16338   0x7f4c002360 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1996> [UID = 1]: deserialize backend context from engine from file :/data/lefugang/tensorrt/ai_box/deepstream/DeepStream-Yolo/yolo5s_model_b1_gpu0_fp32.engine failed, try rebuild
0:00:02.029760736 16338   0x7f4c002360 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 1]: Trying to create engine from model files

Loading pre-trained weights
Loading weights of yolov5s complete
Total weights read: 7295869
Building YOLO network

      layer                        input               output         weightPtr
(0)   conv_silu                  3 x 640 x 640      32 x 320 x 320    3584   
(1)   conv_silu                 32 x 320 x 320      64 x 160 x 160    22272  
(2)   conv_silu                 64 x 160 x 160      32 x 160 x 160    24448  
(3)   route                           -             64 x 160 x 160    24448  
(4)   conv_silu                 64 x 160 x 160      32 x 160 x 160    26624  
(5)   conv_silu                 32 x 160 x 160      32 x 160 x 160    27776  
(6)   conv_silu                 32 x 160 x 160      32 x 160 x 160    37120  
(7)   shortcut_linear: 4              -             32 x 160 x 160        -  
(8)   route                           -             64 x 160 x 160    37120  
(9)   conv_silu                 64 x 160 x 160      64 x 160 x 160    41472  
(10)  conv_silu                 64 x 160 x 160     128 x  80 x  80    115712 
(11)  conv_silu                128 x  80 x  80      64 x  80 x  80    124160 
(12)  route                           -            128 x  80 x  80    124160 
(13)  conv_silu                128 x  80 x  80      64 x  80 x  80    132608 
(14)  conv_silu                 64 x  80 x  80      64 x  80 x  80    136960 
(15)  conv_silu                 64 x  80 x  80      64 x  80 x  80    174080 
(16)  shortcut_linear: 13             -             64 x  80 x  80        -  
(17)  conv_silu                 64 x  80 x  80      64 x  80 x  80    178432 
(18)  conv_silu                 64 x  80 x  80      64 x  80 x  80    215552 
(19)  shortcut_linear: 16             -             64 x  80 x  80        -  
(20)  route                           -            128 x  80 x  80    215552 
(21)  conv_silu                128 x  80 x  80     128 x  80 x  80    232448 
(22)  conv_silu                128 x  80 x  80     256 x  40 x  40    528384 
(23)  conv_silu                256 x  40 x  40     128 x  40 x  40    561664 
(24)  route                           -            256 x  40 x  40    561664 
(25)  conv_silu                256 x  40 x  40     128 x  40 x  40    594944 
(26)  conv_silu                128 x  40 x  40     128 x  40 x  40    611840 
(27)  conv_silu                128 x  40 x  40     128 x  40 x  40    759808 
(28)  shortcut_linear: 25             -            128 x  40 x  40        -  
(29)  conv_silu                128 x  40 x  40     128 x  40 x  40    776704 
(30)  conv_silu                128 x  40 x  40     128 x  40 x  40    924672 
(31)  shortcut_linear: 28             -            128 x  40 x  40        -  
(32)  conv_silu                128 x  40 x  40     128 x  40 x  40    941568 
(33)  conv_silu                128 x  40 x  40     128 x  40 x  40    1089536
(34)  shortcut_linear: 31             -            128 x  40 x  40        -  
(35)  route                           -            256 x  40 x  40    1089536
(36)  conv_silu                256 x  40 x  40     256 x  40 x  40    1156096
(37)  conv_silu                256 x  40 x  40     512 x  20 x  20    2337792
(38)  conv_silu                512 x  20 x  20     256 x  20 x  20    2469888
(39)  route                           -            512 x  20 x  20    2469888
(40)  conv_silu                512 x  20 x  20     256 x  20 x  20    2601984
(41)  conv_silu                256 x  20 x  20     256 x  20 x  20    2668544
(42)  conv_silu                256 x  20 x  20     256 x  20 x  20    3259392
(43)  shortcut_linear: 40             -            256 x  20 x  20        -  
(44)  route                           -            512 x  20 x  20    3259392
(45)  conv_silu                512 x  20 x  20     512 x  20 x  20    3523584
(46)  conv_silu                512 x  20 x  20     256 x  20 x  20    3655680
(47)  maxpool                  256 x  20 x  20     256 x  20 x  20    3655680
(48)  maxpool                  256 x  20 x  20     256 x  20 x  20    3655680
(49)  maxpool                  256 x  20 x  20     256 x  20 x  20    3655680
(50)  route                           -           1024 x  20 x  20    3655680
(51)  conv_silu               1024 x  20 x  20     512 x  20 x  20    4182016
(52)  conv_silu                512 x  20 x  20     256 x  20 x  20    4314112
(53)  upsample                 256 x  20 x  20     256 x  40 x  40        -  
(54)  route                           -            512 x  40 x  40    4314112
(55)  conv_silu                512 x  40 x  40     128 x  40 x  40    4380160
(56)  route                           -            512 x  40 x  40    4380160
(57)  conv_silu                512 x  40 x  40     128 x  40 x  40    4446208
(58)  conv_silu                128 x  40 x  40     128 x  40 x  40    4463104
(59)  conv_silu                128 x  40 x  40     128 x  40 x  40    4611072
(60)  route                           -            256 x  40 x  40    4611072
(61)  conv_silu                256 x  40 x  40     256 x  40 x  40    4677632
(62)  conv_silu                256 x  40 x  40     128 x  40 x  40    4710912
(63)  upsample                 128 x  40 x  40     128 x  80 x  80        -  
(64)  route                           -            256 x  80 x  80    4710912
(65)  conv_silu                256 x  80 x  80      64 x  80 x  80    4727552
(66)  route                           -            256 x  80 x  80    4727552
(67)  conv_silu                256 x  80 x  80      64 x  80 x  80    4744192
(68)  conv_silu                 64 x  80 x  80      64 x  80 x  80    4748544
(69)  conv_silu                 64 x  80 x  80      64 x  80 x  80    4785664
(70)  route                           -            128 x  80 x  80    4785664
(71)  conv_silu                128 x  80 x  80     128 x  80 x  80    4802560
(72)  conv_silu                128 x  80 x  80     128 x  40 x  40    4950528
(73)  route                           -            256 x  40 x  40    4950528
(74)  conv_silu                256 x  40 x  40     128 x  40 x  40    4983808
(75)  route                           -            256 x  40 x  40    4983808
(76)  conv_silu                256 x  40 x  40     128 x  40 x  40    5017088
(77)  conv_silu                128 x  40 x  40     128 x  40 x  40    5033984
(78)  conv_silu                128 x  40 x  40     128 x  40 x  40    5181952
(79)  route                           -            256 x  40 x  40    5181952
(80)  conv_silu                256 x  40 x  40     256 x  40 x  40    5248512
(81)  conv_silu                256 x  40 x  40     256 x  20 x  20    5839360
(82)  route                           -            512 x  20 x  20    5839360
(83)  conv_silu                512 x  20 x  20     256 x  20 x  20    5971456
(84)  route                           -            512 x  20 x  20    5971456
(85)  conv_silu                512 x  20 x  20     256 x  20 x  20    6103552
(86)  conv_silu                256 x  20 x  20     256 x  20 x  20    6170112
(87)  conv_silu                256 x  20 x  20     256 x  20 x  20    6760960
(88)  route                           -            512 x  20 x  20    6760960
(89)  conv_silu                512 x  20 x  20     512 x  20 x  20    7025152
(90)  route                           -            128 x  80 x  80    7025152
(91)  conv_logistic            128 x  80 x  80     255 x  80 x  80    7058047
(92)  yolo                     255 x  80 x  80            -               -  
(93)  route                           -            256 x  40 x  40    7058047
(94)  conv_logistic            256 x  40 x  40     255 x  40 x  40    7123582
(95)  yolo                     255 x  40 x  40            -               -  
(96)  route                           -            512 x  20 x  20    7123582
(97)  conv_logistic            512 x  20 x  20     255 x  20 x  20    7254397
(98)  yolo                     255 x  20 x  20            -               -  

Number of unused weights left: 41472
deepstream-app: yolo.cpp:389: NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&): Assertion `0' failed.
Aborted (core dumped)

version is  yolov5  v6.1 

model is yolov5s.pt

**Comment by marcoslucianops** [comment]
Is it a custom model?

**Comment by LeFuGang** [comment]
> 



> Is it a custom model?

yes, now it is ok!  I solved it，thanks
