### ISSUE TITLE
I got only one output for my custom YOLOv5s model

### ISSUE THREAD

**Issue by 7633** [marcoslucianops/DeepStream-Yolo#197]
When I tryed YOLOv5 model on the same video from pytorch, I got 2-3-4 detections per frame, after converting I got only one per frame.
My model detects only one class and it changed to 320x320 resolution. Rest of model is the same from yolov5s. In another convertions, e.g. to tflite it works fine.
I tried to put "cout << " in NvDsInferParseCustomYolo and got that there're only one numBoxes. 

What's wrong? How can I check numboxes count?

**Comment by marcoslucianops** [comment]
The TensorRT conversion decreases the accuracy of the model.

**Comment by ToonH** [comment]
What's the expected difference in accuracy between PyTorch and TensorRT? I've trained a single-class yolov4 csp model, but for every 10 predictions in TensorRT at a confidence threshold of .47, I'm only getting 3 predictions in PyTorch at a confidence threshold of 0.3. The non-similar, extra predictions made by the TensorRT model are also completely off.

Do you have any idea as to what might cause this? Really feels like a TRT conversion issue, but I can't quite put my finger on it.
