### ISSUE TITLE
Mixing multiple pipelines with different yolo models

### ISSUE THREAD

**Issue by nemosupremo** [marcoslucianops/DeepStream-Yolo#198]
I'm trying to find the cause of a possible race condition in this library. I have 2 deepstream pipelines, one with a yolov4 coco model, and another with a trained yolov5 model. When running them together, after the yolov5 model starts I get:

```
WARNING: Num classes mismatch. Configured: 1, detected by network: 80
```

And then the application segfaults. The config for both engines is configured correctly with the correct number of detected classes (and regardless I don't think num classes mismatch should cause a segfault). Any idea what could be wrong here?

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/issues/193#issuecomment-1164469610

**Comment by nemosupremo** [comment]
I'm not using Yolo as a secondary gie. I have two independent pipelines both running yolo as a primary gie.

**Comment by nemosupremo** [comment]
Actually it looks like I'm experiencing this issue here, in which the fix is the same:

https://github.com/marcoslucianops/DeepStream-Yolo/issues/152#issuecomment-1064035096

I'm wondering if there's a fix where `YOLOLAYER_PLUGIN_VERSION` isn't hardcoded

**Comment by marcoslucianops** [comment]
Using the same files, the TensorRT will use the YoloLayer (version 1) for both models. So, you need to change the version to have 2 different YoloLayers in the TensorRT registry.

**Comment by nemosupremo** [comment]
Another problem I forsee, the values:

```
uint kNUM_BBOXES;
uint kNUM_CLASSES;
```

Are global variables. It's trivial to fix `kNUM_CLASSES`, but `kNUM_BBOXES` seems like it could pose problems if it's different between models.

**Comment by marcoslucianops** [comment]
There's no problem in the global variables. You need to set different YoloLayer versions for each nvinfer (GIE). Please see: https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/multipleGIEs.md
