### ISSUE TITLE
“fatal error: NvCaffeParser.h: No such file or directory” in Jetson docker container

### ISSUE THREAD

**Issue by sxke** [marcoslucianops/DeepStream-Yolo#199]
Platform: Jetson NX
Deepstream: 6.1
JetPack: 5.0.1 DP
Docker Image: nvcr.io/nvidia/deepstream-l4t:6.1-samples

 When I try compile the lib in docker container on Jetson NX ,I got following error : 
"/opt/nvidia/deepstream/deepstream/sources/includes/nvdsinfer_custom_impl.h:126:10: fatal error: NvCaffeParser.h: No such file or directory"

But on host ,its ok.

**Comment by marcoslucianops** [comment]
You should use the deepstream-l4t:6.1-iot image.
