### ISSUE TITLE
app run failed

### ISSUE THREAD

**Issue by hejun888** [marcoslucianops/DeepStream-Yolo#20]
hi，could you please tell me how solve this question?
![1](https://user-images.githubusercontent.com/28728850/103846920-2643c400-50da-11eb-8301-de30040e78a8.jpeg)

**Comment by marcoslucianops** [comment]
Try to use this command

```
export DISPLAY=:0
```

**Comment by hejun888** [comment]
add this command in .bashrc?

**Comment by marcoslucianops** [comment]
> add this command in .bashrc?

You need use only one time
