### ISSUE TITLE
Yolor can not generate the cfg and wts files in colab.

### ISSUE THREAD

**Issue by minhvogremsy** [marcoslucianops/DeepStream-Yolo#201]
I try convert yolor in colab env but after run not error but i don't see 2 file cfg and wts. But when convert with yolov5 it's good. Please help my or give me some advice. Have a nice day! Thanks you.

**Comment by marcoslucianops** [comment]
Which command are you using?

**Comment by minhvogremsy** [comment]
I used this code in colab but i can not convert
```
!git clone https://github.com/WongKinYiu/yolor
!pip install --upgrade pip
%cd yolor
# pip install required packages
!pip install Cython
!pip install -qr requirements.txt
!git clone https://github.com/JunnYu/mish-cuda
%cd mish-cuda
!python setup.py build install
%cd ..
!git clone https://github.com/fbcotter/pytorch_wavelets
%cd pytorch_wavelets
!pip install .
%cd ..
!python3 gen_wts_yolor.py -w yolor_csp.pt -c cfg/yolor_csp.cfg
```
I figure out that when use try catch I am not sure this is error cause crash

> wts_file : cfg/yolor_csp.wts
> IOPub data rate exceeded.
> The notebook server will temporarily stop sending output
> to the client in order to avoid crashing it.
> To change this limit, set the config variable
> `--NotebookApp.iopub_data_rate_limit`.
> 
> Current values:
> NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
> NotebookApp.rate_limit_window=3.0 (secs)
>

**Comment by marcoslucianops** [comment]
It seems an error in Colab enviroment, but I don't have experience with Notebook and Colab.

**Comment by minhvogremsy** [comment]
Can I convert Yolor in Jetson Xavier NX ?

**Comment by marcoslucianops** [comment]
Yes

**Comment by minhvogremsy** [comment]
Thank you! Perhaps, I will try in jetson Xavier.
