### ISSUE TITLE
YOLOv7 (by Chien-Yao Wang and Alexey Bochkovskiy) works

### ISSUE THREAD

**Issue by JetsonPaul** [marcoslucianops/DeepStream-Yolo#204]
Hi, just wanted to let you know that [YOLOv7](https://github.com/WongKinYiu/yolov7)  works without any issue. Just use the [gen_wts_yoloV5.py](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/utils/gen_wts_yoloV5.py) script with the .yaml file in cfg/training and the weight you want to use. Rest is the same compared to YOLOv5.

**Comment by marcoslucianops** [comment]
It should not work correctly because there are some layers that are not implemented in the [gen_wts_yoloV5.py](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/utils/gen_wts_yoloV5.py) file (MP, SPPCSPC, RepConv, IDetect, etc). The support will be added soon.

**Comment by blafasel42** [comment]
@marcoslucianops that sounds good. any idea about a  ETA? v7 seems really interesting

**Comment by marcoslucianops** [comment]
Added support for YOLOv7.
