### ISSUE TITLE
When using two rtsp, one is not as efficient.

### ISSUE THREAD

**Issue by m2msoft** [marcoslucianops/DeepStream-Yolo#205]
My settings are as below:

[source0]
enable=1
type=4 													#Type - 1=CameraV4L2 2=URI 3=MultiURI 4=RTSP
uri=rtsp://192.168.0.2:554/sub/ch7
num-extra-surfaces=5									#디코더에서 제공하는 최소 디코딩 표면 외에 표면의 수입니다
select-rtp-protocol=4									#rtsp 전송 프로토콜 4: tcp 전용
rtsp-reconnect-interval-sec=60
cudadec-memtype=2
gpu-id=0

[sink0]
enable=1
type=4 													#Type - 1=FakeSink 2=EglSink 3=File 4=RTSPStreaming 5=nvdrmvideosink
codec=1													#1=h264 2=h265
enc-type=1												#encoder type 0=Hardware 1=Software
source-id=0
sync=0
bitrate=4000000
profile=0												#H264 Profile - 0=Baseline 2=Main 4=High
														#H265 Profile - 0=Main 1=Main10
rtsp-port=8554											# set below properties in case of RTSPStreaming
udp-port=5400
nvbuf-memory-type=3

[source1]
enable=1
type=4													#Type - 1=CameraV4L2 2=URI 3=MultiURI 4=RTSP
uri=rtsp://192.168.0.1:554/sub/ch7
num-extra-surfaces=5									#디코더에서 제공하는 최소 디코딩 표면 외에 표면의 수입니다
select-rtp-protocol=4									#rtsp 전송 프로토콜 4: tcp 전용
rtsp-reconnect-interval-sec=60
cudadec-memtype=2
gpu-id=0

[sink1]
enable=1
#Type - 1=FakeSink 2=EglSink 3=File 4=RTSPStreaming 5=nvdrmvideosink
type=4
#1=h264 2=h265
codec=1
#encoder type 0=Hardware 1=Software
enc-type=1
source-id=1
sync=0
bitrate=4000000
#H264 Profile - 0=Baseline 2=Main 4=High
#H265 Profile - 0=Main 1=Main10
profile=0
# set below properties in case of RTSPStreaming
rtsp-port=8555
udp-port=5401
nvbuf-memory-type=3

However, if you look at the FPS, the first is normal, but the second is less efficient.

**PERF:  FPS 0 (Avg)    FPS 1 (Avg)
**PERF:  0.00 (0.00)    0.00 (0.00)
** INFO: <bus_callback:194>: Pipeline ready

** INFO: <bus_callback:180>: Pipeline running

**PERF:  18.10 (17.89)  15.55 (11.99)
**PERF:  13.34 (15.15)  10.50 (11.99)
**PERF:  16.60 (15.70)  9.80 (11.16)
**PERF:  13.53 (14.74)  3.58 (8.86)
**PERF:  12.91 (14.62)  0.76 (7.12)
**PERF:  15.32 (14.72)  0.79 (6.00)
**PERF:  13.17 (14.49)  0.79 (5.22)
**PERF:  15.54 (14.64)  0.79 (4.64)

GPU and CPU usage is less than 20%.

Please tell me how to solve it.

Thanks.

**Comment by marcoslucianops** [comment]
Your deepstream_app_config.txt file shoud be

```
[application]
enable-perf-measurement=1
perf-measurement-interval-sec=5

[tiled-display]
enable=1
rows=2
columns=1
width=640
height=720
gpu-id=0
nvbuf-memory-type=0

[source0]
enable=1
type=3
uri=rtsp://192.168.0.1:554/sub/ch7
num-sources=1
gpu-id=0
cudadec-memtype=0

[source1]
enable=1
type=3
uri=rtsp://192.168.0.2:554/sub/ch7
num-sources=1
gpu-id=0
cudadec-memtype=0

[sink0]
enable=1
type=4
codec=1
enc-type=0
sync=0
bitrate=4000000
profile=0
rtsp-port=8554
udp-port=5400
source-id=0

[sink1]
enable=1
type=4
codec=1
enc-type=0
sync=0
bitrate=4000000
profile=0
rtsp-port=8555
udp-port=5401
source-id=1

[osd]
enable=1
gpu-id=0
border-width=5
text-size=15
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Serif
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0

[streammux]
gpu-id=0
live-source=1
batch-size=2
batched-push-timeout=40000
width=1920
height=1080
enable-padding=0
nvbuf-memory-type=0

[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary.txt

[tests]
file-loop=0

```

Also you need to change the `batch-size` in the config_infer_primary file to 2 (remember to change the `model-engine-file`)
