### ISSUE TITLE
Is there a special reason for naming inputBlobName == "data"?

### ISSUE THREAD

**Issue by youngjae-avikus** [marcoslucianops/DeepStream-Yolo#206]
We use the preproc plug-in from deepstream6, where it matches inputBlobName with 'input_1' by default, 
otherwise the execution fails
So, Is there a special reason for naming inputBlobName == "data"?

https://github.com/marcoslucianops/DeepStream-Yolo/blob/f621c0f4294939037de3e779d13db853e515ff01/nvdsinfer_custom_impl_Yolo/nvdsinfer_yolo_engine.cpp#L45

**Comment by youngjae-avikus** [comment]
https://docs.nvidia.com/metropolis/deepstream/6.0.1/dev-guide/text/DS_plugin_gst-nvdspreprocess.html

I think uesr can modify the `tensor-name` from "**input_1**" to "**data**" in property
tensor-name | network input layer name | String | tensor-name=Input_1

**Comment by marcoslucianops** [comment]
It's a generic name. There's no special reason to use `data`.
