### ISSUE TITLE
deepstream-app: utils.cpp:104: std::vector<float> loadWeights(std::__cxx11::string, const string&): Assertion `count > 0 && "\nInvalid .wts file."' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by formerlya** [marcoslucianops/DeepStream-Yolo#207]
deepstream-app version 6.0.1
DeepStreamSDK 6.0.1
CUDA Driver Version: 10.2
CUDA Runtime Version: 10.2
TensorRT Version: 8.2
cuDNN Version: 8.2
libNVWarp360 Version: 2.0.1d3

I trained yolov5n.pt(v6.0)
Then I am implementing mobile phone detection of yolov5n v6.0 with deepstream6.0. 
when I use deepstream's gen_wts_yoloV5.py to get .wts .cfg,done. 
When I put them into deepstream and compiled and modified the relevant files,error.
![image](https://user-images.githubusercontent.com/88373367/179208727-420198fb-b587-4884-a9c1-7aa0092ef961.png)

![image](https://user-images.githubusercontent.com/88373367/179208855-b1cdc5a7-c2aa-4efb-a9b5-dd7a9f8bec28.png)

**Comment by formerlya** [comment]
![image](https://user-images.githubusercontent.com/88373367/179209428-57ff75cf-5e90-411e-bd98-a7c015d8e2b9.png)
![image](https://user-images.githubusercontent.com/88373367/179209489-c1affcff-1a69-4be4-a446-2e27f89f54fd.png)

**Comment by formerlya** [comment]
![image](https://user-images.githubusercontent.com/88373367/179209685-6cc006cc-c7cd-4fbb-9af0-9933c95e02e4.png)

**Comment by marcoslucianops** [comment]
The wts file is wrong.

**Comment by formerlya** [comment]
yes, my wts file is wrong. I use the newest gen_wts_yoloV5.py it say 
"YOLOv5  2022-5-16 Python-3.8.13 torch-1.8.0 CPU

'cat' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
"
When I use the gen_wts_yoloV5.py download 60+ days ago, it worked.
Then I get the right .wts for me.
So it's some version problem? I succeeded two months ago.

**Comment by marcoslucianops** [comment]
Please install

```
sudo apt-get install coreutils
```

And try again using the new `gen_wts_yoloV5.py` file

**Comment by EdouardEPFL** [comment]
I obtain the exact same error using the last gen_wts_yoloV5.py maybe something is still wrong with it ?
Ps: coreutils is already installed and up to date.
-----------
I'm just trying to use the default yolov5s or yolov5n models given by the yolov5 repo, and not a specific trained one. Hence, if you're not able to solve the problem, I would be very happy with the yolov5s.wts or yolov5n.wts that works :)

Thank you in advance for any kind of help

**Comment by formerlya** [comment]
> I obtain the exact same error using the last gen_wts_yoloV5.py maybe something is still wrong with it ? Ps: coreutils is already installed and up to date.
> 
> I'm just trying to use the default yolov5s or yolov5n models given by the yolov5 repo, and not a specific trained one. Hence, if you're not able to solve the problem, I would be very happy with the yolov5s.wts or yolov5n.wts that works :)
> 
> Thank you in advance for any kind of help

My problem is the version, then I use the old one.But I didn't try the newest. 
If you use the default yolo5,download the newest deepstream-yolo and install all the packages(check one by one). 
When generate the wts file, it should just print YOLOv5 2022-5-16 Python-3.8.13……
Good luck!

**Comment by EdouardEPFL** [comment]
> > I obtain the exact same error using the last gen_wts_yoloV5.py maybe something is still wrong with it ? Ps: coreutils is already installed and up to date.
> > I'm just trying to use the default yolov5s or yolov5n models given by the yolov5 repo, and not a specific trained one. Hence, if you're not able to solve the problem, I would be very happy with the yolov5s.wts or yolov5n.wts that works :)
> > Thank you in advance for any kind of help
> 
> My problem is the version, then I use the old one.But I didn't try the newest. If you use the default yolo5,download the newest deepstream-yolo and install all the packages(check one by one). When generate the wts file, it should just print YOLOv5 2022-5-16 Python-3.8.13…… Good luck!

Would it be possible to send me the old one ? Because I already have the configuration that you suggest i.e "the newest deepstream-yolo" but I still have the same error.

Thank you in advance

**Comment by formerlya** [comment]
Of course.
What's your email address?

**Comment by EdouardEPFL** [comment]
edouard.deponnat "arobase" epfl.ch

Thank you very much

**Comment by formerlya** [comment]
edouard.deponnat@epfl.ch？
I searched that the epfl.ch is your college.
Have you received the file?
My pleasure.

**Comment by EdouardEPFL** [comment]
> [edouard.deponnat@epfl.ch](mailto:edouard.deponnat@epfl.ch)？ I searched that the epfl.ch is your college. Have you received the file? My pleasure.

You're right, I confirm that I received the file. Thank you again !

**Comment by marcoslucianops** [comment]
There's a `cat` command in the end of the gen_wts file. You need to install the package to run code without issues.

**Comment by gzcyyds** [comment]
> [edouard.deponnat@epfl.ch](mailto:edouard.deponnat@epfl.ch)？ I searched that the epfl.ch is your college. Have you received the file? My pleasure.

I obtain the exact same error using the last gen_wts_yoloV5.py ，Would it be possible to send me the old one ? very thanks

**Comment by marcoslucianops** [comment]
Run `sudo apt install --reinstall coreutils` to install `cat` command.
