### ISSUE TITLE
How do I insert a YOLOV5 inference module into deepstream in command-line

### ISSUE THREAD

**Issue by hejun888** [marcoslucianops/DeepStream-Yolo#21]
hi,How do I insert a YOLOV5 inference engine  into a deepstream as below
![1](https://user-images.githubusercontent.com/28728850/103874607-57d58300-510c-11eb-84ae-83920b1df1ee.png)

very thanks for this help

**Comment by marcoslucianops** [comment]
Replace path of primary inference to your config_infer_primary.txt path and execute your program with this command (with path to your libmyplugins.so file)

```
LD_PRELOAD=./libmyplugins.so ...
```

Where ... = your program command

**Comment by hejun888** [comment]
That doesn't seem to work,Is there any other way?Is it possible to place libmyplugins.so in config_infer_primary.txt like 'custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_yolo.so' in config_infer_primary.txt

**Comment by marcoslucianops** [comment]
> That doesn't seem to work,Is there any other way?

I know only this way for YOLOv5. Did you test like this?

```
LD_PRELOAD=./libmyplugins.so python3 deepstream.py
```

>Is it possible to place libmyplugins.so in config_infer_primary.txt like 'custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_yolo.so' in config_infer_primary.txt

Not for now, libnvdsinfer_custom_impl_yolo.so is a deepstream lib and libmyplugins.so is a tensorrtx lib. Need both libs to make YOLOv5 works.

**Comment by hejun888** [comment]
Can we compile two .so files(libmyplugins.so and libnvdsinfer_custom_impl_yolo.so ) into a single .so file in the following stages?
![1](https://user-images.githubusercontent.com/28728850/104016346-22569580-51f1-11eb-91d9-f4f383125139.png)

**Comment by marcoslucianops** [comment]
> Can we compile two .so files(libmyplugins.so and libnvdsinfer_custom_impl_yolo.so ) into a single .so file in the following stages?

I will test

**Comment by hejun888** [comment]
hi,What's going on? Did the test work

**Comment by marcoslucianops** [comment]
> hi,What's going on? Did the test work

Yes, I updated the repo, use my new files.

Now you can run with:
```
deepstream-app -c deepstream_app_config.txt
```

**Comment by hejun888** [comment]
thanks，it’s OK . Now it's easier than before.
