### ISSUE TITLE
Failed to create NvDsInferContext instance

### ISSUE THREAD

**Issue by NidhoggBo** [marcoslucianops/DeepStream-Yolo#210]

**Comment by marcoslucianops** [comment]
Can you provide more info about the error (output log, etc)?

**Comment by NidhoggBo** [comment]
> 您能否提供有关错误的更多信息（输出日志等）？

ERROR: [TRT]: 1: [stdArchiveReader.cpp:: StArchiveReader::35] Error Code 1: Seri
alization (Serialization assertion safeVersionRead
== safeSerializationVersion f
ailed.Version tag does not match. Note: Current Version: 0, Serialized Engine Ve
rsion: 43)
ERROR: [TRT]: 4: [runtime.cpp: :deserializeCudaEngine::50] Error Code 4: Internal
Error (Engine deserialization failed.)
ERROR: Deserialize engine failed from file: /opt/nvidia/deepstream/deepstream-6
0/sources/DeepStream-Yolo-master/fire.engine
0:00:02.911339599 12042
0x7f2c001f80 WARN
nvinfer gstnvinfer.c
pp: 635:gst nvinfer
logger: primary_gie> NvDsInferContext[UID 1]: Warning from NV
DsInferContextImpl::deserializeEngineAndBackend()envdsinfer_context_impl.cpp:18
89> [UID = 1]: deserialize engine from file :/opt/nvidia/deepstream/deepstream-6
./sources/DeepStream-Yolo-master/fire.engine failed
0:00:02.912502410 12042
0x7f2c001f80 WARN
nvinfer gstnvinfer.c
pp:635:gst nvinfer_Logger:sprimary_gies NVDsInferContext[UID 1]: Warning fror Nv
DsInferContextImpl::generateBackendcontext() <nvdsinfer context impl.cpp: 1996> [
UID
= 1]: deserialize backend context from engine from file: /opt/nvidia/deepstr
eam/deepstream-6.0/sources/DeepStream-Yolo-master/fire.engine failed, try rebuil
d
0:00:02.912551266 12042
0x7f2c001f80 INFO
nvinfer gstnvinfer.c
pp:638:gst _nvinfer_logger: <primary_gie> NvDsInferContext[UID 1]: Info from NUDsI
nferContextImpl: :buildModel() <nvdsinfer context impl.cpp: 1914> [UID = 1]: Tryin
g to create engine from model files
YOLO config file or weights file ls not specified
ERROR: Failed to create network using custom network creation function
ERROR: Failed to get cuda engine from custom library API
0:00:03.389620523 12042
0x7f2c001f80 ERROR
nvinfer gstnvinfer.c
pp:632:gst_nvinfer_logger:<primary gie> NVDsInferContext[UID 1]: Error in NUDsIn
fercontextImpl::buildModel()snvdsinfercontext_impl.cpp:1934>[UID=1]:butld
engine file failed
0:00:03.390733904 12042
0x7f2c001f80 ERROR
nvinfer gstnvinfer.c
pp:632:gst_nvinfer_logger:<primary_gie> NVDsInferContext[UID 1]: Error in NVDSIn
ferContextImpl::generateBackendcontext()envdsinfer_context_impl.cpp:2020>[UID
= 17: build backend context failed
0:：00:03,390781354 12042
0x7f2c001f80 ERROR
nvinfer gstnvinfer.c
pp:632:gst_nvinfer_logger:<primary_gle> NVDsInferContext[UID 1]: Error in NVDsIn
ferContextImpl::initialize() envdsinfer_context impl.cpp:1257> [UID = 1]: genera
te backend failed, check config file settings
0:00:03.391385911 12042
0x7f2c001f80 WARN
nuitfer gstnvinfer.c
pp:841:gst _nvinfer _start: ‹primary_gies error: Failed to create NuDsInferContext
instance
0:00:03.391426694 12042
0x7f2c001f80 WARN
nvinfer gstnvinfer.c
pp: 841:gst nvinfer_start:<primary_gies error: Config file path: /opt/nvidia/deep
stream/deepstream-6.0/sources/DeepStream-Yolo-master/config_infer_primary_yolov5
- txt, NVDsInfer Error: NVDSINFER_CONFIG_FAILED
** ERROR: main:707>: Failed to set pipeline to PAUSED
Quitting
ERROR from primary gie: Failed to create NVDSInferContext instance
ferContextImpl: :generateBackendContext() <nvdsinfer context _impl.cpp:2020> [UID
= 11: build backend context failed
0:00:03.390781354 12042
0x7f2C001f80 ERROR
nvinfer gstnvinfer.c
pp: 632:gst nvinfer_logger: <primary _gie> NvDsInferContext[UID 1]: Error in NUDsIn
ferContextImpl: :initialize() snvdsinfer_context _impl.cpp:1257> [UID = 1]: genera
te backend failed, check config file settings
0:00:03.391385911 12042
0x7f2c001f80 WARN
nvinfer gstnvinfer.c
pp:841:gst_ nvinfer_start: <primary gie> error: Failed to create NuDsInferContext
instance
0:00:03.391426694 12042
0x7f2c001f80 WARN
nvinfer gstnvinfer.c
pp: 841:gst _nvinfer_start: sprimary_ gie> error: Config file path: /opt/nvidia/deep
stream/deepstream-6.0/sources/Deepstream-Yolo-master/config_infer_primary_yolov5
• txt, NVDsInfer Error: NVDSINFER CONFIG FAILED
** ERROR: main: 707>: Failed to set pipeline to PAUSED
Quitting
ERROR from primary _gie: Failed to create NvDsInferContext instance
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-n
vinfer/gstnvinfer.cpp(841): gst nvinfer_start (): /GstPipeline:pipeline/GstBin:p
rimary _gie bin/GstNvInfer:primary gie:
Config file path: /opt/nvidia/deepstream/deepstream-6.0/sources/Deepstream-Yolo-
master/config_infer _primary_yolov5.txt, NVDsInfer Error: NVDSINFER CONFIG FAILED
App run failed

**Comment by NidhoggBo** [comment]
[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format-o
#custom-network-config=yolov5s.cfg
#model-file=yolov5s.wts
model-engine-file=fire.engine
#int8-calib-file-calib.table
labelfile-path=labels.txt
batch-size=1
network-mode=0
num-detected-classes-1
interval=0
gie-unique-id=-1
process-mode-1
network-type=0
cluster-mode=4
maintain-aspect-ratio=1
parse-bbox-func-name=NvDsInferParseVolo
custom-lib-path=nvdsinfer custom impl Yolo/libnvdsinfer custom implYolo.so
engine-create-func-name=NVDsInferYoloCudaEngineGet
[class-attrs-all]
pre-cluster-threshold=0



it's my config_infer_primary_yoloV5.txt

**Comment by marcoslucianops** [comment]
Are you generating the cfg and wts files using `gen_wts_yoloV5.py` file?

**Comment by NidhoggBo** [comment]
> Are you generating the cfg and wts files using `gen_wts_yoloV5.py` file?

i am using what's already generated engine

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv5.md
