### ISSUE TITLE
Question about output size about input size

### ISSUE THREAD

**Issue by youngjae-avikus** [marcoslucianops/DeepStream-Yolo#212]
Hello
I'm curious about the input and output size of the current yolo implementation
For example, if the model input is defined as 640(W)x386(H),
If the image size is 896(W)x504(H), will the final box coordinates (scaled) be taken in a ratio other than the 896(W)x504(H) size?

In other words, 640/386 = 1.6667 | 896/504 = 1.7777 Does the ratio come out differently?

Thank you!

**Comment by marcoslucianops** [comment]
On a DeepStream pipeline, the final bbox coords is related to streammux size.

**Comment by youngjae-avikus** [comment]
I asked because there is an issue.
In DeepStream 6.0.1 the preproc plug-in is used for the ROI part
The box coordinates do not match in the following points, so the output occurs

- When ROI size does not fit model aspect ratio 
- When ROI overlaps

Are you interested in these issues?

**Comment by marcoslucianops** [comment]
Please check: https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvdspreprocess.html

**Comment by youngjae-avikus** [comment]
Thank you for reply
There's been a problem because I set it out of the ROI
Let's close the issue
