### ISSUE TITLE
App run failed  after running deepstream-app -c deepstream_app_config.txt

### ISSUE THREAD

**Issue by chengzihencai** [marcoslucianops/DeepStream-Yolo#214]
There is something wrong after running deepstream-app -c deepstream_app_config.txt 
generating the cfg and wts files using file: gen_wts_yoloV5.py
`
Using winsys: x11 
ERROR: Could not open lib: /opt/nvidia/deepstream/deepstream-6.0/sources/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so, error string: /opt/nvidia/deepstream/deepstream-6.0/sources/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so: cannot open shared object file: No such file or directory
0:00:00.631199918 11777      0x35d2360 ERROR                nvinfer gstnvinfer.cpp:632:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1248> [UID = 1]: Could not open custom lib: (null)
0:00:00.631298602 11777      0x35d2360 WARN                 nvinfer gstnvinfer.cpp:841:gst_nvinfer_start:<primary_gie> error: Failed to create NvDsInferContext instance
0:00:00.631334312 11777      0x35d2360 WARN                 nvinfer gstnvinfer.cpp:841:gst_nvinfer_start:<primary_gie> error: Config file path: /opt/nvidia/deepstream/deepstream-6.0/sources/DeepStream-Yolo/config_infer_primary_yoloV5.txt, NvDsInfer Error: NVDSINFER_CUSTOM_LIB_FAILED
** ERROR: <main:707>: Failed to set pipeline to PAUSED
Quitting
ERROR from primary_gie: Failed to create NvDsInferContext instance
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvinfer/gstnvinfer.cpp(841): gst_nvinfer_start (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
Config file path: /opt/nvidia/deepstream/deepstream-6.0/sources/DeepStream-Yolo/config_infer_primary_yoloV5.txt, NvDsInfer Error: NVDSINFER_CUSTOM_LIB_FAILED
App run failed
`
`deepstream-app version 6.0.1
DeepStreamSDK 6.0.1
CUDA Driver Version: 10.2
CUDA Runtime Version: 10.2
TensorRT Version: 8.0
cuDNN Version: 8.2
libNVWarp360 Version: 2.0.1d3
Jetpack 4.6 
yolov5s 6.0 (untrained)
`

**Comment by marcoslucianops** [comment]
You need to compile the lib

```
CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo
```

**Comment by chengzihencai** [comment]
Thanks for help! I try to compile the lib and  run deepstream-app -c deepstream_app_config.txt,then I get : 
`
Using winsys: x11 
ERROR: Deserialize engine failed because file path: /home/lcfc/Desktop/DeepStream-Yolo/model_b1_gpu0_fp32.engine open error
0:00:02.222679973 13772      0x17652f0 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1889> [UID = 1]: deserialize engine from file :/home/lcfc/Desktop/DeepStream-Yolo/model_b1_gpu0_fp32.engine failed
0:00:02.222983719 13772      0x17652f0 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1996> [UID = 1]: deserialize backend context from engine from file :/home/lcfc/Desktop/DeepStream-Yolo/model_b1_gpu0_fp32.engine failed, try rebuild
0:00:02.223034568 13772      0x17652f0 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 1]: Trying to create engine from model files

Loading pre-trained weights
Loading weights of yolov5s complete
Total weights read: 7254397
Building YOLO network

        Layer                         Input Shape         Output Shape        WeightPtr
(0)     conv_silu                     [3, 640, 640]       [32, 320, 320]      3584
(1)     conv_silu                     [32, 320, 320]      [64, 160, 160]      22272
(2)     conv_silu                     [64, 160, 160]      [32, 160, 160]      24448
(3)     route: 1                      -                   [64, 160, 160]      -
(4)     conv_silu                     [64, 160, 160]      [32, 160, 160]      26624
(5)     conv_silu                     [32, 160, 160]      [32, 160, 160]      27776
(6)     conv_silu                     [32, 160, 160]      [32, 160, 160]      37120
(7)     shortcut_add_linear: 4        [32, 160, 160]      [32, 160, 160]      -
(8)     route: 7, 2                   -                   [64, 160, 160]      -
(9)     conv_silu                     [64, 160, 160]      [64, 160, 160]      41472
(10)    conv_silu                     [64, 160, 160]      [128, 80, 80]       115712
(11)    conv_silu                     [128, 80, 80]       [64, 80, 80]        124160
(12)    route: 10                     -                   [128, 80, 80]       -
(13)    conv_silu                     [128, 80, 80]       [64, 80, 80]        132608
(14)    conv_silu                     [64, 80, 80]        [64, 80, 80]        136960
(15)    conv_silu                     [64, 80, 80]        [64, 80, 80]        174080
(16)    shortcut_add_linear: 13       [64, 80, 80]        [64, 80, 80]        -
(17)    conv_silu                     [64, 80, 80]        [64, 80, 80]        178432
(18)    conv_silu                     [64, 80, 80]        [64, 80, 80]        215552
(19)    shortcut_add_linear: 16       [64, 80, 80]        [64, 80, 80]        -
(20)    route: 19, 11                 -                   [128, 80, 80]       -
(21)    conv_silu                     [128, 80, 80]       [128, 80, 80]       232448
(22)    conv_silu                     [128, 80, 80]       [256, 40, 40]       528384
(23)    conv_silu                     [256, 40, 40]       [128, 40, 40]       561664
(24)    route: 22                     -                   [256, 40, 40]       -
(25)    conv_silu                     [256, 40, 40]       [128, 40, 40]       594944
(26)    conv_silu                     [128, 40, 40]       [128, 40, 40]       611840
(27)    conv_silu                     [128, 40, 40]       [128, 40, 40]       759808
(28)    shortcut_add_linear: 25       [128, 40, 40]       [128, 40, 40]       -
(29)    conv_silu                     [128, 40, 40]       [128, 40, 40]       776704
(30)    conv_silu                     [128, 40, 40]       [128, 40, 40]       924672
(31)    shortcut_add_linear: 28       [128, 40, 40]       [128, 40, 40]       -
(32)    conv_silu                     [128, 40, 40]       [128, 40, 40]       941568
(33)    conv_silu                     [128, 40, 40]       [128, 40, 40]       1089536
(34)    shortcut_add_linear: 31       [128, 40, 40]       [128, 40, 40]       -
(35)    route: 34, 23                 -                   [256, 40, 40]       -
(36)    conv_silu                     [256, 40, 40]       [256, 40, 40]       1156096
(37)    conv_silu                     [256, 40, 40]       [512, 20, 20]       2337792
(38)    conv_silu                     [512, 20, 20]       [256, 20, 20]       2469888
(39)    route: 37                     -                   [512, 20, 20]       -
(40)    conv_silu                     [512, 20, 20]       [256, 20, 20]       2601984
(41)    conv_silu                     [256, 20, 20]       [256, 20, 20]       2668544
(42)    conv_silu                     [256, 20, 20]       [256, 20, 20]       3259392
(43)    shortcut_add_linear: 40       [256, 20, 20]       [256, 20, 20]       -
(44)    route: 43, 38                 -                   [512, 20, 20]       -
(45)    conv_silu                     [512, 20, 20]       [512, 20, 20]       3523584
(46)    conv_silu                     [512, 20, 20]       [256, 20, 20]       3655680
(47)    maxpool                       [256, 20, 20]       [256, 20, 20]       -
(48)    maxpool                       [256, 20, 20]       [256, 20, 20]       -
(49)    maxpool                       [256, 20, 20]       [256, 20, 20]       -
(50)    route: 46, 47, 48, 49         -                   [1024, 20, 20]      -
(51)    conv_silu                     [1024, 20, 20]      [512, 20, 20]       4182016
(52)    conv_silu                     [512, 20, 20]       [256, 20, 20]       4314112
(53)    upsample                      [256, 20, 20]       [256, 40, 40]       -
(54)    route: 53, 36                 -                   [512, 40, 40]       -
(55)    conv_silu                     [512, 40, 40]       [128, 40, 40]       4380160
(56)    route: 54                     -                   [512, 40, 40]       -
(57)    conv_silu                     [512, 40, 40]       [128, 40, 40]       4446208
(58)    conv_silu                     [128, 40, 40]       [128, 40, 40]       4463104
(59)    conv_silu                     [128, 40, 40]       [128, 40, 40]       4611072
(60)    route: 59, 55                 -                   [256, 40, 40]       -
(61)    conv_silu                     [256, 40, 40]       [256, 40, 40]       4677632
(62)    conv_silu                     [256, 40, 40]       [128, 40, 40]       4710912
(63)    upsample                      [128, 40, 40]       [128, 80, 80]       -
(64)    route: 63, 21                 -                   [256, 80, 80]       -
(65)    conv_silu                     [256, 80, 80]       [64, 80, 80]        4727552
(66)    route: 64                     -                   [256, 80, 80]       -
(67)    conv_silu                     [256, 80, 80]       [64, 80, 80]        4744192
(68)    conv_silu                     [64, 80, 80]        [64, 80, 80]        4748544
(69)    conv_silu                     [64, 80, 80]        [64, 80, 80]        4785664
(70)    route: 69, 65                 -                   [128, 80, 80]       -
(71)    conv_silu                     [128, 80, 80]       [128, 80, 80]       4802560
(72)    conv_silu                     [128, 80, 80]       [128, 40, 40]       4950528
(73)    route: 72, 62                 -                   [256, 40, 40]       -
(74)    conv_silu                     [256, 40, 40]       [128, 40, 40]       4983808
(75)    route: 73                     -                   [256, 40, 40]       -
(76)    conv_silu                     [256, 40, 40]       [128, 40, 40]       5017088
(77)    conv_silu                     [128, 40, 40]       [128, 40, 40]       5033984
(78)    conv_silu                     [128, 40, 40]       [128, 40, 40]       5181952
(79)    route: 78, 74                 -                   [256, 40, 40]       -
(80)    conv_silu                     [256, 40, 40]       [256, 40, 40]       5248512
(81)    conv_silu                     [256, 40, 40]       [256, 20, 20]       5839360
(82)    route: 81, 52                 -                   [512, 20, 20]       -
(83)    conv_silu                     [512, 20, 20]       [256, 20, 20]       5971456
(84)    route: 82                     -                   [512, 20, 20]       -
(85)    conv_silu                     [512, 20, 20]       [256, 20, 20]       6103552
(86)    conv_silu                     [256, 20, 20]       [256, 20, 20]       6170112
(87)    conv_silu                     [256, 20, 20]       [256, 20, 20]       6760960
(88)    route: 87, 83                 -                   [512, 20, 20]       -
(89)    conv_silu                     [512, 20, 20]       [512, 20, 20]       7025152
(90)    route: 71                     -                   [128, 80, 80]       -
(91)    conv_logistic                 [128, 80, 80]       [255, 80, 80]       7058047
(92)    yolo                          [255, 80, 80]       -                   -
(93)    route: 80                     -                   [256, 40, 40]       -
(94)    conv_logistic                 [256, 40, 40]       [255, 40, 40]       7123582
(95)    yolo                          [255, 40, 40]       -                   -
(96)    route: 89                     -                   [512, 20, 20]       -
(97)    conv_logistic                 [512, 20, 20]       [255, 20, 20]       7254397
(98)    yolo                          [255, 20, 20]       -                   -
        batched_nms                   -                   -                   -

Output YOLO blob names: 
yolo_93
yolo_96
yolo_99

Total number of YOLO layers: 272

Building YOLO network complete
Building the TensorRT Engine

NOTE: letter_box is set in cfg file, make sure to set maintain-aspect-ratio=1 in config_infer file to get better accuracy

WARNING: [TRT]: Detected invalid timing cache, setup a local cache instead
Building complete

0:01:44.800012402 13772      0x17652f0 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1947> [UID = 1]: serialize cuda engine to file: /home/lcfc/Desktop/DeepStream-Yolo/model_b1_gpu0_fp32.engine successfully
INFO: [Implicit Engine Info]: layers num: 5
0   INPUT  kFLOAT data            3x640x640       
1   OUTPUT kINT32 num_detections  0               
2   OUTPUT kFLOAT nmsed_boxes     300x4           
3   OUTPUT kFLOAT nmsed_scores    300             
4   OUTPUT kFLOAT nmsed_classes   300             

0:01:45.056062085 13772      0x17652f0 INFO                 nvinfer gstnvinfer_impl.cpp:313:notifyLoadModelStatus:<primary_gie> [UID 1]: Load new model:/home/lcfc/Desktop/DeepStream-Yolo/config_infer_primary_yoloV5.txt sucessfully
** ERROR: <main:724>: Could not open X Display
Quitting
Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
App run failed
`

**Comment by marcoslucianops** [comment]
It seems that you don't have screen or you are using docker image to run. Change the [sink] type to 1 in the `deepstream_app_config.txt` file.

**Comment by chengzihencai** [comment]
Oh,I did not have screen before,now I have a screen.  After running deepstream-app -c deepstream_app_config.txt , the screen show the demo viedo,I also get a file "model_b1_gpu0_fp32.engine". Now I successfully completed the whole process,right?

**Comment by marcoslucianops** [comment]
For a simple run on `deepstream-app`, yes. The next steps is to implement it in your own GStreamer/DeepStream code.

**Comment by marcoslucianops** [comment]
> could you tell me where is the file "model_b1_gpu0_fp32.engine"

You need to run the command with sudo because the `/opt/nvidia/deepstream/deepstream-6.0/sources` path requires privileges.
