### ISSUE TITLE
Are images resized with or without padding in inference?

### ISSUE THREAD

**Issue by jafariparizi** [marcoslucianops/DeepStream-Yolo#216]
Hello. When I use custom yolov5l by deepstream app and get output bounding boxes and evaluate them, precision and recall drops a lot compared to the pytorch model. My guess is that images are resized without padding and changing the aspect ratio causes the decrease in precision and recall. Is the resizing of the images done here or is it deepstream reference app related? Is padding done at all to maintain the aspect ratio? thanks

**Comment by marcoslucianops** [comment]
How are you evaluating the model on DeepStream? Did you create a code for it?

**Comment by jajariparizi** [comment]
For each test image, I saved a file containing the bounding boxes and then I compared the bounding boxes with their ground truth. The code that performed the comparison and evaluation is the same file that was used for the torch model in the same way.

**Comment by jajariparizi** [comment]
> How are you evaluating the model on DeepStream? Did you create a code for it?
For each test image, I saved a file containing the bounding boxes and then I compared the bounding boxes with their ground truth. The code that performed the comparison and evaluation is the same file that was used for the torch model in the same way. We wrote the evaluation code ourselves in Python

**Comment by marcoslucianops** [comment]
The deepstream resizes the input to streammux resolutiom size, then resize to model resolution (adding a padding if `maintain-aspect-ratio=1`), then resize the output coords to streammux resolution size again. I will add my evaluation results soon to the repo and you will able to compare with your results.

**Comment by jafariparizi** [comment]
Ok. I change the `maintain-aspect-ratio` to 1 and see the results. But I had another question that the image resize (with or without padding) is in the deepstream reference app codes or in your repository codes?

**Comment by marcoslucianops** [comment]
https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinfer.html
