### ISSUE TITLE
Output descripancy with yolov5 pytorch and .engine file output

### ISSUE THREAD

**Issue by adimukewar** [marcoslucianops/DeepStream-Yolo#217]
I am able to create consistent output between PyTorch and deepstream for the COCO dataset. However, with my custom data, there is a drop in mAP from .7 to .3 after the conversion. Do you have any pointers on how I can best investigate this issue?

**Comment by marcoslucianops** [comment]
Are you using the new `gen_wts_yoloV5.py` to convert the model? Unfortunately, the TensorRT drops the accuracy during the conversion even using the same YOLOv5 PyTorch net structure.

**Comment by adimukewar** [comment]
Yes, I am using the latest gen_wts_yoloV5.py, which was updated 5 days ago.

**Comment by marcoslucianops** [comment]
Is your model trained with image normalization? (mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225])

**Comment by adimukewar** [comment]
We are not using any normalization, do you think normalization might fix the issue?
Also, is there a way to run the inference using .wts file?

**Comment by marcoslucianops** [comment]
If you were using the inage normalization, you should change the `net-scale-factor` and add `offsets` properties to the config_infer file. The wts file is only the convolution weights from the PyTorch model.

**Comment by adimukewar** [comment]
I trained the medium model on the same data and do not see the same level of performance drop. It is not as noisy and the mAP drop is not significant. What do you think might be the reason for this?

**Comment by marcoslucianops** [comment]
Unfortunately, I don't know about the accuracy drop. It's a internal problem of the TensorRT in my opinion.

**Comment by marcoslucianops** [comment]
I did some changes in the repo. Can you check about the accuracy with the new files?
