### ISSUE TITLE
Converted YOLOv5m does not detect objects.

### ISSUE THREAD

**Issue by zldrobit** [marcoslucianops/DeepStream-Yolo#218]
I converted the YOLOv5s model and deployed it with DeepStream. However, when I try to do the same with YOLOv5m, there's no bbox  in the output. Could anyone reproduce this problem with YOLOv5m model?

PS: I am using YOLOv5 v6.1, PyTorch 1.10.2(CUDA 11.3) and DeepStream 6.1(CUDA 11.6).

**Comment by marcoslucianops** [comment]
Are you using the `gen_wts_yoloV5.py` file to convert the model?

**Comment by zldrobit** [comment]
Yes, I exported YOLOv5m to a `.wts` file in the same way as YOLOv5m. Would you like to tell me your result about YOLOv5m conversion?

**Comment by marcoslucianops** [comment]
![image](https://user-images.githubusercontent.com/47423225/184371140-ea089ecd-a83a-45fd-bd09-46adcff7e859.png)

This is my output using YOLOv5m 6.1

**Comment by zldrobit** [comment]
I can successfully run yolov5m now. The problem is not related to yolov5m model, and it was caused by inference with batch size greater than 1. After pulling the latest master branch and recompiling libraries, the problem is gone. Thank you!
