### ISSUE TITLE
Assertion `scale_1' failed

### ISSUE THREAD

**Issue by hoangnt2601** [marcoslucianops/DeepStream-Yolo#22]
[E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
0
common.hpp:190: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.

**Comment by marcoslucianops** [comment]
Which model are you using?

**Comment by hoangnt2601** [comment]
> Which model are you using?

I use yolov5s model, I fixed it by passing yolov5 to tag 3.1 and tensorrtx project with commit '6d0f5cb'. But continue with the error "Assertion failed: Unsupported SM."
Which tenssort version does the version use?

**Comment by hoangnt2601** [comment]
I fixed it by comment the variable USE_FP16 in yolov5.cpp and the "Unsupported SM" error because I am using gpu RTX3000 and it doesn't match with tensorrt 7.0.
https://github.com/NVIDIA/TensorRT/issues/975
