### ISSUE TITLE
use different nms methods

### ISSUE THREAD

**Issue by destinykela** [marcoslucianops/DeepStream-Yolo#220]
I know the yolov5 model uses batchedNMSplugin to create nms. But how can i use custom nms method to yolov5 model or can i dismiss the batchedNMS in yolov5 model and parser tensorMata in stream?

**Comment by marcoslucianops** [comment]
The batchedNMS used on this repo is not related to the batchedNMS used in official YOLOv5 repo. In the next updates, I will try to set a option to disable the batchedNMS for tensorMeta usage.

**Comment by youngjae-avikus** [comment]
What exactily mean about `tensorMeta usage.` ?

**Comment by marcoslucianops** [comment]
> What exactily mean about `tensorMeta usage.` ?

https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/blob/master/apps/deepstream-ssd-parser/custom_parser_guide.md
