### ISSUE TITLE
Error: 'createBatchedNMSPlugin' was not declared in this scope

### ISSUE THREAD

**Issue by Xinxinatg** [marcoslucianops/DeepStream-Yolo#221]
I am wondering whether anyone has come across this error before. I was using triton 6.0 docker image to compile the deepstream file.

**Comment by Xinxinatg** [comment]
solved by installing tensorrt

**Comment by marcoslucianops** [comment]
The devel docker image already have the TensorRT installed.

**Comment by Xinxinatg** [comment]
@marcoslucianops this was what I thought as well. According to this [issue](https://github.com/upczww/YoLov5-TensorRT-NMS/issues/5), the newest tensorRT version might not have this specified plugin. It works after I reinstall the older version of TensorRT within the Triton docker image.

**Comment by gyusik19** [comment]
@Xinxinatg struggling with the same issue. Doesn't triton docker image also has the TensorRT installed aleady?

**Comment by Xinxinatg** [comment]
> @Xinxinatg struggling with the same issue. Doesn't triton docker image also has the TensorRT installed aleady?

Apparently Triton image is bit strange, for example it is using Ubuntu 20.04 instead of the commonly used 18.04 among Deepstream 6.0 images. You can solve this issue either by reinstalling older tensorRT version within Triton 6.0 image or compiling the file in Deepstream 6.0 devel image

**Comment by gyusik19** [comment]
@Xinxinatg thanks for your rapid reply. It really helped!

**Comment by gyusik19** [comment]
> > @Xinxinatg struggling with the same issue. Doesn't triton docker image also has the TensorRT installed aleady?
> 
> Apparently Triton image is bit strange, for example it is using Ubuntu 20.04 instead of the commonly used 18.04 among Deepstream 6.0 images. You can solve this issue either by reinstalling older tensorRT version within Triton 6.0 image or compiling the file in Deepstream 6.0 devel image

BTW, the version of TensorRT installed in my deepstream-6.0.1 triton image seems to be 8.0.1, which is the older version. To which version did you reinstall?
![image](https://user-images.githubusercontent.com/81060548/184297940-cd6097c4-67ab-4ae0-88b6-e829acc70f46.png)

**Comment by Xinxinatg** [comment]
> > > @Xinxinatg struggling with the same issue. Doesn't triton docker image also has the TensorRT installed aleady?
> > 
> > 
> > Apparently Triton image is bit strange, for example it is using Ubuntu 20.04 instead of the commonly used 18.04 among Deepstream 6.0 images. You can solve this issue either by reinstalling older tensorRT version within Triton 6.0 image or compiling the file in Deepstream 6.0 devel image
> 
> BTW, the version of TensorRT installed in my deepstream-6.0.1 triton image seems to be 8.0.1, which is the older version. To which version did you reinstall? ![image](https://user-images.githubusercontent.com/81060548/184297940-cd6097c4-67ab-4ae0-88b6-e829acc70f46.png)

I randomly chose an older version which might be [TensorRT 8.2 GA Update 3](https://developer.nvidia.com/nvidia-tensorrt-8x-download#trt8242)
