### ISSUE TITLE
Error while trying to use DeepStream-Yolo with Yolov5

### ISSUE THREAD

**Issue by EdouardEPFL** [marcoslucianops/DeepStream-Yolo#222]
I'm currently facing the following problem (see the code below), I'm trying since 3days to run the program but without succes. I tried with the default yolov5s and yolov5n versions given on the official repo. I converted the .pt to .cgf and .wtd with success, however it seems that there is a problem somewhere else.
I mention that all requierements seems to be well installed; I'm running a Jetson TX2 NX with Jetpack 4.6.2 and NVIDIA DeepStream SDK 6.0.1.

Thank you for any kind of help.

> Using winsys: x11 
> ERROR: Deserialize engine failed because file path: /home/fle/DeepStream-Yolo/model_b1_gpu0_fp32.engine open error
> 0:00:06.403384040 13174     0x23a94c70 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1889> [UID = 1]: deserialize engine from file :/home/fle/DeepStream-Yolo/model_b1_gpu0_fp32.engine failed
> 0:00:06.405548906 13174     0x23a94c70 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1996> [UID = 1]: deserialize backend context from engine from file :/home/fle/DeepStream-Yolo/model_b1_gpu0_fp32.engine failed, try rebuild
> 0:00:06.405601961 13174     0x23a94c70 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 1]: Trying to create engine from model files
> 
> Loading pre-trained weights
> Loading weights of yolov5s complete
> Total weights read: 7254397
> Building YOLO network
> 
>         Layer                         Input Shape         Output Shape        WeightPtr
> (0)     conv_silu                     [3, 640, 640]       [32, 320, 320]      3584
> (1)     conv_silu                     [32, 320, 320]      [64, 160, 160]      22272
> (2)     conv_silu                     [64, 160, 160]      [32, 160, 160]      24448
> (3)     route: 1                      -                   [64, 160, 160]      -
> (4)     conv_silu                     [64, 160, 160]      [32, 160, 160]      26624
> (5)     conv_silu                     [32, 160, 160]      [32, 160, 160]      27776
> (6)     conv_silu                     [32, 160, 160]      [32, 160, 160]      37120
> (7)     shortcut_add_linear: 4        [32, 160, 160]      [32, 160, 160]      -
> (8)     route: 7, 2                   -                   [64, 160, 160]      -
> (9)     conv_silu                     [64, 160, 160]      [64, 160, 160]      41472
> (10)    conv_silu                     [64, 160, 160]      [128, 80, 80]       115712
> (11)    conv_silu                     [128, 80, 80]       [64, 80, 80]        124160
> (12)    route: 10                     -                   [128, 80, 80]       -
> (13)    conv_silu                     [128, 80, 80]       [64, 80, 80]        132608
> (14)    conv_silu                     [64, 80, 80]        [64, 80, 80]        136960
> (15)    conv_silu                     [64, 80, 80]        [64, 80, 80]        174080
> (16)    shortcut_add_linear: 13       [64, 80, 80]        [64, 80, 80]        -
> (17)    conv_silu                     [64, 80, 80]        [64, 80, 80]        178432
> (18)    conv_silu                     [64, 80, 80]        [64, 80, 80]        215552
> (19)    shortcut_add_linear: 16       [64, 80, 80]        [64, 80, 80]        -
> (20)    route: 19, 11                 -                   [128, 80, 80]       -
> (21)    conv_silu                     [128, 80, 80]       [128, 80, 80]       232448
> (22)    conv_silu                     [128, 80, 80]       [256, 40, 40]       528384
> (23)    conv_silu                     [256, 40, 40]       [128, 40, 40]       561664
> (24)    route: 22                     -                   [256, 40, 40]       -
> (25)    conv_silu                     [256, 40, 40]       [128, 40, 40]       594944
> (26)    conv_silu                     [128, 40, 40]       [128, 40, 40]       611840
> (27)    conv_silu                     [128, 40, 40]       [128, 40, 40]       759808
> (28)    shortcut_add_linear: 25       [128, 40, 40]       [128, 40, 40]       -
> (29)    conv_silu                     [128, 40, 40]       [128, 40, 40]       776704
> (30)    conv_silu                     [128, 40, 40]       [128, 40, 40]       924672
> (31)    shortcut_add_linear: 28       [128, 40, 40]       [128, 40, 40]       -
> (32)    conv_silu                     [128, 40, 40]       [128, 40, 40]       941568
> (33)    conv_silu                     [128, 40, 40]       [128, 40, 40]       1089536
> (34)    shortcut_add_linear: 31       [128, 40, 40]       [128, 40, 40]       -
> (35)    route: 34, 23                 -                   [256, 40, 40]       -
> (36)    conv_silu                     [256, 40, 40]       [256, 40, 40]       1156096
> (37)    conv_silu                     [256, 40, 40]       [512, 20, 20]       2337792
> (38)    conv_silu                     [512, 20, 20]       [256, 20, 20]       2469888
> (39)    route: 37                     -                   [512, 20, 20]       -
> (40)    conv_silu                     [512, 20, 20]       [256, 20, 20]       2601984
> (41)    conv_silu                     [256, 20, 20]       [256, 20, 20]       2668544
> (42)    conv_silu                     [256, 20, 20]       [256, 20, 20]       3259392
> (43)    shortcut_add_linear: 40       [256, 20, 20]       [256, 20, 20]       -
> (44)    route: 43, 38                 -                   [512, 20, 20]       -
> (45)    conv_silu                     [512, 20, 20]       [512, 20, 20]       3523584
> (46)    conv_silu                     [512, 20, 20]       [256, 20, 20]       3655680
> (47)    maxpool                       [256, 20, 20]       [256, 20, 20]       -
> (48)    maxpool                       [256, 20, 20]       [256, 20, 20]       -
> (49)    maxpool                       [256, 20, 20]       [256, 20, 20]       -
> (50)    route: 46, 47, 48, 49         -                   [1024, 20, 20]      -
> (51)    conv_silu                     [1024, 20, 20]      [512, 20, 20]       4182016
> (52)    conv_silu                     [512, 20, 20]       [256, 20, 20]       4314112
> (53)    upsample                      [256, 20, 20]       [256, 40, 40]       -
> (54)    route: 53, 36                 -                   [512, 40, 40]       -
> (55)    conv_silu                     [512, 40, 40]       [128, 40, 40]       4380160
> (56)    route: 54                     -                   [512, 40, 40]       -
> (57)    conv_silu                     [512, 40, 40]       [128, 40, 40]       4446208
> (58)    conv_silu                     [128, 40, 40]       [128, 40, 40]       4463104
> (59)    conv_silu                     [128, 40, 40]       [128, 40, 40]       4611072
> (60)    route: 59, 55                 -                   [256, 40, 40]       -
> (61)    conv_silu                     [256, 40, 40]       [256, 40, 40]       4677632
> (62)    conv_silu                     [256, 40, 40]       [128, 40, 40]       4710912
> (63)    upsample                      [128, 40, 40]       [128, 80, 80]       -
> (64)    route: 63, 21                 -                   [256, 80, 80]       -
> (65)    conv_silu                     [256, 80, 80]       [64, 80, 80]        4727552
> (66)    route: 64                     -                   [256, 80, 80]       -
> (67)    conv_silu                     [256, 80, 80]       [64, 80, 80]        4744192
> (68)    conv_silu                     [64, 80, 80]        [64, 80, 80]        4748544
> (69)    conv_silu                     [64, 80, 80]        [64, 80, 80]        4785664
> (70)    route: 69, 65                 -                   [128, 80, 80]       -
> (71)    conv_silu                     [128, 80, 80]       [128, 80, 80]       4802560
> (72)    conv_silu                     [128, 80, 80]       [128, 40, 40]       4950528
> (73)    route: 72, 62                 -                   [256, 40, 40]       -
> (74)    conv_silu                     [256, 40, 40]       [128, 40, 40]       4983808
> (75)    route: 73                     -                   [256, 40, 40]       -
> (76)    conv_silu                     [256, 40, 40]       [128, 40, 40]       5017088
> (77)    conv_silu                     [128, 40, 40]       [128, 40, 40]       5033984
> (78)    conv_silu                     [128, 40, 40]       [128, 40, 40]       5181952
> (79)    route: 78, 74                 -                   [256, 40, 40]       -
> (80)    conv_silu                     [256, 40, 40]       [256, 40, 40]       5248512
> (81)    conv_silu                     [256, 40, 40]       [256, 20, 20]       5839360
> (82)    route: 81, 52                 -                   [512, 20, 20]       -
> (83)    conv_silu                     [512, 20, 20]       [256, 20, 20]       5971456
> (84)    route: 82                     -                   [512, 20, 20]       -
> (85)    conv_silu                     [512, 20, 20]       [256, 20, 20]       6103552
> (86)    conv_silu                     [256, 20, 20]       [256, 20, 20]       6170112
> (87)    conv_silu                     [256, 20, 20]       [256, 20, 20]       6760960
> (88)    route: 87, 83                 -                   [512, 20, 20]       -
> (89)    conv_silu                     [512, 20, 20]       [512, 20, 20]       7025152
> (90)    route: 71                     -                   [128, 80, 80]       -
> (91)    conv_logistic                 [128, 80, 80]       [45, 80, 80]        7030957
> (92)    yolo                          [45, 80, 80]        -                   -
> (93)    route: 80                     -                   [256, 40, 40]       -
> (94)    conv_logistic                 [256, 40, 40]       [45, 40, 40]        7042522
> (95)    yolo                          [45, 40, 40]        -                   -
> (96)    route: 89                     -                   [512, 20, 20]       -
> (97)    conv_logistic                 [512, 20, 20]       [45, 20, 20]        7065607
> (98)    yolo                          [45, 20, 20]        -                   -
> 
> Number of unused weights left: 188790
> deepstream-app: yolo.cpp:438: NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&): Assertion `0' failed.
> Aborted (core dumped)
> 

This is what happend when I compile the lib if you wonder (no problem from what I can read):

> CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo
> make: Entering directory '/home/fle/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'
> g++ -c  -o nvdsinfer_yolo_engine.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsinfer_yolo_engine.cpp
> g++ -c  -o nvdsparsebbox_Yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsparsebbox_Yolo.cpp
> g++ -c  -o yoloPlugins.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include yoloPlugins.cpp
> g++ -c  -o layers/convolutional_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/convolutional_layer.cpp
> g++ -c  -o layers/batchnorm_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/batchnorm_layer.cpp
> g++ -c  -o layers/implicit_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/implicit_layer.cpp
> g++ -c  -o layers/channels_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/channels_layer.cpp
> g++ -c  -o layers/shortcut_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/shortcut_layer.cpp
> g++ -c  -o layers/route_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/route_layer.cpp
> g++ -c  -o layers/upsample_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/upsample_layer.cpp
> g++ -c  -o layers/pooling_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/pooling_layer.cpp
> g++ -c  -o layers/activation_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/activation_layer.cpp
> g++ -c  -o layers/reorg_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/reorg_layer.cpp
> g++ -c  -o layers/reduce_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/reduce_layer.cpp
> g++ -c  -o layers/shuffle_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/shuffle_layer.cpp
> g++ -c  -o layers/softmax_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/softmax_layer.cpp
> g++ -c  -o layers/cls_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/cls_layer.cpp
> g++ -c  -o layers/reg_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/reg_layer.cpp
> g++ -c  -o utils.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include utils.cpp
> g++ -c  -o yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include yolo.cpp
> yolo.cpp: In member function ‘nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*)’:
> yolo.cpp:133:85: warning: ‘nvinfer1::ICudaEngine* nvinfer1::IBuilder::buildEngineWithConfig(nvinfer1::INetworkDefinition&, nvinfer1::IBuilderConfig&)’ is deprecated [-Wdeprecated-declarations]
>      nvinfer1::ICudaEngine *engine = builder->buildEngineWithConfig(*network, *config);
>                                                                                      ^
> In file included from layers/convolutional_layer.h:12:0,
>                  from yolo.h:29,
>                  from yolo.cpp:26:
> /usr/include/aarch64-linux-gnu/NvInfer.h:8642:43: note: declared here
>      TRT_DEPRECATED nvinfer1::ICudaEngine* buildEngineWithConfig(
>                                            ^~~~~~~~~~~~~~~~~~~~~
> /usr/local/cuda-10.2/bin/nvcc -c -o yoloForward.o -I/usr/local/cuda-10.2/include/thrust/system/cuda/detail --compiler-options '-fPIC' yoloForward.cu
> /usr/local/cuda-10.2/bin/nvcc -c -o yoloForward_v2.o -I/usr/local/cuda-10.2/include/thrust/system/cuda/detail --compiler-options '-fPIC' yoloForward_v2.cu
> /usr/local/cuda-10.2/bin/nvcc -c -o yoloForward_nc.o -I/usr/local/cuda-10.2/include/thrust/system/cuda/detail --compiler-options '-fPIC' yoloForward_nc.cu
> /usr/local/cuda-10.2/bin/nvcc -c -o yoloForward_r.o -I/usr/local/cuda-10.2/include/thrust/system/cuda/detail --compiler-options '-fPIC' yoloForward_r.cu
> /usr/local/cuda-10.2/bin/nvcc -c -o yoloForward_e.o -I/usr/local/cuda-10.2/include/thrust/system/cuda/detail --compiler-options '-fPIC' yoloForward_e.cu
> /usr/local/cuda-10.2/bin/nvcc -c -o sortDetections.o -I/usr/local/cuda-10.2/include/thrust/system/cuda/detail --compiler-options '-fPIC' sortDetections.cu
> g++ -o libnvdsinfer_custom_impl_Yolo.so  nvdsinfer_yolo_engine.o nvdsparsebbox_Yolo.o yoloPlugins.o layers/convolutional_layer.o layers/batchnorm_layer.o layers/implicit_layer.o layers/channels_layer.o layers/shortcut_layer.o layers/route_layer.o layers/upsample_layer.o layers/pooling_layer.o layers/activation_layer.o layers/reorg_layer.o layers/reduce_layer.o layers/shuffle_layer.o layers/softmax_layer.o layers/cls_layer.o layers/reg_layer.o utils.o yolo.o yoloForward.o yoloForward_v2.o yoloForward_nc.o yoloForward_r.o yoloForward_e.o sortDetections.o -shared -Wl,--start-group -lnvinfer_plugin -lnvinfer -lnvparsers -L/usr/local/cuda-10.2/lib64 -lcudart -lcublas -lstdc++fs -Wl,--end-group
> make: Leaving directory '/home/fle/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'

**Comment by marcoslucianops** [comment]
The cfg file is incorrect for yolov5s and yolov5n versions given on the official repo. The number of classes should be 80 but in your file it's 10.

**Comment by EdouardEPFL** [comment]
> 

As I'm only trying to run the default yolov5s and yolov5n versions combined with deepstream for a demo in my project, would it be possible to just send me the cfg and wts files that are working on another computer please ? It would help me a lot and allow me to verify if the error doesn't come from somewhere else. I mention that I'm running the last version of your program and I don't know why it show me this error even if you told that's fixed in this version.

Thank you again for your help, I really apprreciate it!

**Comment by EdouardEPFL** [comment]
Yep I exactly followed those steps. Yolov5 was already installed, and I previously worked with it, so maybe it comes from there. I'll try to delete and download again my yolov5 repo from scratch. Going to try this solution in 2days and I'll tell you if it works !

**Comment by EdouardEPFL** [comment]
Soooo, I tried from scratch with the new version yolov7 and I obtain the same error.

Library compilation
> desktop:~/DeepStream-Yolo$ CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo
make: Entering directory '/home/f/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'
g++ -c  -o utils.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include utils.cpp
g++ -c  -o yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include yolo.cpp
yolo.cpp: In member function ‘nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*)’:
yolo.cpp:122:85: warning: ‘nvinfer1::ICudaEngine* nvinfer1::IBuilder::buildEngineWithConfig(nvinfer1::INetworkDefinition&, nvinfer1::IBuilderConfig&)’ is deprecated [-Wdeprecated-declarations]
     nvinfer1::ICudaEngine *engine = builder->buildEngineWithConfig(*network, *config);
                                                                                     ^
In file included from layers/convolutional_layer.h:12:0,
                 from yolo.h:29,
                 from yolo.cpp:26:
/usr/include/aarch64-linux-gnu/NvInfer.h:8642:43: note: declared here
     TRT_DEPRECATED nvinfer1::ICudaEngine* buildEngineWithConfig(
                                           ^~~~~~~~~~~~~~~~~~~~~
g++ -c  -o nvdsinfer_yolo_engine.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsinfer_yolo_engine.cpp
g++ -c  -o yoloPlugins.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include yoloPlugins.cpp
g++ -c  -o nvdsparsebbox_Yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsparsebbox_Yolo.cpp
g++ -c  -o layers/reg_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/reg_layer.cpp
g++ -c  -o layers/shortcut_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/shortcut_layer.cpp
g++ -c  -o layers/implicit_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/implicit_layer.cpp
g++ -c  -o layers/batchnorm_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/batchnorm_layer.cpp
g++ -c  -o layers/convolutional_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/convolutional_layer.cpp
g++ -c  -o layers/reduce_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/reduce_layer.cpp
g++ -c  -o layers/pooling_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/pooling_layer.cpp
g++ -c  -o layers/reorg_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/reorg_layer.cpp
g++ -c  -o layers/softmax_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/softmax_layer.cpp
g++ -c  -o layers/activation_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/activation_layer.cpp
g++ -c  -o layers/channels_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/channels_layer.cpp
g++ -c  -o layers/cls_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/cls_layer.cpp
g++ -c  -o layers/route_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/route_layer.cpp
g++ -c  -o layers/upsample_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/upsample_layer.cpp
g++ -c  -o layers/shuffle_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/shuffle_layer.cpp
/usr/local/cuda-10.2/bin/nvcc -c -o yoloForward_v2.o --compiler-options '-fPIC' yoloForward_v2.cu
/usr/local/cuda-10.2/bin/nvcc -c -o yoloForward.o --compiler-options '-fPIC' yoloForward.cu
/usr/local/cuda-10.2/bin/nvcc -c -o yoloForward_r.o --compiler-options '-fPIC' yoloForward_r.cu
/usr/local/cuda-10.2/bin/nvcc -c -o yoloForward_nc.o --compiler-options '-fPIC' yoloForward_nc.cu
/usr/local/cuda-10.2/bin/nvcc -c -o yoloForward_e.o --compiler-options '-fPIC' yoloForward_e.cu
g++ -o libnvdsinfer_custom_impl_Yolo.so  utils.o yolo.o nvdsinfer_yolo_engine.o yoloPlugins.o nvdsparsebbox_Yolo.o layers/reg_layer.o layers/shortcut_layer.o layers/implicit_layer.o layers/batchnorm_layer.o layers/convolutional_layer.o layers/reduce_layer.o layers/pooling_layer.o layers/reorg_layer.o layers/softmax_layer.o layers/activation_layer.o layers/channels_layer.o layers/cls_layer.o layers/route_layer.o layers/upsample_layer.o layers/shuffle_layer.o yoloForward_v2.o yoloForward.o yoloForward_r.o yoloForward_nc.o yoloForward_e.o -shared -Wl,--start-group -lnvinfer_plugin -lnvinfer -lnvparsers -L/usr/local/cuda-10.2/lib64 -lcudart -lcublas -lstdc++fs -Wl,--end-group
make: Leaving directory '/home/f/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'

Then the test:

> desktop:~/DeepStream-Yolo$ deepstream-app -c deepstream_app_config.txt

(gst-plugin-scanner:766): GStreamer-WARNING **: 20:11:39.916: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_inferserver.so': libtritonserver.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:766): GStreamer-WARNING **: 20:11:40.111: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_udp.so': librivermax.so.0: cannot open shared object file: No such file or directory

Using winsys: x11 
ERROR: Deserialize engine failed because file path: /home/f/DeepStream-Yolo/model_b1_gpu0_fp32.engine open error
0:00:05.757696877   765     0x20a11c00 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1889> [UID = 1]: deserialize engine from file :/home/f/DeepStream-Yolo/model_b1_gpu0_fp32.engine failed
0:00:05.758745435   765     0x20a11c00 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1996> [UID = 1]: deserialize backend context from engine from file :/home/f/DeepStream-Yolo/model_b1_gpu0_fp32.engine failed, try rebuild
0:00:05.758793754   765     0x20a11c00 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 1]: Trying to create engine from model files

Loading pre-trained weights
deepstream-app: utils.cpp:104: std::vector<float> loadWeights(std::__cxx11::string, const string&): Assertion `count > 0 && "\nInvalid .wts file."' failed.
Aborted (core dumped)



Currently banging my head... tf is wrong with my configuration, I'm just following the tutorial from scratch.
Is it possible to just send me the default wts and cfg files for yolov7 as I just need to do a demo please. Don't know where the problem come from, but I'm stuck at this point this a long time now. 

Thank you for your help though, really appreciate it, but the reason why it doesn't work is making me crazy.

**Comment by marcoslucianops** [comment]
The problem is in the wts file. Does it have a number of layers in the first line? The `cat` command does the process to add the number of layers of the model to the first line of the wts file. Please check if the `cat` command is working in your env.

**Comment by EdouardEPFL** [comment]
> The problem is in the wts file. Does it have a number of layers in the first line? The `cat` command does the process to add the number of layers of the model to the first line of the wts file. Please check if the `cat` command is working in your env.

I'm using a windows computer to generate the wts and cfg files (as I don't have enough space on jetson to do it) hence, the cat command is not compatible. I'll try to generate this 2 files on a Linux computer that has a cat command and I'll tell you again if it works or not.
