### ISSUE TITLE
has anyone used two stage detectors as in pgie/sgie

### ISSUE THREAD

**Issue by Xinxinatg** [marcoslucianops/DeepStream-Yolo#223]
I am trying to integrate the yolov5 deepstream into a two stage one as the pgie/sgie app in deepstream, could anyone provide some insights into this? Really appreciate your help!

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/multipleGIEs.md

**Comment by Xinxinatg** [comment]
Thanks, will have a look!
