### ISSUE TITLE
Missing detection in some frames on two videos

### ISSUE THREAD

**Issue by tunesh** [marcoslucianops/DeepStream-Yolo#226]
I am using deepstream pipeline (custom deepstream-test3) for detection. I generated the ".so" file.

When I run it on one video there are no missing detections. But while running on two videos, there are missing detections in a few frames. While running on two same videos also see the same issue and also miss on a different frame, there will not be detected in both videos at the same time. It seems the detection just switches from one frame to another in case of multi-streaming and skipping the frame to detect. 
Link for deepstream file.
[https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/blob/master/apps/deepstream-test3/deepstream_test_3.py](https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/blob/master/apps/deepstream-test3/deepstream_test_3.py)

**Comment by marcoslucianops** [comment]
Are you using interval > 0 in the config_infer_primary file?

**Comment by tunesh** [comment]
No, it's interval = 0.

**Comment by marcoslucianops** [comment]
I can't reproduce this issue. Can you send more details?

**Comment by tunesh** [comment]
Here is the link for the config file I am using : 
https://www.dropbox.com/s/f3i8jrzey9yoay9/config_infer_primary_yolov4-tiny.txt?dl=0

Here is the link for the deepstream-test3 code:
https://www.dropbox.com/s/hp7q2hu29lkynkr/deepstream_test_3_working.py?dl=0

**Comment by marcoslucianops** [comment]
I did some changes in the repo. Please test with the new files.

There are many incorrect lines in your `config_infer_primary_yolov4-tiny.txt` file. Please use this [config_infer_primary.txt](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/config_infer_primary.txt) as reference.

**Comment by tunesh** [comment]
I re-cloned the repo and make the .so file again. But now it can't find cfg for for model.

WARNING: ../nvdsinfer/nvdsinfer_model_builder.cpp:1482 Deserialize engine failed because file path: /opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo/model_b1_gpu0_fp32.engine open error
0:00:01.518589132  2217 0x56276197d610 WARN                 nvinfer gstnvinfer.cpp:656:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1888> [UID = 1]: deserialize engine from file :/opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo/model_b1_gpu0_fp32.engine failed
0:00:01.519245800  2217 0x56276197d610 WARN                 nvinfer gstnvinfer.cpp:656:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1993> [UID = 1]: deserialize backend context from engine from file :/opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo/model_b1_gpu0_fp32.engine failed, try rebuild
0:00:01.519265699  2217 0x56276197d610 INFO                 nvinfer gstnvinfer.cpp:659:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 1]: Trying to create engine from model files

File does not exist: /opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo/yolov4.cfg 
YOLO config file or weights file is not exist

ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:723 Failed to create network using custom network creation function
ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:789 Failed to get cuda engine from custom library API
0:00:02.340414672  2217 0x56276197d610 ERROR                nvinfer gstnvinfer.cpp:653:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1934> [UID = 1]: build engine file failed
0:00:02.340976445  2217 0x56276197d610 ERROR                nvinfer gstnvinfer.cpp:653:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2020> [UID = 1]: build backend context failed
0:00:02.341004844  2217 0x56276197d610 ERROR                nvinfer gstnvinfer.cpp:653:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1257> [UID = 1]: generate backend failed, check config file settings
0:00:02.341140637  2217 0x56276197d610 WARN                 nvinfer gstnvinfer.cpp:876:gst_nvinfer_start:<primary_gie> error: Failed to create NvDsInferContext instance
0:00:02.341157336  2217 0x56276197d610 WARN                 nvinfer gstnvinfer.cpp:876:gst_nvinfer_start:<primary_gie> error: Config file path: /opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo/config_infer_primary.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
** ERROR: <main:716>: Failed to set pipeline to PAUSED
Quitting
ERROR from primary_gie: Failed to create NvDsInferContext instance
Debug info: gstnvinfer.cpp(876): gst_nvinfer_start (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
Config file path: /opt/nvidia/deepstream/deepstream-6.1/sources/DeepStream-Yolo/config_infer_primary.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
App run failed

**Comment by tunesh** [comment]
When I am using the old config with the new ".so" file then this error is coming. 

0:00:33.344393676 13982 0x7f13140022f0 INFO                 nvinfer gstnvinfer_impl.cpp:328:notifyLoadModelStatus:<secondary2-nvinference-engine> [UID 2]: Load new model:test_classifier_config_dli.txt sucessfully
Deserialize yoloLayer plugin: yolo
Segmentation fault (core dumped)

**Comment by marcoslucianops** [comment]
You need to delete the old yolo engine file, compile the new so file, change the `custom-network-config` and `model-file` path in ther new config_infer file, and run the code again.

**Comment by tunesh** [comment]
When I deleted the engine files.
Number of unused weights left: 18446744073709358080
python3: yolo.cpp:427: NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&): Assertion `0' failed.
Aborted (core dumped)

**Comment by marcoslucianops** [comment]
Which model you are using and which is the `custom-network-config` and `model-file` paths you put?

**Comment by tunesh** [comment]
> Which model you are using and which is the `custom-network-config` and `model-file` paths you put?

I am using tiny yolov4 model trained on our own dataset. tiny_yolov4_3l.cfg and weights according to it.

**Comment by tunesh** [comment]
I removed the repo and cloned it again, this time is saved the cfg and weights in the directory before making the so file. I did not get the file does not exist error. 

But I got this error.

Number of unused weights left: 18446744073709358080
deepstream-app: yolo.cpp:427: NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&): Assertion `0' failed.
Aborted (core dumped)

**Comment by marcoslucianops** [comment]
I think you are using the wrong weights file for this cfg.

**Comment by tunesh** [comment]
Last time, when I did the conversion by using your code, I used the same cfg and weights file. It worked perfectly.

**Comment by marcoslucianops** [comment]
I can reproduce the issue, working on it.

**Comment by marcoslucianops** [comment]
Fixed, please check with the new files.
