### ISSUE TITLE
how can inference yolo v7 original(before reparameterization) model. >> Model not supported 'IDetect' layers

### ISSUE THREAD

**Issue by HeungJunKim** [marcoslucianops/DeepStream-Yolo#228]
The recently published yolov7 support update works very well.
Thanks for the great repositories and quick updates.

Pretrained coco models and custom trained models(after  work reparameterization) successfully with this repository.

But, the 'IDetect' layer included in the original model could not be converted.
(In our own tests, for the yolov7x model, applying reparameterization reduces the accuracy slightly.)

so, How do I modify gen_wts_yoloV7.py?

1. yolov7x model reparameterization code.
![reparam](https://user-images.githubusercontent.com/88820458/184800193-c86ac4a6-9e90-4e1e-854f-f8b38f9a28d6.png)

2. compare models last layer(reparametrization / original)
<img width="1713" alt="reparam_org" src="https://user-images.githubusercontent.com/88820458/184800271-37c37926-a770-40ba-8c09-e7939cddfbc8.PNG">

3. gen_wts_yoloV7.py
![detect_layer](https://user-images.githubusercontent.com/88820458/184800400-02210c34-58c3-4ecb-bd55-af54ce729585.png)

**Comment by marcoslucianops** [comment]
I will add the support soon.

**Comment by nqthai309** [comment]
the same error

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/issues/241#issuecomment-1256193362

**Comment by pullmyleg** [comment]
@HeungJunKim see: https://github.com/marcoslucianops/DeepStream-Yolo/issues/241#issuecomment-1270969005

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/issues/241#issuecomment-1318019400
