### ISSUE TITLE
 Fatal error: crt/host_defines.h: No such file or directory

### ISSUE THREAD

**Issue by saisriteja** [marcoslucianops/DeepStream-Yolo#229]
I am trying to complie the library from the git repo.

[DeepStream-Yolo/YOLOv7.md at master · marcoslucianops/DeepStream-Yolo · GitHub](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv7.md).

I am using the docker container deepstream6.1_samples. When try to complie the following command, I get the error.
CUDA_VER=11.6 make -C nvdsinfer_custom_impl_Yolo

Error

`
root@57dde0ad4ca3:/workspace# CUDA_VER=11.6 make -C nvdsinfer_custom_impl_Yolo
make: Entering directory '/workspace/nvdsinfer_custom_impl_Yolo'
g++ -c  -o utils.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-11.6/include utils.cpp
In file included from /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:56,
                 from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:53,
                 from /usr/include/x86_64-linux-gnu/NvInfer.h:53,
                 from utils.h:36,
                 from utils.cpp:26:
/usr/local/cuda-11.6/include/cuda_runtime_api.h:147:10: fatal error: crt/host_defines.h: No such file or directory
  147 | #include "crt/host_defines.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:70: utils.o] Error 1
make: Leaving directory '/workspace/nvdsinfer_custom_impl_Yolo'

`

Nvidia-smi

`
Wed Aug 17 06:51:40 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   45C    P8     2W /  N/A |    764MiB /  4096MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

`

**Comment by marcoslucianops** [comment]
Use devel docker image.

**Comment by amirmgh1375** [comment]
The size of the Develop docker image is large for production environment. How to use it in the lighter docker image ?

**Comment by marcoslucianops** [comment]
You can use the ubuntu image as base and install the dependencies using the Dockerfile.
