### ISSUE TITLE
Do you support the V2 DynamictExt Plugin?

### ISSUE THREAD

**Issue by hoangnt2601** [marcoslucianops/DeepStream-Yolo#23]

**Comment by marcoslucianops** [comment]
For now, is used IPluginV2 for YOLOv2, YOLOv3 and YOLOv4.

What do you need IPluginV2DynamicExt with?

**Comment by hoangnt2601** [comment]
> What do you need IPluginV2DynamicExt with?
I try to try dynamic shape when infer with yolov5 but error deserializeCudaEngine gets null when trying to write like this code
https://github.com/wang-xinyu/tensorrtx/blob/3d022d9114d1833b4cad9daa9da72bab27bf75dc/yolov3-spp/yololayer.h

**Comment by marcoslucianops** [comment]
Do you want to change IPluginV2IOExt to IPluginV2DynamicExt in YOLOv5?

**Comment by hoangnt2601** [comment]
> Do you want to change IPluginV2IOExt to IPluginV2DynamicExt in YOLOv5?

yes

**Comment by marcoslucianops** [comment]
I will check

**Comment by marcoslucianops** [comment]
I was unable to implement IPluginV2DynamicExt for now. I recommend that you open a new issue about it in https://github.com/wang-xinyu/tensorrtx repo.
