### ISSUE TITLE
Can't create Yolo V4 tiny's TensorRT engine.

### ISSUE THREAD

**Issue by pngstar** [marcoslucianops/DeepStream-Yolo#231]
Is there something different previous version library?

Here's error msg.

Loading pre-trained weights
Loading weights of config/wild complete
Total weights read: 5912664
Building YOLO network

        Layer                         Input Shape         Output Shape        WeightPtr
(0)     conv_leaky                    [3, 640, 640]       [32, 320, 320]      992
(1)     conv_leaky                    [32, 320, 320]      [64, 160, 160]      19680
(2)     conv_leaky                    [64, 160, 160]      [64, 160, 160]      56800
(3)     route: 2                      -                   [64, 160, 160]      -
(4)     conv_leaky                    [64, 160, 160]      [32, 160, 160]      75360
(5)     conv_leaky                    [32, 160, 160]      [32, 160, 160]      84704
(6)     route: 5, 4                   -                   [64, 160, 160]      -
(7)     conv_leaky                    [64, 160, 160]      [64, 160, 160]      89056
(8)     route: 2, 7                   -                   [128, 160, 160]     -
(9)     maxpool                       [128, 160, 160]     [128, 80, 80]       -
(10)    conv_leaky                    [128, 80, 80]       [128, 80, 80]       237024
(11)    route: 10                     -                   [128, 80, 80]       -
(12)    conv_leaky                    [128, 80, 80]       [64, 80, 80]        311008
(13)    conv_leaky                    [64, 80, 80]        [64, 80, 80]        348128
(14)    route: 13, 12                 -                   [128, 80, 80]       -
(15)    conv_leaky                    [128, 80, 80]       [128, 80, 80]       365024
(16)    route: 10, 15                 -                   [256, 80, 80]       -
(17)    maxpool                       [256, 80, 80]       [256, 40, 40]       -
(18)    conv_leaky                    [256, 40, 40]       [256, 40, 40]       955872
(19)    route: 18                     -                   [256, 40, 40]       -
(20)    conv_leaky                    [256, 40, 40]       [128, 40, 40]       1251296
(21)    conv_leaky                    [128, 40, 40]       [128, 40, 40]       1399264
(22)    route: 21, 20                 -                   [256, 40, 40]       -
(23)    conv_leaky                    [256, 40, 40]       [256, 40, 40]       1465824
(24)    route: 18, 23                 -                   [512, 40, 40]       -
(25)    maxpool                       [512, 40, 40]       [512, 20, 20]       -
(26)    conv_leaky                    [512, 20, 20]       [512, 20, 20]       3827168
(27)    conv_leaky                    [512, 20, 20]       [256, 20, 20]       3959264
(28)    conv_leaky                    [256, 20, 20]       [512, 20, 20]       5140960
(29)    conv_linear                   [512, 20, 20]       [60, 20, 20]        5171740
(30)    yolo                          [60, 20, 20]        -                   -
(31)    route: 27                     -                   [256, 20, 20]       -
(32)    conv_leaky                    [256, 20, 20]       [128, 20, 20]       5205020
(33)    upsample                      [128, 20, 20]       [128, 40, 40]       -
(34)    route: 33, 23                 -                   [384, 40, 40]       -
(35)    conv_leaky                    [384, 40, 40]       [256, 40, 40]       6090780
(36)    conv_linear                   [256, 40, 40]       [60, 40, 40]        6106200
(37)    yolo                          [60, 40, 40]        -                   -

Number of unused weights left: 18446744073709358080
deepstream-app: yolo.cpp:427: NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&): Assertion `0' failed.

**Comment by pngstar** [comment]
system's environment is something wrong. now I can create TensorRT engine.

**Comment by pabsan-0** [comment]
@pngstar Hello! I'm having the same issue, could you please give more details? Thanks

**Comment by marcoslucianops** [comment]
For now, the support is only for Darknet YOLOv4-Tiny.
