### ISSUE TITLE
Any plan to support yolov5-face?

### ISSUE THREAD

**Issue by rahulsharma11** [marcoslucianops/DeepStream-Yolo#232]
Hi,

Any plan to integrate yolov5-face in deepstream("https://github.com/deepcam-cn/yolov5-face").?

or can you suggest important steps to do that?

Thanks

**Comment by marcoslucianops** [comment]
For now, I don't have plans for it.

It's hard to say about the steps because it's a complicated implementation.

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo-Face
