### ISSUE TITLE
understanding gpuYoloLayer.

### ISSUE THREAD

**Issue by rahulsharma11** [marcoslucianops/DeepStream-Yolo#233]
Hi,
i want to integrate yolov5-face with landmarks.

Can you elaborate the gpuToloLayer function?

What is blockIdx.x / blockDim.x and threadIdx.x?
Also how can i add landmark extraction code in gpuYoloLayer?

What is meaning of -
 gpuYoloLayer<<<number_of_blocks, threads_per_block, 0, stream>>>(
            reinterpret_cast<const float*>(input) + (batch * inputSize),
            reinterpret_cast<int*>(num_detections) + (batch),
            reinterpret_cast<float*>(detection_boxes) + (batch * 4 * outputSize),
            reinterpret_cast<float*>(detection_scores) + (batch * outputSize),
            reinterpret_cast<int*>(detection_classes) + (batch * outputSize),
            scoreThreshold, netWidth, netHeight, gridSizeX, gridSizeY, numOutputClasses, numBBoxes, scaleXY,
            reinterpret_cast<const float*>(anchors), reinterpret_cast<const int*>(mask));

Thanks.

**Comment by marcoslucianops** [comment]
It's not only the kernel, there are unsupported layers in the model yaml.
