### ISSUE TITLE
Too low fps at T4 and V100.

### ISSUE THREAD

**Issue by pngstar** [marcoslucianops/DeepStream-Yolo#234]
Here's my system info.

- Driver- 
Fri Aug 19 17:05:54 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:5B:00.0 Off |                    0 |
| N/A   49C    P8    16W /  70W |     14MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1898      G   /usr/lib/xorg/Xorg                 14MiB |
+-----------------------------------------------------------------------------+

- CUDA -
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Thu_Feb_10_18:23:41_PST_2022
Cuda compilation tools, release 11.6, V11.6.112
Build cuda_11.6.r11.6/compiler.30978841_0

- Deepstream -
deepstream-app version 6.1.0
DeepStreamSDK 6.1.0

- TensorRT -
nv-tensorrt-repo-ubuntu2004-cuda11.4-trt8.2.5.1-ga-20220505 1-1

- Gstreamer -
GStreamer 1.16.3

and GPU is T4 and V100. I have two servers.
I test Yolo V4 tiny and V5.
Avg. FPS is 1.x. there's something wrong.
If you need some configuration files, I will share to you.

**Comment by marcoslucianops** [comment]
Please attach the config_infer file and deepstream_app_config.txt file.

**Comment by pngstar** [comment]
[config_infer_primary_yoloV5.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/9382089/config_infer_primary_yoloV5.txt)
[rtsp_analytics_video.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/9382090/rtsp_analytics_video.txt)

**Comment by pngstar** [comment]
attach my config files, thx for your help.

**Comment by pngstar** [comment]
[config_infer_primary_yoloV5.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/9386040/config_infer_primary_yoloV5.txt)
[rtsp_analytics_video.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/9386041/rtsp_analytics_video.txt)

**Comment by pngstar** [comment]
attach my config files, thx for your help.

**Comment by marcoslucianops** [comment]
You are using too many resources in your `rtsp_analytics_video.txt` config. Probably, this is the problem.

**Comment by pngstar** [comment]
I must be use many resources. How can I fix this issue?

**Comment by marcoslucianops** [comment]
You need to create a custom code (preferable in C) to optimize the pipeline for what you want to do. The `deepstream-app` is like a general purpose application.

**Comment by pngstar** [comment]
Are there any problems with the system environment?

**Comment by marcoslucianops** [comment]
What's the framerate when you use default `deepstream_app_config.txt` file?
