### ISSUE TITLE
replicating the results in readme.md 

### ISSUE THREAD

**Issue by saisriteja** [marcoslucianops/DeepStream-Yolo#235]
I am going through results inside the [readme](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/README.md).  I wanted to replicate this, can I know how this is done using deepstream.

**Comment by marcoslucianops** [comment]
I got the result from a custom code that I created. It's not public for now.

**Comment by saisriteja** [comment]
Okay, I am have written code to check the performance using deepstream.


[Code](https://forums.developer.nvidia.com/t/how-to-get-fps-informatiom-from-deepstreamtest1-py/224311/2?u=kuppasaisriteja) I used in Deepstream, to check the FPS.


The below are the results I got, I find that yolov7 is almost equally performing to yolov5. Can let me know the process how would I check if I get greater FPS.


The config files  are used as mentioned in github readme, and I have used deepstreamtest1 sample [code](https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/deepstream-test1).



Name |   | Model Complexity (No of Layers) | Time(fps) | Accuracy
-- | -- | -- | -- | --
yolov7 | 640 | 399 | 35 |  
yolov7x | 640 | 454 | 22 |  
yolov7-d6 | 1280 | 707 | 20 |  
yolov7-e6 | 1280 | 619 | 28 |  
yolov7-w6 | 1280 | 451 | 39 |  
yolov7-e6e | 1280 | 1037 | 17 |  
  |   |   |   |  
yolov5x |   | 545 | 19 |  
yolov5l |   | 450 | 33.4 |  
yolov5s |   | 355 | 67 |  
yolov5m6 |   | 461 | 61 |

**Comment by marcoslucianops** [comment]
> Okay, I am have written code to check the performance using deepstream.

You can just use the deepstream-app to check the FPS.

> I got, I find that yolov7 is almost equally performing to yolov5.

The FPS of the YOLOv7 is very similiar to YOLOv5l.

> Can let me know the process how would I check if I get greater FPS.

The FP16 mode can increase the FPS.
