### ISSUE TITLE
yolov5 and deepstream accuracy problem

### ISSUE THREAD

**Issue by qybing** [marcoslucianops/DeepStream-Yolo#237]
The tensorrt weights I exported using the yolov5 official website are almost the same as the original weight prediction results, and the error range is also within an acceptable range, but the weights I derived according to your method are sometimes very different in the results predicted by Deepstream. Do you have any suggestions?

**Comment by marcoslucianops** [comment]
I'm trying to increase the accuracy of YOLOv5 on DeepStream. The current implementation is the most accurate I've gotten so far.  The TensorRT layers (from DeepStream) are the same PyTorch layers, but there's an accuracy drop on DeepStream.

**Comment by Arpit1496** [comment]
I am also getting really Low Accuracy on yolov5.
Is this relates to waning I get while converting model "Warning [TRT: Subnormal FP16 values detected." ?

**Comment by marcoslucianops** [comment]
> I am also getting really Low Accuracy on yolov5. Is this relates to waning I get while converting model "Warning [TRT: Subnormal FP16 values detected." ?

It's not related to that.

**Comment by Arpit1496** [comment]
okay. Any updates on this ?
How can we help to improve the accuracy ?

**Comment by marcoslucianops** [comment]
No updates yet.

**Comment by Alberto1404** [comment]
@marcoslucianops Does this happens as well in recent versions of YOLO?

**Comment by marcoslucianops** [comment]
Yes, but, in my use cases, it's not a relevant drop, so I still using DeepStream and YOLO on projects.

**Comment by OctaM** [comment]
I've noticed this for yoloV8 also. Are there any updates?

**Comment by sruap1214** [comment]
I've noticed this for yolov7-tiny. I have a model for 6-classes, and one particular class has a major drop in comparisson with pytorch

**Comment by pullmyleg** [comment]
Hi @marcoslucianops we're having this issue too but are keen to help resolve it. Do you have any suggestions on where we should start?

We have also attempted to resolve this by using yolov8 as an onnx model, which had similar results. 

We're seeing a significant drop in accuracy for some objects (40%) when running inference with ultralytics yolov8 vs in deep stream. With yolov4 we do not see much of a drop in accuracy comparison to running inference with darknet vs deep stream. 

Any tips or comments on where we should begin would be greatly appreciated! Thanks!

**Comment by KindOfBlue7** [comment]
Is there a certain YOLO model that works fine after deployment without any issues?

**Comment by marcoslucianops** [comment]
> We have also attempted to resolve this by using yolov8 as an onnx model, which had similar results.

https://github.com/marcoslucianops/DeepStream-Yolo/issues/339

> Is there a certain YOLO model that works fine after deployment without any issues?

I'm adding new benchmarks to the `README.md`. You will be able to see the results and choose the best option.
