### ISSUE TITLE
Model not supported error while converting Yolov7 weights 'IDetect layer'

### ISSUE THREAD

**Issue by junaidp1** [marcoslucianops/DeepStream-Yolo#241]
I am getting Model not supported error when I use `gen_wts_yoloV7.py` to generate weights and config file. Yolov7 model that I have contains IDetect layer which I don't see in the `gen_wts_yoloV7.py`.

Any idea how to fix it? Thanks

**Comment by marcoslucianops** [comment]
The IDetect layer isn't implemented yet. I will add soon.

**Comment by GiorgosBetsos** [comment]
I also have a custom Yolo v7 model and get the same error when trying to convert using gen_wts_yoloV7.py. How can I tell if the error is due the same reason described here, or due to some other reason?

**Comment by ksd777** [comment]
When can we expect implementation of IDetect layer? Or maybe you can let me know which version of Yolov7 is using Detect layer instead of IDetect?

**Comment by franckmarineai** [comment]
IDetect support is what we are waiting for to complete an important project. Any ETA for that ?

**Comment by rbgreenway** [comment]
Need IDetect support badly.  
I'm assuming that there are yolov7 models that don't use IDetect.  Which ones?  At least need an interim solution.

**Comment by emirkiani** [comment]
We have the same error while trying to convert the custom yolov7 model.

**Comment by marcoslucianops** [comment]
The IDetect layer is used in re-parameterized models. I will work on it in the next days.

**Comment by pullmyleg** [comment]
@marcoslucianops I dont think you need to support idetect :). From my understanding Idetect is for training, detect is for inference (faster) as per the scripts in the cfg/deploy folder of yolov7. I just got this working with V7 tiny using your current tools. 

This has been tested with Deepstream 6.0.1 running on a jetson nano. 

Steps:

1. [Reparamitise](https://github.com/WongKinYiu/yolov7/blob/main/tools/reparameterization.ipynb) the model. Note you need to update the [reparamitizer script replacing 105 with 77 if you are using yolov7-tiny](https://github.com/WongKinYiu/yolov7/issues/514) or another up supported model. 
2. use the [config](https://github.com/WongKinYiu/yolov7/tree/main/cfg/deploy) from cfg/deploy supplied in repo.
3. convert as per usual using [existing tooling](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv7.md).

**Comment by marcoslucianops** [comment]
Yes, the IDetect is for training. You need to do the [reparameterization](https://github.com/WongKinYiu/yolov7/blob/main/tools/reparameterization.ipynb) to convert the model using the `gen_wts_yoloV7.py`.

**Comment by animeesh** [comment]
https://colab.research.google.com/drive/17HIHsKAdfTbZQSu7LxZIwtHQr7LZYSKD?usp=sharing this colab file can help you guys in .pt to .wts model conversion

**Comment by anchalgupta2412** [comment]
Weights obtained from re-parameterization differ from original weights. I am getting different recall & precision on same images with 2 models.

**Comment by marcoslucianops** [comment]
> Weights obtained from re-parameterization differ from original weights. I am getting different recall & precision on same images with 2 models.

Did you test using YOLOv7 repo?

**Comment by marcoslucianops** [comment]
Use the new ONNX export method.
