### ISSUE TITLE
Wrong target when running deepstream app

### ISSUE THREAD

**Issue by chengzihencai** [marcoslucianops/DeepStream-Yolo#245]
When I finished deploying YoloV5 by DeepStream-Yolo, most targets can be detected.But there is also something wrong:
There is almost always a misidentified target in the upper left corner of the window. They are all gray labels that do not show confidence. (Other labels are red, orange, etc.)
YoloV5 6.1 engine file is in FP32
I try to set pre-cluster-threshold=0.9, this problem has been greatly alleviated, but it still occurs occasionally.

**Comment by marcoslucianops** [comment]
The `pre-cluster-threshold` is the `conf-thres` (PyTorch YOLOv5). Are you using custom code or the `deepstream-app`?

**Comment by marcoslucianops** [comment]
Please use the default `nms-iou-threshold=0.45`.
