### ISSUE TITLE
Is batch_nms basically included in the TensorRT build?

### ISSUE THREAD

**Issue by YoungjaeDev** [marcoslucianops/DeepStream-Yolo#247]
Hello
I can see the batch_nms layer at the end of the TensorRT build, is this basically included? 
What can I do if I want to exclude this?

**Comment by youngjae-avikus** [comment]
Oh, it's gone because I recently updated the code commits.
nms basically working when cluster_mode=4 in the TensorRT model?
I want to use the post-processing code that I made, but I want to use as little resources as possible when cluster_mode=4

**Comment by marcoslucianops** [comment]
I reverted the NMS to DeepStream default NMS due to accurary drop, so the Batched NMS isn't used anymore.
