### ISSUE TITLE
Process Killed yoloR_w6

### ISSUE THREAD

**Issue by alejoGT1202** [marcoslucianops/DeepStream-Yolo#248]
Hello,

I follow the steps described [here ](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOR.md) and was able to generate the `.wts ` and .`cfg` files. However, when I execute the `deepstream-app -c deepstream_app_config.txt` command the process gets killed.

The last thing my console prints is: 

```
Total number of YOLO layers: 638

Building YOLO network complete
Building the TensorRT Engine

Killed
```

I'm running the code in a  Jetson Nano Dev Kit, using the yoloR_w6 weights, is it possible to run this weights on Jetson Nano or should I use the CSP weights? 

Thanks for the help.

**Comment by pabsan-0** [comment]
Looks like you're out of RAM. Maybe you can relieve some by killing stuff like text editor, web browser... Use `jtop` on Jetson for a detailed monitor. If you can't you'll probably need to switch to a lighter model.

I haven't tried TensorRT conversion, but recently we could not infer Yolov5L or Yolov4-P6 (with torch) on the Nano for this very reason, it is quite memory-limited.

**Comment by marcoslucianops** [comment]
You sould use tiny models on Jetson Nano board. It doesn't have sufficient resources to run heavy models.
