### ISSUE TITLE
Issue with Jetpack > 5.0 

### ISSUE THREAD

**Issue by JetsonPaul** [marcoslucianops/DeepStream-Yolo#249]
Hi, 

I have an error with the detection running Jetpack > 5.0. Reported [here](https://forums.developer.nvidia.com/t/deepstream-bug-jp-5-0/227638) because I think it's a Nvidia bug. You have the same issues? 

Paul

**Comment by JetsonPaul** [comment]
A short update. I tested [Nvidas implementation](https://github.com/NVIDIA-AI-IOT/deepstream_tao_apps) of YOLOv5 and Deepstreamer and its working without any issues. I actually don't know where the issue is coming from. Deepstreamer 6.1 working fine on our workstation. So I think it must be related to the Jetson Devices.

**Comment by marcoslucianops** [comment]
Did you test with the new JetPack 5.0.2?

**Comment by JetsonPaul** [comment]
Yes

**Comment by marcoslucianops** [comment]
Did you get the same error?

**Comment by marcoslucianops** [comment]
I will test in the next days.

**Comment by JetsonPaul** [comment]
Thank you very much!

**Comment by JetsonPaul** [comment]
Hi Marcos, 
Nvidia announced [easier update](https://developer.nvidia.com/blog/simplifying-cuda-upgrades-for-nvidia-jetson-users/) for CUDA on Jetson devices starting with CUDA 11.8. 

I tried to run your repo with it to check if its an error with the CUDA version (because JetPack 4.6.x is working and also your repo is working with deepstream 6.1 and CUDA 11.4 on our work station). 

I got the error message: 

CUDA failure: the provided PTX was compiled with an unsupported toolchain. in file yoloPlugins.cpp at line 185

Best regards 
Paul

**Comment by JetsonPaul** [comment]
And another update: We now had the Issue also on JP 4.6.x. We guess it's related to a current issue or throttling. Strangely it not happened with the Nvidia Tao implementation so far.

**Comment by marcoslucianops** [comment]
The TAO Toolkit implementation is totally different of this implementation. I use the PPYOLOE (this repository) in my projects on AGX board and I didn't get this issue. Are you using custom code?

**Comment by JetsonPaul** [comment]
Hi Marcos, 

So I could narrowed it down. The problem seems to be on the conversion side. When I use the Tao Implementation to convert my custom YOLOv5s Model with only one class and then use the engine model in your implementation everything is fine. So I guess there must be a problem with the Jetson Xavier NX (I also tested another Xavier) and the way the model gets converted in your implementation. The video below shows the problem again. On the left the engine model converted with your implementation and on the right the engine model converted with the tao implementation. Both running with your Deepstream implementation.  

https://user-images.githubusercontent.com/49520314/196958599-128a96e2-767b-4fef-863c-299f4f5c6e68.mp4
