### ISSUE TITLE
about reducing memory when running

### ISSUE THREAD

**Issue by hejun888** [marcoslucianops/DeepStream-Yolo#25]
hi,why the whole process takes up so much memory, and is there any way to reduce the memory

**Comment by marcoslucianops** [comment]
Are you using Jetson platform?

**Comment by BarcaBear** [comment]
I'm seeing a similar issue on an Xavier NX. The detection is much better then YoloV3 but it's slower. Around 20fps vrs 30fps for YoloV3. YoloV4-CSP seems to be the fastest. Tried fp16/32 and int8. But don't notice much difference. 

Would be great to achieve 25fps with same level of detection. 

Any tweaks you can think of ?

**Comment by hejun888** [comment]
yes i use jetson platform

**Comment by marcoslucianops** [comment]
Idk how to reduce deepstream memory usage, but you can reduce system memory usage by using lxde (see my video: https://youtu.be/Z3K43Q34sIs). Btw, the system will have more memory to use during deepstream/post process.
