### ISSUE TITLE
YOLOV5 model has very weak detection capability after deployment

### ISSUE THREAD

**Issue by chengzihencai** [marcoslucianops/DeepStream-Yolo#251]
`Jetpack 4.6
deepstream 6.0.1
yolov5 6.1 
`
I tested yolov5s , yolov7 , yolor （untrained,all of them），the can work well.
I trained yolov5（changed backbone，but layers(CBH , LC_block , Dense) can be find in  gen_wts_yoloV5.py）, the model in pytorch can work ,tested by detect.py.
I found that my improved YOLOV5 model had very weak detection ability after transformation, and used the default precision (FP32) when generating the model.

**Comment by chengzihencai** [comment]
When I edit pre-cluster-threshold=1.0,the wrong labels didn't show.But no any right labels ,too.

**Comment by chengzihencai** [comment]
Update some information:I try to use the five hyp files of yolov5 for training and get five models. I found that their results under deepstream are different, but they are very poor.

    After I modified cfg.yaml file, I expanded the parameters of each layer to twice the previous one, and after retraining I got a model that was more than twice as large as the previous model, although its detection speed became slower, this test did not find a misdetected target, there was a certain correct target, but there was a certain missed detection.

**Comment by marcoslucianops** [comment]
> `Jetpack 4.6 deepstream 6.0.1 yolov5 6.1 ` I tested yolov5s , yolov7 , yolor （untrained,all of them），the can work well. I trained yolov5（changed backbone，but layers(CBH , LC_block , Dense) can be find in gen_wts_yoloV5.py）, the model in pytorch can work ,tested by detect.py. I found that my improved YOLOV5 model had very weak detection ability after transformation, and used the default precision (FP32) when generating the model.

About layers, there is probably another different implementation you did that I didn't identify during the additions of those new layers. I need more info on what you changed in yolov5 to fix it.

> Update some information:I try to use the five hyp files of yolov5 for training and get five models. I found that their results under deepstream are different, but they are very poor.
> 
> After I modified cfg.yaml file, I expanded the parameters of each layer to twice the previous one, and after retraining I got a model that was more than twice as large as the previous model, although its detection speed became slower, this test did not find a misdetected target, there was a certain correct target, but there was a certain missed detection.

There's an accuracy drop on TensorRT models converted from PyTorch. I'm trying to find a solution for it.

**Comment by chengzihencai** [comment]
> > `Jetpack 4.6 deepstream 6.0.1 yolov5 6.1 ` I tested yolov5s , yolov7 , yolor （untrained,all of them），the can work well. I trained yolov5（changed backbone，but layers(CBH , LC_block , Dense) can be find in gen_wts_yoloV5.py）, the model in pytorch can work ,tested by detect.py. I found that my improved YOLOV5 model had very weak detection ability after transformation, and used the default precision (FP32) when generating the model.
> 
> About layers, there is probably another different implementation you did that I didn't identify during the additions of those new layers. I need more info on what you changed in yolov5 to fix it.
> 
> > Update some information:I try to use the five hyp files of yolov5 for training and get five models. I found that their results under deepstream are different, but they are very poor.
> > After I modified cfg.yaml file, I expanded the parameters of each layer to twice the previous one, and after retraining I got a model that was more than twice as large as the previous model, although its detection speed became slower, this test did not find a misdetected target, there was a certain correct target, but there was a certain missed detection.
> 
> There's an accuracy drop on TensorRT models converted from PyTorch. I'm trying to find a solution for it.

I will send my file via email,they are all the files I have changed.

**Comment by ledinhtri97** [comment]
@marcoslucianops do you have any update on this accuracy issue.

I also tried the repo build TensoRT yolov7 engien from `wang-xinyu/tensorrtx` and see their model engine has more object detection then your. Of course the condition is fair to compare

**Comment by marcoslucianops** [comment]
I will do some tests to verify it.

**Comment by Alberto1404** [comment]
@

> @marcoslucianops do you have any update on this accuracy issue.
> 
> I also tried the repo build TensoRT yolov7 engien from `wang-xinyu/tensorrtx` and see their model engine has more object detection than your engine created. Of course the condition is fair to compare

@ledinhtri97 Did you try that engine in deepstream? If so, could you share the ```config_infer_primary_yoloV5.txt``` you are using?

**Comment by lswgh** [comment]
I had the same problem above! did you have any way about this ?

**Comment by marcoslucianops** [comment]
No updates yet.

**Comment by KindOfBlue7** [comment]
Any updates regarding lower accuracy after deployment? I have the same issue with missing detections using Yolov5n trained on custom data.

**Comment by marcoslucianops** [comment]
> Any updates regarding lower accuracy after deployment? I have the same issue with missing detections using Yolov5n trained on custom data.

https://github.com/marcoslucianops/DeepStream-Yolo/issues/339
