### ISSUE TITLE
Do Inference size width and height have to be equal?

### ISSUE THREAD

**Issue by Xinxinatg** [marcoslucianops/DeepStream-Yolo#254]
![Screenshot from 2022-09-22 14-05-45](https://user-images.githubusercontent.com/72983482/191656130-368fcb89-279b-42b3-b173-4b0b74e80cff.png)
I trained the yolov5 model with size 640, and wants to set the inference size to be as big as possible. In one case the width is 1920 and the height is 1080 which are the same as the size of the input images. But I was given the error as indicated in the screenshot. Also, when the model was working where the inference width and height are both 1920, the performance is significantly lower than what is like in the orignial torch model. Really appreciate it if someone can offer some insight into it!

**Comment by marcoslucianops** [comment]
You must use the same size of the trained model (640) to get the correct output. The sizes must be multiple of 32.

**Comment by Xinxinatg** [comment]
> It doesn't need to be width=height but you must use the same size of the trained model (640) to get the correct output. The sizes must be multiple of 32.

thanks, this helps!
