### ISSUE TITLE
nvdsinfer_custom_impl_Yolo for Triton Server

### ISSUE THREAD

**Issue by levipereira** [marcoslucianops/DeepStream-Yolo#255]
Hi @marcoslucianops  did you have a version of nvdsinfer_custom_impl_Yolo wich works with Deepstream and Triton Server.
Nvidia https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_custom_YOLO.html#set-up-the-sample support  only old versions of Yolo.
I need function custom_parse_bbox_func: "NvDsInferParseYolo"  with support (yolor and yolov7) compatible with deepstream-triton.
If you have any version wich works with triton server let me know.

my conf:
```
infer_config {
  unique_id: 1
  gpu_ids: [0]
  max_batch_size: 20
  backend {
    triton {
      model_name: "yolov7"
      version: -1
      grpc {
        url: "0.0.0.0:8001"
      }
    }
  }

  preprocess {
    network_format: IMAGE_FORMAT_RGB 
    tensor_order: TENSOR_ORDER_NHWC
    maintain_aspect_ratio: 1
    frame_scaling_hw: FRAME_SCALING_HW_DEFAULT
    frame_scaling_filter: 1
    normalize {
      scale_factor: 0.0039215697906911373
    }
  }

  postprocess {
    labelfile_path: "/apps/configs/labels.txt"
    detection {
      num_detected_classes: 8
      custom_parse_bbox_func: "NvDsInferParseYolo"
      nms {
        confidence_threshold: 0.5
        topk: 300
        iou_threshold: 0.45
      }
    }
  }

  extra {
    copy_input_to_host_buffers: false
  }
  custom_lib {
    path : "/apps/custom/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so"
  }
}
input_control {
  process_mode : PROCESS_MODE_FULL_FRAME
  interval : 0
}
```

**Comment by levipereira** [comment]
I solve my problem using this :
https://forums.developer.nvidia.com/t/tutorial-how-to-run-yolov7-on-deepstream/229045

**Comment by levipereira** [comment]
https://github.com/WongKinYiu/yolov7/issues/875

**Comment by marcoslucianops** [comment]
Hi. I have no experience with Triton yet. Sorry.
