### ISSUE TITLE
I want to modfiy batchsize, what should I do?

### ISSUE THREAD

**Issue by BibibNanana** [marcoslucianops/DeepStream-Yolo#256]
yolov5 default batchsize value is 1, I want modify this, but I don't know where should I modify?
![image](https://user-images.githubusercontent.com/39188004/194273270-9af8cfe2-d506-4769-9848-19b233ec32b1.png)

**Comment by marcoslucianops** [comment]
Please see: https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/customModels.md#understanding-and-editing-config_infer_primary-file

The batch-size must be changed before the engine generation on DeepStream.

**Comment by Alberto1404** [comment]
@marcoslucianops , I have trained a custom model using 1280 as img-size during training. For best and most accurate predictions, as far as I know, the inference must take the same img-size. This should also be defined in ```config_infer_primary``` file? Does it take any default value (e.g. 640)? If so, the parameter to define in the txt file, based on [this website](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinfer.html#gst-nvinfer-file-configuration-specifications) should be ```infer-dims```, right?
That is, ```config_infer_primary``` should contain as follows: 
```
...
infer-dims = 3;1280;1280
...
```
Thanks in advance.

**Comment by marcoslucianops** [comment]
You just need to change the cfg file (width and height) and generate the engine again.
