### ISSUE TITLE
How to resize the input video stream in deepstream-app?

### ISSUE THREAD

**Issue by srikar242** [marcoslucianops/DeepStream-Yolo#26]
Hello @marcoslucianops . I have followed your repo and able to run yolov4-tiny model in deepstream. Now I want to run a video with a framesize of 2464X1440 in deepstream. I am getting a log that deepstream at max supports resolution of 2048X2048. So I want to resize my original input video framesize to less than 2048X2048. So how to do this resizing and where to add this? Your help would be appreciated.

**Comment by marcoslucianops** [comment]
Do you want to resize the yolo network, muxer or display?

**Comment by srikar242** [comment]
@marcoslucianops I think I have to resize muxer. I just want to resize the input frames that I am feeding into deepstream-app for inference.

**Comment by marcoslucianops** [comment]
> @marcoslucianops I think I have to resize muxer. I just want to resize the input frames that I am feeding into deepstream-app for inference.

Resize yolo network: change width and height in yolo.cfg to your values. It needs be square to use in deepstream, example: 2048x2048.

Resize muxer: change width and height in deepstream_app_config.txt in [streammux] section. It can be any value, not need to be square like yolo.cfg.

For better accuracy, you need to change the yolo network, but it will decrease the fps a lot according to the resolution.
