### ISSUE TITLE
yolov7 nms problem

### ISSUE THREAD

**Issue by peterchensm** [marcoslucianops/DeepStream-Yolo#261]
I trained a customed yolov7 model that reference from https://github.com/WongKinYiu/yolov7.
Then I use gen_wts_yoloV7.py to convert pt file to wts file.
I found the 349th line in gen_wts_yoloV7.py a problem and original code is：
 elif child._get_name() == '**Detect**':
            layers.Detect(child)
I modify this code to that.. 
 elif child._get_name() == '**IDetect'**:
            layers.Detect(child)

finally, the wts file could be generated by gen_wts_yoloV7.py .

My deepstream version is 6.1.
When I use my cutomed model wts and cfg file, the inference results of detection have the bad bounding box location.
I guess that is the NMS problem caused by deepstream inference.

I also inference the raw images by detect.py from https://github.com/WongKinYiu/yolov7 and the inference result is good.

**Comment by chirag-adagrad** [comment]
@peterchensm, did you resolve this issue?

**Comment by chirag-adagrad** [comment]
> @peterchensm, did you resolve this issue? I'm facing the same problem

@peterchensm, `IDetect` and `Detect` are apparently not interchangeable, which will result in unwanted behaviour, a work-around I did was to re-train my model with `Detect` and then generate the wts and cfg file. Ideal solution would be to add support for `IDetect` layer in `gen_wts_yoloV7.py` file

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/issues/241#issuecomment-1318019400
