### ISSUE TITLE
Running yolov4-tiny in deepstream python app slow FPS.

### ISSUE THREAD

**Issue by pteran2403** [marcoslucianops/DeepStream-Yolo#264]
Hello, I successfully ran my custom yolov4-tiny model using this repo and achieve 60 FPS. I tried using the Deesptream python sample apps with my custom models using the same 'nvdsinfer_custom_impl_Yolo' folder and I can only achieve 30 FPS. Is the C++/C implementation faster than the Python implementation?

**Comment by marcoslucianops** [comment]
C/C++ is faster than Python, but it's not a big difference. Are you using `sync=0` in your sink element?

**Comment by pteran2403** [comment]
Yes, I figured that `sync=0` will improve performance. Thanks for the reply. Your repo has been very helpful!
