### ISSUE TITLE
how setting nvinfer properties value in config-file via C++ code

### ISSUE THREAD

**Issue by simplystart-from-begining** [marcoslucianops/DeepStream-Yolo#272]
When i use g_object_set method，occur following case:
g_object_get_is_valid_property: object class 'GstNvInfer' has no property named 'num-detected-classes'

**Comment by marcoslucianops** [comment]
You need to set them in the `config_infer.txt` file.

**Comment by marcoslucianops** [comment]
You can check the available properties to use with `g_object_set` using the command:

```
gst-inspect-1.0 nvinfer
```
