### ISSUE TITLE
Can't generate a rtsp ?

### ISSUE THREAD

**Issue by Cong-Wan** [marcoslucianops/DeepStream-Yolo#273]
![image](https://user-images.githubusercontent.com/71088400/203711783-0408d7ce-3923-489a-94c5-69491a6cbc46.png)

**Comment by Cong-Wan** [comment]
> ![image](https://user-images.githubusercontent.com/71088400/203711783-0408d7ce-3923-489a-94c5-69491a6cbc46.png)

Sorry! I misunderstand this error message.
I mean ,the app must show in local? Does it can't generate a rtsp ?

**Comment by marcoslucianops** [comment]
Hi, you need to set `[sink] type=1` (Fakesink) in the `deepstream_app_config.txt` file. You are using SSH, and the output display isn't supported using it.

**Comment by Cong-Wan** [comment]
> Hi, you need to set `[sink] type=1` (Fakesink) in the `deepstream_app_config.txt` file. You are using SSH, and the output display isn't supported using it.

Morning！I change this and it's work! But I havn't get any rtsp output address, what's the problem?
I try to use this ip address`rtsp://<server IP>:8554/ds-test`, but it doesn't work. 
And I wanna know how add some logic in my algorithms!
![image](https://user-images.githubusercontent.com/71088400/203887668-227e4c32-9be9-42fc-8299-7dff2640399e.png)

**Comment by xzkeee** [comment]
try this, working on my jetson nano
`[sink0]
enable=1
#1: Fakesink 2: EGL based windowed sink (nveglglessink)3: Encode + File Save (encoder + muxer + filesink)4: Encode + RTSP streaming5: Overlay (Jetson only)6: Message converter + Message broker
type=4
sync=0
gpu-id=0
nvbuf-memory-type=0
#1=mp4 2=mkv
container=1
#1=h264 2=h265 3=mpeg4
codec=2
sync=0
bitrate=4000000       #=4000 kbps
rtsp-port=8854
udp-port=5400
source-id=0`

**Comment by Cong-Wan** [comment]
> 

I try to replace yours [sink0] with mine, it can generate a rtsp url, but it's invaild.
![image](https://user-images.githubusercontent.com/71088400/203930173-bb9b516d-b58b-4a29-9167-0ba2c9481ecb.png)
[config.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/10089693/config.txt)

**Comment by marcoslucianops** [comment]
For RTSP output:

```
[sink0]
enable=1
type=4
codec=1
enc-type=0
sync=0
bitrate=4000000
profile=0
rtsp-port=8554
udp-port=5400
source-id=0
```

**Comment by Cong-Wan** [comment]
> For RTSP output:
> 
> ```
> [sink0]
> enable=1
> type=4
> codec=1
> enc-type=0
> sync=0
> bitrate=4000000
> profile=0
> rtsp-port=8554
> udp-port=5400
> source-id=0
> ```

Thanks, it's work!!
But I have another question, if I wanna add some logic to my algorithms, what can I do?

**Comment by marcoslucianops** [comment]
You will need to create your custom code based on [deepstream_python_apps](https://github.com/NVIDIA-AI-IOT/deepstream_python_apps) or deepstream_c_apps (`/opt/nvidia/deepstream/deepstream-6.1/sources/apps/sample_apps`)
