### ISSUE TITLE
CUDA 11.4 Deepstream 6.1.1i do get this engine warning? When i try to create fp16 engine it does not then.

### ISSUE THREAD

**Issue by hazratpoladov** [marcoslucianops/DeepStream-Yolo#274]
CUDA_VER=11.4 make -C nvdsinfer_custom_impl_Yolo
make: Entering directory '/home/jetsonproject/Desktop/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'
g++ -c  -o utils.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-11.4/include utils.cpp
g++ -c  -o yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-11.4/include yolo.cpp
yolo.cpp: In member function ‘nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*)’:
yolo.cpp:122:85: warning: ‘nvinfer1::ICudaEngine* nvinfer1::IBuilder::buildEngineWithConfig(nvinfer1::INetworkDefinition&, nvinfer1::IBuilderConfig&)’ is deprecated [-Wdeprecated-declarations]
  122 | ne *engine = builder->buildEngineWithConfig(*network, *config);
      |                                                              ^

In file included from layers/convolutional_layer.h:12,
                 from yolo.h:29,
                 from yolo.cpp:26:
/usr/include/aarch64-linux-gnu/NvInfer.h:8899:43: note: declared here
 8899 |     TRT_DEPRECATED nvinfer1::ICudaEngine* buildEngineWithConfig(
      |                                           ^~~~~~~~~~~~~~~~~~~~~

**Comment by hazratpoladov** [comment]
I do get this engine failure when im trying to implement fp16 yolov7 engine

WARNING: Deserialize engine failed because file path: /home/jetsonproject/Desktop/DeepStream-Yolo/yolov7_b1_gpu0_fp16.engine open error
0:00:05.068192735  8221 0xaaaad80fd030 WARN                 nvinfer gstnvinfer.cpp:643:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1897> [UID = 1]: deserialize engine from file :/home/jetsonproject/Desktop/DeepStream-Yolo/yolov7_b1_gpu0_fp16.engine failed
0:00:05.128476377  8221 0xaaaad80fd030 WARN                 nvinfer gstnvinfer.cpp:643:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2002> [UID = 1]: deserialize backend context from engine from file :/home/jetsonproject/Desktop/DeepStream-Yolo/yolov7_b1_gpu0_fp16.engine failed, try rebuild

**Comment by marcoslucianops** [comment]
> ```8899 | TRT_DEPRECATED nvinfer1::ICudaEngine* buildEngineWithConfig(```

This warning is related to TensorRT and it's not a problem.

> ```WARNING: Deserialize engine failed because file path: /home/jetsonproject/Desktop/DeepStream-Yolo/yolov7_b1_gpu0_fp16.engine open error```

The engine is created with the default name `model_b1_gpu0_fp16.engine`. You need to rename it to `yolov7_b1_gpu0_fp16.engine` to prevent the new creation of the engine.
