### ISSUE TITLE
Can i use my .trt engine in Deepstream config file somehow?

### ISSUE THREAD

**Issue by hazratpoladov** [marcoslucianops/DeepStream-Yolo#275]
I have generated .trt file for my custom dataset individually. I want to know that how to implement this file in config docs of DeepstreamYolo repo.

**Comment by marcoslucianops** [comment]
Is it an YOLO model? If so, you need to do the steps available in the docs related to your YOLO model.

**Comment by Alberto1404** [comment]
I tried something similar exporting a pt file directly to .engine as follows: 
```
git clone https://github.com/ultralytics/yolov5.git
cd yolov5; pip install -r requirements.txt

python export.py --weights yolov5n.pt --data data/coco.yaml --img 540 960 --batch-size 4 --device 0 --int8 --dynamic --nms --topk-all 100 --iou-thres 0.45 --conf-thres 0.25 --include engine
```
This returns a engine file.
I set the correct path in the config file, leaving it somehow as below: 
```
[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
#custom-network-config=yolov5s.cfg
#model-file=yolov5s.wts
model-engine-file=model_b4_gpu0_int8.engine
int8-calib-file=calib.table
labelfile-path=labels.txt
batch-size=4
network-mode=1
num-detected-classes=80
interval=0
gie-unique-id=1
process-mode=1
network-type=0
cluster-mode=2
maintain-aspect-ratio=1
parse-bbox-func-name=NvDsInferParseYolo
custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
engine-create-func-name=NvDsInferYoloCudaEngineGet
symmetric-padding=1

[class-attrs-all]
topk=100
nms-iou-thres=0.45
pre-cluster-threshold=0.25
```
But when running Deepstream, it overwrites the engine file, instead of reading the one I creadted via ```export.py```

**Comment by marcoslucianops** [comment]
You should use this process to convert the model

https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv5.md
