### ISSUE TITLE
How can I display the detected objects on the video stream?

### ISSUE THREAD

**Issue by AIJIA000** [marcoslucianops/DeepStream-Yolo#276]
How can I display the detected objects on the video stream,thanks

**Comment by marcoslucianops** [comment]
Do you mean to output video stream (RTSP output)?

**Comment by AIJIA000** [comment]
Yes

**Comment by marcoslucianops** [comment]
For `deepstream-app`

```
[sink0]
enable=1
type=4
codec=1
enc-type=0
sync=0
bitrate=4000000
profile=0
rtsp-port=8554
udp-port=5400
gpu-id=0
```

The output RTSP will be `rtsp://localhost:8554/ds-test` with this configuration.

**Comment by emad555** [comment]
I am getting this error when I try to do the rtsp:
GLib-GObject-WARNING **: 14:04:56.299: g_object_get_is_valid_property: object class 'GstUDPSrc' has no property named 'pt'

**Comment by marcoslucianops** [comment]
It's not an error, just a GStreamer warning.
