### ISSUE TITLE
Yolov7 instance segmentation with deepstream?

### ISSUE THREAD

**Issue by aurelm95** [marcoslucianops/DeepStream-Yolo#279]
How can I deploy an instance segmentation yolov7 model with deepstream? Once I export the model to `.trt`, I need to parse the output layers.

Is it planned to add this feature here?

Thanks!

**Comment by marcoslucianops** [comment]
Hi, I have plan to implement it in the future.

**Comment by aurelm95** [comment]
Nice, thank you. I will stay tuned

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo-Seg
