### ISSUE TITLE
Some tactics do not have sufficient workspace memory to run

### ISSUE THREAD

**Issue by JsBlueCat** [marcoslucianops/DeepStream-Yolo#28]
Some tactics do not have sufficient workspace memory to run

when using yolov4 in jetson NX1

already have set the workspace-size = 4000

**Comment by marcoslucianops** [comment]
Where did you set workspace-size?

**Comment by marcoslucianops** [comment]
I think it's a bug with TensorRT, but you can try to increase it to a high value based on the available GPU memory.

**Comment by marcoslucianops** [comment]
Edit /opt/nvidia/deepstream/deepstream-5.0/sources/libs/nvdsinfer/nvdsinfer_model_builder.h file

```
static const size_t kWorkSpaceSize = 450 * 1024 * 1024; // 450MB
```

To high value based on the available GPU memory.

See intructions in README file (in folder) to compile it again.

If you get ``` Cuda Error in allocate: 2 (out of memory)``` error, try decreasing the value until it works

Set workspace-size to same value you set in nvdsinfer_model_builder file.

**Comment by JsBlueCat** [comment]
> Edit /opt/nvidia/deepstream/deepstream-5.0/sources/libs/nvdsinfer/nvdsinfer_model_builder.h file
> 
> ```
> static const size_t kWorkSpaceSize = 450 * 1024 * 1024; // 450MB
> ```
> 
> To high value based on the available GPU memory.
> 
> See intructions in README file (in folder) to compile it again.
> 
> If you get ` Cuda Error in allocate: 2 (out of memory)` error, try decreasing the value until it works
> 
> Set workspace-size (in config_infer_primary.txt file) to same value you defined in nvdsinfer_model_builder file
> 
> In my tests, these steps don't increase performance

thanks , solved!
