### ISSUE TITLE
Yolov5 run slow with python binding

### ISSUE THREAD

**Issue by arielkantorovich** [marcoslucianops/DeepStream-Yolo#280]
• Hardware Platform :Jetson Nano
• DeepStream: 6.0
• JetPack Version: 4.6.1
• TensorRT Version: 8.2.1.8
• NVIDIA GPU Driver Version (valid for GPU only)
• Issue Type: questions

Hi  everyone I have some problem that I can't figure out  I try
To run yolo5s on my jetson nano, When I run by the command:

`deepstream-app -c deepstream_app_config.txt`

I get result around 8.5 FPS

and when I try using binding in python I get a very slow result I can’t understand why? of course I need to mention that I new with deepstream I learn this only this week and using python binding can very help me to my goals.

I add to short videos of the result I would be happy to any help thank you :)
In addition I run my code with the configuration:

[config_infer_primary_yoloV5.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/10257915/config_infer_primary_yoloV5.txt)

when I try to run the code with this configuration I get parsing error I cant understand why?

[deepstream_app_config_yoloV5_check.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/10257926/deepstream_app_config_yoloV5_check.txt)

I will be happy to help of course I want to run yolo with python bindings it's exactly what I need for my project and I am sure that it's some configuration problem.

https://user-images.githubusercontent.com/56262208/208392325-ed968f8d-1a17-40d0-9a2d-b7e2dda6ae76.mp4

https://user-images.githubusercontent.com/56262208/208392334-812fda2c-2661-4eb6-bcce-65b6033a2b44.mp4

**Comment by marcoslucianops** [comment]
Please change/add to your code (after the `sink = Gst.ElementFactory.make`)

```
sink.set_property('sync', 0)
```
