### ISSUE TITLE
INT8 Quantization - calibration table missing

### ISSUE THREAD

**Issue by costaz9** [marcoslucianops/DeepStream-Yolo#282]
Hi,
I'm using your repo to run inference on live camera stream with YoloV5 (Jetson Nano - DeepStream-6).
The engine work well using FP32 or FP16. 

However, I'm trying to convert the model with int8 quantization, and I followed your guide:

- build **nvdsinfer_custom_impl_Yolo** lib
- download and setup a **calibration folder** with the images
- modify the config file with **network-mode=1** and **int8-calib-file=calib.table**

The problem is that te calibration table (**calib.table**) is not generated during the above steps.
Do you have any suggestions to solve this problem and perform integer quantization, or there are other related issues?.

Thanks for your time.

**Comment by Alberto1404** [comment]
That happened to me as well. [Check this](https://forums.developer.nvidia.com/t/engine-file-and-calib-table-not-saved-in-deepstream/237755/2)
I solved it removing everything and doing it again in my Jetson, following this guide: [https://docs.ultralytics.com/tutorials/nvidia-jetson/#int8-calibration](https://docs.ultralytics.com/tutorials/nvidia-jetson/#int8-calibration). 
It suddenly began working for me.

**Comment by ClydeU420** [comment]
> That happened to me as well. [Check this](https://forums.developer.nvidia.com/t/engine-file-and-calib-table-not-saved-in-deepstream/237755/2) I solved it removing everything and doing it again in my Jetson, following this guide: https://docs.ultralytics.com/tutorials/nvidia-jetson/#int8-calibration. It suddenly began working for me.

I found your link first, but it didn't work for me

**Comment by marcoslucianops** [comment]
Hi. You need to compile the `nvdsinfer_custom_impl_Yolo` with OpenCV to make the calibration. Did you do it?

**Comment by Muammer06** [comment]
hi, you should need train first with calibration images, after that step calib.table is generated and no longer need calibration images.

**Comment by avn3r** [comment]
This error is because you need to clean the lib before recreating the lib with OpenCV.
```
rm -rf nvdsinfer_custom_impl_Yolo/*.o
rm -rf nvdsinfer_custom_impl_Yolo/*.so
CUDA_VER=<YOUR-CUDA> OPENCV=1 make -C nvdsinfer_custom_impl_Yolo
```

@marcoslucianops You might want to add this in the tutorial. Basically if the lib has been created running the lib wont reinstall it with OpenCV. So you have to clean the make and then reinstall.

**Comment by marcoslucianops** [comment]
@avn3r You can run

```
CUDA_VER=<YOUR-CUDA> OPENCV=1 make -C nvdsinfer_custom_impl_Yolo clean
```

To remove the old files and run the

```
CUDA_VER=<YOUR-CUDA> OPENCV=1 make -C nvdsinfer_custom_impl_Yolo
```

To compile.

**Comment by avn3r** [comment]
@marcoslucianops Thanks, that's an even cleaner solution. I'm unblocked on this end. It was more about potentially adding this to the INT8 quantization doc to avoid others from getting this error. 

Thanks for your work!
