### ISSUE TITLE
Is there any difference from the engine file created through onnx?

### ISSUE THREAD

**Issue by YoungjaeDev** [marcoslucianops/DeepStream-Yolo#283]
Since the build methods are different even though they are the same pytorch pt file, 
can you say that the engine made by DeepStream yolo is better?

**Comment by marcoslucianops** [comment]
I didn't test it yet, but I have plans to make the comparisson between them soon.

**Comment by Alberto1404** [comment]
@youngjae-avikus How do you build the engine with onnx?

**Comment by youngjae-avikus** [comment]
> @youngjae-avikus How do you build the engine with onnx?

Simply use torch.onnx.export.

**Comment by Alberto1404** [comment]
> > @youngjae-avikus How do you build the engine with onnx?
> 
> Simply use torch.onnx.export.

Sorry, I was referring to create the engine in deepstream given the onnx
