### ISSUE TITLE
Deserialize yoloLayer plugin: (Unnamed Layer* 256) [PluginV2IOExt]

### ISSUE THREAD

**Issue by colinleng** [marcoslucianops/DeepStream-Yolo#284]
firt i use gen_wts-yoloV5.py in program to out put *.cfg and *.wts ,this step is OK
then i use *.wts,*.wts  in  deepstram-yolo and replace to config_infer_primary_yoloV5.txt
then i run deepstram-app -c deepstram_app_config.txt  this step is OK
then i use this engine in deepstream-python , i got this erro:
Deserialize yoloLayer plugin: (Unnamed Layer* 256) [PluginV2IOExt]

so , can you help me. how to do ?

**Comment by marcoslucianops** [comment]
Hi, can you send the full log? It's strange because this repo doesn't use `PluginV2IOExt`.
