### ISSUE TITLE
Output of video is PERF 0.00 (0.00)

### ISSUE THREAD

**Issue by rasugurav** [marcoslucianops/DeepStream-Yolo#285]
I have followed all the steps given in the repo. Installed all dependencies as well. 
After running model there is no error but output video is not generating, I am getting below output

**PERF:  FPS 0 (Avg)
**PERF:  0.00 (0.00)
** INFO: <bus_callback:194>: Pipeline ready

**PERF:  0.00 (0.00)
**PERF:  0.00 (0.00)
**PERF:  0.00 (0.00)
**PERF:  0.00 (0.00)
**PERF:  0.00 (0.00)
**PERF:  0.00 (0.00)
**PERF:  0.00 (0.00)
**PERF:  0.00 (0.00)
**PERF:  0.00 (0.00)
**PERF:  0.00 (0.00)

I have used YoloV7 weights and cfg.

**Comment by marcoslucianops** [comment]
Which board are you using?
