### ISSUE TITLE
how to configure deepstream with msg_broker? 

### ISSUE THREAD

**Issue by animeesh** [marcoslucianops/DeepStream-Yolo#286]
I am struggling in configuring deepstream for msg broker. my end goal is to take generated meta data and create powerBi analytics .

**Comment by marcoslucianops** [comment]
Hi, to use msgbroker, you need to use the `deepstream-test4` or `deepstream-test5` apps, or create custom code with `nvmsgconv` and `nvmsgborker` plugins.

**Comment by animeesh** [comment]
I have finished configuring it, but the data is in stream format i.e by Kafka means. i need to push it to a database for further analytics.

**Comment by marcoslucianops** [comment]
The `deepstream-app` is only an example for use this repo. You can use it in every deepstream code by setting it in the `nvinfer` plugin.
