### ISSUE TITLE
Ghost layers in YOLOv5

### ISSUE THREAD

**Issue by junghyun-avikus** [marcoslucianops/DeepStream-Yolo#287]
I was trying to implement ghost layers in the yolov5 model/hub directory in gen_wts.py,
and I am sort of stuck in implementing GhostBottleneck.

```python
class GhostBottleneck(nn.Module):
    # Ghost Bottleneck https://github.com/huawei-noah/ghostnet
    def __init__(self, c1, c2, k=3, s=1):  # ch_in, ch_out, kernel, stride
        super().__init__()
        c_ = c2 // 2
        self.conv = nn.Sequential(
            GhostConv(c1, c_, 1, 1),  # pw
            DWConv(c_, c_, k, s, act=False) if s == 2 else nn.Identity(),  # dw
            GhostConv(c_, c2, 1, 1, act=False))  # pw-linear
        self.shortcut = nn.Sequential(DWConv(c1, c1, k, s, act=False), Conv(c1, c2, 1, 1,
                                                                            act=False)) if s == 2 else nn.Identity()

    def forward(self, x):
        return self.conv(x) + self.shortcut(x)
```

I have implemented GhostConv with the following code snippet,
```python
  def GhostConv(self, child):
      self.currenct = child.i
      self.fc.write('\n# GhostConv\n')

      self.convolutional(child.cv1)
      self.convolutional(child.cv2)
      self.route('-2', '-1')
```

Should I just fully extract all the layers stacked by GhostConv -> DWConv -> GhostConv in the GhostBottleneck func?
Or should I implement GhostConv and DWConv, and just call them in the GhostBottleneck func?
Since GhostConv write into fc, it seems like I can't just call them in the GhostBottleneck func.

**Comment by marcoslucianops** [comment]
Hi, you need to create the logic for those function because they aren't simple convolutions.
