### ISSUE TITLE
How to edit reference deepstream-app for custom functions?

### ISSUE THREAD

**Issue by Justin-king-de** [marcoslucianops/DeepStream-Yolo#29]
Hi @marcoslucianops I have followed your tutorial and able to run tiny-yolov4 model on nano. I understood a pipeline in deepstream can be created using config files. Now however I want to edit the reference `deepstream-app` to add some custom functionalities. In which file can I edit for them? I have seen some` deepstream-test` samples and all of them have a .c/.cpp files to edit the pipeline. I have followed your tutorial. So in this process, which files are used. Are the files in located in `/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-app` ? If I edit the file in` /opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-app` and then run from your directory, will they work? In which file should I edit. Please help me with this.

**Comment by marcoslucianops** [comment]
You need to edit files in ```/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-app/```, recompile and move generated ```deepstream-app``` to ```/opt/nvidia/deepstream/deepstream-5.0/bin/``` folder to use from anywhere with the command ```deepstream-app -c ...```.

**Comment by marcoslucianops** [comment]
You can simple ```make``` and ```sudo make install``` to compile and move to ```/opt/nvidia/deepstream/deepstream-5.0/bin``` folder.

**Comment by Justin-king-de** [comment]
@marcoslucianops Okay. Thanks
