### ISSUE TITLE
How to save the output result of yolov5 detection video

### ISSUE THREAD

**Issue by hupu1dong** [marcoslucianops/DeepStream-Yolo#291]
I ran yoloV5 successfully, but I found that there was no option to save the results. I want to know how to save the video detection results. my command is deepstream-app -c deepstream_app_config.txt

**Comment by marcoslucianops** [comment]
Add these lines before `[osd]` in `deepstream_app_config.txt` file:

```
[sink1]
enable=1
type=3
container=1
codec=1
enc-type=0
sync=0
bitrate=4000000
profile=0
output-file=output.mp4
source-id=0
```

**Comment by hupu1dong** [comment]
**When I enter a command：**

deepstream-app -c deepstream_app_config.txt

**display：**

Opening in BLOCKING MODE 
Deserialize yoloLayer plugin: yolo_93
Deserialize yoloLayer plugin: yolo_96
Deserialize yoloLayer plugin: yolo_99
0:00:07.467033471 16463     0x218ce390 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1900> [UID = 1]: deserialized trt engine from :/mnt/zsfdatas/DeepStream-Yolo-master/model_b1_gpu0_fp32.engine
INFO: [Implicit Engine Info]: layers num: 4
0   INPUT  kFLOAT data            3x640x640       
1   OUTPUT kFLOAT yolo_93         24x80x80        
2   OUTPUT kFLOAT yolo_96         24x40x40        
3   OUTPUT kFLOAT yolo_99         24x20x20        

0:00:07.467425631 16463     0x218ce390 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2004> [UID = 1]: Use deserialized engine model: /mnt/zsfdatas/DeepStream-Yolo-master/model_b1_gpu0_fp32.engine
0:00:07.663486650 16463     0x218ce390 INFO                 nvinfer gstnvinfer_impl.cpp:313:notifyLoadModelStatus:<primary_gie> [UID 1]: Load new model:/mnt/zsfdatas/DeepStream-Yolo-master/config_infer_primary_yoloV5.txt sucessfully

Runtime commands:
        h: Print this help
        q: Quit

        p: Pause
        r: Resume

NOTE: To expand a source in the 2D tiled display and view object details, left-click on the source.
      To go back to the tiled display, right-click anywhere on the window.


**PERF:  FPS 0 (Avg)
**PERF:  0.00 (0.00)
** INFO: <bus_callback:194>: Pipeline ready

Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
** INFO: <bus_callback:180>: Pipeline running

NvMMLiteOpen : Block : BlockType = 4 
===== NVMEDIA: NVENC =====
NvMMLiteBlockCreate : Block : BlockType = 4 
H264: Profile = 66, Level = 0 
NVMEDIA_ENC: bBlitMode is set to TRUE 
**PERF:  33.58 (33.44)
**PERF:  33.19 (33.31)
**PERF:  33.15 (33.27)
**PERF:  32.80 (33.15)
**PERF:  33.09 (33.12)
**PERF:  33.06 (33.13)
** INFO: <bus_callback:217>: Received EOS. Exiting ...

Quitting
App run successful

**Comment by hupu1dong** [comment]
There is no detection result in this output video.

**Comment by hupu1dong** [comment]
![image](https://user-images.githubusercontent.com/58175002/217424158-ef8cf81a-679d-4a5b-bbd5-b1eafe44ecd3.png)

**Comment by hupu1dong** [comment]
**my deepstream_app_config.txt:**

`[application]
enable-perf-measurement=1
perf-measurement-interval-sec=5

[tiled-display]
enable=1
rows=1
columns=1
width=1280
height=720
gpu-id=0
nvbuf-memory-type=0

[source0]
enable=1
type=3
uri=file://sunsity.mp4
num-sources=1
gpu-id=0
cudadec-memtype=0

[sink0]
enable=0
type=2
sync=0
gpu-id=0
nvbuf-memory-type=0

[sink1]
enable=1
type=3
container=1
codec=1
enc-type=0
sync=0
bitrate=4000000
profile=0
output-file=output.mp4
source-id=0

[osd]
enable=0
gpu-id=0
border-width=5
text-size=15
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Serif
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0

[streammux]
gpu-id=0
live-source=0
batch-size=1
batched-push-timeout=40000
width=1920
height=1080
enable-padding=0
nvbuf-memory-type=0

[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary_yoloV5.txt

[tests]
file-loop=0
`

**Comment by hupu1dong** [comment]
my **config_infer_primary_yoloV5.txt**

`[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
custom-network-config=suncity.cfg
model-file=suncity.wts
model-engine-file=model_b1_gpu0_fp32.engine
#int8-calib-file=calib.table
labelfile-path=vavdt.txt
batch-size=1
network-mode=0
num-detected-classes=3
interval=0
gie-unique-id=1
process-mode=1
network-type=0
cluster-mode=2
maintain-aspect-ratio=1
parse-bbox-func-name=NvDsInferParseYolo
custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
engine-create-func-name=NvDsInferYoloCudaEngineGet

[class-attrs-all]
nms-iou-threshold=0.6
pre-cluster-threshold=0.25
`

**Comment by hupu1dong** [comment]
**my vavdt.txt:**
car
truck
bus

**Comment by hupu1dong** [comment]
But I used YOLOv5 detect.py to test this model. The result is

![image](https://user-images.githubusercontent.com/58175002/217426094-1931dfaf-a7c2-413d-a681-569b6baf4c0d.png)

**Comment by hupu1dong** [comment]
Can be detected，when osd enable = 1:

![image](https://user-images.githubusercontent.com/58175002/217429105-e5d3fbcf-bd41-48ba-bb5c-13d685a967a7.png)

**Comment by hupu1dong** [comment]
But why is the box black

**Comment by hupu1dong** [comment]
How to use this osd

**Comment by marcoslucianops** [comment]
For `deepstream-app`, you can refer to https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_ref_app_deepstream.html#osd-group

**Comment by hupu1dong** [comment]
You are a real master. Thank you very much
