### ISSUE TITLE
benchmarks results

### ISSUE THREAD

**Issue by aurelm95** [marcoslucianops/DeepStream-Yolo#292]
According to the [results ](https://github.com/marcoslucianops/DeepStream-Yolo#results) in your readme, the yolov7-tiny and yolov4 tiny are equally fast. How is this posible? isn't yolov7 supposed to be way faster than the v4?

Thanks!

**Comment by marcoslucianops** [comment]
I realized that the V100 was performing ~630 FPS at maximum. I will change the tests to T4 to get more confident results.

**Comment by jiangdizhao** [comment]
yoloPlugins.cpp:45:1: error: ‘cudaError_t’ does not name a type; did you mean ‘cudaEvent_t’?
 cudaError_t cudaYoloLayer_x(const void* input, void* num_detections, void* detection_boxes, void* detection_scores,
 ^~~~~~~~~~~
 cudaEvent_t
yoloPlugins.cpp:49:1: error: ‘cudaError_t’ does not name a type; did you mean ‘cudaEvent_t’?
 cudaError_t cudaYoloLayer_v8(const void* input, void* num_detections, void* detection_boxes, void* detection_scores,
 ^~~~~~~~~~~
 cudaEvent_t

**Comment by jiangdizhao** [comment]
can not understand why "‘cudaError_t’" can not be found ?  When I try to compile older version of  the project(with no yolov8 support), there is no such problem. I even checkout makefile and every .h file, but nothing has beed found

**Comment by marcoslucianops** [comment]
Try to add

```
#include <cuda_runtime_api.h>
```

In the top of the `nvdsinfer_custom_impl_Yolo]
/yoloPlugins.h` file.

**Comment by jiangdizhao** [comment]
actually, I added 
#include "driver_types.h"
#include "cuda_runtime_api.h"

succeed!

By the way, is the model FP16 or FP32 by default setting ?

**Comment by marcoslucianops** [comment]
The default is FP32. To use FP16, you need to set `network-mode=2` in the `config_infer.txt` file.
