### ISSUE TITLE
Error in compiling the lib

### ISSUE THREAD

**Issue by lucastack** [marcoslucianops/DeepStream-Yolo#293]
Hi!

I'm using docker image `nvcr.io/nvidia/deepstream:6.1.1-triton` to build the app. Already have the .cfg and .wts files of  `yolov7` in DeepStream-Yolo folder.  

When triying to compile it with `CUDA_VER=11.7 make -C nvdsinfer_custom_impl_Yolo` i get the following error

![image](https://user-images.githubusercontent.com/53802157/216080664-306e7a3e-21ba-469b-a186-a13cdefa0892.png)

Is there anything im missing out? 

Thanks

**Comment by marcoslucianops** [comment]
The TensorRT installed on `triton` image doesn't have the createReorgPlugin function. If you will not use YOLOv2, you can comment the lines related to it in the code (only the YOLOv2 part). Another option is use the `devel` image, and it will work without need to change the code.

**Comment by lucastack** [comment]
I could compile it after commenting those lines, thanks! 

But after i try to run the app with `deepstream-app -c deepstream_app_config.txt` i get this

![image](https://user-images.githubusercontent.com/53802157/216188652-983280e7-536d-4070-bd15-e75db24bed00.png)


My config is 

[application]
enable-perf-measurement=1
perf-measurement-interval-sec=5

[tiled-display]
enable=1
rows=1
columns=1
width=1280
height=720
gpu-id=0
nvbuf-memory-type=0

[source0]
enable=1
type=3
uri=file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4
num-sources=1
gpu-id=0
cudadec-memtype=0

[sink0]
enable=1
type=1
container=1
codec=1
enc-type=0
sync=0
bitrate=4000000
profile=0
output-file=output.mp4
source-id=0

[osd]
enable=1
gpu-id=0
border-width=5
text-size=15
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Serif
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0

[streammux]
gpu-id=0
live-source=0
batch-size=1
batched-push-timeout=40000
width=1920
height=1080
enable-padding=0
nvbuf-memory-type=0

[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary_yoloV7.txt

[tests]
file-loop=0


I need to process an mp4 video and get the output.mp4 file, is this configuration correct?

Im running this inside docker

Thanks in advance!

**Comment by marcoslucianops** [comment]
You file seems correct. Can you send me the output of the below command?

```
gst-inspect-1.0 nvinfer
```

Note: You can disable the `[tiled-display]` running without `[sink] type=2` (`nveglglessink`)

**Comment by lucastack** [comment]
It looks like i had some problems with drivers on the machine. After reinstalling them everything went good and i could get the output.mp4 with type=3 in the sink. Sadly, it doesn't show any detection, is there something i'm missing?

**Comment by lucastack** [comment]
It looks like i had to set enable=1 and display-bbox=1 [osd] in the config file, afther that i get the bboxes

![image](https://user-images.githubusercontent.com/53802157/216399468-3ea16e4b-5aef-4833-8f67-da539561a29c.png)

Appreciate you help, thank you!
