### ISSUE TITLE
Error compiling lib with opencv

### ISSUE THREAD

**Issue by Alberto1404** [marcoslucianops/DeepStream-Yolo#296]
Hi, I attempted to compile the lib using the following command: 
```CUDA_VER=10.2 OPENCV=1 make -C nvdsinfer_custom_impl_Yolo```
And I am getting the following error: 
![error](https://user-images.githubusercontent.com/91409881/216316228-84303e78-5bae-45c1-9f1b-2ba36b1dcfe1.png)
Any idea?
Regards

**Comment by marcoslucianops** [comment]
I updated the repo to fix this error

**Comment by Alberto1404** [comment]
Thank you. Solved
