### ISSUE TITLE
Grayscale YoloV5 Support

### ISSUE THREAD

**Issue by Arpit1496** [marcoslucianops/DeepStream-Yolo#297]
Does yolov5 support grayscale ?
When I try to change the model-color-format  to 2 (from 0) in config_infer_yolov5, the engine generation failed saying “error: model format color was gray but channels was not set to 1”.

I tried to change channels from 3 to 1 in gen_wts_yolov5 while building cfg and wts files but still engine building failed with “error: unused weights”. 

Does the repo support grayscale model formats ?

**Comment by marcoslucianops** [comment]
Yes, it supports, but your model need to be trained with 1 color channel.

To run it, you need to change the `yolo.cfg` file

```
channels=3
```

to 

```
channels=1
```

And change the `config_infer.txt` file

```
model-color-format=0
```

to 

```
model-color-format=2
```

**Comment by Arpit1496** [comment]
Hey,
Thanks for the quick response. I have been trying this since 2 days with different permutations and combinations, but had no success. These are the different cases I tried. I have a base yolov8s model pt file which was trained on 1 channel with no. of classes being 1.

Trial 1:
- I copied gen_wts_yolov8.py file in folder. 
- I ran the following command: "python3 gen_wts_yolov8.py -s 320"
- It generated .cfg. and .wts file. The .cfg file had channels -3 which I changed to 1 (as you mentioned) before building engine.
- I set model color format to 2 in config_infer.txt.
- I built the engine but it Failed with "Unused weights left" error. 
- This error occurred with channel = 3 as well in .cfg. The unused weights altered a little in both error messages.

Trial 2:
- I copied gen_wts_yolov8.py file in folder. 
- I updated "hard coded" channel=3 in gen_wts_yolov8.py (Line 86).
- I ran the following command: "python3 gen_wts_yolov8.py -s 320"
- It generated .cfg. and .wts file. The .cfg file had channels -1.
- I set model color format to 2 in config_infer.txt.
- I built the engine but it Failed with "Unused weights left" error again.

Can you guide me where I might be doing something wrong ?

**Comment by marcoslucianops** [comment]
Can you send me the first epoch of your model to check the conversion?

**Comment by Arpit1496** [comment]
Thans for your time.
This is the lin of the model yolob8s with nc =1 and channel =1.
https://drive.google.com/file/d/1WlVy01dxkHkFp2of3tTtP-ddOPHyRbjm/view?usp=sharing

**Comment by marcoslucianops** [comment]
![image](https://user-images.githubusercontent.com/47423225/217873095-2fe6079c-68f0-4709-b7c8-765643ca697d.png)

Your model is 3 channel in the input (see the input of the conv_0).

**Comment by marcoslucianops** [comment]
How did you change the channels in the ultralytics?

**Comment by Arpit1496** [comment]
We changed the yaml file used for training. 
Just added “ch=1” before training. 
It is also to be noted that even tho the channels shown in convolution layer is 3, it still fails to build engine even with channel =3 in cfg file.

**Comment by marcoslucianops** [comment]
The `model.yaml` returns `... 'ch': 3}` in the pt file.

![image](https://user-images.githubusercontent.com/47423225/217915304-302a6f87-d614-4c7a-aec8-cd8d8da32f73.png)

**Comment by Arpit1496** [comment]
Hey,
sorry for the late reply. 
i saw the training file in repository and it seems they accept ch as input but does not use it. This is the issue of yolov8. I will raise an issue there. Also I will try this again after a fix. Thanks for your time.
