### ISSUE TITLE
Fail to execute deepstream on yolov7

### ISSUE THREAD

**Issue by PhiDCH** [marcoslucianops/DeepStream-Yolo#298]
Hi, I followed the instructions from https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv7.md but on the last step app failed to run.

Docker image: nvcr.io/nvidia/deepstream:6.1.1-devel
I run container by: 
docker run -it --rm -v DeepStream-Yolo:/opt/nvidia/deepstream/deepstream-6.1/DeepStream-Yolo nvcr.io/nvidia/deepstream:6.1.1-devel

root@1220d6a7a7cc:/opt/nvidia/deepstream/deepstream-6.1/DeepStream-Yolo# deepstream-app -c deepstream_app_config.txt 
** ERROR: <create_multi_source_bin:1457>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1550>: create_multi_source_bin failed
** ERROR: <create_pipeline:1327>: create_pipeline failed
** ERROR: <main:697>: Failed to create pipeline
Quitting
App run failed

**Comment by marcoslucianops** [comment]
Try to run `/opt/nvidia/deepstream/deepstream/user_additional_install.sh` to install missing dependencies.

**Comment by PhiDCH** [comment]
I've already run 
/opt/nvidia/deepstream/deepstream/user_additional_install.sh
 when start docker container, but still got the same error

**Comment by marcoslucianops** [comment]
Did you change the `deepstream_app_config.txt` file?

**Comment by PhiDCH** [comment]
Thank you, I've change deepstream_app_config.txt file.
I restarted docker and ran container with the following and it worked!

docker run --gpus all -it --rm --net=host --privileged -v deepstream:/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream -e DISPLAY=$DISPLAY -w /opt/nvidia/deepstream/deepstream-6.1 nvcr.io/nvidia/deepstream:6.1.1-devel
