### ISSUE TITLE
Convert to fp16 or mixed precision

### ISSUE THREAD

**Issue by PhiDCH** [marcoslucianops/DeepStream-Yolo#299]
I ran [deepstream-app](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv7.md) and noticed that the code convert model to tensorrt fp32 precision. Is there any way to convert to a more efficient tensorrt model like fp16 or mixed precision?

**Comment by marcoslucianops** [comment]
To use FP16, you need to set `network-mode=2` in the `config_infer.txt` file. You also need to change the `model-engine-file` to `model-engine-file=model_b1_gpu0_fp16.engine` to prevent engine recreation every run.

**Comment by PhiDCH** [comment]
The model size was reduced by a half but fps did not increase, still the same as fp32

**Comment by marcoslucianops** [comment]
What's the FPS and which board are you using?

**Comment by PhiDCH** [comment]
![image](https://user-images.githubusercontent.com/59147911/217496333-becb1c5a-7448-4950-bfe8-46cb775f9ebe.png)
fps is calculated by deepstream app

**Comment by marcoslucianops** [comment]
When using `[sink] type=2`, in the `deepstream_app_config.txt` file, the FPS is limited to the screen vsync. You need to use `[sink] type=1` (fakesink) to get the maximum fps.

**Comment by PhiDCH** [comment]
Thank you, it worked

**Comment by huytranvan2010** [comment]
> Thank you, it worked

@PhiDCH @marcoslucianops could you share code to evaluate .engine model to receive mAP in Deepstream-yolo? I am really appreciate

**Comment by huytranvan2010** [comment]
> 
> @huytranvan2010 the code to evaluate mAP of .engine model does not relate to Deepstream, it depends on the yolo version (yolov5, v6,v7, ..)

I mean that we evaluate .engine model (after converting in Deepstream from .pt model). I understood that we can evaluate .pt model. Did you evaluate .engine Yolo's model?

**Comment by PhiDCH** [comment]
@huytranvan2010 .engine model created by Deepstream is the same .engine model when convert by tensorrt, so you can test mAP using tensorrt python API
