### ISSUE TITLE
save bounding box data and show the cropped object detection

### ISSUE THREAD

**Issue by jeansely** [marcoslucianops/DeepStream-Yolo#3]
Hi, Thank you for this repository,
i am not professional in C&C++. and use 3 yolo models back to back for car plate recognition. 
how can save and show only object detected in each step of deepstream. and in last model how can sort left to right object detection(for take plate numbers). please sample code..
 Many Thanks .

**Comment by marcoslucianops** [comment]
Hi,

> how can save and show only object detected in each step of deepstream

To do this, I think you need use gst-dsexample (located in /opt/nvidia/deepstream/deepstream-4.0/sources/gst-plugins) and add opencv function to save/show images during detection process.

> how can sort left to right object detection(for take plate numbers)

You need manipulate [NvDsObjectMeta](https://docs.nvidia.com/metropolis/deepstream/4.0/dev-guide/DeepStream_Development_Guide/baggage/struct__NvDsObjectMeta.html), [NvDsFrameMeta](https://docs.nvidia.com/metropolis/deepstream/4.0/dev-guide/DeepStream_Development_Guide/baggage/struct__NvDsFrameMeta.html) and [NvOSD_RectParams](https://docs.nvidia.com/metropolis/deepstream/4.0/dev-guide/DeepStream_Development_Guide/baggage/struct__NvOSD__RectParams.html) to get label, position, etc.

> please sample code

My ALPR project isn't open source. I can help you with above informations.
