### ISSUE TITLE
Use custom yolov4-tiny model which has 6 classes on Deepstream

### ISSUE THREAD

**Issue by mtduman** [marcoslucianops/DeepStream-Yolo#30]
Hi,  thanks for your hard work and sharing it with us !
I'm able to use pre-trained yoloV4 and yoloV4-tiny with Deepstream, but had problem on custom yoloV4-tiny model. I would like to use my custom yoloV4-tiny model which has 6 classes.

For the original Deepstream API, I was just changing the "static const int NUM_CLASSES_YOLO = 6" on "nvdsparsebbox_Yolo.cpp" file , then make it and then able to use the generated "libnvdsinfer_custom_impl_Yolo.so" file with my custom-yoloV3 weight file to inference on Deepstream 5.

Please guide me to use my custom yoloV4-tiny model on Deeepstream 5

Your help would be appreciated!

**Comment by marcoslucianops** [comment]
Hi,

You don't need to edit cpp files, my files parse yolo.cfg file and config all settings automatically during engine build. Just edit config_infer_primary.txt for your custom model.

**Comment by mtduman** [comment]
Great!
It works, thanks
