### ISSUE TITLE
Exception occured on int8 calibration

### ISSUE THREAD

**Issue by kks-bakaneko** [marcoslucianops/DeepStream-Yolo#302]
Hi guys, I want int8 calibrated my custom yolov5 model, when I tried to convert it I got Aborted(core dumped).
File does not exist: /opt/nvidia/deepstream/~yoloengine path/calib.table
python3: yolo.cpp:76: nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*): Assertion `builder->platformHasFastInt8()' failed.
Aborted

And, I got this message in when load model

Using winsys: x11 
0:00:00.368514852  8197     0x3f56f150 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 1]: Trying to create engine from model files
WARNING: INT8 not supported by platform. Trying FP16 mode.

What could be problem?

**Comment by kks-bakaneko** [comment]
Just hardware issue
TX2 doesn't support  int8 calibration

**Comment by marcoslucianops** [comment]
Yes, TX2 doesn't support it.
