### ISSUE TITLE
wts and cfg files generate engine how to support dynamic dimension input

### ISSUE THREAD

**Issue by hupu1dong** [marcoslucianops/DeepStream-Yolo#303]
I now need an engine to detect 640x320 and 3840x2176 images, but I found that I can only manually change the configuration in cfg each time
**[net]
width=3840
height=2176
channels=3**
Regenerate the engine to detect the weights of different sizes separately. This is too slow and troublesome. Can you support dynamic input

**Comment by marcoslucianops** [comment]
The `[net]` section is related to the model input. It's not related to the image input. If your model is trained in 640, you should keep it 640. If you have only rectangular images, you can generate the `wts` and `cfg` files again setting the size arg `-s 360 640` (or the required aspect ratio) to get a bit more performance on the inference.

**NOTE:** The rectangular size should be used only when the model is trained with letter_box (maintaining the aspect ratio) or when the model is trained in rectangular input size.

**Comment by hupu1dong** [comment]
OK, thank you, but now I have a problem. My training dataset is 640x640, and the configuration items [net] width and height in the wts file are 640. But now I need to use this engine to detect 640x640 and 3280x2764 images. The 640x640 detection effect is very good, but 3280x2764 will have many missed detection, and half of the target will miss detection. When I change the [net] width height of wts to 3280 and 2764, The target in the 3280x2764 image will be detected

**Comment by hupu1dong** [comment]
That's why I asked if the input size supports variable size

**Comment by hupu1dong** [comment]
This is the detection effect of setting 
[net]
width=640
height=640
channels=3

**Comment by hupu1dong** [comment]
![image](https://user-images.githubusercontent.com/58175002/219010643-3bdaac0d-b678-466e-b337-0a6217d73477.png)

**Comment by hupu1dong** [comment]
The resolution of this picture is 3840x2176

**Comment by hupu1dong** [comment]
This is the detection effect of setting
[net]
width=3840
height=2176
channels=3

**Comment by hupu1dong** [comment]
![7a01e17f08f6dcb143b2c34fb3b2532](https://user-images.githubusercontent.com/58175002/219010890-b96aa669-0870-4d58-a878-fe1c8ebc37ba.png)

**Comment by marcoslucianops** [comment]
> That's why I asked if the input size supports variable size

The input dimension isn't dynamic. You must set the size when generating the `wts` and `cfg` files.

**Comment by hupu1dong** [comment]
It is too slow to generate engine every time, so I want to ask how to use the same engine to detect images with different resolutions

**Comment by marcoslucianops** [comment]
> It is too slow to generate engine every time, so I want to ask how to use the same engine to detect images with different resolutions

You don't need to generate the engine every run. Just change the `model-engine-file` in the `config_infer` file to the name of the generated engine.
