### ISSUE TITLE
CUDA failure: an illegal memory access was encountered in file yoloPlugins.cpp at line 259

### ISSUE THREAD

**Issue by Arpit1496** [marcoslucianops/DeepStream-Yolo#306]
I am getting this error when running prolonged yolov5s6 without display on jetson nx 16 Gb production module.
We use python to run deepstream piipelines.
Can you help ?

**Comment by marcoslucianops** [comment]
Check if you are facing memory leak in RAM or GPU.

**Comment by Arpit1496** [comment]
How can I check it ?
It says error is in yoloPlugins.cpp. I am using deepstream with python. My python script runs back to back detector and saves some frame to disk.

**Comment by marcoslucianops** [comment]
Run `jtop` while you deepstream code is running and check the memory usage.
