### ISSUE TITLE
Does this code support yolo-pose？

### ISSUE THREAD

**Issue by lofyol** [marcoslucianops/DeepStream-Yolo#309]

**Comment by marcoslucianops** [comment]
It doesn't support pose yet.

**Comment by hhackbarth** [comment]
I am also interested in adaptions for YOLOv8-pose.
Anyone who has gone that path already and can share something?

**Comment by simonvvd** [comment]
@marcoslucianops Could you give the steps to add support for yolov8-pose in that repository? We're willing to make a PR for it as we need it for our product.

**Comment by marcoslucianops** [comment]
The pose estimation needs a custom output layer using the TensorMeta. It's more complex.

**Comment by marcoslucianops** [comment]
Added support for Pose: https://github.com/marcoslucianops/DeepStream-Yolo-Pose
