### ISSUE TITLE
Do it support deepstream 6.2 in Jetson-AGX-orin

### ISSUE THREAD

**Issue by CasvalRay** [marcoslucianops/DeepStream-Yolo#310]
I use command "deepstream-app -c deepstream_app_config.txt".
It shows:
nvbufsurftransform: Could not get EGL display connection
** ERROR: <main:716>: Failed to set pipeline to PAUSED
Quitting
nvstreammux: Successfully handled EOS for source_id=0
ERROR from sink_sub_bin_sink1: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Debug info: gstbasesink.c(5367): gst_base_sink_change_state (): /GstPipeline:pipeline/GstBin:processing_bin_0/GstBin:sink_bin/GstBin:sink_sub_bin1/GstNv3dSink:sink_sub_bin_sink1:
Failed to start
App run failed

My version is :
deepstream-app version 6.2.0
DeepStreamSDK 6.2.0
CUDA Driver Version: 11.4
CUDA Runtime Version: 11.4
TensorRT Version: 8.5
cuDNN Version: 8.6
nvbufsurftransform: Could not get EGL display connection
libNVWarp360 Version: 2.0.1d3

**Comment by kks-bakaneko** [comment]
Did you set export DISPLAY=:0 ?

**Comment by marcoslucianops** [comment]
I didn't test on DeepStream 6.2 yet because I'm finishing a project. Probably I will do the necessary changes to support the 6.2 version till next week.

**Comment by marcoslucianops** [comment]
Seems that you are not using display in your board. Try to run it changing the `[sink] type` to `1` in the `deepstream_app_config.txt` file.

**Comment by nakanolab** [comment]
Just for your reference, I was able run `deepstream-app` with YOLOv5 on AGX Orin with freshly installed JetPack 5.1 (via SDK Manager) and DeepStream 6.2. You might want to check:
- Make sure the prerequisites are installed (https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_Quickstart.html).
- Check if sample configs under `/opt/nvidia/deepstream/deepstream/samples` can be run without problem.
- Recomplie source code under `DeepStream-Yolo/nvdsinfer_custom_impl_Yolo`.
- Just in case, delete the TensorRT engine file and regenerate it (if you already have one generated by the previous version of DeepStream).
