### ISSUE TITLE
How to extract stream metadata. 

### ISSUE THREAD

**Issue by gigwegbe** [marcoslucianops/DeepStream-Yolo#32]
Hello @marcoslucianops,
Thanks for the awesome work, I truly appreciate the great work. I want to extract the stream metadata, which contains useful information about the frames in the batched buffer for YOLOv3-Tiny-PRN model. How can I obtain the metadata?

**Comment by marcoslucianops** [comment]
See https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/readme.md#extract-metadata

I recommend that you take a look at the NVIDIA Developer Forum for more information.

**Comment by gigwegbe** [comment]
Thanks for the resource. I will check it out.

**Comment by gigwegbe** [comment]
Hello @marcoslucianops,
I have modified the  `write_kitti_output` function in `deepstream-app.c`  located at  `/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-app` to reflect the format for the metadata however how do I compile `deepstream-app.c`?

**Comment by marcoslucianops** [comment]
Hi, you need to compile ```deepstream-app.c``` (```make```) and move compiled file to ```/opt/nvidia/deepstream/deepstream-5.0/bin``` folder (```sudo make install```).

**Comment by gigwegbe** [comment]
Thanks for the response. It worked.

**Comment by gdwu1427** [comment]
@gigwegbe Thank you very much for your work, can you tell me how to modify the function write_kitti_output to extract stream metadata
