### ISSUE TITLE
Does this code support yolo-face?

### ISSUE THREAD

**Issue by knavezl** [marcoslucianops/DeepStream-Yolo#326]

**Comment by marcoslucianops** [comment]
What's the repo?

**Comment by phamminhhanhuet** [comment]
> _No description provided._

Maybe this repo: https://github.com/deepcam-cn/yolov5-face ?
It seems that the architecture of yolo-face (yolov5, yolov7) is same as the original yolov5, yolov7. 
I'm doing with yolo7-face too, model was converted to onnx & engine formats well (I modified the output of onnx model to (classes, boxes, scores, landmarks) but I'm finding where to extract the output detection info. 

> What's the repo?

**Comment by marcoslucianops** [comment]
This repo doesn't support landmarks, you should create a custom output parser to get the output from yolo-face. I can try to convert it in the future (I'm finishing some works and I will start the segmentation, pose, and other conversions for this repo).

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo-Face
