### ISSUE TITLE
yolov4 tiny generates bboxes on non-targeted regions

### ISSUE THREAD

**Issue by MashaelAlswayyed** [marcoslucianops/DeepStream-Yolo#33]
Hello,

I'm running two yolov4 tiny models on deepstream app, the first detector works on the full frame to detect cars then the second one works on the detected cars boxes to extract windshields. The first detection works fine but the second one there are some bboxes that are detected out of car's region as shown in the images below, the green box is from the first detector and the red box is from the second detector:

![1](https://user-images.githubusercontent.com/51006809/107869757-892b3680-6ea2-11eb-8157-9991d92c09dd.jpg)
![2](https://user-images.githubusercontent.com/51006809/107869758-89c3cd00-6ea2-11eb-9f41-a66b2d046a39.jpg)

These are the yolo make folders and configuration files 
[nvdsinfer_custom_impl_Yolo.zip](https://github.com/marcoslucianops/DeepStream-Yolo/files/5977071/nvdsinfer_custom_impl_Yolo.zip)
[nvdsinfer_custom_impl_Yolo_ws.zip](https://github.com/marcoslucianops/DeepStream-Yolo/files/5977072/nvdsinfer_custom_impl_Yolo_ws.zip)
[vehicle_detection_config.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/5977073/vehicle_detection_config.txt)
[ws_detection_config.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/5977074/ws_detection_config.txt)

**Comment by marcoslucianops** [comment]
Try to disable DLA core and use use cluster-mode=4.

**Comment by MashaelAlswayyed** [comment]
I tried to disable DLA core and set cluster-mode to 4 but same issue, I think the issue occurs from yolo make files and how the two models are connected

**Comment by MashaelAlswayyed** [comment]
The issue has been solve by setting maintain-aspect-ratio=0

Thank you

**Comment by marcoslucianops** [comment]
About cluster-mode=4, in my code, NMS function is coded in nvdsparsebbox_Yolo function. You don't need to use another NMS mode (cluster-mode<4).

**Comment by MashaelAlswayyed** [comment]
OK, thank you very much
