### ISSUE TITLE
jetpack4.6.3 deepstream6.0.1

### ISSUE THREAD

**Issue by Lvjinhong** [marcoslucianops/DeepStream-Yolo#330]
After generating the .wts and .cfg files according to the steps in the documentation and placing the relevant files in the appropriate locations, I ran the program and got the following error:
Using winsys: x11
Deserialize yoloLayer plugin: (Unnamed Layer* 256) [PluginV2IOExt]
Segmentation fault (core dumped)

I have tried many methods and read many documents, but there are very few solutions that support DeepStream 6.0.1 and JetPack 4.6.3. I hope someone can help me with this problem, and I would be extremely grateful.

**Comment by marcoslucianops** [comment]
Now you can use the ONNX conversion to DeepStream.

[Docs](https://github.com/marcoslucianops/DeepStream-Yolo/tree/master/docs)
