### ISSUE TITLE
Yolov7-tiny model support

### ISSUE THREAD

**Issue by muhammederem** [marcoslucianops/DeepStream-Yolo#331]
Is there any way to run yolov7-tiny model or how can we create any models .cfg file and  TensorRT model?

**Comment by ssunyoung2** [comment]
I want to know too!!!

**Comment by whittenator** [comment]
It supports Yolov7 tiny. You have to follow this guide:
https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv7.md

In step 4, reparameterize weights, which you can find here: https://github.com/WongKinYiu/yolov7/blob/main/tools/reparameterization.ipynb

You simply need to follow alter the regular yolov7 model by changing all of the **model.105.m.** in the python script to **model.77.m.**.

**Comment by muhammederem** [comment]
Okay thanks but right now it throws this:
`model.state_dict()['model.77.m.0.weight'].data[i, :, :, :] *= state_dict['model.77.im.0.implicit'].data[:, i, : :].squeeze()`
`KeyError: 'model.77.im.0.implicit'`

**Comment by muhammederem** [comment]
> Okay thanks but right now it throws this:
> `model.state_dict()['model.77.m.0.weight'].data[i, :, :, :] *= state_dict['model.77.im.0.implicit'].data[:, i, : :].squeeze()`
> `KeyError: 'model.77.im.0.implicit'`

Its already reparameterized. Thank you so much! @whittenator
