### ISSUE TITLE
Problem with multiple pgie

### ISSUE THREAD

**Issue by kks-bakaneko** [marcoslucianops/DeepStream-Yolo#333]
Hi, I'm using multiple yolo engine as pgie
And when I use different engine in same time, It seems dumping memory space of other engine.
Can you check it?

**Comment by marcoslucianops** [comment]
Did you change the `const char* YOLOLAYER_PLUGIN_VERSION {"1"};` in the `nvdsinfer_custom_impl_Yolo/yoloPlugins.h` file?
