### ISSUE TITLE
Yolov7 with width_multiple，Failed to convert WTS file

### ISSUE THREAD

**Issue by chrichard** [marcoslucianops/DeepStream-Yolo#334]
I trained my own model using yolov7.yml, and in order to reduce the size of the model, I set “width_multiple=0.5 & height_multiple=0.5”, and then used reparametrize to convert and got yolov7_test.pt, and these processes are correct. 
Then I converted yolov7_test.pt with gen_wts_yoloV7.py to generate the .wts file and an error occurred (Invalid weights file). Is there anything I need to pay attention to?

**Comment by marcoslucianops** [comment]
Now you can use the ONNX conversion to DeepStream.

[YOLOv7](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv7.md)
