### ISSUE TITLE
Change confidence of Detection 

### ISSUE THREAD

**Issue by storm12t48** [marcoslucianops/DeepStream-Yolo#335]
Hello everyone 

little beginner's question, can we change the confidence settings like on a python program / opencv / yolov8 I would like the drop to allow to push the object detection and how to save the resulting video

Thanks in advance

**Comment by 124bit** [comment]
Yes, I'm not sure what option in config.txt is the equivalent to --conf parameter for yolo v8 too. 

Is the pre-cluster-threshold parameter equivalent to the yolov8 torch implementation predict --conf parameter?

Thanks

**Comment by storm12t48** [comment]
yes according to the official documentation not very up to date
the equivalent of conf on yolov8 classic is indeed pre-cluster-threshold but I have the impression that has no incident on the number of detection as can be conf: s where it has a minimum threshold value

cf :https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinfer.html#:~:text=Both-,pre%2Dcluster%2Dthreshold,-Detection%20threshold%20to

**Comment by marcoslucianops** [comment]
The `pre-cluster-threshold` is equal to `conf-thres` on PyTorch YOLO models. In the `config_infer_primary` file, you can use `[class-attrs-all]`  to change the confidence of all classes, or `[class-attrs-0]`, `[class-attrs-1]`, etc to change the confidence of specific class number.
