### ISSUE TITLE
Error when Testing the model???

### ISSUE THREAD

**Issue by huytranvan2010** [marcoslucianops/DeepStream-Yolo#337]
Thanks for repo. I followed your guide to test operation of YOLOv7 on my local PC, I used Docker container but I have error:
`nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 

(gst-plugin-scanner:2886): GStreamer-WARNING **: 10:27:38.041: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_inferserver.so': libtritonserver.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:2886): GStreamer-WARNING **: 10:27:38.084: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_udp.so': librivermax.so.0: cannot open shared object file: No such file or directory
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
nvbufsurftransform:cuInit failed : 804 
** ERROR: <create_multi_source_bin:1490>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1583>: create_multi_source_bin failed
** ERROR: <create_pipeline:1485>: create_pipeline failed
** ERROR: <main:697>: Failed to create pipeline
Quitting
App run failed`

These are steps I run:
1. Convert yolov7.pt (after parameterization) and receive .wts and .cfg (outside of Container). I copy to Deepstream-YOLO
2. Run `xhost +`
3. Run `docker run --rm -it --gpus all --net=host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix -v ./yolov7:/yolov7 -v ./DeepStream-Yolo:/DeepStream-Yolo --name jetsonyolo nvcr.io/nvidia/deepstream:6.2-devel`
4. Run `cd /DeepStream-Yolo/`
5. Run `apt-get install build-essential` to install g++
6. Run `/opt/nvidia/deepstream/deepstream/user_additional_install.sh`
7. Run `CUDA_VER=11.8 make -C nvdsinfer_custom_impl_Yolo` and I got a message
make: Entering directory '/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'
make: Nothing to be done for 'all'.
make: Leaving directory '/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'
9. Run `deepstream-app -c deepstream_app_config.txt` and I got error as above

Could you @marcoslucianops give me advice where is issues? This is the first time I get to know with Deepstream. Thanks a lot.

**Comment by marcoslucianops** [comment]
Did you install the CUDA 11.8 and NVIDIA docker on your machine?

Please see: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

**Comment by CHR1122** [comment]
Perhaps the driver version is incorrect. I also encountered this issue when the driver version was 515, but after replacing it with 525.105.17, the issue was resolved.

**Comment by huytranvan2010** [comment]
Yes, it related to nvidia driver. Thanks
