### ISSUE TITLE
ERROR: <main:716>: Failed to set pipeline to PAUSED

### ISSUE THREAD

**Issue by HGD-ai** [marcoslucianops/DeepStream-Yolo#340]
When I used deepstream6.1.1 and yolov5, the following error occurred

** ERROR: <main:716>: Failed to set pipeline to PAUSED
Quitting
App run failed

**********deepstream-app_config.txt ************ 
[application]
enable-perf-measurement=1
perf-measurement-interval-sec=5

[tiled-display]
enable=1
rows=1
columns=1
width=1280
height=720
gpu-id=0
nvbuf-memory-type=0

[source0]
enable=1
type=3
uri=file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4
num-sources=1
gpu-id=0
cudadec-memtype=0

[sink0]
enable=1
type=2
sync=0
gpu-id=0
nvbuf-memory-type=0

[osd]
enable=1
gpu-id=0
border-width=5
text-size=15
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Serif
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0

[streammux]
gpu-id=0
live-source=0
batch-size=1
batched-push-timeout=40000
width=1920
height=1080
enable-padding=0
nvbuf-memory-type=0

[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary_yolov5.txt

[tests]
file-loop=0

***********config_infer_primary_yoloV5.txt**************
[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
custom-network-config=yolov5_best.cfg
model-file=yolov5_best.wts
model-engine-file=best8415.engine
#int8-calib-file=calib.table
labelfile-path=labels.txt
batch-size=1
network-mode=0
num-detected-classes=80
interval=0
gie-unique-id=1
process-mode=1
network-type=0
cluster-mode=2
maintain-aspect-ratio=1
symmetric-padding=1
parse-bbox-func-name=NvDsInferParseYolo
custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
engine-create-func-name=NvDsInferYoloCudaEngineGet

[class-attrs-all]
nms-iou-threshold=0.45
pre-cluster-threshold=0.25
topk=300

Looking forward to your reply, thank you very much for your answer！

**Comment by HGD-ai** [comment]
I have resolved this issue by modifying the configuration file. The modified configuration file contains the following content
[sink1]
enable=1
type=3
container=1
codec=1
enc-type=0
sync=0
bitrate=4000000
profile=0
output-file=output.mp4
source-id=0

**Comment by marcoslucianops** [comment]
Without using display, you need to use `[sink] type=1` (fakesink), `[sink] type=3` (file output) or `[sink] type=4` (RTSP output).
