### ISSUE TITLE
Yolo-Nas

### ISSUE THREAD

**Issue by arielkantorovich** [marcoslucianops/DeepStream-Yolo#341]
Hi,
Thank you for your great Git, I don't think that is exactly an issue maybe more requests, there is an option that you public Yolo-nas with a deep stream.

**Comment by marcoslucianops** [comment]
It's already supported.

[YOLO-NAS](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLONAS.md)

**Comment by arielkantorovich** [comment]
Thank you for your help you are the best :)

**Comment by arielkantorovich** [comment]
Hi, I try to follow your instruction (https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLONAS.md)
unfortunately, there is a problem installing super-gradient on jetson xavier because there is a problem installing the on-simplifier.
Did you manage to overcome this problem?

**Comment by marcoslucianops** [comment]
You can skip the `onnx-simplifier` installation and run the export command without `--simplify` flag. If you want to use the ONNX simplifier, export the model in a x86 computer and use the exported ONNX model in the Jetson board.
