### ISSUE TITLE
Deleted decoder code

### ISSUE THREAD

**Issue by robosina** [marcoslucianops/DeepStream-Yolo#345]
It appears that you have created a decoder for YOLO-NAS in this commit:

https://github.com/marcoslucianops/DeepStream-Yolo/blob/b4e2dbdcf80ee2b372a441955f233196454da234/nvdsinfer_custom_impl_Yolo/nvdsparsebbox_Yolo_cuda.cu#LL161C1-L163C2

It appears that the CUDA decoder has been removed from the codebase, as indicated in the `big update` commit. Could you clarify whether this is indeed the case and provide any specific reasons for this removal? Additionally, I am curious to know if a general solution for the ONNX decoder has been implemented. I would greatly appreciate any insights you can share on this matter. Thank you

**Comment by marcoslucianops** [comment]
It slower than the current implementation. I added it using a custom layer on PyTorch before the conversion to ONNX.

**Comment by marcoslucianops** [comment]
I did many tests and the current implementation is the faster one (about 200 FPS more on S model using V100 GPU).

**Comment by robosina** [comment]
@marcoslucianops, thank you for your response. I appreciate your response and I'm examining the code found in the utils folder regarding the exportation of the Torch model to ONNX. I noticed that you've added a custom layer as shown below:

```python

class DeepStreamOutput(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        boxes = x[0]
        scores, classes = torch.max(x[1], 2, keepdim=True)
        return torch.cat((boxes, scores, classes), dim=2)
```

Upon review, it appears to me that this piece of code is not performing Non-Maximum Suppression (NMS), but rather, it seems to be executing the initial steps leading up to NMS. I'm checking this code now. Thanks

**Comment by marcoslucianops** [comment]
The NMS is hardcoded on DeepStream code. I use the DeepStream NMS (`cluster-mode=2`) to keep the [`class-attrs`] function. Using TensorRT NMS, it's not possible to change the IoU threshold, confidence threshold, topK and per-class confidence threshold without regenerate the engine file.

**Comment by robosina** [comment]
@marcoslucianops , Thanks for the response.
