### ISSUE TITLE
YoloV8 engine always predicts the same class

### ISSUE THREAD

**Issue by M1ke002** [marcoslucianops/DeepStream-Yolo#346]
I use deepstream 6.1.1 and I converted my custom yolov8m.pt to onnx and then generated the engine file. The model can predict 3 classes but the engine file always outputs the first class in the labels.txt file for all objects. I tested the .pt file and it works normally.
These are the warnings when generating the engine:

WARNING: [TRT]: onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
WARNING: [TRT]: onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
WARNING: [TRT]: Tensor DataType is determined at build time for tensors not marked as input or output.
WARNING: [TRT]: The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
WARNING: [TRT]: The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
0:01:44.315479866   131 0x555a80650a40 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1955> [UID = 1]: serialize cuda engine to file: /opt/nvidia/deepstream/deepstream-6.1/sources/my_deepstream/DeepStream-Yolo/last.onnx_b1_gpu0_fp32.engine successfully
WARNING: [TRT]: The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT input           3x640x640       
1   OUTPUT kFLOAT output          8400x6

**Comment by M1ke002** [comment]
nevermind, i forgot to change the config to config_infer_primary_yoloV8 :)

**Comment by marcoslucianops** [comment]
Did you test with the updated files (converting the model again and regenerating the engine file)?

**Comment by M1ke002** [comment]
> Did you test with the updated files (converting the model again and regenerating the engine file)?

I tried again with the new files but still got the same problem

**Comment by marcoslucianops** [comment]
Can you send an image from the output?

**Comment by M1ke002** [comment]
![Screenshot from 2023-05-21 22-19-14](https://github.com/marcoslucianops/DeepStream-Yolo/assets/92376409/f47bd9b6-05e7-4c0f-96df-7944837f8f5b)
I run it in a docker container. The bounding boxes are correct, only the class name is wrong

**Comment by M1ke002** [comment]
By the way I tried the older version to generate the wts and cfg file and it works

**Comment by marcoslucianops** [comment]
Can you send me the model via email to test?

**Comment by M1ke002** [comment]
> Can you send me the model via email to test?

I just sent it to you

**Comment by relaxtheo** [comment]
I have encountered the same problem. Just using the official yolov8 pt file, and the deepstream 6.1.1 sample program

**Comment by marcoslucianops** [comment]
I can't reproduce this issue. I need more information about how to reproduce it.

**Comment by LuckyPandaa** [comment]
I have the same problem,do you solve this problem?

**Comment by marcoslucianops** [comment]
The problem is already solved in the new commit.

**Comment by lzylzylzy123456** [comment]
I generated an engine using the weights file. It works fine on my laptop and produces correct detection results. However, when I run it on other computers as mentioned in this post, I encounter the same issue. All the detection results are of the first class (if I put 'car' as the first class, it outputs 'car' for all detections; if I put 'person' as the first class, it outputs 'person' for all detections). My laptop is using DeepStream 6.0, while the two desktop computers with issues are using DeepStream 6.0.1 and 6.2 respectively. The weights file was generated using darknet.

![Screenshot from 2023-06-16 16-27-43](https://github.com/marcoslucianops/DeepStream-Yolo/assets/113103514/d869f7d2-5794-404c-be90-7ddf5ac9a3a8)
![微信图片_20230616171514](https://github.com/marcoslucianops/DeepStream-Yolo/assets/113103514/19e4f7ff-dfd1-4c32-b762-25340b2c2bc9)

**Comment by marcoslucianops** [comment]
Are you using the newer files in this repo? I did an update to fix this issue. You need to generate the engine again.

**Comment by lzylzylzy123456** [comment]
I pulled the latest code from both the RTX4080 device and the orin nx, but both were identified as the same type. On my previous machine, I pulled the code from before your latest update, and there was no such situation. As I am currently Ling Chen, I am planning to pull the latest code from my previous machine tomorrow morning to test it. If the same effect occurs, then there may be a bug in the code?

**Comment by marcoslucianops** [comment]
Fixed. Please use the new files and regenerate the engine file.

**Comment by lzylzylzy123456** [comment]
I just conducted a test and this bug has been fixed. Thank you for fixing it

**Comment by ggyybb** [comment]
> I pulled the latest code from both the RTX4080 device and the orin nx, but both were identified as the same type. On my previous machine, I pulled the code from before your latest update, and there was no such situation. As I am currently Ling Chen, I am planning to pull the latest code from my previous machine tomorrow morning to test it. If the same effect occurs, then there may be a bug in the code?

我也遇到了同样的问题，请问你怎么解决的最后，我用的最新的代码，还是同样的，标签只有第一类。4070显卡，之前用的1080ti，也没有问题好像。

**Comment by ggyybb** [comment]
> I have encountered the same problem. Just using the official yolov8 pt file, and the deepstream 6.1.1 sample program

请问你解决了么，是显卡的问题么
