### ISSUE TITLE
Confusing output format

### ISSUE THREAD

**Issue by aidevmin** [marcoslucianops/DeepStream-Yolo#347]
I see that output format of yolov7 .engine model as follow
`
0   INPUT  kFLOAT input           3x640x640    
   
1   OUTPUT kFLOAT output          25200x7
`
I understood that 25200 = 3x(80^2 + 40^2 + 20^2), but what does it mean for value 7). I know each bbox have x_min, y_min, w, h, class_id, class_prob, total is 6. Please clarify each values in value 7? And size of bounding boxes is relative or absolute values. Thanks

**Comment by marcoslucianops** [comment]
In the new update, it's 25200x6. The '7' was the objectness (used in many YOLO models), but now it's multiplying the objectness with the scores in the DeepStreamOutput layer (PyTorch output implementation).

**Comment by marcoslucianops** [comment]
The size of the bboxes are absolute values according to the input size.

**Comment by aidevmin** [comment]
> The size of the bboxes are absolute values according to the input size.

Yeah. Thank you. But output format is (25200, 7). Could you clarify 7 values? Often we have xmin, ymin, w, h, class id, class prob, total is 6.

**Comment by marcoslucianops** [comment]
> In the new update, it's 25200x6. The '7' was the objectness (used in many YOLO models), but now it's multiplying the objectness with the scores in the DeepStreamOutput layer (PyTorch output implementation).

**Comment by aidevmin** [comment]
> In the new update, it's 25200x6. The '7' was the objectness (used in many YOLO models), but now it's multiplying the objectness with the scores in the DeepStreamOutput layer (PyTorch output implementation).

It turn that you again commited today. I ran source yesterday and received (25200, 7). I will check the lastest source code. Thanks

**Comment by marcoslucianops** [comment]
I changed it again to fix some errors. The output now is: `boxes [8400, 4]`, `scores [8400, 1]` (best score) and `classes [8400, 1]` (class id from the best score).

**Comment by aidevmin** [comment]
@marcoslucianops yeah, I think that it's better to give consistent output format for all YOLO, because we can directly use one postprocessing for all. It is the reason sometimes I need to check output format. It is better if you mention in Readme.md for easy usage.

**Comment by marcoslucianops** [comment]
In the current version, there is only one output for all of the models:

> `boxes [8400, 4]`, `scores [8400, 1]` (best score) and `classes [8400, 1]` (class id from the best score)

The only difference is the parser function `parse-bbox-func-name` (`NvDsInferParseYolo` and `NvDsInferParseYoloE`).

- The `NvDsInferParseYoloE` is for PPYOLOE, YOLO-NAS and DAMO-YOLO output and it's [left, right, width, height] in the engine output.

- The `NvDsInferParseYolo` is for the other models output and it's [x_center, y_center, width, height] in the engine output.
