### ISSUE TITLE
Error wile compiling the lib using "CUDA_VER=11.4 make -C nvdsinfer_custom_impl_Yolo" for YoloV8

### ISSUE THREAD

**Issue by prabal27** [marcoslucianops/DeepStream-Yolo#350]
**Deepstream Vesrsion: 6.2
Jetpack Version: 5.1-b147
TensorRT Version: 8.5.2-1+cuda11.4**

I am getting the following error:

_/usr/bin/ld: cannot find -lnvinfer_plugin
collect2: error: ld returned 1 exit status
make: *** [Makefile:78: libnvdsinfer_custom_impl_Yolo.so] Error 1
make: Leaving directory '/home/prabal2021/Drivers/Camera/FLIR/Gstreamer/gstreamer-pyspin-src/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'_

**Comment by marcoslucianops** [comment]
I tested on AGX with JetPack 5.1.1 and I didn't get this error. Are you using docker?

**Comment by marcoslucianops** [comment]
Are the DeepStream installed in the standard directory (`/opt/nvidia/deepstream/deepstream`)?

**Comment by prabal27** [comment]
Yes, my deepstream is located in the same location. Basically, it is not able to find "-lnvinfer_plugin", is it deepstream library or a tensorRT library? Can you please tell me where exactly this library should be located?

**Comment by marcoslucianops** [comment]
The `nvinfer_plugin` is a TensorRT lib. How did you install it?

**Comment by marcoslucianops** [comment]
The location are

```
/lib/x86_64-linux-gnu/libnvinfer_plugin.so
/lib/x86_64-linux-gnu/libnvinfer_plugin.so.8
```

**Comment by prabal27** [comment]
My libnvinfer_plugin.so was broken. Got it working now. Thanks for the help!
