### ISSUE TITLE
Too many detection occupied the screen

### ISSUE THREAD

**Issue by relaxtheo** [marcoslucianops/DeepStream-Yolo#354]
Just follow the docs/YOLOv5.md, but there are many unexpected detection full of the screen.

Environment:
1. latest yolov5 code: git clone https://github.com/ultralytics/yolov5.git
2. get the yolov5 v7.0 pt file:
    wget https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt
3. convert to onnx:
    python3 export_yoloV5.py -w yolov5s.pt --opset 12 --simplify --dynamic
    Note:
    - "Unsupported ONNX opset version: 17" reported without setting the opset option
    - I have tried both 12 and 15
 4. Copy the generated onnx file to Jetson Xavier Nx
 5. The application deepstream-app and Deepstream-Yolo/nvdsinfer_custom_impl_Yolo is building and running in docker container based on nvcr.io/nvidia/deepstream-l4t:6.1.1-samples
 6. Editing the deepstream_app_config.txt and config_infer_primary_yoloV5.txt according to onnx file
 7. Running the deepstream-app -c deepstream_app_config.txt, engine file can be generated, but there are too many unexpected detection boxes full of the screen as the attached image
 

![IMG_20230529_172545](https://github.com/marcoslucianops/DeepStream-Yolo/assets/3756357/51cba5b0-eef3-4726-8881-531e3a5cefc8)

**Comment by marcoslucianops** [comment]
Can you send me the `deepstream_app_config.txt` and `config_infer_primary_yoloV5.txt` files?

**Comment by relaxtheo** [comment]
[config_infer_primary_yoloV5.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/11595367/config_infer_primary_yoloV5.txt)
[deepstream_app_config.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/11595368/deepstream_app_config.txt)

**Comment by marcoslucianops** [comment]
I will try to reproduce this issue. Which JetPack version are you using?

**Comment by relaxtheo** [comment]
5.0.2

**Comment by relaxtheo** [comment]
I found it is fine on JetPack 5.1 + DeepStream 6.2

**Comment by marcoslucianops** [comment]
If I understood, on JetPack 5.1 it's working and JetPack 5.0.2 it's not working, is it?

**Comment by relaxtheo** [comment]
Yes, it works on JetPack5.1+DS6.2

**Comment by marcoslucianops** [comment]
I just updated the repo to fix the output for DeepStream version < 6.2. If you want to try, export the ONNX model with the new export file, generate the TensorRT engine again with the updated files, and use the new `config_infer_primary_yoloV5.txt` file.

**Comment by relaxtheo** [comment]
Confirm fixed on JetPack5.0.2+DS6.1.1 on Xavier NX, thank you very much
