### ISSUE TITLE
Displaying Confidence value with label in deepstream-app

### ISSUE THREAD

**Issue by Abulala10** [marcoslucianops/DeepStream-Yolo#355]
I understood that we have to edit the process_meta() function in deepstream_app.c  to show the confidence value on screen, but what exactly do we have to edit ?

**Comment by marcoslucianops** [comment]
It's better to create your own code instead to edit the `deepstream-app`. See: https://github.com/NVIDIA-AI-IOT/deepstream_python_apps

**Comment by Tstegen21** [comment]
Hello @marcoslucianops , I  also  have a similar issue . But for my case , I am using  deepstream_app in c . Any suggestions regarding this without python-bindings (I  do not want to switch to python) .

**Comment by marcoslucianops** [comment]
You can use the C/C++ apps. They are located in `/opt/nvidia/deepstream/deepstream/sources/apps/sample_apps`.

**Comment by Abulala10** [comment]
> It's better to create your own code instead to edit the `deepstream-app`. See: https://github.com/NVIDIA-AI-IOT/deepstream_python_apps

Okay and do you have any idea as to what part of code I should edit, if I am using the C/C++ app ?

**Comment by dharaatech** [comment]
Great @marcoslucianops I was able to make some basic changes  and run the app no problem  , but there is a minor issue . I am not able to integrate my  confidence score with the inferencing display . I have tried digging into this but no real fixes yet . Could you please tell me where to look ?

**Comment by Tstegen21** [comment]
Great @marcoslucianops I was able to do some basic changes and run the  app , but I am facing issues while trying to display  my confidence scores while inferencing . Could please guide me how to display the confidence score on the screen ?

**Comment by marcoslucianops** [comment]
Without tracker

```
snprintf(obj_meta->text_params.display_text, MAX_LABEL_SIZE, "%s (%.2f)", obj_meta->obj_label, obj_meta->confidence);
```

With tracker

```
snprintf(obj_meta->text_params.display_text, MAX_LABEL_SIZE, "%s %ld (%.2f)", obj_meta->obj_label, obj_meta->object_id, obj_meta->confidence);
```

**Comment by Abulala10** [comment]
> Without tracker
> 
> ```
> snprintf(obj_meta->text_params.display_text, MAX_LABEL_SIZE, "%s (%.2f)", obj_meta->obj_label, obj_meta->confidence);
> ```
> 
> With tracker
> 
> ```
> snprintf(obj_meta->text_params.display_text, MAX_LABEL_SIZE, "%s %ld (%.2f)", obj_meta->obj_label, obj_meta->object_id, obj_meta->confidence);
> ```

Thank you @marcoslucianops !!!
It works !

**Comment by githubwalt** [comment]
> Without tracker
> 
> ```
> snprintf(obj_meta->text_params.display_text, MAX_LABEL_SIZE, "%s (%.2f)", obj_meta->obj_label, obj_meta->confidence);
> ```
> 
> With tracker
> 
> ```
> snprintf(obj_meta->text_params.display_text, MAX_LABEL_SIZE, "%s %ld (%.2f)", obj_meta->obj_label, obj_meta->object_id, obj_meta->confidence);
> ```

Dear Marcos,  I was also trying to display the confidence in the labels, without success.
Where and in which file do I paste this code?
(I'm using the deepstream-app, deepstream_app_main.c, deepstream_app.c)
Thanks,
Walter
