### ISSUE TITLE
Yolov7 - Segmentation fault

### ISSUE THREAD

**Issue by sruap1214** [marcoslucianops/DeepStream-Yolo#356]
Hi Marcos

I have been using your repository for several months. Recently I update the compilation with the last version of the repo, but when I executed my code in the container it says segmentation fault for Yolov7. I go back to  commit "ab6de54c4398c1daeb6fc31b06af29f97663f211" and works perfectly. Nevertheless with the last commit happen that

**Comment by sruap1214** [comment]
I double check and the commit that generates the problem is the one called "Big update" 07feae9509ffb581fa85f65bec653d1c1d001056.

I tried the commit before that one and works perfectly for yolov7. I am trying in with docker container in a x86 and discrete GPU (RTX 3080)

**Comment by marcoslucianops** [comment]
The new update only work with engines exported with the new method. You need to compile the new lib and use the `export_yoloV7.py` to export your model to ONNX and run with the `config_infer_primary_yoloV7.txt` file with the exported model on DeepStream.
