### ISSUE TITLE
How to set ProfilingVerbosity::DETAILED in Deepstream?

### ISSUE THREAD

**Issue by aidevmin** [marcoslucianops/DeepStream-Yolo#359]
@marcoslucianops  Is there any way to set ProfilingVerbosity::DETAILED in Deepstream config? I need the feature to get full graph.json from generated engine. If not, how to set in C++ code, I serach for in `/opt/nvidia/deepstream/deepstream-6.2/sources/apps/sample_apps/deepstream-app/` but I didn't found. Thanks

**Comment by marcoslucianops** [comment]
For now, it's possible to do only in Darknet models because I didn't create the custom function to create the ONNX engine yet (it's using the default function from DeepStream).

Change the `yolo.cpp` file from:

```
  nvinfer1::ICudaEngine *engine = builder->buildEngineWithConfig(*network, *config);
  if (engine)
    std::cout << "Building complete\n" << std::endl;
  else
    std::cerr << "Building engine failed\n" << std::endl;
```

to

```
  config->setProfilingVerbosity(nvinfer1::ProfilingVerbosity::kDETAILED);

  nvinfer1::ICudaEngine *engine = builder->buildEngineWithConfig(*network, *config);
  if (engine)
    std::cout << "Building complete\n" << std::endl;
  else
    std::cerr << "Building engine failed\n" << std::endl;

  nvinfer1::IExecutionContext *context = engine->createExecutionContext();
  nvinfer1::IEngineInspector *inpector = engine->createEngineInspector();
  inpector->setExecutionContext(context);
  std::ofstream graph;
  graph.open("graph.json");
  graph << inpector->getEngineInformation(nvinfer1::LayerInformationFormat::kJSON);
  graph.close();
  delete inpector;
  delete context;
```

**Comment by marcoslucianops** [comment]
With the new files, you can generate the graph of the ONNX exported model. Add `GRAPH=1` in the `make` command and it will be generated in `graph.json` file.

**Comment by aidevmin** [comment]
@marcoslucianops  
Thanks, I will try it.
