### ISSUE TITLE
TypeError: attempt_load() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by trameshape** [marcoslucianops/DeepStream-Yolo#360]
When running export_yoloV5.py, It supported an error, " TypeError: attempt_load() got an unexpected keyword argument 'device' "

**Comment by marcoslucianops** [comment]
Please use the `master` branch of the `ultralytics/yolov5` to convert the model (even using older versions).

**Comment by ghty11468** [comment]
> Please use the branch of the to convert the model (even using older versions).`master``ultralytics/yolov5`

Is it necessary to use the model obtained from the old version of the YOLOv5 project? Isn't yolov5 6.0 okay?

**Comment by ghty11468** [comment]
> Please use the branch of the to convert the model (even using older versions).`master``ultralytics/yolov5`

I am also reporting errors like this. How can I solve it?

**Comment by shuzhenglin** [comment]
@ghty11468 sir,have you solve this problem.I also get this error when i use export_yoloV5.So use the export.py in yolov5 6.0.The generated ONNX file runs out of DeepStream without a Bounding Box in the container

**Comment by jimenghua** [comment]
@shuzhenglin I met the same problem, use export.py in yolov5-6.0 export onnx file, but can't draw labels in deepstream.
When running export_yoloV5.py, It supported an error, " TypeError: attempt_load() got an unexpected keyword argument 'device' ", have you tried export.py in yolov5-7.0

**Comment by marcoslucianops** [comment]
Use the main or v7.0 branch to export the model with the export_yoloV5.py file available on this repo.
