### ISSUE TITLE
Detections not correctly parsed after exporting to ONNX

### ISSUE THREAD

**Issue by SIGLOST** [marcoslucianops/DeepStream-Yolo#362]
Hi Marcos,

Thank you for the great work!

I've been testing the last iteration and apparently there's a mismatch between the export scripts and the bounding box parser.

Followed the instructions and used the Ultralytics container with the latest available export script (defaulting to ONNX opset 17): 
```
root@a42479e971ed:/usr/src/app# python3 export_yoloV5.py -w yolov5s.pt --simplify --dynamic

Starting: yolov5s.pt
Opening YOLOv5 model

YOLOv5 🚀 v7.0-175-g5f11555 Python-3.10.9 torch-2.0.0 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients

Creating labels.txt file

Exporting the model to ONNX
================ Diagnostic Run torch.onnx.export version 2.0.0 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Simplifying the ONNX model
Done: yolov5s.onnx
```

This is what I get when deploying the resulting model on a **dGPU with DeepStream 6.1.1** container (NMS clustering is enabled):
![yolov5s_issue](https://github.com/marcoslucianops/DeepStream-Yolo/assets/44586120/5de0e57e-84ba-4b29-997f-0815f5145da7)

Tried other YOLO variants like `yoloV8` and `yolonas`, and in such cases we get the correct bounding boxes positions but always the same object class `person` (which is the 1st occurrence of the 80 classes present in the labels.txt of COCO dataset):
![yolo8_yolonas_issue](https://github.com/marcoslucianops/DeepStream-Yolo/assets/44586120/9f35d9f4-e447-473e-9783-823c14e80762)

**Comment by marcoslucianops** [comment]
I'm not sure, but maybe the problem is in PyTorch >= 2. I will test today.

**Comment by marcoslucianops** [comment]
I can reproduce this issue in the DeepStream 6.1.1 using docker.

**Comment by marcoslucianops** [comment]
Try again with new updated files I just uploaded to the repo. Export the ONNX model with the new export file, generate the TensorRT engine again with the updated files, and use the new config_infer_primary file according to the model.

**Comment by M1ke002** [comment]
> Try again with new updated files I just uploaded to the repo. Export the ONNX model with the new export file, generate the TensorRT engine again with the updated files, and use the new config_infer_primary file according to the model.

thanks, it's working now

**Comment by SIGLOST** [comment]
@marcoslucianops I've tested successfully export to ONNX and deploying with DS 6.1.1 (dGPU) container the following variants: `yolov5` / `yolov8` / `yolonas`

Thanks a lot!
