### ISSUE TITLE
Deserialization failed with a custom fp32 engine model .

### ISSUE THREAD

**Issue by dharaatech** [marcoslucianops/DeepStream-Yolo#363]
Hi @marcoslucianops ,

I have a custom yolov7 model file (.pt) and  I have used  Deepstream-Yolo(marcoslucianops /DeepStream-Yolo )  to convert this to fp32 engine file  , while running this on deepstream-app it works fine but while testing the same thing one  deepstream-test3 app it  fails in the deserializing block . I am attaching the error screenshot for your reference.
![error](https://github.com/marcoslucianops/DeepStream-Yolo/assets/109078668/96c9723b-d038-4072-a14e-db66ddd9c660)

**Comment by marcoslucianops** [comment]
Are you using the engine file from one computer/board to another computer/board and running it in the deepstream-test3 app?

**Comment by dharaatech** [comment]
Thanks @marcoslucianops , it was a different type of an engine file
