### ISSUE TITLE
Not detect on custom data yolo-nas

### ISSUE THREAD

**Issue by arielkantorovich** [marcoslucianops/DeepStream-Yolo#364]
setup:
* Jetson Xavier
* deepstream 6.1.0
* cuda 11.4

Hi, 
thank you for the great Git, I run Yolo-nas on coco weights, and everything works fine. When I convert the file.pth to file.onnx I do not use the flag --dynamic.
Now I want to use my training network the model again is yolo nas-small version is name is Gazbo_Nas.pth I success to convert to Gazbo_Nas.onnx and I get Gazbo_Nas.onnx_b1_gpu0_fp32.engine but when I run the pipeline I detect nothing.
I think my problem is some configuration problem that I do not understand.
Of course, before I go to deep-stream I check my results and see that it works without deepstream using supergradient libraries.
I will be happy for any advice thank you.

I attached the configuration files:
[deepstream_app_config.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/11650798/deepstream_app_config.txt)
[labels2.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/11650799/labels2.txt)
[config_infer_primary_yolonas.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/11650800/config_infer_primary_yolonas.txt)

**Comment by marcoslucianops** [comment]
Try again with new updated files I just uploaded to the repo. Export the ONNX model with the new export file, generate the TensorRT engine again with the updated files, and use the new `config_infer_primary_yolonas.txt` file.

**Comment by arielkantorovich** [comment]
Hi, Unfortunately, It didn't solve this problem.

**Comment by marcoslucianops** [comment]
You need to use the `export_yolonas.py` from this repo. Did you change some parameter in the image preprocessing on your trained model?

**Comment by marcoslucianops** [comment]
I meant image normalization, or other preprocessing. The TensorRT drops a bit the accuracy of the model, but in my experience, I still getting the output of my models.

**Comment by arielkantorovich** [comment]
I don’t do something special, just transfer learning to my data from coco exactly like the notebook of super gradient

**Comment by arielkantorovich** [comment]
> > Try again with new updated files I just uploaded to the repo. Export the ONNX model with the new export file, generate the TensorRT engine again with the updated files, and use the new `config_infer_primary_yolonas.txt` file.
> 
> I have the same issue. If I lower score and IoU thresholds to 0.1 I do see some weird static bounding boxes. It didn't improve with the latest update (re-exported ONNX file and generated TensorRT engine. YOLO-NAS COCO started working properly but custom model didn't).
> 
> By the way, awesome work! I really like the ONNX approach you've chosen.

I will be happy to know if you solve this problem

**Comment by arielkantorovich** [comment]
> > Try again with new updated files I just uploaded to the repo. Export the ONNX model with the new export file, generate the TensorRT engine again with the updated files, and use the new `config_infer_primary_yolonas.txt` file.
> 
> I have the same issue. If I lower score and IoU thresholds to 0.1 I do see some weird static bounding boxes. It didn't improve with the latest update (re-exported ONNX file and generated TensorRT engine. YOLO-NAS COCO started working properly but custom model didn't).
> 
> By the way, awesome work! I really like the ONNX approach you've chosen.

I will be happy to know if you solve this problem in your case ?

**Comment by marcoslucianops** [comment]
The command for custom YOLO-NAS model is

```
python3 export_yolonas.py -m yolo_nas_s -w Gazbo_Nas.pth -n 5
```

The `-n` or `--classes` is the number of classes in your model.

**Comment by storm12t48** [comment]
Maybe off topic but have you found a way to install supergradient on a jetson? knowing that onnx-simplifier simply does not want to install even with a cmake with the source

**Comment by arielkantorovich** [comment]
@storm12t48 
Hi,
I first install cmake using `pip install cmake`, and then I install onnx-simplifier on my case work.

**Comment by arielkantorovich** [comment]
@marcoslucianops 
are you find some solution or explanation for why yolo-nas doesn't detect objects? 
When I run yoloV5 everything work fine.

**Comment by storm12t48** [comment]
> @storm12t48 Salut, j'installe d'abord cmake en utilisant `pip install cmake`, puis j'installe onnx-simplifier sur mon travail de cas.

But it installs me onnxsim something that I know how to do without going through cmake onnxsim=onnx-simplifier?

**Comment by marcoslucianops** [comment]
@arielkantorovich
Can you send the model to my email for testing?

**Comment by arielkantorovich** [comment]
@marcoslucianops  sure, I will send you the weights pt, and short video that you will can check the results please send me your email, and again thank you for help me.

**Comment by marcoslucianops** [comment]
I didn't received the model but I fixed the issue.

I added the `config_infer_primary_yolonas_custom.txt` file to the repo. For custom YOLO-NAS model you should use it.

The pretrained YOLO-NAS is using `net-scale-factor=0.0039215697906911373` and the custom YOLO-NAS is trained with `net-scale-factor=1`.
