### ISSUE TITLE
Why ONNX?

### ISSUE THREAD

**Issue by OctaM** [marcoslucianops/DeepStream-Yolo#365]
It's not an actual issue. But i'm just curious why it was changed to .onnx from .wts & .cfg? Is it a performance improvement?

**Comment by marcoslucianops** [comment]
Because it's easier to use any model in the DeepStream. It has a native ONNX parser, so I don't need to create the conversor layer by layer.

**Comment by OctaM** [comment]
Cool, thanks for your answer!

**Comment by marcoslucianops** [comment]
I forgot to say, but the speed and accuracy between both methods are equal.
