### ISSUE TITLE
error occured when run:deepstream-app -c deepstream_app_config.txt

### ISSUE THREAD

**Issue by wxzyqqj** [marcoslucianops/DeepStream-Yolo#367]
deepstream-app: error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory

**Comment by marcoslucianops** [comment]
Probably you are not using the correct environment for DeepStream. Please check: https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/benchmarks.md

**Comment by marcoslucianops** [comment]
Probably you are not using the correct environment for DeepStream. Please check: https://github.com/marcoslucianops/DeepStream-Yolo#requirements

**Comment by wxzyqqj** [comment]
yolov5 can use tensorRT8?  ?   I use Jetson TX2 and my tensorRT version is tenRT8

**Comment by marcoslucianops** [comment]
Yes it can but you need to use the correct version for the DeepStream because it's pre-compiled with specific TensorRT version.
