### ISSUE TITLE
How do I create an engine file?

### ISSUE THREAD

**Issue by sandongk** [marcoslucianops/DeepStream-Yolo#37]
hello.
I need an engine file to run in deepstreemsdk. How do I create a model.engine file?

I use jetson nano and deepstreem sdk 5.0.1

**Comment by marcoslucianops** [comment]
It's generated automatically by DeepStream. You just need to set your yolo files.

**Comment by sandongk** [comment]
Oh, I see
Thank you very much

2021년 2월 21일 (일) 오후 11:32, Marcos Luciano <notifications@github.com>님이 작성:
