### ISSUE TITLE
Displaying secondary classifier (sgie) output values

### ISSUE THREAD

**Issue by dharaatech** [marcoslucianops/DeepStream-Yolo#371]
I want to run a detector and a classifier inside deepstream-app .Currently I am able to display the confidence values for the detector on the screen while performing the inference . But I am unable to get the meta data of the classifier inside the deepstream-app.

PS: I have done all the necessary and relevant configurations for classifier and detector.

**Comment by marcoslucianops** [comment]
Search for `NvDsClassifierMeta` in the `deepstream-app` code. You should manipulate the classifier meta there.

Reference for the `NvDsClassifierMeta`: https://docs.nvidia.com/metropolis/deepstream/sdk-api/struct__NvDsClassifierMeta.html
