### ISSUE TITLE
Where can I set the generated engine to FP16?

### ISSUE THREAD

**Issue by lrjj** [marcoslucianops/DeepStream-Yolo#372]
Where can I set the generated engine to FP16?

**Comment by marcoslucianops** [comment]
You need to set

```
model-engine-file=model_b1_gpu0_fp16.engine
```

and

```
network-mode=2
```

In the config_infer_primary file (according to the model you are using). Delete the old engine and regenerate it.

**Comment by lrjj** [comment]
> You need to set
> 
> ```
> model-engine-file=model_b1_gpu0_fp16.engine
> ```
> 
> and
> 
> ```
> network-mode=2
> ```
> 
> In the config_infer_primary file (according to the model you are using). Delete the old engine and regenerate it.

Thank you very much, it's already working!
