### ISSUE TITLE
Multiple GPUs appear and GPUs are not used

### ISSUE THREAD

**Issue by lzylzylzy123456** [marcoslucianops/DeepStream-Yolo#374]
Have you ever encountered this situation? I couldn't find the answer on the NVIDIA forum. I have already asked a question, and this is my question link. https://forums.developer.nvidia.com/t/multiple-gpus-appear-and-gpus-are-not-used/256306

**Comment by lzylzylzy123456** [comment]
The official response is that we still have some plugins that can set gpu-id, such as nvstreammux, videoconvert, etc. After modifying according to this method, it is indeed useful. However, as the number of pipelines increases, the GPU utilization rate is very low. I have also asked you this question. Please take a look. Thank you. The name of this issue is Low GPU utilization

**Comment by marcoslucianops** [comment]
The method I said is better than set the `gpu-id`. You will have more performance using one pipeline per GPU.
