### ISSUE TITLE
error: 'string' is not a member of 'std'

### ISSUE THREAD

**Issue by zardadi** [marcoslucianops/DeepStream-Yolo#375]
Apparently header files are missing string library. When I tried to compile nvinfer lib (libnvdsinfer_custom_impl_Yolo.so) got `error: 'string' is not a member of 'std'` error. 

`layers/deconvolutional_layer.cpp:9:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?`

To remove the error I had to  add `#include <string>` to all the heard files inside '/nvdsinfer_custome_impl_Yolo/layers/`

**Comment by marcoslucianops** [comment]
I don't have this issue, but I will add in the next update. Thank you.
