### ISSUE TITLE
Feature Request: Add support for yoloV8 Instance Segmentation models

### ISSUE THREAD

**Issue by prabal27** [marcoslucianops/DeepStream-Yolo#376]
Hello, 
Thank you so much for creating this, it's very useful.

I just wanted to ask if you are planning to add support for adding YoloV8 Instance Segmentation models to the Deepstream framework.

Thanks

**Comment by marcoslucianops** [comment]
Yes, soon.

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo-Seg
