### ISSUE TITLE
bounding box color 

### ISSUE THREAD

**Issue by bongpigeon** [marcoslucianops/DeepStream-Yolo#378]
Hello, I'm detecting only two objects but the bounding box has the same color. Is it possible for me to change the bounding box color for each class?

**Comment by PJongBeom** [comment]
i fixed the problem. 
Thank you!

**Comment by aidevmin** [comment]
@marcoslucianops How did you do?

**Comment by PJongBeom** [comment]
go to the deepstream_app_config.txt and edit [primary-gie] 
# The color of the borders for the objects of a specific class ID, specified in RGBA format. The key must be of format 

   bbox-border-color<class-id>. This property can be identified multiple times for multiple class IDs. If this property is 

   not identified for the class ID, the borders are not drawn for objects of that class-id.

# R:G:B:A Float, 0≤R,G,B,A≤1

bbox-border-color0=1;0;0;1 => Red for class-id 0

bbox-border-color1=0;1;1;1

bbox-border-color2=0;0;1;1

bbox-border-color3=0;1;0;1

# The color of the boxes drawn over objects of a specific class ID, in RGBA format. The key must be of format 

   bbox-bg-color<class-id>. This property can be used multiple times for multiple class IDs. If it is not used for a class 

   ID, the boxes are not drawn for objects of that class ID.
(https://blog.naver.com/PostView.nhn?blogId=ambidext&logNo=221673421548&from=search&redirect=Log&widgetTypeCall=true&directAccess=false)

**Comment by aidevmin** [comment]
@PJongBeom thanks

**Comment by KamranHuseyn11** [comment]
@PJongBeom could you please share the whole deepstream_app_config.txt and [primary-gie] config files?  I have a custom sample so, the configs are a little bit mixed up, I wanna see where exactly I should make modifications.

**Comment by PJongBeom** [comment]
sorry for the late reply 

[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary.txt
bbox-border-color=1;0;0;1
bbox-border-color=0;1;1;1

you need to add bbox-border-color part to your custom pipeline
