### ISSUE TITLE
 Low GPU utilization 

### ISSUE THREAD

**Issue by lzylzylzy123456** [marcoslucianops/DeepStream-Yolo#379]
We have a problem with low GPU utilization. We once achieved high GPU utilization by running 50 pipelines on 4 T4s, and the inference time was fast. However, after that environment was reset, the environment we reinstalled could no longer achieve the same effect. We suspect it is an environmental issue, but we are not sure. Have you ever encountered such a situation?Please take a look at this post, which contains detailed descriptions.https://forums.developer.nvidia.com/t/low-gpu-utilization/255835

**Comment by marcoslucianops** [comment]
The limitation is de GPU decoder. You can check it with the command:

```
watch -n 0.5 "nvidia-smi -a | grep Decoder"
```

**Comment by lzylzylzy123456** [comment]
I have conducted some experiments on my own server using two RTX 3090 graphics cards. The rest of the environment was configured according to DeepStream 6.2 version, and the inference model used was YOLOv7. I measured the inference time by calculating it using two probes, one before and one after the detector bin. In my case, if the inference time is less than 80ms, it is considered acceptable.

Following your method, I made the following attempts: Firstly, I used the program itself to set the GPU ID and tested both with a single card and with two cards. With a single 3090, I was able to run up to 23 pipelines, and the GPU decoder utilization reached around 70%. With two 3090 cards, I could run up to 30 pipelines, and the GPU decoder utilization reached around 50%.

Then, I conducted another experiment by running two instances of the program, each specifying a different GPU for processing. This allowed me to handle 32 pipelines, meaning each program could handle 16 pipelines, and the GPU decoder reached around 50% utilization. In these scenarios, the CPU usage was between 55% and 60%.

Based on the above experiments, I wonder if the performance of the two 3090 cards is not fully utilized. Since a single card can handle up to 23 pipelines, and it seems that the GPU decoder is not the bottleneck when testing with two cards, I am curious if two RTX 3090 cards can handle 40 pipelines. Do you have any experience or insights to share on this matter?

**Comment by marcoslucianops** [comment]
I replied there
