### ISSUE TITLE
using RTSP error

### ISSUE THREAD

**Issue by LuckyPandaa** [marcoslucianops/DeepStream-Yolo#380]
This is my deepstream_app_config.txt
`[source0]
enable=1
type=4
uri=rtsp://192.168.1.113:8554/1
drop-frame-interval=2
rtsp-reconnect-interval-sec=60
rtsp-reconnect-attempts=10
udp-buffer-size=2000000
gpu-id=0
cudadec-memtype=0

[sink0]
enable=1
type=4
codec=1
sync=0
enc-type=0
bitrate=4000000
profile=0
rtsp-port=8233
udp-port=5400`
When i runned deepstream-app -c deepstream_app_config.txt, it had a error like this
![Screenshot from 2023-06-14 18-05-28](https://github.com/marcoslucianops/DeepStream-Yolo/assets/92358330/4b0cb2db-d1f9-420b-ab94-8b67930f9747)
But vlc play is ok

**Comment by marcoslucianops** [comment]
Test with

```
[source0]
enable=1
type=3
uri=rtsp://192.168.1.113:8554/1
drop-frame-interval=2
num-sources=1
gpu-id=0
cudadec-memtype=0
```

**Comment by LuckyPandaa** [comment]
Thanks,it works!
