### ISSUE TITLE
Output format of YOLOv4?

### ISSUE THREAD

**Issue by aidevmin** [marcoslucianops/DeepStream-Yolo#382]
Thanks @marcoslucianops for the amazing repo.
I follow your guide for Darknet YOLOv4 model https://github.com/marcoslucianops/DeepStream-Yolo/tree/68f762d5bdeae7ac3458529bfe6fed72714336ca. I want to evaluate my engine model. I see in the in the raw output of engine model **(before postprocessing)** has bboxes, score and class. One raw bbox has 4 values and I am confusing about these values. Can you confirm:
- Which format is for 4 values? (x1, y1, w, h or x1, y1, x2, y2 or x_center, y_center, w, h)
- Values are absolute or relative to original image size (or input size of model)?

**Comment by marcoslucianops** [comment]
The output of the Darknet (`parse-bbox-func-name=NvDsInferParseYolo`) is:

- In the engine file: `[x_center, y_center, w, h]` and the values are absolute in a range of 0 - input size of the model (640 for example).

- In the deepstream code: you get the `[left, top, width, height]` from the `obj_meta` and the values are absolute in a range of 0 - streammux size (1920 for x and 1080 for y for example).
