### ISSUE TITLE
Error when inference YOLOv4 engine model - [executionContext.cpp::enqueueV2::520] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueV2::520, condition: !mEngine.hasImplicitBatchDimension()?

### ISSUE THREAD

**Issue by aidevmin** [marcoslucianops/DeepStream-Yolo#388]
My project based on your repo with commit SHA - 68f762d5bdeae7ac3458529bfe6fed72714336ca https://github.com/marcoslucianops/DeepStream-Yolo/tree/68f762d5bdeae7ac3458529bfe6fed72714336ca
I generated int8 engine model and use repo https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/main/trt.py to evaluate engine model, but I got an error 
```bash
[executionContext.cpp::enqueueV2::520] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueV2::520, condition: !mEngine.hasImplicitBatchDimension()
```
This error is not happen with lasted version of your repo, but I need to use older version. How to fix this @marcoslucianops? Thanks

**Comment by aidevmin** [comment]
@marcoslucianops  I fixed it. But output of generated int8 engine is not correct. 
Yolov4 engine output has 4 elements:
- first element: number of detections `data[0]`
- second element: bounding boxes `data[1]`
- third element: score `data[2]`
- fourth element: class index `data[3]`
-
![Screenshot from 2023-06-17 17-28-43](https://github.com/marcoslucianops/DeepStream-Yolo/assets/133469610/92a80b24-9b59-4db0-9306-45c1eac889b2)

You can see the above debug image: class index is not integer. I check many images max(class index) is float < 1 (it should be 79). And number of detections `data[0]` < 0. 
I used version https://github.com/marcoslucianops/DeepStream-Yolo/tree/68f762d5bdeae7ac3458529bfe6fed72714336ca for YOLOv4. 
Where can I wrong?

**Comment by marcoslucianops** [comment]
The new version of the repo isn't compatible with the old files (libs, texts, engines, etc). I recommend you to use the updated files.

**Comment by aidevmin** [comment]
@marcoslucianops I use old version with old files but output values seem not correct

**Comment by marcoslucianops** [comment]
> I generated int8 engine model and use repo https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/main/trt.py to evaluate engine model, but I got an error

You can't evaulate the engines from this repo in other codes because it's generated specifically for the output I set in this repo for the DeepStream.

**Comment by aidevmin** [comment]
@marcoslucianops 
Yeah. I know the output format is different and I has changed source code. Until now I only get the output of  engine model to check the correctness. As in the above image, I check length of `data`, shape of data components, and ít values. `data` is raw output of engine when we feed image.

**Comment by marcoslucianops** [comment]
I'm not sure how the old code works.

> You can see the above debug image: class index is not integer (4.2 e-44). I check many images max(class index) is float < 1 (it should be 79). And number of detections data[0] < 0.

The num_detections have the number of valid detections. You need to check the bboxes, scores and classes from 0 to the num_detections[0] value. If the num_detections[0] is 0, it means that there's no detection in the image, and the values in the array are only the allocated memory (they aren't valid).

**Comment by marcoslucianops** [comment]
> `4   OUTPUT kFLOAT detection_classes 22743`

The detection_classes output is a kFLOAT array. You need to cast it as float and convert to int after the cast.

**Comment by aidevmin** [comment]
Thanks. For Darknet model, output from engine model is same as output from Darknet model or you modified it? I see you did many custom layers (file .cpp). For what are these .cpp files? I see that Nvidia offical repo doesn't have any .cpp filea.

**Comment by marcoslucianops** [comment]
> For Darknet model, output from engine model is same as output from Darknet model or you modified it?

It has the post-processing in the engine.

> I see that Nvidia offical repo doesn't have any .cpp filea

This repo is an improvement of the NVIDIA YOLO. Here you will have support for more models and easier implementation.

**Comment by aidevmin** [comment]
>It has the post-processing in the engine.

It may be the reason there is a strange value when running inference by using Tensorrt Python API.
Could you point me which file you custom to do postprocessing in engine?

As my understanding, Deepstream generate engine model, run inference on image, and output of engine will be passed into `nvdsparsebbox_yolo.cpp` and finnaly passed into NMS? Is it right? 

You mentioned `It has the post-processing in the engine`. Which post processing do you mean? Is it different from post-processing as I mentioned above?

**Comment by marcoslucianops** [comment]
if you use the latest commit, the output will be

```
(float) boxes = outputLayersInfo[0];
(float) scores = outputLayersInfo[1];
(float) classes = outputLayersInfo[2];
```

```
(int) outputSize = boxes.inferDims.d[0]; // first dimension size of the layer
```

```
for (uint b = 0; b < outputSize; ++b) {
  float maxProb = scores[b];  // best detection score
  int maxIndex = (int) classes[b];  // class with the best detection score

  float bxc = boxes[b * 4 + 0];  // x_center
  float byc = boxes[b * 4 + 1];  // y_center
  float bw = boxes[b * 4 + 2];  // width
  float bh = boxes[b * 4 + 3];  // height
}
```

**Comment by aidevmin** [comment]
Yeah, thanks. I have read these code for parsing bboxes. This processing is not included in engine.
Honesty, I didn't find the reason why output from Deepstream generated engine model when running by using Tensorrt API is strange.

**Comment by marcoslucianops** [comment]
The post-processing included in the engine is the https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/nvdsinfer_custom_impl_Yolo/yoloForward.cu / https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/nvdsinfer_custom_impl_Yolo/yoloForward_nc.cu

**Comment by marcoslucianops** [comment]
If possible, send me more detailed what you are doing to my email and I will try to help you.

**Comment by aidevmin** [comment]
@marcoslucianops 
Thank you so much. Please check email.
