### ISSUE TITLE
Recipe for target 'yolo.o' failed

### ISSUE THREAD

**Issue by garaujo23** [marcoslucianops/DeepStream-Yolo#39]
Using the new deepstream-5.1 triton docker to build the nvdsinfer_custom_impl_Yolo I get the following error in make:

yolo.cpp: In member function 'NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&)':
yolo.cpp:298:48: error: 'createReorgPlugin' was not declared in this scope
             nvinfer1::IPluginV2* reorgPlugin = createReorgPlugin(2);
                                                ^~~~~~~~~~~~~~~~~
yolo.cpp:298:48: note: suggested alternative: 'reorgPlugin'
             nvinfer1::IPluginV2* reorgPlugin = createReorgPlugin(2);
                                                ^~~~~~~~~~~~~~~~~
                                                reorgPlugin
Makefile:61: recipe for target 'yolo.o' failed

Checking cuda version using nvcc --version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0

I have done sudo chmod -R 777 /opt/nvidia/deepstream/deepstream-5.1/sources/ and ran CUDA_VER=11.1 make -C nvdsinfer_custom_impl_Yolo.

No issues previously using 5.0.1 and old instructions

**Comment by garaujo23** [comment]
Seems to be an issue with the triton docker image, just tried with the devel and had no issues, feel free to close the issue.

**Comment by marcoslucianops** [comment]
Hi, are you using my files?

**Comment by garaujo23** [comment]
Yeah so I copy the native files to the source folder and rename yolo, no issues. The problem it appears is with the triton docker image for 5.1 DS, I had no issues building with devel 5.1 DS

**Comment by pramodwic1** [comment]
Hi @garaujo23 @marcoslucianops , 

I am trying to compile the files from nvidia deepstream 5.1 image (5.1-21.02-devel) on x86. As this is an ongoing project I cannot use deepstream 6.0. however the compilation always fails as shown below. If possible could you let me know, how you got it to compile and run.

![image](https://user-images.githubusercontent.com/105900664/169446016-99c7cd15-c918-4c74-8c44-6f07937dd709.png)

**Comment by marcoslucianops** [comment]
@pramodwic1, It only works on DeepStream 6.0.1

**Comment by marcoslucianops** [comment]
Added support for DeepStream 5.1
