### ISSUE TITLE
There is no file named "gen_wts_yolov5.py" in utils.How to general yolov5.cfg?

### ISSUE THREAD

**Issue by yangaaa123** [marcoslucianops/DeepStream-Yolo#391]

**Comment by hhackbarth** [comment]
It's export_yolov5.py now. See: https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv5.md

**Comment by yangaaa123** [comment]
> It's export_yolov5.py now. See: https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv5.md

OK.Thank you very much!
