### ISSUE TITLE
How to apply in realtime?

### ISSUE THREAD

**Issue by Eunsunggcu** [marcoslucianops/DeepStream-Yolo#392]
Hi!, i searched issue, but i dont know exactly what to search, so i write issue.

HW : Jetson Xavier
SW : Jetpack 5.1.1, ubuntu 20.04, ROS noetic
and i can run deepstream-app -c deepstream_app_config.txt like example. (complete the step)

However, if i am running that code, it seems that only uri's example video can be executed.
I want to run the video that i received from realsense in real time.
and I use ROS noetic and realsense-ros, yolov5-ros package.

Can I get some help?

**Comment by marcoslucianops** [comment]
You can create you custom code based on NVIDIA samples (https://github.com/NVIDIA-AI-IOT/deepstream_python_apps for example) and use the nvinfer calling the config_infer_primary file. But I don't have experience with ROS, so I can't help you, sorry. Take a look on https://github.com/NVIDIA-AI-IOT/ros2_deepstream and check if it can help.
