### ISSUE TITLE
Inference does not proceed immediately after model creation with NvDsInferYoloCudaEngineGet in onnx

### ISSUE THREAD

**Issue by YoungjaeDev** [marcoslucianops/DeepStream-Yolo#393]
Hello, I am running v5 as Fp16 based on onnx.
When there is no trt engine fie, it is well made to create a model based on onnx, but inference does not proceed immediately after model creation. I have to kill the process and then restart it to work normally, do you know why? I'm not sure if it's a DeepStream problem or a this lib problem here.

my commit
https://github.com/marcoslucianops/DeepStream-Yolo/tree/b2c4bee8dcbc4729f1bd13b598a574228ff10c27

**Comment by youngjae-avikus** [comment]
@marcoslucianops 

https://github.com/marcoslucianops/DeepStream-Yolo/tree/b2c4bee8dcbc4729f1bd13b598a574228ff10c27
Can you tell me what changes were applied in this commit, the master commit, and the yolov5 side?

**Comment by marcoslucianops** [comment]
Try to use the latest commit. I solved a lot of bugs.

**Comment by marcoslucianops** [comment]
Which docker image are you using?

**Comment by ConnorMcGuirk** [comment]
> Which docker image are you using?

nvcr.io/nvidia/deepstream:6.2-devel

**Comment by marcoslucianops** [comment]
Strange, I don't have this issue here. Try to set

```
[sink0]
type=1
```

in the `deepstream_app_config.txt` file to check if it's an error related to the x output.

**Comment by ConnorMcGuirk** [comment]
Hmm I seem to be getting several warnings regarding gstreamer files

_deepstream-app -c deepstream_app_config.txt 

(gst-plugin-scanner:13): GStreamer-WARNING **: 15:09:09.760: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_nvblender.so': libcuda.so.1: cannot open shared object file: No such file or directory

(gst-plugin-scanner:13): GStreamer-WARNING **: 15:09:09.764: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_inferserver.so': libtritonserver.so: cannot open shared object file: No such file or director_

Do you have an example Dockerfile for how you are building the image?

**Comment by marcoslucianops** [comment]
>```
> (gst-plugin-scanner:13): GStreamer-WARNING **: 15:09:09.760: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_nvblender.so': libcuda.so.1: cannot open shared object file: No such file or directory
>
> (gst-plugin-scanner:13): GStreamer-WARNING **: 15:09:09.764: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_inferserver.so': libtritonserver.so: cannot open shared object file: No such file or directory
> ```

You can ignore the warnings from the start of the `deepstream-app`. Those are because you are using an image that doesn't have the plugins.

> ```
> (gst-plugin-scanner:13): GStreamer-WARNING **: 15:09:09.776: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_eglglessink.so': libcuda.so.1: cannot open shared object file: No such file or directory
> ```

This one, if I'm not wrong, is because you are using 

```
[sink0]
type=2
```

But you didn't enable the xhost to the enable x display. You need to enable it (`xhost +`) or change to:

```
[sink0]
type=1
```

**Comment by ConnorMcGuirk** [comment]
Sorry, I just updated my previous comment to contain the output when using
```
[sink0]
type=1
```

```
deepstream-app -c deepstream_app_config.txt 
** ERROR: <create_multi_source_bin:1490>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1583>: create_multi_source_bin failed
** ERROR: <create_pipeline:1485>: create_pipeline failed
** ERROR: <main:697>: Failed to create pipeline
Quitting
App run failed
```

**Comment by ConnorMcGuirk** [comment]
Tried with two slightly different config.txts (only changes under [sink0]

[deepstream_app_config_v0.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/11950897/deepstream_app_config_v0.txt)
[deepstreamapp_output_v0.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/11950898/deepstreamapp_output_v0.txt)

[deepstream_app_config_v1.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/11950899/deepstream_app_config_v1.txt)
[deepstreamapp_output_v1.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/11950900/deepstreamapp_output_v1.txt)

**Comment by marcoslucianops** [comment]
The correct is:

```
[sink0]
enable=1
type=1
sync=0
gpu-id=0
nvbuf-memory-type=0
```

I think you have a problem with your CUDA. Which CUDA are you using? Did you install the [`nvidia-container-toolkit`](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)?

**Comment by ConnorMcGuirk** [comment]
Hmmmm it seems I either have an issue with my docker-compose setup or that some dialog is being suppressed when I run with `sudo docker compose up`
I am able to successfully run the deepstream-app test and my own code when I run in an interactive session with --gpus all

Eitherway, does not seem to be an issue with DeepStream-Yolo, thanks!

**Comment by marcoslucianops** [comment]
You need to run the deepstream-app in the entrypoint on the Dockerfile.

**Comment by ConnorMcGuirk** [comment]
Yes, all good now. The issue was related to this all along...https://stackoverflow.com/questions/51362213/docker-compose-not-printing-stdout-in-python-app

**Comment by youngjae-avikus** [comment]
@marcoslucianops 

I am moving from the commit mentioned in the text to the current master commit.
However, to build the trt engine in the onnx model, in the past, the model-engine-file was created as {onnx-file}_bX_gpu0_fp16.engine in the path where the onnx-file is located, but now it is just created as model_ prefix.

After thinking about this for a bit, this phenomenon appeared when NvDsInferYoloCudaEngineGet was redefined as Extern in DeepStream yolo. Is there a big difference between the NvDsInferYoloCudaEngineGet defined by default in deepstream and the NvDsInferYoloCudaEngineGet function defined in DeepStream yolo?

**Comment by marcoslucianops** [comment]
@youngjae-avikus
The new implementation is to make the TensorRT able to use INT8 calibrator and implicit batch.

**Comment by youngjae-avikus** [comment]
It seems that the default build setting is **_explicit batch._**

**Comment by marcoslucianops** [comment]
@youngjae-avikus 
Yes, but you can force the implicit batch using `force-implicit-batch-dim=1`.

**Comment by marcoslucianops** [comment]
To use `force-implicit-batch-dim=1` you to export the model with `--batch 1` (example for batch-size 1) instead the `--dynamic`.
