### ISSUE TITLE
Nvcsf pipeline 

### ISSUE THREAD

**Issue by storm12t48** [marcoslucianops/DeepStream-Yolo#394]
may be off topic but how to implement an nvcsf tracker pipeline to a yolov8 detection with deepstream for example cordially

**Comment by marcoslucianops** [comment]
Take a look on https://github.com/NVIDIA-AI-IOT/deepstream_python_apps

There's many examples using Python there. You just need to set the pgie `config-file-path` property to the config_infer_primary file from this repo to use the YOLO inference.

**Comment by storm12t48** [comment]
ok thx

**Comment by storm12t48** [comment]
thx
