### ISSUE TITLE
Add blur to video stream - YOLOv8

### ISSUE THREAD

**Issue by gaiadobc** [marcoslucianops/DeepStream-Yolo#396]
Hi, I'm thinking how to add blur on the video stream to anonymize faces but I'm not able to find a section of the code where i can add this functionality. Can you help me?

**Comment by marcoslucianops** [comment]
The blur will drop the performance of your pipeline. You can use the nvdsosd to hide the face. Take a look on:

- C++:
https://github.com/NVIDIA-AI-IOT/redaction_with_deepstream

- Python:
https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/deepstream-imagedata-multistream-redaction
