### ISSUE TITLE
Error generating engine for YOLOv8 on Jetson, deepstream 5.1

### ISSUE THREAD

**Issue by M1ke002** [marcoslucianops/DeepStream-Yolo#397]
Hi, 
I'm using deepstream 5.1 on my Jetson Xavier with Jetpack 4.5.1 for yolov8. I downloaded the official yolov8s.pt from ultralytics and followed your instructions in https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv8.md. I converted the model to ONNX using only --opset 12. But when I run deepstream-app to generate the .engine file, I get the error: Repeated layer name: /0/model.22/Split_1 (layers must have distinct names).

Here is the full log when running deepstream-app: 
Unknown or legacy key specified 'symmetric-padding' for group [property]
ERROR: Deserialize engine failed because file path: /home/DeepStream-Yolo/yolov8s.engine open error
0:00:01.888546334 16196   0x7f40002390 WARN                 nvinfer gstnvinfer.cpp:616:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1690> [UID = 1]: deserialize engine from file :/home/DeepStream-Yolo/yolov8s.engine failed
0:00:01.888666815 16196   0x7f40002390 WARN                 nvinfer gstnvinfer.cpp:616:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1797> [UID = 1]: deserialize backend context from engine from file :/home/DeepStream-Yolo/yolov8s.engine failed, try rebuild
0:00:01.888709887 16196   0x7f40002390 INFO                 nvinfer gstnvinfer.cpp:619:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1715> [UID = 1]: Trying to create engine from model files

Input filename:   /home/DeepStream-Yolo/yolov8s.onnx
ONNX IR version:  0.0.7
Opset version:    12
Producer name:    pytorch
Producer version: 2.0.1
Domain:           
Model version:    0
Doc string:       

onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
WARNING: [TRT]: Tensor DataType is determined at build time for tensors not marked as input or output.

Building the TensorRT Engine

ERROR: [TRT]: Repeated layer name: /0/model.22/Split_1 (layers must have distinct names)
ERROR: [TRT]: Network validation failed.
Building engine failed

Failed to build CUDA engine
ERROR: Failed to create network using custom network creation function
ERROR: Failed to get cuda engine from custom library API
0:00:02.242192269 16451   0x7f54002320 ERROR                nvinfer gstnvinfer.cpp:613:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1735> [UID = 1]: build engine file failed
0:00:02.242257069 16451   0x7f54002320 ERROR                nvinfer gstnvinfer.cpp:613:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1821> [UID = 1]: build backend context failed
0:00:02.242294701 16451   0x7f54002320 ERROR                nvinfer gstnvinfer.cpp:613:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1148> [UID = 1]: generate backend failed, check config file settings
0:00:02.242370862 16451   0x7f54002320 WARN                 nvinfer gstnvinfer.cpp:809:gst_nvinfer_start:<primary_gie> error: Failed to create NvDsInferContext instance
0:00:02.242398478 16451   0x7f54002320 WARN                 nvinfer gstnvinfer.cpp:809:gst_nvinfer_start:<primary_gie> error: Config file path: /home/DeepStream-Yolo/config_infer_primary_yoloV8.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
** ERROR: <main:655>: Failed to set pipeline to PAUSED
Quitting
ERROR from primary_gie: Failed to create NvDsInferContext instance
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvinfer/gstnvinfer.cpp(809): gst_nvinfer_start (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
Config file path: /home/DeepStream-Yolo/config_infer_primary_yoloV8.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
App run failed

**Comment by marcoslucianops** [comment]
Can you try with `--opset 11` and/or PyTorch < 2?

**Comment by M1ke002** [comment]
I tried with Pytorch 1.11.0 and it works, thanks alot!

**Comment by ghty11468** [comment]
> Can you try with `--opset 11` and/or PyTorch < 2?

I also encountered this issue, but I adjusted the opset but it couldn't be resolved

**Comment by PaoXi** [comment]
**Title**: Issue with TensorRT model export: ONNX model from PyTorch 1.14 showing PyTorch 2.0.0 in TensorRT logs

Hi,

I'm encountering an issue when exporting a YOLOv8 model to ONNX using PyTorch 1.14, but when I run the model through TensorRT, the logs indicate that it's using PyTorch 2.0.0 as the producer version. Here are the details:

1. **Export Process**:
   - I used PyTorch version 1.14 for exporting the model to ONNX:
     ```python
     torch.onnx.export(model, dummy_input, "yolov8s.onnx", opset_version=11)
     ```
   - The ONNX export completed without errors, and the model file `yolov8s.onnx` was generated successfully.

2. **TensorRT Conversion**:
   - When I use TensorRT's `trtexec` to convert the ONNX model, I notice that the logs show that the model's producer is listed as PyTorch 2.0.0:
     ```
     [12/06/2024-12:32:39] [I] [TRT] Producer name:    pytorch
     [12/06/2024-12:32:39] [I] [TRT] Producer version: 2.0.0
     ```

  


 - The export was done with PyTorch 1.14, not 2.0.0.

   - I expected the producer version to show 1.14, consistent with the PyTorch version used during export.

3. **What I've Tried**:
   - I've double-checked my PyTorch version with `torch.__version__` and confirmed it's 1.14.
   - I've tried re-exporting the model and rebuilding the environment but still get the same result.

4. **Environment**:
   - PyTorch version: 1.14
   - TensorRT version: 8.5.2
   - CUDA version: 11.4

Has anyone encountered this issue before? Any suggestions on how to resolve this discrepancy?

Thanks!

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv8.md
