### ISSUE TITLE
Interfacing Kafka with DeepStream-Yolo

### ISSUE THREAD

**Issue by gigwegbe** [marcoslucianops/DeepStream-Yolo#40]
Hello @marcoslucianops, 
Once again thanks for your response. I will like to interface Kafka with DeepStream-Yolo to stream inference. Is there anyway to go around it?Thanks.

**Comment by marcoslucianops** [comment]
Hi, I don't know how Kafka works, but you can use my files in all NVIDIA DeepStream SDK apps. You just need to look how to implement Kafka in DeepStream and use my files with your model in config file.

**Comment by PareshKamble** [comment]
Hi @marcoslucianops 
Did you manage to find a way to interface Kafka with DeepStream-Yolo?

**Comment by marcoslucianops** [comment]
There are many ways to use. One of them is:
- https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/deepstream-test4
