### ISSUE TITLE
webRTC

### ISSUE THREAD

**Issue by bongpigeon** [marcoslucianops/DeepStream-Yolo#401]
hello, thank for your hard work!
I am trying to use webRTC protocol to send deepstream results. 
Is there any recommendation to do it? or is it impossible to do it?

**Comment by marcoslucianops** [comment]
The WebRTC plugins works only with GStreamer 1.22+ while the DeepStream works only with GStreamer 1.16.3. Probably in the future when NVIDIA updates the plugins to the new version.
