### ISSUE TITLE
Detecion information python app

### ISSUE THREAD

**Issue by storm12t48** [marcoslucianops/DeepStream-Yolo#402]
Good morning
Thank you for your very good work and I encourage you to continue
But I have a question I am developing an app in python by following the examples given on the official site
But I can't find a way to get detection information like inference speed for example

Thanks in advance

**Comment by marcoslucianops** [comment]
You can use the example from NVIDIA: https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/blob/master/apps/common/FPS.py

Or you can create a custom code to do it using the GStreamer probe functions.

**Comment by storm12t48** [comment]
hello 
Sorry I don't understand I can't get this metadata NvDsFrameLatencyInfo::latency
 from APi: [Here](https://docs.nvidia.com/metropolis/deepstream/sdk-api/structNvDsFrameLatencyInfo.html)
Saying that the binding don't work but I would like to try the creation of the probe if you have a link or something like that

**Comment by marcoslucianops** [comment]
If I'm not wrong, the NvDsFrameLatencyInfo is related to the `nvdslogger` plugin. It can be used for the perf measurement.

**Comment by marcoslucianops** [comment]
Probably, there's no bindings for the `Latency Measurement API` for Python. Only for C/C++. The easier way is do similiar to the link I sent you.
