### ISSUE TITLE
Impossible to get detection in yolov8

### ISSUE THREAD

**Issue by hdnh2006** [marcoslucianops/DeepStream-Yolo#411]
Hello,

Thanks for the fantastic job you have done with this repo.

In the past, I could succesfully export and run an app using deepstream in my Jetson Xavier NX (https://github.com/marcoslucianops/DeepStream-Yolo/issues/390#issuecomment-1632510589). 

However, no matter what I do, what version of onnx or opset I use, I can't see the bounding boxes in the image predicted.

These are the settings I have tried (always `torch==1.12`):

- `--opset 11` and `onnx==1.14` and `onnxruntime==1.15.1`
- `--opset 12` and `onnx==1.14` and `onnxruntime==1.15.1`
- `--opset 11` and `onnx==1.12` and `onnxruntime==1.12`
- `--opset 12` and `onnx==1.12` and `onnxruntime==1.12`

I am always using the same command:
`python3 export_yoloV8.py -w yolov8s.pt --dynamic --simplify --opset **`

I am leaving all the weights I have used in this [link](https://we.tl/t-SqkuTTdWOe) (available one week). 

Can somebody help me to understand what I am doing wrong? maybe something is being wrongly cached? I don't understand why I could do it in the past, and what I am doing different now. I have even checked the `.bash_history` and I am repeting the same process and nothing...

Please help.

**Comment by marcoslucianops** [comment]
What's your DeepStream version?

**Comment by hdnh2006** [comment]
Sorry @marcoslucianops for the late reply. 

I am using deepstream 6.2 on my Jetson Xavier NX device.

**Comment by marcoslucianops** [comment]
I don't have a Jetson board to test it now. But you can export the ONNX model in your computer and use on the Jetson. Can you try?
