### ISSUE TITLE
Can I use the same calib.table while building different batch size of .eninge file?

### ISSUE THREAD

**Issue by shao77622** [marcoslucianops/DeepStream-Yolo#414]
Firstly, I build the model_b1_gpu0_int8.engine file with calibration, and I got the calib.table file.
Then I need to build other batch size of .engine file for different batch inference.  Do I need to make calibration every time?
thank you!

**Comment by marcoslucianops** [comment]
You don't need to recalibrate. Just keep the `calib.table` file and it will use the generated calibration.
