### ISSUE TITLE
Yolov5 Performance Metrics - Jetson Nano

### ISSUE THREAD

**Issue by rickymedrano** [marcoslucianops/DeepStream-Yolo#42]
Hi,
I noticed your table is empty for FPS for Yolov5s on the Jetson Nano. Have you gotten any FPS results lately? I followed your Yolov5s example and am getting ~13FPS for Yolov5s (pretrained weights; 608 resolution)) on the Nano 4GB using the default video file in the main config. 

Also, under your "NVIDIA GTX 1050 (4GB Mobile)" section, you have 3 tables: TensorRT, Darknet, and PyTorch. What's the difference between the TensorRT table and the Darknet table? Because doesn't deepstream-app automatically convert your cfg and weights file into a TensorRT engine anyway? So essentially you'll be using TensorRT whether you point directly to a .engine file or a .cfg/.weights file? I understand why you would have the PyTorch table because you're starting with a different architecture configuration, but doesn't Yolov4 in the TensorRT table have the same architecture in the end as the Yolov4 in the Darknet table? Hope that makes sense, just look for clarity.

**Comment by marcoslucianops** [comment]
Hi, about results in Jetson Nano, it's blank because I haven't done the tests yet.

About TensorRT, Darknet and PyTorch tables:

TensorRT table = results using DeepStream SDK with conveyed engine.

Darknet table = results using Darknet (AlexeyAB) with YOLO model (cfg and weights).

PyTorch table = results using Ultralytics with YOLOv5 models.

**Comment by rickymedrano** [comment]
> TensorRT table = results using DeepStream SDK with converted YOLO engine.

In this case, did you use tlt-converter to generate the engine or some other way?

**Comment by marcoslucianops** [comment]
The DeepStream automatically converts YOLO (v2, v3 and v4) cfg and weights to TensorRT with my repo. To convert YOLOv5 to TensorRT, I use TensorRTX repo.
