### ISSUE TITLE
WARNING: [TRT]: Unknown embedded device detected.

### ISSUE THREAD

**Issue by whittenator** [marcoslucianops/DeepStream-Yolo#420]
**Specs:
Nvidia Jetson Orin 64GB
Deepstream Version: 6.2
Deepstream-Yolo: Latest**

When I convert a YoloV7, YoloV8 or YOLO-NAS ONNX file to an engine file using the Nvidia Jetson Orin, I get the following warning constantly being output:
```bash
WARNING: [TRT]: Unknown embedded device detected. Using 59655MiB as the allocation cap for memory on embedded devices.
WARNING: [TRT]: Unknown embedded device detected. Using 59655MiB as the allocation cap for memory on embedded devices.
WARNING: [TRT]: Unknown embedded device detected. Using 59655MiB as the allocation cap for memory on embedded devices.
WARNING: [TRT]: Unknown embedded device detected. Using 59655MiB as the allocation cap for memory on embedded devices.
WARNING: [TRT]: Unknown embedded device detected. Using 59655MiB as the allocation cap for memory on embedded devices.
```

This is continuously printed to terminal until the .engine file is created. Is this anything to be concerned about?

At the end I get the following messages:
```bash
WARNING: [TRT]: TensorRT encountered issues when converting weights between types and that could affect accuracy.
WARNING: [TRT]: If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
WARNING: [TRT]: Check verbose logs for the list of affected weights.
WARNING: [TRT]: - 72 weights are affected by this issue: Detected subnormal FP16 values.
WARNING: [TRT]: - 11 weights are affected by this issue: Detected values less than smallest positive FP16 subnormal value and converted them to the FP16 minimum subnormalized value.
Building complete
```

Any concerns here?

Thanks

**Comment by marcoslucianops** [comment]
> When I convert a YoloV7, YoloV8 or YOLO-NAS ONNX file to an engine file using the Nvidia Jetson Orin, I get the following warning constantly being output:

Probably this is a issue from NVIDIA side with the JetPack components (mainly the TensorRT for the Orin series).

> At the end I get the following messages:

This is normal warnings, you can ignore it.

**Comment by Crear12** [comment]
How long did it take for your Orin to generate the .engine file? I got exactly same behavior.....It's been printing forever....

**Comment by whittenator** [comment]
> How long did it take for your Orin to generate the .engine file? I got exactly same behavior.....It's been printing forever....

I am using the Jetson Orin 64GB and it took about 15-20 minutes. If you are using something smaller(i.e Nano or 32GB) it could take like an hour or so.

**Comment by marcoslucianops** [comment]
It takes a very long time, it's a TensorRT issue.

**Comment by vodan37** [comment]
same problem with other model. Now it is going for 1 hour and i don't know when is the end.

**Comment by whittenator** [comment]
When I build on the Jetson Orin 32GB it takes ~10 minutes to build the
engine file for a YoloV7-small model. What size model are you using?
