### ISSUE TITLE
count objects per frame

### ISSUE THREAD

**Issue by bongpigeon** [marcoslucianops/DeepStream-Yolo#424]
hi! 
Is there any way I can count objects per frame? 
I don't want to track them just want to count the objects.

**Comment by marcoslucianops** [comment]
Take a look on: https://github.com/NVIDIA-AI-IOT/deepstream_python_apps

You can use this repo as `pgie` on the code and get the number of objects using `frame_meta.num_obj_meta`.

**Comment by bongpigeon** [comment]
if I use the python-apps, can I use YOLOv8 which is in your github repo?

**Comment by bongpigeon** [comment]
can you tell me more specific?
I'm using yolov8 for detection and you're saying I can use deepstream-test-1 in my jetson board?

**Comment by marcoslucianops** [comment]
Yes, just set

```
pgie.set_property('config-file-path', "config_infer_primary_yoloV8.txt")
```

With the path of the `config_infer_primary_yoloV8.txt` file.

**Comment by bongpigeon** [comment]
do i need to use python-app? Is there anyway I can just edit some parts of your repo?

**Comment by bongpigeon** [comment]
plus if you see the deepstream-test files, you can see deepstream_test_app.c files in each sample apps. How does this repo work without deepstream_test_app.c files?

**Comment by marcoslucianops** [comment]
> do i need to use python-app? Is there anyway I can just edit some parts of your repo?

If you want to use the code in Python.

> plus if you see the deepstream-test files, you can see deepstream_test_app.c files in each sample apps. How does this repo work without deepstream_test_app.c files?

This repo works with any DeepStream code. As first use, this repo shows how to run it in the `deepstream-app`. It's already built when you install the DeepStream SDK.

> I think I can use this code from deepstream_test1.c but I don't know how to put it to. Can you help me?

You need to edit hte part you wnat, compile the entire code, and run you compiled application.
