### ISSUE TITLE
’CUDA=10.2 make - C nvdsinder_ Custom_ Impl_ Yolo 'has been run，but no engine file

### ISSUE THREAD

**Issue by ghty11468** [marcoslucianops/DeepStream-Yolo#426]
’CUDA=10.2 make - C nvdsinder_ Custom_ Impl_ Yolo 'has been run, and the compilation process seems to have been compiled, but it seems that no engine file has been generated. The following is the compilation process:

jetson@yahboom:~/DeepStream-Yolo-master$ CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo
make: Entering directory '/home/jetson/DeepStream-Yolo-master/nvdsinfer_custom_impl_Yolo'
g++ -c  -o utils.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include utils.cpp
g++ -c  -o yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include yolo.cpp
yolo.cpp: In member function ‘nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*)’:
yolo.cpp:207:83: warning: ‘nvinfer1::ICudaEngine* nvinfer1::IBuilder::buildEngineWithConfig(nvinfer1::INetworkDefinition&, nvinfer1::IBuilderConfig&)’ is deprecated [-Wdeprecated-declarations]
   nvinfer1::ICudaEngine* engine = builder->buildEngineWithConfig(*network, *config);
                                                                                   ^
In file included from /usr/include/aarch64-linux-gnu/NvOnnxParser.h:26:0,
                 from yolo.cpp:26:
/usr/include/aarch64-linux-gnu/NvInfer.h:8642:43: note: declared here
     TRT_DEPRECATED nvinfer1::ICudaEngine* buildEngineWithConfig(
                                           ^~~~~~~~~~~~~~~~~~~~~
g++ -c  -o nvdsinfer_yolo_engine.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsinfer_yolo_engine.cpp
g++ -c  -o nvdsinitinputlayers_Yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsinitinputlayers_Yolo.cpp
g++ -c  -o nvdsparsebbox_Yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsparsebbox_Yolo.cpp
g++ -c  -o yoloPlugins.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include yoloPlugins.cpp
g++ -c  -o layers/convolutional_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/convolutional_layer.cpp
g++ -c  -o layers/route_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/route_layer.cpp
g++ -c  -o layers/shortcut_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/shortcut_layer.cpp
g++ -c  -o layers/pooling_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/pooling_layer.cpp
g++ -c  -o layers/reorg_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/reorg_layer.cpp
g++ -c  -o layers/batchnorm_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/batchnorm_layer.cpp
g++ -c  -o layers/activation_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/activation_layer.cpp
g++ -c  -o layers/channels_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/channels_layer.cpp
g++ -c  -o layers/sam_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/sam_layer.cpp
g++ -c  -o layers/deconvolutional_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/deconvolutional_layer.cpp
g++ -c  -o layers/upsample_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/upsample_layer.cpp
g++ -c  -o layers/implicit_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include layers/implicit_layer.cpp
/usr/local/cuda-10.2/bin/nvcc -c -o yoloForward_v2.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include yoloForward_v2.cu
/usr/local/cuda-10.2/bin/nvcc -c -o yoloForward.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include yoloForward.cu
/usr/local/cuda-10.2/bin/nvcc -c -o yoloForward_nc.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include yoloForward_nc.cu
/usr/local/cuda-10.2/bin/nvcc -c -o nvdsparsebbox_Yolo_cuda.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsparsebbox_Yolo_cuda.cu
g++ -o libnvdsinfer_custom_impl_Yolo.so  utils.o yolo.o nvdsinfer_yolo_engine.o nvdsinitinputlayers_Yolo.o nvdsparsebbox_Yolo.o yoloPlugins.o layers/convolutional_layer.o layers/route_layer.o layers/shortcut_layer.o layers/pooling_layer.o layers/reorg_layer.o layers/batchnorm_layer.o layers/activation_layer.o layers/channels_layer.o layers/sam_layer.o layers/deconvolutional_layer.o layers/upsample_layer.o layers/implicit_layer.o yoloForward_v2.o yoloForward.o yoloForward_nc.o nvdsparsebbox_Yolo_cuda.o -shared -Wl,--start-group -lnvinfer_plugin -lnvinfer -lnvparsers -lnvonnxparser -L/usr/local/cuda-10.2/lib64 -lcudart -lcublas -lstdc++fs -Wl,--end-group
make: Leaving directory '/home/jetson/DeepStream-Yolo-master/nvdsinfer_custom_impl_Yolo'

I earnestly request the author's help in answering. Thank you.

**Comment by marcoslucianops** [comment]
The engine is created when you run the `deepstream-app` command for the model you are running.

**Comment by ghty11468** [comment]
> 引擎是在为正在运行的模型运行命令时创建的。`deepstream-app`

Thank you for your answer. I have also learned this content. But what happened when I encountered this error after running the command?

![e22606c9b19d4baaa93c727f0e2063f](https://github.com/marcoslucianops/DeepStream-Yolo/assets/110895140/2e083c18-1c87-49f7-855c-9d448da1627f)

**Comment by marcoslucianops** [comment]
Which Jetson board are you using?

**Comment by ghty11468** [comment]
> 您使用的是哪种 Jetson 板？

Yes, I'm using a Jetson nano

**Comment by marcoslucianops** [comment]
Can you debug the `deepstream-app` using `gdb`?

**Comment by ghty11468** [comment]
> Can you debug the `deepstream-app` using `gdb`?

Sorry, I can't do the operation you mentioned

**Comment by marcoslucianops** [comment]
The commands are

```
gdb deepstream-app
```

and 

```
run -c deepstream_app_config.txt
```

**Comment by marcoslucianops** [comment]
To get the output

```
where
```

**Comment by ghty11468** [comment]
> To get the output
> 
> ```
> where
> ```

![ad80b17d200f5d54c7f8f9692c5e5ff](https://github.com/marcoslucianops/DeepStream-Yolo/assets/110895140/c1637b53-e5dd-4c75-abc2-ee38365a9a4c)
![75533d48f9876a9200a5c37cd8936ed](https://github.com/marcoslucianops/DeepStream-Yolo/assets/110895140/5c1d214b-27f5-4b5e-bad8-f15c10769461)

**Comment by marcoslucianops** [comment]
Which model are you trying to run?

**Comment by ghty11468** [comment]
> Which model are you trying to run?

I am using the YOLOv5S model. If this command is successfully run, will an engine file be generated?

**Comment by marcoslucianops** [comment]
Yes, but I don't know why you're getting this error. Maybe something wrong in the board enviroment or exported model.

**Comment by ghty11468** [comment]
> Yes, but I don't know why you're getting this error. Maybe something wrong in the board enviroment or exported model.

Thank you. Do you still have any previous version of the code package? I am using the one that utilizes cfg and wts files

**Comment by marcoslucianops** [comment]
You can get it in the old commits, but I recommend you to use the new files (with ONNX export) because it's more optimized now.

**Comment by ghty11468** [comment]
> You can get it in the old commits, but I recommend you to use the new files (with ONNX export) because it's more optimized now.

Thank you. May I ask where the old commits you mentioned is? Sorry, I couldn't find it

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/tree/e652ef4e394fbcee0b8b8652c4630802bec4eab3

This is the last commit that uses the wts and cfg files.

**Comment by ghty11468** [comment]
> https://github.com/marcoslucianops/DeepStream-Yolo/tree/e652ef4e394fbcee0b8b8652c4630802bec4eab3
> 
> 这是使用 wts 和 cfg 文件的最后一次提交。

Thank you very much, thank you for the patient answer above

**Comment by ghty11468** [comment]
> https://github.com/marcoslucianops/DeepStream-Yolo/tree/e652ef4e394fbcee0b8b8652c4630802bec4eab3
> 
> 这是使用 wts 和 cfg 文件的最后一次提交。

Thank you very much. My problem has been resolved, just download the project file again. Perhaps the previous project code file was damaged
