### ISSUE TITLE
Performance YOLOv5 deepstream

### ISSUE THREAD

**Issue by constantinfite** [marcoslucianops/DeepStream-Yolo#43]
Hi, I was wondering if the performance I was getting with deepstream yolov5 was normal on the jetson nano 4GB?

I run inference on 2 video camera (1280*720) and I get very laggy preview.
I have to set drop-frame-interval=5 to obtain a real-time inference, it takes 0.15s to make inference on each camera

Maybe it's my config ?

Environment : 
jetpack 4.5.1
deepstream 5.1

Model used YOLOv5s 3.0 

btw: nice tuto !

## deepstream_app_config.txt : 

[application]
enable-perf-measurement=1
perf-measurement-interval-sec=1

[tiled-display]
enable=1
rows=1
columns=2
width=1920
height=1080
gpu-id=0
nvbuf-memory-type=0

[source0]
enable=1
type=3
uri=rtsp://192.168.1.19:554/1/h264major
num-sources=1
gpu-id=0
cudadec-memtype=0
#latency=200
#drop-frame-interval=5

[source1]
enable=1
type=3
uri=rtsp://192.168.1.20:554/1/h264major
num-sources=1
gpu-id=0
cudadec-memtype=0
#latency=200
#drop-frame-interval=5

[sink0]
enable=1
type=2
sync=0
source-id=0
gpu-id=0
nvbuf-memory-type=0

[sink1]
enable=1
type=2
sync=0
source-id=1
gpu-id=0
nvbuf-memory-type=0

[osd]
enable=1
gpu-id=0
border-width=1
text-size=15
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Serif
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0

[streammux]
gpu-id=0
live-source=1
batch-size=2
batched-push-timeout=40000
width=1280
height=720
enable-padding=0
nvbuf-memory-type=0

[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary.txt

[tests]
file-loop=0

**Comment by marcoslucianops** [comment]
It's normal, the Jetson Nano can't run YOLOv5s in realtime like YOLOv3/v4-tiny models.

**Comment by constantinfite** [comment]
for what reason? because it is not tiny ?

**Comment by marcoslucianops** [comment]
YOLOv5s model has a larger network than YOLO Tiny models
