### ISSUE TITLE
segmentation fault （core dumped）

### ISSUE THREAD

**Issue by ghty11468** [marcoslucianops/DeepStream-Yolo#430]
![587ff9fbef59b4bb4c98760bceab29b](https://github.com/marcoslucianops/DeepStream-Yolo/assets/110895140/1072e9f9-a47d-4788-ba2f-c42f18e1b095)

The engine file has been generated, but this error always occurs during inference. What should I do?

**Comment by marcoslucianops** [comment]
Please follow: https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv5.md

The engine output is wrong, so you are using the wrong ONNX model.

**Comment by ghty11468** [comment]
> 请关注： https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv5.md
> 
> 引擎输出错误，因此您使用了错误的 ONNX 模型。

My onnx file was generated using the Ultratics/Yolov5 project, but is it not allowed?

**Comment by marcoslucianops** [comment]
You need to use the `export_yoloV5.py` file from the `utils` folder in this repo to export the ONNX model from the YOLOv5 PyTorch model (as said in the link I sent you, please follow it).

**Comment by emad555** [comment]
> You need to use the `export_yoloV5.py` file from the `utils` folder in this repo to export the ONNX model from the YOLOv5 PyTorch model (as said in the link I sent you, please follow it).

This does not generate an engine file, only onnx file.

**Comment by marcoslucianops** [comment]
The engine file is generated in the fisrt time you run the `deepstream-app` command.

**Comment by emad555** [comment]
Thank yo, it is working now!
