### ISSUE TITLE
Print out the location of the bounding box.

### ISSUE THREAD

**Issue by emad555** [marcoslucianops/DeepStream-Yolo#433]
I am trying to print out the location of the bounding box of the detected object, the location of the box in the frame.
What is the best way to do that?

**Comment by marcoslucianops** [comment]
Using https://github.com/NVIDIA-AI-IOT/deepstream_python_apps

**Comment by emad555** [comment]
The Python files are using plugins to run the code. So I need to edit the plugins, right?

**Comment by marcoslucianops** [comment]
You need to edit the code, the metadata is got in the probe functions. Check one of the `deepstream-test` applications.
