### ISSUE TITLE
REFPS in python binding  deepstream

### ISSUE THREAD

**Issue by khosrooo** [marcoslucianops/DeepStream-Yolo#437]

**Comment by khosrooo** [comment]
Hi marcos  , i used fps.py in common in this directory for get RERFS but i get same FPS for every models , but when used deepstream-app -c deepstream_app_config.txt i get write fps why in the python biding deepstream i get just PERF 30 for every model i think it is the ferekanse monitor ?

**Comment by marcoslucianops** [comment]
The fps should be the same for all running streams. It will only change if you are running in 20 fps in the output and the camera have less framerate in its configuration. If you are saying about the python code having less fps than the `deepstream-app`, maybe you added something to the code that is slowing the pipeline. If don't so, check if you are using `sink.set_property("sync", 0)` in your code.
