### ISSUE TITLE
onnx from T4 to G4

### ISSUE THREAD

**Issue by chrichard** [marcoslucianops/DeepStream-Yolo#439]
The yolov8 model I trained on the T4 GPU and then converted to onnx files. Can this onnx file be used on the P4 GPU?

**Comment by marcoslucianops** [comment]
The ONNX model yes, but you need to generate the engine again running the `deepstream-app` command (or running a custom code).

**Comment by chrichard** [comment]
I generated an onnx file on the GPU of T4 and then wanted to convert to the model of int8 on P4. The following error is prompted


///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Added elements to bin
Using file: sample_720p.h264
WARNING: [TRT]: CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
WARNING: ../nvdsinfer/nvdsinfer_model_builder.cpp:1487 Deserialize engine failed because file path: /opt/nvidia/deepstream/deepstream-6.3/sources/apps/sample_apps/deepstream-test1/model_b1_gpu0_int8.engine open error
0:00:04.273382917 18176 0x56264d758240 WARN                 nvinfer gstnvinfer.cpp:679:gst_nvinfer_logger:<primary-nvinference-engine> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1976> [UID = 1]: deserialize engine from file :/opt/nvidia/deepstream/deepstream-6.3/sources/apps/sample_apps/deepstream-test1/model_b1_gpu0_int8.engine failed
0:00:04.314764262 18176 0x56264d758240 WARN                 nvinfer gstnvinfer.cpp:679:gst_nvinfer_logger:<primary-nvinference-engine> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2081> [UID = 1]: deserialize backend context from engine from file :/opt/nvidia/deepstream/deepstream-6.3/sources/apps/sample_apps/deepstream-test1/model_b1_gpu0_int8.engine failed, try rebuild
0:00:04.315510868 18176 0x56264d758240 INFO                 nvinfer gstnvinfer.cpp:682:gst_nvinfer_logger:<primary-nvinference-engine> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:2002> [UID = 1]: Trying to create engine from model files
WARNING: [TRT]: CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
WARNING: ../nvdsinfer/nvdsinfer_model_builder.cpp:659 INT8 calibration file not specified/accessible. INT8 calibration can be done through setDynamicRange API in 'NvDsInferCreateNetwork' implementation

File does not exist: /opt/nvidia/deepstream/deepstream-6.3/sources/apps/sample_apps/deepstream-test1/yolov8n_obj.onnx
ONNX model file does not exist

ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:728 Failed to create network using custom network creation function
ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:794 Failed to get cuda engine from custom library API
0:00:06.721963949 18176 0x56264d758240 ERROR                nvinfer gstnvinfer.cpp:676:gst_nvinfer_logger:<primary-nvinference-engine> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:2022> [UID = 1]: build engine file failed
0:00:06.764874041 18176 0x56264d758240 ERROR                nvinfer gstnvinfer.cpp:676:gst_nvinfer_logger:<primary-nvinference-engine> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2108> [UID = 1]: build backend context failed
0:00:06.765020515 18176 0x56264d758240 ERROR                nvinfer gstnvinfer.cpp:676:gst_nvinfer_logger:<primary-nvinference-engine> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1282> [UID = 1]: generate backend failed, check config file settings
0:00:06.883311589 18176 0x56264d758240 WARN                 nvinfer gstnvinfer.cpp:898:gst_nvinfer_start:<primary-nvinference-engine> error: Failed to create NvDsInferContext instance
0:00:06.883369670 18176 0x56264d758240 WARN                 nvinfer gstnvinfer.cpp:898:gst_nvinfer_start:<primary-nvinference-engine> error: Config file path: config_infer_primary_yoloV8.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
Running...
ERROR from element primary-nvinference-engine: Failed to create NvDsInferContext instance
Error details: gstnvinfer.cpp(898): gst_nvinfer_start (): /GstPipeline:dstest1-pipeline/GstNvInfer:primary-nvinference-engine:
Config file path: config_infer_primary_yoloV8.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
Returned, stopping playback
Deleting pipeline
ai@ai-Precision-7820
