### ISSUE TITLE
Draw lines on the output display.

### ISSUE THREAD

**Issue by emad555** [marcoslucianops/DeepStream-Yolo#440]
This is not an issue related to the repo implementation. I am trying to draw lines on perpendicular lines on the display.

I wrote this function inside deepstream_app_main.c:

```
void draw_perpendicular_lines(Display *display, Window window) {
    XGCValues gc_values;
    GC gc;

    gc_values.foreground = BlackPixel(display, DefaultScreen(display));
    gc = XCreateGC(display, window, GCForeground, &gc_values);

    int width, height;
    XWindowAttributes attr;
    XGetWindowAttributes(display, window, &attr);
    width = attr.width;
    height = attr.height;

    // Draw a horizontal line in the middle
    XDrawLine(display, window, gc, 0, height / 2, width, height / 2);

    // Draw a vertical line in the middle
    XDrawLine(display, window, gc, width / 2, 0, width / 2, height);

    XFreeGC(display, gc);
}
```

And I call it as:

```
for (i = 0; i < num_instances; i++) {
draw_perpendicular_lines(display, windows[i]);
}
```

The code runs successfully with the perpendicular lines but I get the following error after few seconds of running the pipeline:

`deepstream-app: ../../src/hb-object-private.hh:154: Type* hb_object_reference(Type*) [with Type = hb_unicode_funcs_t]: Assertion `hb_object_is_valid (obj)' failed.`

Is there a better implementation of drawing the lines, and if no, what should I edit in m code to run probably?

**Comment by marcoslucianops** [comment]
You need to draw the line using the `display_meta`. Check about the `nvds_add_display_meta_to_frame` function in the NVIDIA forums.
