### ISSUE TITLE
Cross platform engine export

### ISSUE THREAD

**Issue by tomikpik** [marcoslucianops/DeepStream-Yolo#442]
Hi there, could you please give me a hint on how to perform cross-platform engine export? I'd like to export the engine for the Jetson AGX Xavier on the x86 machine with NVIDIA A10 GPU x86 machine. 

Thanks :)

**Comment by marcoslucianops** [comment]
You can use the ONNX model in x86 and Jetson platforms, but the engine isn't possible.

**Comment by tomikpik** [comment]
So that basically means I need to distribute the model as ONNX with my application and perform the engine export on target device?

**Comment by marcoslucianops** [comment]
Yes, you will need to build the engine using the distributed ONNX model in each platform.
