### ISSUE TITLE
Call GPIO

### ISSUE THREAD

**Issue by ghty11468** [marcoslucianops/DeepStream-Yolo#443]
I would like to ask the author, I want to call GPIO to control external hardware in this project. Where should I rewrite it?

**Comment by marcoslucianops** [comment]
It's better to use database/kafka, in my opinion, to save the results and use another code to control de GPIO. But you can put the GPIO code in the DeepStream code (Python would be the easiest way).

**Comment by ghty11468** [comment]
> It's better to use database/kafka, in my opinion, to save the results and use another code to control de GPIO. But you can put the GPIO code in the DeepStream code (Python would be the easiest way).

You are right. But I still don’t understand how to add GPIO code (controlled by python) to Deepstream. For example, I want to add the GPIO control code to the back of the NMS in the inference process of YOLOV5, where should I add it?

**Comment by marcoslucianops** [comment]
Before the NMS? If so, why?

**Comment by ghty11468** [comment]
> Before the NMS? If so, why?

It's not the front of NMS, it's the back of NMS. After the NMS is executed, the detection results are available. I use the detection results obtained to call the GPIO interface to implement the operation of external hardware.

**Comment by marcoslucianops** [comment]
You can set it in the `pad_buffer_probe` function in any `deepstream_python_apps` after the `frame_meta` or `obj_meta` cast depending on what you want to do.

**Comment by ghty11468** [comment]
> You can set it in the `pad_buffer_probe` function in any `deepstream_python_apps` after the `frame_meta` or `obj_meta` cast depending on what you want to do.

What the author means is that this project cannot be completed. Does it need to be set up in deepstream in the python environment? My jetson nano has a deepstream image of the python environment

**Comment by marcoslucianops** [comment]
You need to install the python bindings to use the DeepStream python code. https://github.com/NVIDIA-AI-IOT/deepstream_python_apps
