### ISSUE TITLE
Saving video with python biding DeepStream

### ISSUE THREAD

**Issue by mam1680** [marcoslucianops/DeepStream-Yolo#445]
Hi 
I have a question:
I want to save the video with deepstream_test1.py and I add this part to my code:

```
    sink = Gst.ElementFactory.make("filesink", "filesink")
    if not sink:
        sys.stderr.write(" Unable to create file sink \n")

    sink.set_property("location", "./out.mp4")
    sink.set_property("sync", 1)
    sink.set_property("async", 0)
```

but it keeps running after 4 frames and won't stop (like it is in an infinite loop) 
what's the problem?

**Comment by marcoslucianops** [comment]
To save mp4 video you need: `nvvideoconvert` (caps `format=I420`) -> `nvv4l2h264enc` -> `h264parse` -> `qtmux` -> `filesink`.
