### ISSUE TITLE
how to add nvidia tracker to it

### ISSUE THREAD

**Issue by EscaticZheng** [marcoslucianops/DeepStream-Yolo#448]
I try to add [tracker] group in deepstream_app_config.txt, but it can't display id on screen. Also I don't know why no label.

![_1576182769_qq_pic_merged_1693970061486_1693970061000_xg_0](https://github.com/marcoslucianops/DeepStream-Yolo/assets/107376080/76c78799-6a97-4698-944b-3c0c351af14a)

deepstream_app_config.txt:
[application]
enable-perf-measurement=1
perf-measurement-interval-sec=5

[tiled-display]
enable=1
rows=1
columns=1
width=1280
height=720
gpu-id=0
nvbuf-memory-type=0

[source0]
enable=1
type=3
uri=file:///home/jetson/Videos/1/2/3/31.mp4
num-sources=1
gpu-id=0
cudadec-memtype=0

[source1]
enable=1
type=3
uri=rtsp://admin:123456@10.12.8.101:554/H264?ch=1&subtype=0
num-sources=1
gpu-id=0
cudadec-memtype=0

[sink0]
enable=1
type=2
sync=0
gpu-id=0
nvbuf-memory-type=0

[tracker]
tracker-width = 640
tracker-height = 384
enable = 1
gpu-id= 0
ll-lib-file = /opt/nvidia/deepstream/deepstream-6.2/lib/libnvds_nvmultiobjecttracker.so
ll-config-file = /opt/nvidia/deepstream/deepstream-6.2/samples/configs/deepstream-app/config_tracker_IOU.yml
enable-past-frame = 1
enable-batch-process = 1
display-tracking-id = 1

[osd]
enable=1
gpu-id=0
border-width=5
text-size=15
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Serif
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0

[streammux]
gpu-id=0
live-source=0
batch-size=1
batched-push-timeout=40000
width=1920
height=1080
enable-padding=0
nvbuf-memory-type=0

[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
#config-file=config_infer_primary.txt
config-file=config_infer_primary_yoloV5.txt

[tests]
file-loop=0

**Comment by marcoslucianops** [comment]
In the `deepstream-app`, when you have more than one source, you need to click in each camera in the grid, with the mouse (left click to expand and right click to back to the grid), to expand the output of the camera and see the labels.
