### ISSUE TITLE
YoloV5

### ISSUE THREAD

**Issue by Endeavor-Gcl** [marcoslucianops/DeepStream-Yolo#45]
How can i use yolov5?

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/YOLOv5.md

**Comment by Endeavor-Gcl** [comment]
> https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/YOLOv5.md

Thank you！Your code is very good.
