### ISSUE TITLE
[Inference] No detections in the output

### ISSUE THREAD

**Issue by NishaniKasineshan** [marcoslucianops/DeepStream-Yolo#452]
I am trying to make inference with the custom yolov5 model tensorrt engine  which i made using [https://github.com/mailrocketsystems/JetsonYolov5](https://github.com/mailrocketsystems/JetsonYolov5). So i tried to pass it customly to deepstream using this repository. My config_infer_primary_yolov5.txt file contains following :
[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
#onnx-file=yolov5s.onnx
model-engine-file=best.engine
#int8-calib-file=calib.table
labelfile-path=labels.txt
batch-size=1
network-mode=0
num-detected-classes=13
interval=0
gie-unique-id=1
process-mode=1
network-type=0
cluster-mode=2
maintain-aspect-ratio=1
symmetric-padding=1
#workspace-size=2000
parse-bbox-func-name=NvDsInferParseYolo
#parse-bbox-func-name=NvDsInferParseYoloCuda
custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
engine-create-func-name=NvDsInferYoloCudaEngineGet

[class-attrs-all]
nms-iou-threshold=0.45
pre-cluster-threshold=0.25
topk=300

and deepstream_app_config.txt as following: 

[application]
enable-perf-measurement=1
perf-measurement-interval-sec=5

[tiled-display]
enable=1
rows=1
columns=1
width=1280
height=720
gpu-id=0
nvbuf-memory-type=0

[source0]
enable=1
type=3
uri=file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4
num-sources=1
gpu-id=0
cudadec-memtype=0

[sink0]
enable=1
type=2
sync=0
gpu-id=0
nvbuf-memory-type=0

[osd]
enable=1
gpu-id=0
border-width=5
text-size=15
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Serif
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0

[streammux]
gpu-id=0
live-source=0
batch-size=1
batched-push-timeout=40000
width=1920
height=1080
enable-padding=0
nvbuf-memory-type=0

[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary_yoloV5.txt

[tests]
file-loop=0
 when i ran deepstream-app -c deepstream_app_config.txt am getting 
Deserialize yoloLayer plugin: (Unnamed Layer* 256) [PluginV2IOExt]
Segmentation Fault [core dumped] error. Let me know if i am missing or need to change something.

**Comment by marcoslucianops** [comment]
You need to convert from ultralytics/yolov5 repo. https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv5.md

**Comment by NishaniKasineshan** [comment]
@marcoslucianops thanks for your help.. but i dont get any detections in the output. Similar to above i used export_yolov5.py to convert my .pt weights to .onnx format. Everything is fine creating the engine file and inference display too but i see no detections.Both configs are same as above where i used onnx file instead.

**Comment by NishaniKasineshan** [comment]
I can get the detections too. Maybe i have messed up with creating the onnx file or due to the latest update in the repository. Thank you.
