### ISSUE TITLE
Introduction of ONNX, questions Yolo::buildYoloNetwork existence

### ISSUE THREAD

**Issue by jstumpin** [marcoslucianops/DeepStream-Yolo#454]
Ever since the [Big update](https://github.com/marcoslucianops/DeepStream-Yolo/commit/07feae9509ffb581fa85f65bec653d1c1d001056) commit, we don't have to build the engine from TensorRT API anymore. Empirically (tested on YOLOv5 & YOLOv8), conversion via **trtexec** yields identical performance & accuracy. Not sure whether or not [Yolo::buildYoloNetwork](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/nvdsinfer_custom_impl_Yolo/yolo.cpp#L270) is a necessary step for DeepStream, but for my use case (non-DeepStream), it offers me the option to build the engine offline and simplify the codebase. 

Big update demands big appreciation! THANKS!

**Comment by marcoslucianops** [comment]
The `Yolo::buildYoloNetwork` is for Darknet models (YOLOv2, YOLOv3 and YOLOv4).

**Comment by jstumpin** [comment]
My bad, that is true, although one could [convert those into ONNX](https://github.com/AlexeyAB/darknet#yolo-v4-in-other-frameworks) as well. In fact, [Yolo::createEngine](https://github.com/marcoslucianops/DeepStream-Yolo/blob/b738644f6e5c8918e9035647209af3814e406c17/nvdsinfer_custom_impl_Yolo/nvdsinfer_yolo_engine.cpp#L132) is also unneeded with the out-of-source creation via **trtexec**.
