### ISSUE TITLE
In Deepstream, where is the NMS?

### ISSUE THREAD

**Issue by relaxtheo** [marcoslucianops/DeepStream-Yolo#456]
I need to customized a yolov5 based model with rotated boundingbox, but where is the NMS in deepstream system? In the bbox parser, we can the candidates that much more than the final results, so it seems there is a deepstream component do the NMS work later. 

Which Deepstream component did this? I hope it is a opensource component and I can customize it. 

Anybody knows this? Thank you

**Comment by marcoslucianops** [comment]
The NMS is the `/opt/nvidia/deepstream/deepstream/sources/libs/nvdsinfer/nvdsinfer_context_impl_output_parsing.cpp` file.

The DeepStream doesn't support the rotated bounding box natively. You need to customize the output and add the bounding boxes using the [NvDsInferTensorMeta](https://docs.nvidia.com/metropolis/deepstream/sdk-api/structNvDsInferTensorMeta.html).

**Comment by relaxtheo** [comment]
Thank you!
