### ISSUE TITLE
change number of classes to detect

### ISSUE THREAD

**Issue by Rajkumarsaswamy** [marcoslucianops/DeepStream-Yolo#46]
i want only "person" to be detected by yolov4

so i modified label.txt and config_infer_primary.txt num-detected-classes=1 

i should also change in nvdsparsebbox_Yolo.cpp right, where is the variable to change?

**Comment by marcoslucianops** [comment]
With my files, you don't need to edit nvdsparsebbox_Yolo.cpp file. But you can't change label.txt file and num-detected-classes from one model, it will not work. By using default YOLOv4 model, you need to use all 80 classes and filter classes by using filter-out-class-ids in config_infer_primay.txt file (see NVIDIA docs: https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinfer.html)
