### ISSUE TITLE
config_tracker_NvDeepSORT.yml dose not work

### ISSUE THREAD

**Issue by khosrooo** [marcoslucianops/DeepStream-Yolo#462]
Hi 
when i add this part  
`ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so

ll-config-file=config_tracker_NvDeepSORT.yml` 
to deepstream_app_config.txt i get this error 

![Screenshot from 2023-09-22 14-37-21](https://github.com/marcoslucianops/DeepStream-Yolo/assets/77171348/e6339bab-ba8e-4887-a6a3-ff7a2ceff69b) 
how to fixe it another tacker.yml are completely correct but deep sort has problem

**Comment by khosrooo** [comment]
can u answer me please

**Comment by marcoslucianops** [comment]
https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvtracker.html#setup-and-usage-of-re-id-model
