### ISSUE TITLE
Triton Server Integration with DeepStream

### ISSUE THREAD

**Issue by Darshcg** [marcoslucianops/DeepStream-Yolo#47]
Hi @marcoslucianops,

Thanks for your Projects. It helped me a lot honestly.
Actually, I have run the Yolov3 model(trained on my Custom Dataset) on Jetson Nano using DeepStream with 4 Cameras. Next, I want to Integrate Triton Server with DeepStream for the same model. 
So, my doubts are:
1.) How to do the Integration, what all I need to do extra?
2.) Can I serve the TRT models with the triton Server integrated with DeepStream?

Thanks

**Comment by marcoslucianops** [comment]
Hi, I have no experience with Triton Server, sorry.

**Comment by Darshcg** [comment]
Hi @marcoslucianops,

Thanks for your reply.

One more doubt is how to run Inference on Two Models using DeepStream. 
I want to run both Yolov3 and face Detection model using DeepStream. What are the steps to be followed?

Face Detection model used: https://github.com/biubug6/Face-Detector-1MB-with-landmark

Thanks,
Darshan

**Comment by Darshcg** [comment]
Looking forward to your reply.

**Comment by marcoslucianops** [comment]
Your Face Detection model is a caffe model or TensorRT converted model?

**Comment by Darshcg** [comment]
Thanks for your reply, it is TensorRT Converted model

**Comment by marcoslucianops** [comment]
If possible, send me your Face Detection model config_infer.txt file.

**Comment by Darshcg** [comment]
Hi @marcoslucianops, below is the config_infer.txt file for my FD Model
```
[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
model-engine-file=model.engine
labelfile-path=sgie/labels.txt
batch-size=1
network-mode=2
num-detected-classes=1
interval=0
gie-unique-id=2
process-mode=2
network-type=0
cluster-mode=2
maintain-aspect-ratio=1
parse-bbox-func-name=NvDsInferParseCustomCenterNetFace
custom-lib-path=/opt/nvidia/deepstream/deepstream-5.1/lib/libnvds_infercustomparser_centernet.so

[class-attrs-all]
pre-cluster-threshold=0.3
threshold=0.7

```

**Comment by marcoslucianops** [comment]
add to [secondary-gie0] in deepstream_app_config.txt and [property] in centerface.txt
```
operate-on-gie-id=1
# class ids you want to operate: 1, 1;2, 2;3;4, 3 etc
operate-on-class-ids=0
```

**Comment by Darshcg** [comment]
Added it, and worked Perfectly!
Thank you for your help

**Comment by Darshcg** [comment]
@marcoslucianops,

When I am inferencing Yolov3 using Deepstream with Triton Server on Jetson nano, the detections are going wrong
![IMG_20210406_105918](https://user-images.githubusercontent.com/48723743/113917104-6e1fd780-97fe-11eb-97ed-5173065a6b17.jpg)

I don't know what's going wrong. But when I am using Local Deepstream, I am getting the correct detections.

Can you please help me to resolve the issue?

Thanks,
Darshan

**Comment by marcoslucianops** [comment]
I think it's a problem/bug on Triton
