### ISSUE TITLE
FPS on jetson xavier NX

### ISSUE THREAD

**Issue by anhtr-nguyn** [marcoslucianops/DeepStream-Yolo#478]
Hi,
I have run YoloV5s and everything has worked. However, the average FPS is just around 21 FPS with default setting (FP32) for camera webcam. Is that normal ? In many example before, the average FPS is about 30 for sample Video.

**Comment by marcoslucianops** [comment]
If the camera is set to 20 FPS, the output will be limited to the its framerate. If you set FP16, you can get more FPS (if the camera isn't limiting it).
