### ISSUE TITLE
Write a application to run yolo in deepstream?

### ISSUE THREAD

**Issue by reddevil1310** [marcoslucianops/DeepStream-Yolo#48]
Hi, I built and run sample-app deepstream. I wonder how to write a application to run yolo in deepstream. Thank you!

**Comment by marcoslucianops** [comment]
Hi, follow the steps: https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/customModels.md

**Comment by reddevil1310** [comment]
thank you!
