### ISSUE TITLE
Wrong custom YoloV5 labels

### ISSUE THREAD

**Issue by flmello** [marcoslucianops/DeepStream-Yolo#482]
When using yolov5s.pt and it's 80 labels from labels.txt, everything get's fine. But when change it to a custom yolov5 model with its corresponding label (it contains just 8 classes), it seems that detection class ID is wrong.

For instance, using yolov5s.onnx, in a scene with a person and a truck, both objects are correctly detected. In labels.txt, person is 1st label, and truck is the 8th label.

But when I change the model to my customized Yolov5 model (epi.onnx), and it's corresponding labels_epi.txt, the same truck is labeled as an earplug (by the way earplug is 8th at the new label_epi.txt, as truck is the 8th label from the original label.txt) . Moreover, a truck shouldn't be detected because the was no truck images at my dataset.

My labels_epi.txt is like this:
```
person
helmet
suit
boot
gloves
mask
glasses
earplug
```

epi.onnx and labels_epi.txt were exported by running `python3 export_yoloV5.py -w epi.pt --opset 12`

These are the changes I made in config files:
At config_infer_primary_yoloV5.txt:
```
[property]
....
#onnx-file=yolov5s.onnx
onnx-file=epi.onnx

#labelfile-path=labels.txt
labelfile-path=labels_epi.txt

#num-detected-classes=80
num-detected-classes=8
....
```

At deepstream_app_config.txt:
```
....
[primary-gie]
....
config-file=config_infer_primary_yoloV5.txt
....
```

So, the truck is an object being labeled with 7 (the 8th element from labels file) which is tagged as earplug. What I am missing? A truck should never be detected in the customized model, this class was not trained.

**Comment by marcoslucianops** [comment]
You need to remove the engine file and generate the new one for the custom model.

**Comment by flmello** [comment]
OK, just in case I removed all engine files and generated a new one, but the problem persists.

Take a look at this extract from label files of yolov5s.pt and my custom model epi.pt
```
yolov5s.pt labels   epi.pt labels
person                    person
bicycle                   helmet
car                       suit
motorcycle                boot
airplane                  gloves
bus                       mask
train                     glasses
truck                     earplug
boat
.....
```
And this is what I obtain when exporting epi.pt to epi.onnx. The DeepStream-Yolo folder now contains just the epi.onnx and label.txt. This is what I get:

![Screenshot from 2023-11-08 12-15-40](https://github.com/marcoslucianops/DeepStream-Yolo/assets/34199582/e8c932eb-9711-4d06-bc5f-4bb8e94733dd)
Clearly, it is using the original weights, the ones from yolov5s. For instance, it detects an object whose class are bicycles ("1") and by label file says it is helmet, or an object belonging to trucks ("7") and my label file says it is an earplug. It look like it is ignoring my training and using just the original weights from yolov5s.

When I trained my custom model (epi.pt) I made a transfer learning from yolov5s. This is what I did for training my custom model (epi.pt): `python3 train.py --img 640 --batch 16 --epochs 1000 --data epi.yaml --weights yolov5s.pt --cache --save-period 10`

And this is what my custom model epi.pt returns when I run: `python3 ~/yolov5/detect.py --weights epi.pt --source tegra.mp4`. 

![vlcsnap-2023-11-08-13h46m56s815](https://github.com/marcoslucianops/DeepStream-Yolo/assets/34199582/67b149d5-d68a-4c4e-ba67-fba0a4944f29)


What's going wrong? Is the export script creating an incomplete onnx file?

**Comment by marcoslucianops** [comment]
It's a very strange case, if you are using the correct onnx model and changing the labels.txt file, it should work without any issues.

**Comment by marcoslucianops** [comment]
As I said, you need to take care about the engine file, because it could run the old file if you don't delete it, even changing the onnx model in the config_infer file.

**Comment by flmello** [comment]
Now I understand what is happening, and this comment is just to register the solution (thanks to @marcoslucianops).

In your config_infer_primary_yolo<whatelse>.txt, the `model-engine-file` always prevails over onnx-file. And in fact, despite my previous ignorance, it makes sense. The .engine file set by `model-engine-file` is built from the `onnx-file`, and the former is the one ran by Deepstream. Therefore, if .engine file exists, its is reasonable to Deepstream that it doesn't have to build it at all, just need to run it. I makes model loading pretty much faster and `onnx-file `is ignored.
