### ISSUE TITLE
Is darknet/yolov4-csp supported?

### ISSUE THREAD

**Issue by vtyw** [marcoslucianops/DeepStream-Yolo#483]
Does this repo support yolov4-csp (scaled yolov4) from [darknet](https://github.com/AlexeyAB/darknet)?

I tried using a yolov4-csp model by following the same instructions as for yolov4. The detections appear fine in DeepStream, but when I check carefully, it's producing the same detections as the original model but with much lower confidence scores (e.g., 0.4 instead of 0.8).

**Comment by marcoslucianops** [comment]
Yes, it is supported, but the TensorRT reduces a bit the accuracy of the converted model.

**Comment by vtyw** [comment]
@marcoslucianops 
The accuracy drop is higher than I would have expected.
I took the pretrained [config](https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-csp.cfg) and [weights](https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-csp.weights) for darknet yolov4-csp and ran inference on a traffic video through darknet as well as through the equivalent deepstream pipeline that outputs detections. Both methods are using FP32 inference. The detections are roughly the same in a frame by frame comparison, except:

* Maybe a third of confidence scores are wildly mismatched (differ by more than 0.05)
* Probably due to the above, the DeepStream inference misses one or more objects (out of an average of ~14) in the majority of frames
* It's not uncommon for two matching objects to have more than 0.02 discrepancy in bounding box coordinates.

Do you know why the models perform so differently after TensorRT conversion? Even a normal FP32->FP16 conversion rarely exceeds 0.02 error in my experience. I thought it might be something to do with TensorRT not having native support for the Mish activation function.

**Comment by vtyw** [comment]
I checked whether I also experience the same inaccuracy with regular yolov4:

Error confidence scores can still exceed 0.05, but bbox coordinates are generally within 0.02 of their original value from darknet inference.

**Comment by marcoslucianops** [comment]
> Do you know why the models perform so differently after TensorRT conversion?

I don't.

> I checked whether I also experience the same inaccuracy with regular yolov4

It occurs with all converted models.
