### ISSUE TITLE
Deepstream V4l2 multi source

### ISSUE THREAD

**Issue by MagnusGabell** [marcoslucianops/DeepStream-Yolo#484]
Hi Marcos!

I know this is the wrong place but I could really use your help. I have reached the end of the road when it comes to the
pipeline for three cameras.

Can you support in helping me with getting deepstream to work with three cameras?
The deepstream-test1-usbcam works, so I understand I need to combine 1 and 3 somehow but I just cant get it to work.

??
I would be in ever debt if you can help me.
I can add the code I've made so far...

kind regards,
Magnus

**Comment by mgabell** [comment]
Here is the source. I get error running the code:
Error: gst-stream-error-quark: Internal data stream error. (1): gstbasesrc.c(3072): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:usb-cam-source-cam1:
streaming stopped, reason not-linked (-1)
[Uploading deepstream_pipeline_test1.zip…]()

**Comment by marcoslucianops** [comment]
You need to add each source pipeline (`v4l2src` -> `capsfilter` -> `videoconvert` -> `nvvideoconvert` -> `capsfilter`) to one `sink` pad (`sink_0`, `sink_1`, `sink_2`) of the `nvstreammux`.
