### ISSUE TITLE
Gen_wts issue with runnung 

### ISSUE THREAD

**Issue by AbdullahGM1** [marcoslucianops/DeepStream-Yolo#486]
Hello,

I have an issue with running gen_wts for YoloV8

It shows me this error:

` File "gen_wts_yoloV8.py", line 5, in <module>
    from ultralytics.yolo.utils.torch_utils import select_device
ModuleNotFoundError: No module named 'ultralytics.yolo'
`

How to solve this issue?

thank you

**Comment by marcoslucianops** [comment]
The gen_wts is outdated. Try to use the new ONNX export method.
