### ISSUE TITLE
Is yolov8 60FPS locked?

### ISSUE THREAD

**Issue by karacanil** [marcoslucianops/DeepStream-Yolo#496]
Hey, 
I was experimenting with different YoloV8 models (yolov8s and yolov8n) by following the instructions given in this repo, and by switching from yolov8s to yolo8n I was expecting FPS to increase and GPU load to decrease but the FPS didn't change at all. Even though yolov8n decreases the GPU load, they both have similar FPS values (around 60). Is this an expected behavior? I'm running my tests on Jetson AGX Orin 64GB Developer Kit. 

I'm new to this area of study so sorry in advance if I'm asking an unnecessary question.

**Comment by KochT22** [comment]
@karacanil, I'm facing the same issue.

**Comment by marcoslucianops** [comment]
This is a GPU decoder limitation. The model can performs better but the GPU can only decode a specific number of frames per second.

**Comment by marcoslucianops** [comment]
Set `[sink] type=1 sync=0` in the `deepstream_app_config.txt` file. With the output windows `type=2`, the FPS is limited to the monitor vsync rate (60 in the most of the cases).
