### ISSUE TITLE
API

### ISSUE THREAD

**Issue by adrianosantospb** [marcoslucianops/DeepStream-Yolo#50]
Hi, great job. I'm trying to deploy a model as an API service and I'd like to know if is it possible to do using your repo?
If yes, could you help me with this? 

Tks!

**Comment by marcoslucianops** [comment]
Vi que você é brasileiro também, não entendi muito bem a finalidade de criar a API.

**Comment by adrianosantospb** [comment]
Oi, Marcos.

Eu tenho um modelo (YoloV3) em producão, e eu estou trabalhando em um projeto para minizar os custos do ambiente de producao. Estou testando o Jetson NX. A minha ideia é criar um servico de deteccao e tracking, como uma API REST, na qual eu envio a imagem para lá, o servico me retorna as informacoes de deteccao para um possivel cliente (similar a essa estrutura aqui https://github.com/adrianosantospb/unifacisa-visao-computacional/tree/master/modulo2/5-publicacao).
