### ISSUE TITLE
Parser make error: utils.h:36:10: fatal error: NvInfer.h: No such file or directory

### ISSUE THREAD

**Issue by taeyoung-yoo** [marcoslucianops/DeepStream-Yolo#505]
Platform: AGX Orin
docker image: nvcr.io/nvidia/deepstream-l4t :6.3-samples
command: CUDA_VER=11.4 make -C nvdsinfer_custom_impl_Yolo
error: utils.h:36:10: fatal error: NvInfer.h: No such file or directory

Is there other lib that use nvinfer1, so I can replace the NvInfer.h
Or if there are someone who face this error, it would be a great help if you share the experience.
Tnx :)

**Comment by taeyoung-yoo** [comment]
solved, install TensorRT and add its path to makefile.

**Comment by colingoodman** [comment]
I am having this exact issue. @taeyoung-yoo could you post the modified Makefile for reference?

**Comment by NoeBrt** [comment]
how do you install tensorRT ?
