### ISSUE TITLE
Way too many bounding boxes, misclassifications

### ISSUE THREAD

**Issue by dmoham1476** [marcoslucianops/DeepStream-Yolo#51]
Hello, I followed your instructions for yolov5. I was able to run till the last step. The only change in my custom model was to change #labels from 80 to 6 and then change labels.txt. My model was fine-tuned on custom data (using ultralytics yolov5 repo). I updated yololayer.h accordingly. The yolov5.engine/wts file also has the same number of labels. However when I run deepstream-app on a test video, I get way too many bounding boxes and labels all over. There is no problem when  I just run yolov5 test without deepstream. Any knobs I may have missed changing for a custom yolov5s model and following the entire set of steps?

**Comment by marcoslucianops** [comment]
Are you using 3.0/3.1 model?

**Comment by dmoham1476** [comment]
Sorry what version is this? You mean for the custom yolov5s mode?

**Comment by dmoham1476** [comment]
Forked the v4.0 branch of ultralytics/yolov5s and then did training on custom dataset

**Comment by marcoslucianops** [comment]
Currently, this repo only works with v3.0 or v3.1 YOLOv5 models

**Comment by dmoham1476** [comment]
I see, so for custom models, other than changing labels.txt and yololayer.h and generating the wts file, is there any other knob that needs tweaking? What specifics changed between 3.0 and 5.0?

**Comment by marcoslucianops** [comment]
The YOLOv5 v4.0 uses differents layers, it needs a new yololayer.cu and yololayer.h files, but I can't work on that for now.

**Comment by SokPhanith** [comment]
I found this Error. You need edit file yolo/nvdsinfer_custom_impl_Yolo/yololayer.h  : 
    static constexpr int CLASS_NUM = 1;
    static constexpr int INPUT_H = 416;
    static constexpr int INPUT_W = 416;
and then,
CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo
Note: 
when you run ./yolov5 -s to build yolov5.engine u must edit tensorrtx/yolov5/yololayer.h
                                                                                     like    yolo/nvdsinfer_custom_impl_Yolo/yololayer.h

**Comment by marcoslucianops** [comment]
I updated the repo for YOLOv5 v5.0, v4.0 and v3.0/3.1

**Comment by dmoham1476** [comment]
Thank you
