### ISSUE TITLE
NvDsInfer Error: NVDSINFER_CONFIG_FAILED

### ISSUE THREAD

**Issue by zcz-lsy** [marcoslucianops/DeepStream-Yolo#523]
my environment is:

1. Jetson Xavier
2. deepstream 6.1.0
3. cuda 11.4

I got thid error:
ERROR: Could not open lib: /home/ubuntu/zcz/StudyRoomDetetection/bin/studyConfig/deepstream_yolov4/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so, error string: /home/ubuntu/zcz/StudyRoomDetetection/bin/studyConfig/deepstream_yolov4/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so: cannot open shared object file: No such file or directory
0:00:01.869691879 10437   0x7f64002d30 ERROR                nvinfer gstnvinfer.cpp:613:gst_nvinfer_logger:<primary-nvinference-engine-0> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1139> [UID = 1]: Could not open custom lib: (null)
0:00:01.869774729 10437   0x7f64002d30 WARN                 nvinfer gstnvinfer.cpp:809:gst_nvinfer_start:<primary-nvinference-engine-0> error: Failed to create NvDsInferContext instance
0:00:01.869808650 10437   0x7f64002d30 WARN                 nvinfer gstnvinfer.cpp:809:gst_nvinfer_start:<primary-nvinference-engine-0> error: Config file path: ./config_infer_primary_yoloV4.txt, NvDsInfer Error: NVDSINFER_CUSTOM_LIB_FAILED
ERROR from element primary-nvinference-engine-0: Failed to create NvDsInferContext instance
Error details: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvinfer/gstnvinfer.cpp(809): gst_nvinfer_start (): /GstPipeline:analysis-pipeline/GstNvInfer:primary-nvinference-engine-0:
Config file path: ./config_infer_primary_yoloV4.txt, NvDsInfer Error: NVDSINFER_CUSTOM_LIB_FAILED

I am relly not understand way I would be happy to any help!

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/issues/524
