### ISSUE TITLE
Regoin of Interest before prediction

### ISSUE THREAD

**Issue by luk8475** [marcoslucianops/DeepStream-Yolo#53]
Hello, I know this is not directly related issue, but have you tried to implement ROI for each RTSP stream before feeding to model?
I've tried to add nvvideoconvert crop attribute after each streamux, but eventually I am getting segmentation faults. Since it doesn't crash instantly only until reaching exact frame my guess is that some frames crashes the app (maybe ROI is out of the crop or something like that).

`Cuda failure: status=700 in CreateTextureObj at line 2919
nvbufsurftransform.cpp:2703: => Cuda failure: status=700 in CreateTextureObj at line 2902
Transformation Failed -2`

Have you tried implementing such functionality in C or Python? I would really appreciate some help on this

**Comment by marcoslucianops** [comment]
I don't know how to do this, sorry.
