### ISSUE TITLE
Trying to add a trace and getting trace results

### ISSUE THREAD

**Issue by liukp557** [marcoslucianops/DeepStream-Yolo#539]
I'm trying to get the tracking results from write_kitti_track_output but I can only get the labels not the ids and bboxes correctly
![b1ed94198ca9884566e2e5d63c5c3f8](https://github.com/marcoslucianops/DeepStream-Yolo/assets/103980130/b755554e-8bc8-4900-8bf4-6d48308b05c7)

**Comment by marcoslucianops** [comment]
This is related to the `deepstream-app`. Please check in the NVIDIA forums.
