### ISSUE TITLE
Custom RTSP output address

### ISSUE THREAD

**Issue by abovzv** [marcoslucianops/DeepStream-Yolo#540]
The default rtsp address is `rtsp://localhost:8554/ds-test`, how should I change it?
For example:
```
[source0]
uri=rtsp:xxx0

[source1]
uri=rtsp:xxx1

....

[sink0]
rtsp-output-address=rtsp:localhost:8554/demo00

[sink1]
rtsp-output-address=rtsp:localhost:8554/demo01
```

Can it be realized?

And I found this [link](https://forums.developer.nvidia.com/t/changing-rtsp-output-name-from-ds-test-to-something-else/140722).

**Comment by jhowrez** [comment]
Hi @boxbox-0427 , 
If you walk through the source files in the sdk as nvidia pointed out in the link and change specifically the `/opt/nvidia/deepstream/deepstream/source/apps/apps-common/src/deepstream_sink_bin.c` file, it's possible to change the path for the gst rtsp server sink. 
To accomplish an individual endpoint per stream you'll need to create a custom field for the NvDsSinkBin struct, parse it and modify the create_udp_bin to use this new field.
