### ISSUE TITLE
Yolov8-OBB implementation

### ISSUE THREAD

**Issue by mikelmujika11** [marcoslucianops/DeepStream-Yolo#544]
Hi,

Last week I noticed that there is a new Yolo model, Yolov8-OBB, that apart from providing de bboxes it also gives the orientation of the bbox. I have tried using it in Deepstream but I am not able to see the rotation. I suppose that I have to change the nvdsparsebbox_Yolo.cpp file but I want to know if it is already implemented or it is on development, not to do the work twice.

**Comment by bhavina18** [comment]
@mikelmujika11 Did you get any solution for this. I am also trying to plot the bounding boxes with their orientation but not able to find a solution.

**Comment by leechaeyoungg** [comment]
> @mikelmujika11 Did you get any solution for this. I am also trying to plot the bounding boxes with their orientation but not able to find a solution.

I am also trying to do the same thing. Did you solve the problem?

**Comment by mikelmujika11** [comment]
Hi, I've been busy with other projects. I will get back to it shortly. I will post any progress.

**Comment by marcoslucianops** [comment]
The OBB isn't supported natively on the DeepStream bbox parser. It requires a custom tensor meta parser. That's why it's not supported on this repo.
