### ISSUE TITLE
YOLOV8 generation engine ERROR

### ISSUE THREAD

**Issue by daihuidai** [marcoslucianops/DeepStream-Yolo#549]
When I execute deepstream-app -c deepstream_app_config.txt times the following error:

![image](https://github.com/marcoslucianops/DeepStream-Yolo/assets/43409147/7538eebb-f6a4-42ef-9afc-d3112d40610a)

When I execute the same configuration and command on jetson, no error is reported. What is the reason for this

**Comment by daihuidai** [comment]
What is the version requirement of gcc, g++ and cmake? I suspect this is the reason because I have updated the version before and it is currently 9.4.0.

**Comment by marcoslucianops** [comment]
You can see on: https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_Installation.html#platform-and-os-compatibility

**Comment by daihuidai** [comment]
ths,I've solved the problem
