### ISSUE TITLE
[TRT]: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.

### ISSUE THREAD

**Issue by frenky-strasak** [marcoslucianops/DeepStream-Yolo#55]
Deepstream: 5.1
CUDA Version: 11.2
Driver Version: 460.32.03
GPU: RTX 3090 24GB

Hi,
everytime when I create new engine model by "deepstream-app" (according **marcoslucianops** guidelines in [repo](https://github.com/marcoslucianops/DeepStream-Yolo#native-tensorrt-conversion)), this warning occurs:
_"**[TRT]: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.**"_

I tried to find a solution, for example [here](https://forums.developer.nvidia.com/t/some-tactics-do-not-have-sufficient-workspace-memory-to-run-increasing-workspace-size-may-increase-performance-please-check-verbose-output/126877) they speak about "workspace-size" in the "config_infer_primary.txt" file. I tried several values (workspace-size=8000, workspace-size=24000) but it does not work for yolov4-tiny and rest of the models. 

Do you have any idea how to remove this warning?

**Comment by marcoslucianops** [comment]
See https://github.com/marcoslucianops/DeepStream-Yolo/issues/28

**Comment by frenky-strasak** [comment]
Thank you very much!

However, if I set **kWorkSpaceSize**" variable to biger value than **2047 * 1024 * 1024** it gives me "integer overflow" error since maximum integer number is 2147483647.

**Comment by frenky-strasak** [comment]
ok, **long** works: **2048L * 1024L * 1024L**
Thank you!
