### ISSUE TITLE
INT8 calibration

### ISSUE THREAD

**Issue by shancaidazf** [marcoslucianops/DeepStream-Yolo#552]
hi ,sir .   I am doing the work about INT8 calibration.   things  seem to be all right except when i set export OPENCV=1 and run the command: make -C nvdsinfer_custom_impl_Yolo clean && make -C nvdsinfer_custom_impl_Yolo.
The error  is here
![image](https://github.com/marcoslucianops/DeepStream-Yolo/assets/3223579/7b4349f7-d8d1-46d0-9d02-9e1b78aaef91)

**Comment by marcoslucianops** [comment]
For docker images, you need to run `/opt/nvidia/deepstream/deepstream/user_additional_install.sh` to install the dependencies.
