### ISSUE TITLE
Deepstream-app titled-display with messed bboxes from different channels under YoloV5-v4 model

### ISSUE THREAD

**Issue by edge-ai4cv** [marcoslucianops/DeepStream-Yolo#56]
Hello,

When added more than one video source in the deepstream-app-config.txt file and ran the app, I found in addition to the right bboxex and labels, I saw ones from other channels flickered from time to time. Did I miss some configuration or it's a bug?

Thanks,

**Comment by marcoslucianops** [comment]
Hi,

Please attach your deepstream_app_config.txt and config_infer_primary.txt files

**Comment by edge-ai4cv** [comment]
Hi,

Attached please find two config files and one image I grabbed to demonstrate the bbox issue. 

[config_infer_primary.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/6524940/config_infer_primary.txt)
[deepstream_app_config.txt](https://github.com/marcoslucianops/DeepStream-Yolo/files/6524941/deepstream_app_config.txt)
![Screenshot](https://user-images.githubusercontent.com/80353459/119194637-61bfa900-ba51-11eb-81c2-2c02d61944c1.png)

**Comment by marcoslucianops** [comment]
Try use ```type=3``` in [source0] section and ```batch-size=4``` (= number of sources) and ```live-source=1``` in [streammux] section in deepstream_app_config.txt file.
You can comment ```nms-iou-threshold=0.5``` line in config_infer_primary, it isn't used in current code.

**Comment by edge-ai4cv** [comment]
Thank you for your prompt reply! I changed the settings according to your instruction and the issue was solved.  Great work!
I found the key setting is the batch-size in the [streammux] group, which should be equal to the number of video sources.
