### ISSUE TITLE
Change source to USB camera 

### ISSUE THREAD

**Issue by maoweinasa** [marcoslucianops/DeepStream-Yolo#571]
How to change source filename to usb camera style ？

**Comment by marcoslucianops** [comment]
Use

```
[source0]
enable=1
type=1
camera-width=640
camera-height=480
camera-fps-n=30
camera-fps-d=1
camera-v4l2-dev-node=0
```

and set `live-source=1` in `[streammux]` property.

More info: https://docs.nvidia.com/metropolis/deepstream/7.0/dev-guide/text/DS_ref_app_deepstream.html
