### ISSUE TITLE
Deepstream 7.1 not working

### ISSUE THREAD

**Issue by mr-mainak** [marcoslucianops/DeepStream-Yolo#576]
@marcoslucianops Hi.
I'm receiving the following error while compiling in DS 7.1, CUDA=12.6, Trt=10.3.0.26
```
yolo.cpp: In member function ‘nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*)’:
yolo.cpp:207:44: error: ‘class nvinfer1::IBuilder’ has no member named ‘buildEngineWithConfig’
  207 |   nvinfer1::ICudaEngine* engine = builder->buildEngineWithConfig(*network, *config);
      |                                            ^~~~~~~~~~~~~~~~~~~~~
yolo.cpp: In member function ‘NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&)’:
yolo.cpp:468:36: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations]
  468 |     nvinfer1::IPluginV2DynamicExt* yoloPlugin = new YoloLayer(m_InputW, m_InputH, m_NumClasses, m_NewCoords, m_YoloTensors,
      |                                    ^~~~~~~~~~
/usr/include/x86_64-linux-gnu/NvInferRuntime.h:403:22: note: declared here
  403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext
      |                      ^~~~~~~~~~~~~~~~~~~
make: *** [Makefile:81: yolo.o] Error 1
make: Leaving directory '/home/eegrab/c++/deepstream/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'
```
Any help is highly appreciated

**Comment by marcoslucianops** [comment]
I will add support for DeepStream 7.1 this week.

**Comment by Hammer-888** [comment]
> I will add support for DeepStream 7.1 this week.

waiting。。。。

**Comment by Terencesun** [comment]
> I will add support for DeepStream 7.1 this week.

looking forward to the latest version 👍

**Comment by Heiheicxx** [comment]
waiting....

**Comment by fengwj2003** [comment]
waiting...

**Comment by Heiheicxx** [comment]
来信已收到^-^谢谢你的来信，保持联系

**Comment by siz0001** [comment]
waiting haha

**Comment by Aspirinkb** [comment]
Hi there, any updates?

**Comment by marcoslucianops** [comment]
Added support for DeepStream 7.1

**Comment by Heiheicxx** [comment]
来信已收到^-^谢谢你的来信，保持联系

**Comment by rosklyar** [comment]
Unfortunately it is not working with CUDA 12.6.

HEAD is now at b451b03 DeepStream 7.1 + Fixes + New model output format

--------------------------------------------------
Compilation output:
root@jetson-desktop:/opt/nvidia/deepstream/deepstream/sources/DeepStream-Yolo# make -C nvdsinfer_custom_impl_Yolo
make: Entering directory '/opt/nvidia/deepstream/deepstream-7.1/sources/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'
g++ -c  -o nvdsinfer_yolo_engine.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include nvdsinfer_yolo_engine.cpp
g++ -c  -o nvdsparsebbox_Yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include nvdsparsebbox_Yolo.cpp
g++ -c  -o utils.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include utils.cpp
g++ -c  -o yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include yolo.cpp
In file included from yolo.cpp:29:
yoloPlugins.h:53:59: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations]
   53 |     nvinfer1::IPluginV2DynamicExt* clone() const noexcept override;
      |                                                           ^~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22,
                 from /usr/include/aarch64-linux-gnu/NvOnnxParser.h:26,
                 from yolo.cpp:26:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here
  403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext
      |                      ^~~~~~~~~~~~~~~~~~~
In file included from yolo.cpp:29:
yoloPlugins.h:124:9: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations]
  124 |         override {
      |         ^~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22,
                 from /usr/include/aarch64-linux-gnu/NvOnnxParser.h:26,
                 from yolo.cpp:26:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here
  403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext
      |                      ^~~~~~~~~~~~~~~~~~~
In file included from yolo.cpp:29:
yoloPlugins.h:130:18: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations]
  130 |         noexcept override {
      |                  ^~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22,
                 from /usr/include/aarch64-linux-gnu/NvOnnxParser.h:26,
                 from yolo.cpp:26:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here
  403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext
      |                      ^~~~~~~~~~~~~~~~~~~
yolo.cpp: In member function ‘NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&)’:
yolo.cpp:476:36: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations]
  476 |     nvinfer1::IPluginV2DynamicExt* yoloPlugin = new YoloLayer(m_InputW, m_InputH, m_NumClasses, m_NewCoords,
      |                                    ^~~~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22,
                 from /usr/include/aarch64-linux-gnu/NvOnnxParser.h:26,
                 from yolo.cpp:26:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here
  403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext
      |                      ^~~~~~~~~~~~~~~~~~~
g++ -c  -o yoloPlugins.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include yoloPlugins.cpp
In file included from yoloPlugins.cpp:26:
yoloPlugins.h:53:59: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations]
   53 |     nvinfer1::IPluginV2DynamicExt* clone() const noexcept override;
      |                                                           ^~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22,
                 from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:21,
                 from yolo.h:29,
                 from yoloPlugins.h:31,
                 from yoloPlugins.cpp:26:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here
  403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext
      |                      ^~~~~~~~~~~~~~~~~~~
In file included from yoloPlugins.cpp:26:
yoloPlugins.h:124:9: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations]
  124 |         override {
      |         ^~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22,
                 from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:21,
                 from yolo.h:29,
                 from yoloPlugins.h:31,
                 from yoloPlugins.cpp:26:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here
  403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext
      |                      ^~~~~~~~~~~~~~~~~~~
In file included from yoloPlugins.cpp:26:
yoloPlugins.h:130:18: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations]
  130 |         noexcept override {
      |                  ^~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22,
                 from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:21,
                 from yolo.h:29,
                 from yoloPlugins.h:31,
                 from yoloPlugins.cpp:26:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here
  403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext
      |                      ^~~~~~~~~~~~~~~~~~~
yoloPlugins.cpp:106:26: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations]
  106 | YoloLayer::clone() const noexcept
      |                          ^~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22,
                 from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:21,
                 from yolo.h:29,
                 from yoloPlugins.h:31,
                 from yoloPlugins.cpp:26:
/usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here
  403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext
      |                      ^~~~~~~~~~~~~~~~~~~
g++ -c  -o layers/activation_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/activation_layer.cpp
g++ -c  -o layers/batchnorm_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/batchnorm_layer.cpp
g++ -c  -o layers/channels_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/channels_layer.cpp
g++ -c  -o layers/convolutional_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/convolutional_layer.cpp
g++ -c  -o layers/deconvolutional_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/deconvolutional_layer.cpp
g++ -c  -o layers/implicit_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/implicit_layer.cpp
g++ -c  -o layers/pooling_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/pooling_layer.cpp
g++ -c  -o layers/reorg_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/reorg_layer.cpp
g++ -c  -o layers/route_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/route_layer.cpp
g++ -c  -o layers/sam_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/sam_layer.cpp
g++ -c  -o layers/shortcut_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/shortcut_layer.cpp
g++ -c  -o layers/slice_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/slice_layer.cpp
g++ -c  -o layers/upsample_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/upsample_layer.cpp
/usr/local/cuda-12.6/bin/nvcc -c -o nvdsparsebbox_Yolo_cuda.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include nvdsparsebbox_Yolo_cuda.cu
/usr/local/cuda-12.6/bin/nvcc -c -o yoloForward.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include yoloForward.cu
/usr/local/cuda-12.6/bin/nvcc -c -o yoloForward_nc.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include yoloForward_nc.cu
/usr/local/cuda-12.6/bin/nvcc -c -o yoloForward_v2.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include yoloForward_v2.cu
g++ -o libnvdsinfer_custom_impl_Yolo.so  nvdsinfer_yolo_engine.o nvdsparsebbox_Yolo.o utils.o yolo.o yoloPlugins.o layers/activation_layer.o layers/batchnorm_layer.o layers/channels_layer.o layers/convolutional_layer.o layers/deconvolutional_layer.o layers/implicit_layer.o layers/pooling_layer.o layers/reorg_layer.o layers/route_layer.o layers/sam_layer.o layers/shortcut_layer.o layers/slice_layer.o layers/upsample_layer.o nvdsparsebbox_Yolo_cuda.o yoloForward.o yoloForward_nc.o yoloForward_v2.o -shared -Wl,--start-group -lnvinfer_plugin -lnvinfer -lnvonnxparser -L/usr/local/cuda-12.6/lib64 -lcudart -lcublas -lstdc++fs -Wl,--end-group
make: Leaving directory '/opt/nvidia/deepstream/deepstream-7.1/sources/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'

-----------------------------
But the result of execution is:
Class_id=1, label=car, confidence=2.0, bbox=[left=1.0, top=0.0, width=1.0, height=1.0]
Detection received: [id:1, confidence:2.0]
Segmentation fault (core dumped)

**Comment by mr-mainak** [comment]
> Unfortunately it is not working with CUDA 12.6.
> 
> HEAD is now at [b451b03](https://github.com/marcoslucianops/DeepStream-Yolo/commit/b451b036b2fa9f8b92cb13bb5f4585f8883beec8) DeepStream 7.1 + Fixes + New model output format
> 
> Compilation output: root@jetson-desktop:/opt/nvidia/deepstream/deepstream/sources/DeepStream-Yolo# make -C nvdsinfer_custom_impl_Yolo make: Entering directory '/opt/nvidia/deepstream/deepstream-7.1/sources/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo' g++ -c -o nvdsinfer_yolo_engine.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include nvdsinfer_yolo_engine.cpp g++ -c -o nvdsparsebbox_Yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include nvdsparsebbox_Yolo.cpp g++ -c -o utils.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include utils.cpp g++ -c -o yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include yolo.cpp In file included from yolo.cpp:29: yoloPlugins.h:53:59: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations] 53 | nvinfer1::IPluginV2DynamicExt* clone() const noexcept override; | ^~~~~~~~ In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22, from /usr/include/aarch64-linux-gnu/NvOnnxParser.h:26, from yolo.cpp:26: /usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here 403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext | ^~~~~~~~~~~~~~~~~~~ In file included from yolo.cpp:29: yoloPlugins.h:124:9: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations] 124 | override { | ^~~~~~~~ In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22, from /usr/include/aarch64-linux-gnu/NvOnnxParser.h:26, from yolo.cpp:26: /usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here 403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext | ^~~~~~~~~~~~~~~~~~~ In file included from yolo.cpp:29: yoloPlugins.h:130:18: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations] 130 | noexcept override { | ^~~~~~~~ In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22, from /usr/include/aarch64-linux-gnu/NvOnnxParser.h:26, from yolo.cpp:26: /usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here 403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext | ^~~~~~~~~~~~~~~~~~~ yolo.cpp: In member function ‘NvDsInferStatus Yolo::buildYoloNetwork(std::vector&, nvinfer1::INetworkDefinition&)’: yolo.cpp:476:36: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations] 476 | nvinfer1::IPluginV2DynamicExt* yoloPlugin = new YoloLayer(m_InputW, m_InputH, m_NumClasses, m_NewCoords, | ^~~~~~~~~~ In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22, from /usr/include/aarch64-linux-gnu/NvOnnxParser.h:26, from yolo.cpp:26: /usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here 403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext | ^~~~~~~~~~~~~~~~~~~ g++ -c -o yoloPlugins.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include yoloPlugins.cpp In file included from yoloPlugins.cpp:26: yoloPlugins.h:53:59: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations] 53 | nvinfer1::IPluginV2DynamicExt* clone() const noexcept override; | ^~~~~~~~ In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22, from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:21, from yolo.h:29, from yoloPlugins.h:31, from yoloPlugins.cpp:26: /usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here 403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext | ^~~~~~~~~~~~~~~~~~~ In file included from yoloPlugins.cpp:26: yoloPlugins.h:124:9: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations] 124 | override { | ^~~~~~~~ In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22, from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:21, from yolo.h:29, from yoloPlugins.h:31, from yoloPlugins.cpp:26: /usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here 403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext | ^~~~~~~~~~~~~~~~~~~ In file included from yoloPlugins.cpp:26: yoloPlugins.h:130:18: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations] 130 | noexcept override { | ^~~~~~~~ In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22, from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:21, from yolo.h:29, from yoloPlugins.h:31, from yoloPlugins.cpp:26: /usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here 403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext | ^~~~~~~~~~~~~~~~~~~ yoloPlugins.cpp:106:26: warning: ‘IPluginV2DynamicExt’ is deprecated [-Wdeprecated-declarations] 106 | YoloLayer::clone() const noexcept | ^~~~~~~~ In file included from /usr/include/aarch64-linux-gnu/NvInfer.h:22, from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:21, from yolo.h:29, from yoloPlugins.h:31, from yoloPlugins.cpp:26: /usr/include/aarch64-linux-gnu/NvInferRuntime.h:403:22: note: declared here 403 | class TRT_DEPRECATED IPluginV2DynamicExt : public nvinfer1::IPluginV2Ext | ^~~~~~~~~~~~~~~~~~~ g++ -c -o layers/activation_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/activation_layer.cpp g++ -c -o layers/batchnorm_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/batchnorm_layer.cpp g++ -c -o layers/channels_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/channels_layer.cpp g++ -c -o layers/convolutional_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/convolutional_layer.cpp g++ -c -o layers/deconvolutional_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/deconvolutional_layer.cpp g++ -c -o layers/implicit_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/implicit_layer.cpp g++ -c -o layers/pooling_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/pooling_layer.cpp g++ -c -o layers/reorg_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/reorg_layer.cpp g++ -c -o layers/route_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/route_layer.cpp g++ -c -o layers/sam_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/sam_layer.cpp g++ -c -o layers/shortcut_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/shortcut_layer.cpp g++ -c -o layers/slice_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/slice_layer.cpp g++ -c -o layers/upsample_layer.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include layers/upsample_layer.cpp /usr/local/cuda-12.6/bin/nvcc -c -o nvdsparsebbox_Yolo_cuda.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include nvdsparsebbox_Yolo_cuda.cu /usr/local/cuda-12.6/bin/nvcc -c -o yoloForward.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include yoloForward.cu /usr/local/cuda-12.6/bin/nvcc -c -o yoloForward_nc.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include yoloForward_nc.cu /usr/local/cuda-12.6/bin/nvcc -c -o yoloForward_v2.o --compiler-options '-fPIC' -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-12.6/include yoloForward_v2.cu g++ -o libnvdsinfer_custom_impl_Yolo.so nvdsinfer_yolo_engine.o nvdsparsebbox_Yolo.o utils.o yolo.o yoloPlugins.o layers/activation_layer.o layers/batchnorm_layer.o layers/channels_layer.o layers/convolutional_layer.o layers/deconvolutional_layer.o layers/implicit_layer.o layers/pooling_layer.o layers/reorg_layer.o layers/route_layer.o layers/sam_layer.o layers/shortcut_layer.o layers/slice_layer.o layers/upsample_layer.o nvdsparsebbox_Yolo_cuda.o yoloForward.o yoloForward_nc.o yoloForward_v2.o -shared -Wl,--start-group -lnvinfer_plugin -lnvinfer -lnvonnxparser -L/usr/local/cuda-12.6/lib64 -lcudart -lcublas -lstdc++fs -Wl,--end-group make: Leaving directory '/opt/nvidia/deepstream/deepstream-7.1/sources/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo'
> 
> But the result of execution is: Class_id=1, label=car, confidence=2.0, bbox=[left=1.0, top=0.0, width=1.0, height=1.0] Detection received: [id:1, confidence:2.0] Segmentation fault (core dumped)

I'm also facing the same issue. Any suggestion @marcoslucianops

**Comment by Heiheicxx** [comment]
来信已收到^-^谢谢你的来信，保持联系

**Comment by marcoslucianops** [comment]
Please export the onnx file again with the new files from the repo.

**Comment by marcoslucianops** [comment]
Also use the updated files for inference.
