### ISSUE TITLE
cannot run get_wts_yolov8.py

### ISSUE THREAD

**Issue by irsyad565** [marcoslucianops/DeepStream-Yolo#577]
/usr/bin/python3.10 /home/dyna/DeepStream-Yolo/utils/gen_wts_yoloV8.py --weights /home/dyna/Downloads/best.pt --size 640
Error in cpuinfo: prctl(PR_SVE_GET_VL) failed
Traceback (most recent call last):
  File "/home/dyna/DeepStream-Yolo/utils/gen_wts_yoloV8.py", line 5, in <module>
    from ultralytics.yolo.utils.torch_utils import select_device
ModuleNotFoundError: No module named 'ultralytics.yolo'

hi, i cant run the code
Name: ultralytics
Version: 8.3.19

thank you for the help

**Comment by marcoslucianops** [comment]
The `get_wts_yolov8.py` exporter isn't supported anymore. Please use the [utils/export_yoloV8.py](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/utils/export_yoloV8.py).

**Comment by irsyad565** [comment]
hi i have done export best.pt to best.onnx but 

/opt/nvidia/deepstream/deepstream-7.0/sources/apps/sample_apps/deepstream-nvdsanalytics-test/deepstream-app -c /opt/nvidia/deepstream/deepstream-7.0/sources/apps/sample_apps/deepstream-nvdsanalytics-test/deepstream_app_config.txt

(deepstream-app:8593): GLib-GObject-WARNING **: 08:54:44.163: g_object_set_is_valid_property: object class 'nvv4l2h264enc' has no property named 'gpu-id'

 *** DeepStream: Launched RTSP Streaming at rtsp://localhost:8554/ds-test ***

NVDSANALYTICS_CFG_PARSER: Group 'message-broker' ignored
Opening in BLOCKING MODE 
gstnvtracker: Loading low-level lib at /opt/nvidia/deepstream/deepstream-7.0/lib/libnvds_nvmultiobjecttracker.so
[NvMultiObjectTracker] Initialized
Setting min object dimensions as 16x16 instead of 1x1 to support VIC compute mode.
0:00:00.700059504  8593 0xaaaadbaac260 INFO                 nvinfer gstnvinfer.cpp:682:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:2109> [UID = 1]: Trying to create engine from model files
WARNING: [TRT]: onnx2trt_utils.cpp:372: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
WARNING: [TRT]: onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
WARNING: [TRT]: Tensor DataType is determined at build time for tensors not marked as input or output.

Building the TensorRT Engine

Building complete

WARNING: Serialize engine failed because of file path: /opt/nvidia/deepstream/deepstream-7.0/sources/apps/sample_apps/deepstream-nvdsanalytics-test/model_b4_gpu0_fp32.engine opened error
0:04:49.579314992  8593 0xaaaadbaac260 WARN                 nvinfer gstnvinfer.cpp:679:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:2136> [UID = 1]: failed to serialize cude engine to file: /opt/nvidia/deepstream/deepstream-7.0/sources/apps/sample_apps/deepstream-nvdsanalytics-test/model_b4_gpu0_fp32.engine
WARNING: [TRT]: The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
INFO: [Implicit Engine Info]: layers num: 4
0   INPUT  kFLOAT input           3x640x640       
1   OUTPUT kFLOAT boxes           8400x4          
2   OUTPUT kFLOAT scores          8400x1          
3   OUTPUT kFLOAT classes         8400x1          

0:04:49.585098170  8593 0xaaaadbaac260 WARN                 nvinfer gstnvinfer.cpp:679:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::checkBackendParams() <nvdsinfer_context_impl.cpp:2027> [UID = 1]: Backend has maxBatchSize 1 whereas 4 has been requested
0:04:49.585130586  8593 0xaaaadbaac260 ERROR                nvinfer gstnvinfer.cpp:676:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:2159> [UID = 1]: deserialized backend context :/opt/nvidia/deepstream/deepstream-7.0/sources/apps/sample_apps/deepstream-nvdsanalytics-test/model_b4_gpu0_fp32.engine failed to match config params
0:04:50.030136826  8593 0xaaaadbaac260 ERROR                nvinfer gstnvinfer.cpp:676:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2215> [UID = 1]: build backend context failed
0:04:50.030210715  8593 0xaaaadbaac260 ERROR                nvinfer gstnvinfer.cpp:676:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1352> [UID = 1]: generate backend failed, check config file settings
0:04:50.030287037  8593 0xaaaadbaac260 WARN                 nvinfer gstnvinfer.cpp:912:gst_nvinfer_start:<primary_gie> error: Failed to create NvDsInferContext instance
0:04:50.030303869  8593 0xaaaadbaac260 WARN                 nvinfer gstnvinfer.cpp:912:gst_nvinfer_start:<primary_gie> error: Config file path: /home/dyna/DeepStream-Yolo/config_infer_primary_yoloV8.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
[NvMultiObjectTracker] De-initialized
** ERROR: <main:674>: Failed to set pipeline to PAUSED
Quitting
nvstreammux: Successfully handled EOS for source_id=0
nvstreammux: Successfully handled EOS for source_id=1
nvstreammux: Successfully handled EOS for source_id=2
nvstreammux: Successfully handled EOS for source_id=3
ERROR from primary_gie: Failed to create NvDsInferContext instance
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvinfer/gstnvinfer.cpp(912): gst_nvinfer_start (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
Config file path: /home/dyna/DeepStream-Yolo/config_infer_primary_yoloV8.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
App run failed


here is the config_infer_primary_yolov8.txt

[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
onnx-file=/home/dyna/DeepStream-Yolo/utils/best.onnx
#model-engine-file=model_b1_gpu0_fp32.engine
#int8-calib-file=calib.table
labelfile-path=labels.txt
batch-size=1
network-mode=0
num-detected-classes=80
interval=0
gie-unique-id=1
process-mode=1
network-type=0
cluster-mode=2
maintain-aspect-ratio=1
symmetric-padding=1
#workspace-size=2000
parse-bbox-func-name=NvDsInferParseYolo
#parse-bbox-func-name=NvDsInferParseYoloCuda
custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
engine-create-func-name=NvDsInferYoloCudaEngineGet

[class-attrs-all]
nms-iou-threshold=0.45
pre-cluster-threshold=0.25
topk=300

thank you for the help

**Comment by marcoslucianops** [comment]
You are using static batch-size 4 on the onnx model and building the engine with batch-size=1. You need to use dynamic batch-size or set the same batch on the ONNX file when exporting.
