### ISSUE TITLE
Preprocessing frame before Pgie inference

### ISSUE THREAD

**Issue by Wassssim** [marcoslucianops/DeepStream-Yolo#58]
Hello!

I'm working on an ALPR project with Yolov4  on the Jetson Nano, and I want to add a preprocessing step (Histogram equalization - CLAHE) before passing the frame to the PGIE, but idk where to add it without messing up the performence?

Btw thank you for this repo, it is extreamly helpful!

**Comment by marcoslucianops** [comment]
Hi,

I think it's not possible to add it without losing a lot of performance in Nano.
You need to create a model to directly recognize it.

**Comment by Wassssim** [comment]
Yes I already trained a model on preprocessed images, but I'm talking about the inference, I have to apply the preprocessing step somewhere in the deepstream pipeline bofore the PGIE, but I don't know how.

**Comment by marcoslucianops** [comment]
You need to use gst-dsexample but it will decrease the board performance.

**Comment by Wassssim** [comment]
Another thing, the model I am using for character recognition is yolov4 (it works really well), but it's a detector, is there a way to make yolov4 act as if it's a classifier? (change the custom parser function maybe?)

**Comment by marcoslucianops** [comment]
I think you don't. You need to create a classifier model to use as classifier.

**Comment by Wassssim** [comment]
Is it possible to alter Yolov4 architecture so that it behaves like a classifier? Maybe just changing the output layer?

**Comment by marcoslucianops** [comment]
I don't know, I use yolo only as detector.

**Comment by Wassssim** [comment]
I tested it, it is possible to use yolov4 as a classifier, all you have to do is edit the `nvdsparsebbox_Yolo.cpp`
