### ISSUE TITLE
Problems exporting non-square model with utils/export_yoloV8.py

### ISSUE THREAD

**Issue by blafasel42** [marcoslucianops/DeepStream-Yolo#588]
I am trying to build a 800x448 model since my camera is 16:9.
I understand I can do this usually with YoloV8, and also the onnx export of ultralytics allows for imgsz=448,800 setting, the resulting onnx model is then prepared for an input size of H=448 and W=800.
But DeepStream-Yolo will not work with the Ultralytice-exported ONNX model. I have to use utils/export_yoloV8.py.
I see there is a --size parameter which says you can give [H, W] as size parameters for the export.
But if i call with `python3 utils/export_yoloV8.py -w <modelpath>.pt -s 448 -s 800 --dynamic --simplify` it generates a ONNX model with 800x800 input size (which is way too big to perform well). 
Am i doing something wrong or is this not really supported?

**Comment by marcoslucianops** [comment]
The command is

`python3 export_yoloV8.py -w <modelpath>.pt -s 448 800 --dynamic --simplify`

**Comment by blafasel42** [comment]
ah, thanks. i tried --size="448 800" but it did not work. Also --size=448 800 does not work. Python argparse magic i guess... Thanks for the answer. Much appreciated!
