### ISSUE TITLE
Use deep stream for custom applications

### ISSUE THREAD

**Issue by PythonImageDeveloper** [marcoslucianops/DeepStream-Yolo#6]
Hi @marcoslucianops 
In your opinion, Is it possible to use deep stream for custom app? for example : face recognition
That's mean I want to use decode multi-stream and one detector of deep stream for face detection, but for face recognition, the deep stream doesn't support any model for this task, I want to know How I can integrated the face rec system to deep steam? I want to get outputs like counting and coordinates of deep stream, Is it possible?

**Comment by marcoslucianops** [comment]
> In your opinion, Is it possible to use deep stream for custom app? for example : face recognition

If you use some supported model, it's possible.

> I want to get outputs like counting and coordinates of deep stream, Is it possible?

Yes, it's possible.
