### ISSUE TITLE
Issue with multiple yolov5 models in deepstream

### ISSUE THREAD

**Issue by Samjith888** [marcoslucianops/DeepStream-Yolo#60]
We can only use models which are designed to have the same batch size, same input width/height. Seems this is because we can have only one libmyplugins.so in the environment variable LD_PRELOAD.

This will be a feature request to your repo , please help to resolve this issue

**Comment by marcoslucianops** [comment]
For now, you need to edit the tensorrtx configs and yololayer.h before generate the engine.
In future, I will create a full parser for YOLOv5 from wts.

**Comment by Samjith888** [comment]
Which lines should be edit for this ? Also you can tag this as an feature request

**Comment by marcoslucianops** [comment]
In tensorrtx/yolov5/yolov5.cpp
```
#define USE_FP16  // set USE_INT8 or USE_FP16 or USE_FP32
#define BATCH_SIZE 1
```

In tensorrtx/yolov5/yololayer.h and DeepStream-Yolo/external/yolov5-5.0/nvdsinfer_custom_impl_Yolo/yololayer.h
```
static constexpr int CLASS_NUM = 80;
static constexpr int INPUT_H = 640;
static constexpr int INPUT_W = 640;
```

You need to recompile all files and regenerate engine after change these lines.

**Comment by Samjith888** [comment]
This is the configuring yolov5.cpp and yololayer.h for generating .wts file from pytorch weight !
I meant , i have trained two yolov5 models ,

**1st model :**    
-  BATCH_SIZE  = 1
-  CLASS_NUM  = 1
-  INPUT_H        = 1020
-  INPUT_W       = 1020

**2nd model :**

-  BATCH_SIZE  = 1
-  CLASS_NUM  = 1
-  INPUT_H        = 1020
-  INPUT_W       = 1020
I would like to integrate above two models into Deepstream. If i use convertion into TRT for above two models then it will generate model1.wts and model2.wts and two libmyplugins.so files too. Both of this models can't be run at a time in deepstream. How can we solve this !!

**Comment by marcoslucianops** [comment]
You don't need use libmyplugins.so, just compile the new files for YOLOv5 in this repo editing the yololayer.h.

See this link https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/multipleInferences.md and https://github.com/marcoslucianops/DeepStream-Yolo/tree/master/examples/multiple_inferences

You need to do something like this to run two inferences at same time.

1. Replace nvdsinfer_custom_impl_Yolo folder in pgie and sgie1 folders to nvdsinfer_custom_impl_Yolo folder available in YOLOv5 folder.

2. Change these lines in yololayer.cu in sgie1 folder (only SGIE)

lines 164 to:
```
    const char* YoloLayerPlugin::getPluginVersion() const
    {
        return "2";
    }
```

line 279 to:
```
    const char* YoloPluginCreator::getPluginVersion() const
    {
        return "2";
    }
```

3. Edit yololayer.h based in each model and compile nvdsinfer_custom_impl_Yolo.

4. Edit config_infer and deepstream_app_config files to your model (based in YOLOv5 files comparing with multipleInferences files).

**Comment by Xinxinatg** [comment]
@Samjith888 Hi I have come accross the same issue as you. I am wondering if you are trying to use two models as pgie and sgie as in sgie will only work after the results of pgie meet certain requirement.

**Comment by marcoslucianops** [comment]
@Xinxinatg https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/multipleGIEs.md
