### ISSUE TITLE
How build my custom TRT enigne ? 

### ISSUE THREAD

**Issue by MrGolden1** [marcoslucianops/DeepStream-Yolo#68]
Hi, first thanks for your great job and sharing it.
I'm new to this framework and i'm confused about some point.

I trained my model with [darknet](https://github.com/AlexeyAB/darknet) which has only one object class. My network is yolov4-tiny with dimensions 320*320. Platform which i'm working on is jetson nano.
I followed your [instructions](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/customModels.md) and compiled it with `CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo`. 
Here my question:
The engine that is made (`model_b1_gpu0_fp16.engine`) is tensorRT optimized engine? or do i need to take another steps to convert it to tensorRT?

**Comment by marcoslucianops** [comment]
The model_b1_gpu0_fp16.engine is the TensorRT optimized engine for DeepStream.

**Comment by MrGolden1** [comment]
> The model_b1_gpu0_fp16.engine is the TensorRT optimized engine for DeepStream.

Thanks a lot !
