### ISSUE TITLE
YOLOv5 Accuracy dropped

### ISSUE THREAD

**Issue by avn3r** [marcoslucianops/DeepStream-Yolo#70]
Hello @marcoslucianops 

Thanks for your work. I see that on your README you show results on GTX hardware and there seems to be a significant drop in mAP when converting models to TRT. I was able to successfully follow your repo to get both YOLOv4 and YOLOv5 models but the YOLOv5 models are showing very poor accuracy results and I get no errors in the process. I'm able to test my models with deepstream and everything, but similar to your numbers YOLOv5 TRT models performing much worst than their PyTorch equivalents. I tried with both FP16 and INT8 and no luck with either.

Any suggestions as to what can be done to ensure converted TRT models give mAP closer to their PyTorch models?

I also saw you recently updated that section you were comparing models, are you able to get YOLOv5 TRT models to produce the same output as YOLOv5 PyTorch models?

**Comment by marcoslucianops** [comment]
The YOLOv5 conversion isn't made by me, I used the TensorRTX to convert and use it in DeepStream. The YOLOv4 (my conversion method)  works good with TensorRT, but I can't guarantee the YOLOv5 accuracy. For that YOLOv5 support, please refer to TensorRTX repo.

**Comment by avn3r** [comment]
Thanks @marcoslucianops. I'm aware, I was mainly confirming if you also have experience that problem.

**Comment by marcoslucianops** [comment]
Yes, I have the same problem in my tests.

**Comment by PonyPC** [comment]
Same problem
