### ISSUE TITLE
GPU based Non-maximum Suppression

### ISSUE THREAD

**Issue by frenky-strasak** [marcoslucianops/DeepStream-Yolo#71]
When number of detected objects per frame is high, Non-maximum Suppression (NMS) is a bottleneck in my case. What is the best way to speed up the NMS? Is there any way to implement GPU based NMS? Thank you!

**Comment by marcoslucianops** [comment]
Is your model YOLOv4 or YOLOv5?

**Comment by frenky-strasak** [comment]
Sorry, I forgot to mention it. My model is yolov4. 
In case of yolov5, is there default GPU based Non-maximum Suppression?

**Comment by marcoslucianops** [comment]
YOLOv4 and YOLOv5 uses CPU NMS.

**Comment by frenky-strasak** [comment]
So what could be the best way to speed up the NMS? Is there any implementation of GPU based NMS?

**Comment by marcoslucianops** [comment]
How many objects are you detecting in one frame?

**Comment by frenky-strasak** [comment]
I tested my deepstream pipeline with own yolov4-csp model fp16 batch=8 (thanks to your repo) on different videos. For videos with less than 30 objects per frame in average, the FPS is stable (80FPS for each identical stream).  For videos with 60 objects per frame in average, the FPS is low (around 30-40 FPS) and unstable (for some videos it goes from 40FPS to 85 FPS to 33 FPS to 84 FPS).

I concluded it is caused by NMS, because all settings (deepstream pipellie, yolov4-csp model) were same for all tested video samples. The only thing that differed in all tested videos was the number of detected objects

I already asked on [https://forums.developer.nvidia.com/t/unstable-performance/181094](https://forums.developer.nvidia.com/t/unstable-performance/181094) and they suggest to use some GPU based NMS.

Could it be caused by slow NMS? Can GPU based NMS help me? 

My PC:
GPU Type: rtx 3090 24Gb
AMD ryzen 5 2600, 6 cores, 12 threads

**Comment by marcoslucianops** [comment]
Are you using a secondary detector or classifier?

**Comment by frenky-strasak** [comment]
I am using the Gst-nvinfer in primary mode.

**Comment by marcoslucianops** [comment]
But, do you have any secondary or tracker after the pgie?

**Comment by frenky-strasak** [comment]
No, I don't.

**Comment by marcoslucianops** [comment]
So, in this case, the NMS could affect the performance. I will look about GPU NMS but I can't set a deadline to it.

**Comment by marcoslucianops** [comment]
Performance comparison

Board: AGX

| CPU NMS | BatchedNMS |
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/47423225/154852357-f58e5db6-67cf-4484-9b5c-a6828e01916c.png) | ![image](https://user-images.githubusercontent.com/47423225/154852333-54865730-84cd-4062-be4e-ab84b560e20d.png) |

**Comment by marcoslucianops** [comment]
> Performance comparison
> 
> Board: AGX Model: YOLOv5n Mode: FP16
> 
> CPU NMS	GPU BatchedNMS	GPU EfficientNMS
> ![image](https://user-images.githubusercontent.com/47423225/154852357-f58e5db6-67cf-4484-9b5c-a6828e01916c.png)	![image](https://user-images.githubusercontent.com/47423225/154852333-54865730-84cd-4062-be4e-ab84b560e20d.png)	![image](https://user-images.githubusercontent.com/47423225/154868049-33be8d72-1818-4028-a4c5-08e9a213e852.png)
