### ISSUE TITLE
Does this external yolov5 v5 plugin support YOLOv5-P6 models?

### ISSUE THREAD

**Issue by luvwinnie** [marcoslucianops/DeepStream-Yolo#72]
The official YOLOv5 repository has released v5 which have some new YOLOv5-P6 models such as yolov5s6.pt,yolov5m6.pt,yolov5l6.pt,yolov5x6.pt. Wondering does this plugin tested with those model?

**Comment by marcoslucianops** [comment]
It's not tested, but it should work.
