### ISSUE TITLE
Changing custom model

### ISSUE THREAD

**Issue by MrGolden1** [marcoslucianops/DeepStream-Yolo#73]
Hi my dear,
I had already followed  your instructions to setup yolo for deepstream.
As you said i put the `config file` and `weights` for yolovd4-tiny in the config_infer_primary.txt and compile it with make.
My network was 320 by 320 it worked fine. But now i want to change my model with new weights and new config. The size of the new network is 608 by 608. I repeat the instruction as well as first one but dosn't change. still when the layers is loading it will print:
```
INFO: [Implicit Engine Info]: layers num: 3
0   INPUT  kFLOAT data            3x320x320       
1   OUTPUT kFLOAT yolo_31         18x10x10        
2   OUTPUT kFLOAT yolo_38         18x20x20    
```

What should i do ?!

**Comment by MrGolden1** [comment]
I got it. I just should to comment `model-engine-file=......` and run the deepstream-app again. It will create the engine automatically 😀

**Comment by marcoslucianops** [comment]
You can just delete the old engine and it will create a new engine again. If you comment the engine line in config_infer file, it will create a new engine whenever you run the deepstream-app command.
