### ISSUE TITLE
Missing cpp headers

### ISSUE THREAD

**Issue by pop134** [marcoslucianops/DeepStream-Yolo#76]
Hello @marcoslucianops, thanks for the great work of yours.
So I follow the steps in the readme file to the native folder
I tried to compile the c++ libs on jetson nano using this command: 
`CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo`
But it seems like some header files are missing for nvdsinfer_yolo_engine.cpp
`
#include "nvdsinfer_custom_impl.h"
#include "nvdsinfer_context.h"
`
and the make command yield errors. Am I missing any steps here or where can I get the header files, thank you.

**Comment by marcoslucianops** [comment]
Which directory is your DeepStream installation?

**Comment by marcoslucianops** [comment]
Change nvdsinfer_custom_impl_Yolo/Makefile line 40:

```
CFLAGS+= -I/opt/nvidia/deepstream/deepstream-5.1/sources/includes -I/usr/local/cuda-$(CUDA_VER)/include
```

to your DeepStream directory

**Comment by pop134** [comment]
Thanks a lot for fast and detailed replies, it worked out.
I'll close this issue
