### ISSUE TITLE
Request for tiny-yolov4

### ISSUE THREAD

**Issue by srikar242** [marcoslucianops/DeepStream-Yolo#8]
Hi @marcoslucianops Can you also put what all we need to configure to run tiny yolov4 and yolov4 model on Deepstream?

**Comment by marcoslucianops** [comment]
> Hi @marcoslucianops Can you also put what all we need to configure to run tiny yolov4 and yolov4 model on Deepstream?

I will try to add soon.

**Comment by marcoslucianops** [comment]
Hi @srikar242, 

I added YoloV4-Tiny configuration for DeepStream on this repository.
See [here](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/YOLOV4-TINY.md)
