### ISSUE TITLE
Use two independent models for detection

### ISSUE THREAD

**Issue by piotlinski** [marcoslucianops/DeepStream-Yolo#80]
I am currently trying to prepare a deepstream app following the `multiple_inferences` instructions. I have a case where I need two models to perform inference on the entire frame (i.e. two PGIEs) and to draw the results on the frame with OSD. However I cannot make the OSD to draw detections from the SGIE, even though the memory is being taken with the secondary GIE enabled; from what I see in DeepStream there is one PGIE and multiple SGIEs, which operate only on detections produced by the PGIE.

Is it possible to make SGIE work like a PGIE? I already tried to change the `process-mode` property to 1, but still, no detections appear in the resulting video.

Here are configs:

`deepstream_app_config.txt`
```cfg
[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=pgie/config_infer_primary.txt

[secondary-gie0]
enable=1
gpu-id=0
gie-unique-id=2
operate-on-gie-id=1
nvbuf-memory-type=0
config-file=sgie1/config_infer_secondary1.txt
```

`config_infer_primary.txt`
```cfg
[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
custom-network-config=pgie/yolo.cfg
model-file=yolo.cfg.weights
model-engine-file=model_b128_gpu0_fp16.engine
#int8-calib-file=calib.table
labelfile-path=labels.txt
batch-size=128
network-mode=2
num-detected-classes=1
interval=0
gie-unique-id=1
process-mode=1
network-type=0
cluster-mode=4
maintain-aspect-ratio=1
parse-bbox-func-name=NvDsInferParseYolo
custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
engine-create-func-name=NvDsInferYoloCudaEngineGet

[class-attrs-all]
pre-cluster-threshold=0.1
```

`config_infer_secondary1 .txt`
```cfg
[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
custom-network-config=sgie1/yolo.cfg
model-file=yolo.weights
model-engine-file=model_b128_gpu0_fp16.engine
#int8-calib-file=calib.table
labelfile-path=labels.txt
batch-size=128
network-mode=2
num-detected-classes=1
interval=0
gie-unique-id=2
process-mode=1
network-type=0
cluster-mode=4
maintain-aspect-ratio=1
parse-bbox-func-name=NvDsInferParseYolo
custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
engine-create-func-name=NvDsInferYoloCudaEngineGet

[class-attrs-all]
pre-cluster-threshold=0.01
```

**Comment by marcoslucianops** [comment]
It's not possible in current deepstream-app version. You can try to do this using a custom python/C++ code (deepstream/gstreamer pipeline).
