### ISSUE TITLE
Support for pp-yolo model

### ISSUE THREAD

**Issue by Justin-king-de** [marcoslucianops/DeepStream-Yolo#83]
Hello @marcoslucianops @satchelwu @pieris98  I have read that pp-yolo gives good accuracy with very good FPS. But how to run pp-yolo model using deepstream SDK. How to convert pp-yolo  model from paddle-paddle framework into deepstream compatible tensorrt model. Can you please help me in implementing this?

**Comment by Justin-king-de** [comment]
@marcoslucianops Okay. But is there any tiny version of YOLOR? Because I have to run it on nano.

**Comment by marcoslucianops** [comment]
> @marcoslucianops Okay. But is there any tiny version of YOLOR? Because I have to run it on nano.

It doesn't have for now. I will see about PP-YOLO.

**Comment by Justin-king-de** [comment]
@marcoslucianops Okay. Thanks. Please let me know when you are able to do it.

**Comment by marcoslucianops** [comment]
I will use these new models in my new projects, so I'm planning to start in next days.

**Comment by Justin-king-de** [comment]
Okay. Sure. I will post a query here about your progress after few weeks or a month.

**Comment by garaujo23** [comment]
> I will use these new models in my new projects, so I'm planning to start in next days.

Hey @marcoslucianops is there any update on YOLOR support for your deepstream repo?

**Comment by marcoslucianops** [comment]
End of year probably @garaujo23.

**Comment by marcoslucianops** [comment]
@garaujo23 Repo updated with native support for YOLOR models (for now, available for YOLOR-CSP, YOLOR-CSP*,YOLOR-CSP-X and YOLOR-CSP-X*).

**Comment by garaujo23** [comment]
@marcoslucianops you are a legend, will do some testing now :)

**Comment by marcoslucianops** [comment]
Added support for PP-YOLOE.
