### ISSUE TITLE
Deserialise engine failed because [model_b1_gpu0_fp32.engine] file missing 

### ISSUE THREAD

**Issue by maheshksingh** [marcoslucianops/DeepStream-Yolo#84]
![image](https://user-images.githubusercontent.com/25975932/131790032-f04e03e7-e615-44d2-930f-3561d7c1d225.png)

model_b1_gpu0_fp32.engine file missing, please see the image for details. Thanks,

**Comment by marcoslucianops** [comment]
It's generated automatically when you run the deepstream-app (for YOLOv2, v3 or v4) and the file doesn't exist. The path for yolov4.cfg is wrong (see the log).

**Comment by marcoslucianops** [comment]
@JangDongMan, you forgot the step 8

8. Change the deepstream_app_config.txt file

```
...
[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary_yolor.txt
```

Change ```config-file=config_infer_primary.txt``` to ```config-file=config_infer_primary_yolor.txt```

**Comment by JangDongMan** [comment]
So, sorry
I miss metion it "YOLOR usage"  I tried  "YOLOv5 usage"
So I forgot step 8. 
[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary_yolov5.txt

then I got error message under.
![image](https://user-images.githubusercontent.com/37603789/154624798-59ec9bb7-e20a-4570-9f1c-123e1947f882.png)

what config file  I  miss  it? 
thanks

**Comment by marcoslucianops** [comment]
@JangDongMan the correct path is ```config_infer_primary_yoloV5.txt```. The 'V' is in uppercase.

**Comment by JangDongMan** [comment]
Thanks for your kindly reply.
and I fixed it and run agian

![image](https://user-images.githubusercontent.com/37603789/154895129-8d646504-2dcf-43a2-9902-02bb40fccaa6.png)

that result are means I got mistake some configures?

![image](https://user-images.githubusercontent.com/37603789/154895269-ecfa4a91-84c1-442b-b78e-5a2d6e61ec11.png)

**Comment by marcoslucianops** [comment]
I saw the error cuGraphicsGLRegisterBuffer failed with error(219). Are you using a physical monitor?

**Comment by JangDongMan** [comment]
Thanks for your reply.
I did test via RealVNC and still connected local monitor and keyboard.
![image](https://user-images.githubusercontent.com/37603789/155059344-44b3397c-db44-4739-8fe9-06cc8b498f9b.png)

obove screen is caputred after by local keyboard and monitor.
Did RealVNC influenced for test result?

thanks a lot.

**Comment by marcoslucianops** [comment]
There's no problem to use RealVNC.

Did you install the requirements as it's in README.md page?

**Comment by JangDongMan** [comment]
Sure I all install for requirements .
[Ubuntu 18.04]
[CUDA 11.4.3]
[TensorRT 8.0 GA (8.0.1)]
[cuDNN >= 8.2]
[NVIDIA Driver >= 470.82.01
[NVIDIA DeepStream SDK 6.0]

What should I check more?
I can not found any soultion in google search.

**Comment by marcoslucianops** [comment]
You can use without the display by change the [sink] type from 2 to 1.

This error is related to OpenGL. It seems missing in your NVIDIA Driver installation, but I'm not sure about it. I recommend you check this specific error in NVIDIA forums.

**Comment by imSrbh** [comment]
@marcoslucianops & team
I noticed with this custom parser:
Every time I see the model engine file is generated with `model_b1_gpu0_fp32.engine` this kind of name.
It's not picking the name which I am providing in` model-engine-file=/path/<somename>.engine`
& The engine is not getting generated in the desired path which I am providing in `model-engine-file` here.

**Comment by marcoslucianops** [comment]
It's a limitation in DeepStream SDK custom parser. The model engine file always will be generated in current path and as model_b{batch-size}_{network-mode}.engine .

**Comment by JangDongMan** [comment]
I did reinstall nvidia driver  ver-470.63.01 
and I rebooted then it auto matically upgrade 470.103.01
So I reinstall and prevent upgrade driver.

I got blelow result.
Monitor connected to onboard RGB port. Server PC is Intel® Server System R2308WFTZS , 2U, zeon cpu. graphic nvidia A4000.
thanks
![image](https://user-images.githubusercontent.com/37603789/156967487-ab2a5687-350f-4de4-9630-fc064239a5d7.png)

**Comment by marcoslucianops** [comment]
Why does it install automatically?

Did you do this step?

#### 3. Disable Nouveau

```
sudo nano /etc/modprobe.d/blacklist-nouveau.conf
```

* Add

```
blacklist nouveau
options nouveau modeset=0
```

* Run

```
sudo update-initramfs -u
```

#### 4. Reboot the computer

```
sudo reboot
```

**Comment by JangDongMan** [comment]
Thanks a lot for your reply.!!


I did not install "nouveau".
so I edit 20auto-upgrades file  like this
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::AutocleanInterval "0";
APT::Periodic::Unattended-Upgrade "0";
then no more driver upgrade.
So I test it driver version "470.63.01" . But result is same.

**Comment by marcoslucianops** [comment]
You don't to install nouveau, you need to blacklist it doing the steps I sent.

**Comment by ingbeeedd** [comment]
@marcoslucianops 

In this storage, I have to create a trt.engine file in advance, right?

**Comment by marcoslucianops** [comment]
No, the engine will be created by the DeepStream when you run it.

**Comment by marcoslucianops** [comment]
It's supported only Darknet for YOLOv4.

**Comment by millionmilk** [comment]
Hello
I got the some problem when I training own yolov5 model.
please see detail as bellow, 
![image](https://user-images.githubusercontent.com/102300282/159920087-f73035d3-ab4e-41f4-b0c3-a64d67f6edf3.png)
![image](https://user-images.githubusercontent.com/102300282/159920259-6fe043e0-75f9-49bb-98d0-41733f81a458.png)

I change all parameters of gpu-id to 1 and batch-size to 16 in deepstream_app_config.txt
what config file I miss it ?
thanks

**Comment by marcoslucianops** [comment]
@millionmilk, please rename your wts and cfg files to yolov5_best and try again.

**Comment by millionmilk** [comment]
@marcoslucianops 
Thanks for you reply
after rename the file name and try again
I found that maybe it's my GPU source problem
Thanks a lot

**Comment by ecardozog** [comment]
Tuve el mismo problema. El error que cometí fué que copié un archivo incorrecto en yolov4.cfg, verifiqué bien, copié el archivo correcto y se ejecutó correctamente.
