### ISSUE TITLE
Is support yolov4-p6?

### ISSUE THREAD

**Issue by amelieko** [marcoslucianops/DeepStream-Yolo#85]
Hi, @marcoslucianops,
I use Yolov4-p6 with DeepStream 5.1 .
I follow the step and use DeepStream-Yolo/native  to generate engine file.
I changed the config_infer_primary.txt and deepstream_app_config.txt to match my setting.
However, after execute , I got error message as below,

deepstream-app: yolo.cpp:361: NvDsInferStatus Yolo::buildYoloNetwork(std::vector<float>&, nvinfer1::INetworkDefinition&): Assertion `0' failed.
Aborted (core dumped)

I have no idea whether the .pt file is not right or  wrong setting.
Or,  yolov6-p6 is not supported now?
Please give me some advise.
Thanks a lot,

**Comment by marcoslucianops** [comment]
You did something wrong, here it works normally.

**Comment by marcoslucianops** [comment]
[yolov4-p6.cfg](https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-p6.cfg)
[yolov4-p6.weights](https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-p6.weights)

**Comment by amelieko** [comment]
Hi, @marcoslucianops ,

I execute this setting and it's work.  Thanks for helping to check,
In my situation is,
I use Pytorch-Scaled-YOLOv4 to build new model. It's work when I do inference use python. 
However, when I generate engine. it still show error message.

Loading pre-trained weights
deepstream-app: utils.cpp:90: std::vector<float> loadWeights(std::__cxx11::string, const string&): Assertion `file.gcount() == 4' failed.
Aborted (core dumped)

maybe the config setting is wrong. 
I have two classes and I modified the cfg. file for four yolo block,( changed parameters: classes=2, filter=24, activation=linear)
Did I miss other settings?
Thanks again.

amelie

**Comment by marcoslucianops** [comment]
Are you using the Darknet model or PyTorch model? The PyTorch model isn't supported for now.

**Comment by amelieko** [comment]
Ohhhh....That's why I can't execute my model because I use Pytorch model.
anyway, thank you very much.
