### ISSUE TITLE
inference speed is very slow

### ISSUE THREAD

**Issue by amelieko** [marcoslucianops/DeepStream-Yolo#86]
Hi @marcoslucianops 
I do inference on Jetson AGX but inference speed is so slow

=======================================
use FP32 or FP16 , I got  the same speed

Opening in BLOCKING MODE
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
** INFO: <bus_callback:167>: Pipeline running

**PERF:  2.30 (2.28)	
**PERF:  2.26 (2.24)	
**PERF:  2.30 (2.22)	
**PERF:  2.30 (2.27)	
**PERF:  2.30 (2.26)	
....
===================
My environment as below,
use  ScaledYolov4-P6 ( use darknet )
Jetpack: 4.5
Deepstream: 5.1

===================
deepstream_app_config.txt, use original setting is the follow  value. 
config_infer_primary.txt,  I changed classes and replace model to meet my model.

Have any suggestion for speed up inference? or some setting I missed?
Thank you very much.

**Comment by marcoslucianops** [comment]
Run these commands on the Jetson to boost the performance

```
sudo nvpmodel -m 0
sudo jetson_clocks
```

**Comment by amelieko** [comment]
Thanks for replied, After I tested,

For FP32,
----------------------------------- 
When Mode 30W ALL, the speed around 1.xx
**PERF:  FPS 0 (Avg)	
**PERF:  0.00 (0.00)	
** INFO: <bus_callback:181>: Pipeline ready

** INFO: <bus_callback:167>: Pipeline running

**PERF:  1.48 (1.43)	
**PERF:  1.53 (1.41)	
===============================================
After run two commands,
When set MAXN, 
For FP32: 
-----------------------------------
**PERF:  FPS 0 (Avg)	
**PERF:  0.00 (0.00)	
** INFO: <bus_callback:181>: Pipeline ready

** INFO: <bus_callback:167>: Pipeline running

**PERF:  2.29 (2.25)	
**PERF:  2.30 (2.22)	
**PERF:  2.30 (2.28)	
**PERF:  2.22 (2.26)	

For FP16:
-----------------------------------
**PERF:  FPS 0 (Avg)	
**PERF:  0.00 (0.00)	
** INFO: <bus_callback:181>: Pipeline ready

** INFO: <bus_callback:167>: Pipeline running

**PERF:  6.68 (6.50)	
**PERF:  6.83 (6.75)	
**PERF:  6.86 (6.77)	
**PERF:  6.86 (6.78)	
**PERF:  6.81 (6.78)	
=====================
the speed doesn't improve enough. 
so wried..
As below is setting I used. Have any idea for setting?
Thanks,

=============================================================
my config_infer_primary.txt as below, ( use FP16 and  1 class )
------------------------------------------------------------------
for FP16, 1 classes, 

[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
custom-network-config=yolov4-p6.cfg
model-file=yolov4-p6.weights
model-engine-file=yolov4-p6_fp16.engine
#int8-calib-file=calib.table
labelfile-path=labels.txt
batch-size=1
network-mode=2
num-detected-classes=1
interval=0
gie-unique-id=1
process-mode=1
network-type=2
cluster-mode=4
maintain-aspect-ratio=1
parse-bbox-func-name=NvDsInferParseYolo
custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
engine-create-func-name=NvDsInferYoloCudaEngineGet

[class-attrs-all]
pre-cluster-threshold=0.5
# pre-cluster-threshold=0.25

------------------------------------------------------------------
deepstream_app_config.txt  ==> just use original setting, only replace path for video file.
------------------------------------------------------------------
[application]
enable-perf-measurement=1
perf-measurement-interval-sec=5

[tiled-display]
enable=1
rows=1
columns=1
width=1280
height=720
gpu-id=0
nvbuf-memory-type=0

[source0]
enable=1
type=3
uri=file:///home/ubuntu/Downloads/1.mp4
# uri=file:///opt/nvidia/deepstream/deepstream-5.1/samples/streams/sample_1080p_h264.mp4
num-sources=1
gpu-id=0
cudadec-memtype=0

[sink0]
enable=1
type=2
sync=0
source-id=0
gpu-id=0
nvbuf-memory-type=0

[osd]
enable=1
gpu-id=0
border-width=1
text-size=15
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Serif
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0
nvbuf-memory-type=0

[streammux]
gpu-id=0
live-source=0
batch-size=1
batched-push-timeout=40000
width=1920
height=1080
enable-padding=0
nvbuf-memory-type=0

[primary-gie]
enable=1
gpu-id=0
gie-unique-id=1
nvbuf-memory-type=0
config-file=config_infer_primary.txt

[tests]
file-loop=0

**Comment by marcoslucianops** [comment]
This model is very heavy, I think this is the correct performance for this board

**Comment by amelieko** [comment]
Because of model? No way to improve? 
But Yolov4-p6 is used for large image, right?  
That's why I choose this. Now, I got conflict.  Why??
Would you please explain more clear?  
Thanks,

**Comment by marcoslucianops** [comment]
![image](https://user-images.githubusercontent.com/47423225/134174671-d2a85b2d-cc7c-40c3-ad7b-9d223a482166.png)

**Comment by amelieko** [comment]
Thanks for replied. I understood the reason. Thanks a lot. 😬 👍
