### ISSUE TITLE
ERROR - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)

### ISSUE THREAD

**Issue by This-Is-Not-Brad** [marcoslucianops/DeepStream-Yolo#87]
Hi there,

Trying to run a Yolov4-Tiny demo on a Jetson Xavier NX. Encountering the following error.

`brad@brad-xavier:~/nvme/DeepStream-Yolo/native$ deepstream-app -c deepstream_app_config.txt

(deepstream-app:10651): GLib-GObject-WARNING **: 14:30:54.317: g_object_set_is_valid_property: object class 'avenc_mpeg4' has no property named 'bufapi-version'
WARNING: [TRT]: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
Deserialize yoloLayer plugin: yolo_31
Deserialize yoloLayer plugin: yolo_38
0:00:04.251287881 10651      0x571f410 INFO                 nvinfer gstnvinfer.cpp:619:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1702> [UID = 1]: deserialized trt engine from :/home/brad/nvme/DeepStream-Yolo/native/model_b1_gpu0_fp32.engine
INFO: [Implicit Engine Info]: layers num: 3
0   INPUT  kFLOAT data            3x416x416       
1   OUTPUT kFLOAT yolo_31         255x13x13       
2   OUTPUT kFLOAT yolo_38         255x26x26       

0:00:04.251546347 10651      0x571f410 INFO                 nvinfer gstnvinfer.cpp:619:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1806> [UID = 1]: Use deserialized engine model: /home/brad/nvme/DeepStream-Yolo/native/model_b1_gpu0_fp32.engine
0:00:04.258473488 10651      0x571f410 INFO                 nvinfer gstnvinfer_impl.cpp:313:notifyLoadModelStatus:<primary_gie> [UID 1]: Load new model:/home/brad/nvme/DeepStream-Yolo/native/config_infer_primary.txt sucessfully

Runtime commands:
        h: Print this help
        q: Quit

        p: Pause
        r: Resume

NOTE: To expand a source in the 2D tiled display and view object details, left-click on the source.
      To go back to the tiled display, right-click anywhere on the window.

** INFO: <bus_callback:181>: Pipeline ready

Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
** INFO: <bus_callback:167>: Pipeline running

**ERROR: [TRT]: ../rtSafe/safeContext.cpp (133) - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)
ERROR: [TRT]: FAILED_EXECUTION: std::exception
ERROR: Failed to enqueue inference batch
ERROR: Infer context enqueue buffer failed, nvinfer error:NVDSINFER_TENSORRT_ERROR`**

My config_infer_primary.txt is as follows:

`[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
custom-network-config=yolov4-tiny.cfg
model-file=yolov4-tiny.weights
model-engine-file=model_b1_gpu0_fp32.engine
#int8-calib-file=calib.table
labelfile-path=labels.txt
batch-size=1
network-mode=0
num-detected-classes=80
interval=0
gie-unique-id=1
process-mode=1
network-type=0
cluster-mode=4
maintain-aspect-ratio=0
parse-bbox-func-name=NvDsInferParseYolo
custom-lib-path=nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
engine-create-func-name=NvDsInferYoloCudaEngineGet

[class-attrs-all]
pre-cluster-threshold=0.25`

**Comment by marcoslucianops** [comment]
Are you using the JetPack?

**Comment by This-Is-Not-Brad** [comment]
> Are you using the JetPack?

Yes I am.

# R32 (release), REVISION: 4.4, GCID: 23942405, BOARD: t186ref, EABI: aarch64, DATE: Fri Oct 16 19:37:08 UTC 2020
