### ISSUE TITLE
ERROR: [TRT]: ../rtSafe/cuda/caskConvolutionRunner.cpp (373) - Cask Error in checkCaskExecError<false>: 7 (Cask Convolution execution)

### ISSUE THREAD

**Issue by mk123qwe** [marcoslucianops/DeepStream-Yolo#88]
Dear friend
jetson nano
jetpack # R32 (release), REVISION: 4.4, GCID: 23942405, BOARD: t210ref, EABI: aarch64, DATE: Fri Oct 16 19:44:43 UTC 2020
cuda release 10.2, V10.2.89
testing model yolov5s

ERROR: [TRT]: ../rtSafe/cuda/caskConvolutionRunner.cpp (373) - Cask Error in checkCaskExecError<false>: 7 (Cask Convolution execution)
ERROR: [TRT]: FAILED_EXECUTION: std::exception
ERROR: Failed to enqueue inference batch
ERROR: Infer context enqueue buffer failed, nvinfer error:NVDSINFER_TENSORRT_ERROR
0:00:05.095316960 12432     0x1f700680 WARN                 nvinfer gstnvinfer.cpp:1225:gst_nvinfer_input_queue_loop:<primary_gie> error: Failed to queue input batch for inferencing
ERROR: Failed to make stream wait on event, cuda err_no:4, err_str:cudaErrorLaunchFailure
ERROR: Preprocessor transform input data failed., nvinfer error:NVDSINFER_CUDA_ERROR
0:00:05.095537901 12432     0x1f700680 WARN                 nvinfer gstnvinfer.cpp:1225:gst_nvinfer_input_queue_loop:<primary_gie> error: Failed to queue input batch for inferencing
ERROR: Failed to make stream wait on event, cuda err_no:4, err_str:cudaErrorLaunchFailure
ERROR: Preprocessor transform input data failed., nvinfer error:NVDSINFER_CUDA_ERROR

thanks!

**Comment by marcoslucianops** [comment]
It seems something related to your JetPack prebuilt libs (CUDA/TensorRT).
