### ISSUE TITLE
Image size in config file for training yolov4

### ISSUE THREAD

**Issue by shubham-shahh** [marcoslucianops/DeepStream-Yolo#9]
first of all thanks for such a great repo to explain how to run yolov3 tiny with the deepstream. I am training a yoloV4 and the image size for training I have is 150(width)x80(height) to 600(width)x150(height). my config file contains height and width = 416x416. so is that a correct size or shall I change the size in the config file based on my image size? does yolo resize the image while keeping the aspect ratio constant in training?

thanks once again

**Comment by marcoslucianops** [comment]
> I change the size in the config file based on my image size? does yolo resize the image while keeping the aspect ratio constant in training?

Yolo resizes all images to 416x416 to make inference. It doesn't keep the aspect ratio.
