### ISSUE TITLE
Do you have code for YoloV3 integration as well?

### ISSUE THREAD

**Issue by rajeshroy402** [marcoslucianops/DeepStream-Yolo#92]
Hey, what part will change if I want to integrate Yolov3 with the standard weight and cfg file with DS-5.1, is there a working walkthrough available for that as well? Thanks!

**Comment by marcoslucianops** [comment]
Solved

**Comment by linhdb-2149** [comment]
@marcoslucianops I encoutered the same error with yolov5
```
** ERROR: main:655: Failed to set pipeline to PAUSED
Quitting
ERROR from src_bin_muxer: Output width not set
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvmultistream/gstnvstreammux.c(2512): gst_nvstreammux_change_state (): /GstPipeline:pipeline/GstBin:multi_src_bin/GstNvStreamMux:src_bin_muxer
App run failed
```

**Comment by neilyoung** [comment]
I'm also facing this "ERROR from src_bin_muxer: Output width not set". What to do with this?

**Comment by marcoslucianops** [comment]
@neilyoung your `deepstream_app_config.txt` is missing properties. Please check with the file provided in this repo.

**Comment by neilyoung** [comment]
@marcoslucianops Yes, thanks for the pointer. Meanwhile I managed that. Thanks
