### ISSUE TITLE
why to use yololayer.cu and yololayer.h

### ISSUE THREAD

**Issue by ButlelyGuru** [marcoslucianops/DeepStream-Yolo#94]
hello marcoslucianops,, 
first thanks for your github project to use yolo and deepstream with kind explanation.

but i have a question about using <nvdsinfer_custom_impl_Yolo>
so,  i already transfer yolov5 model to yolov5 tensorrt and i confirm it did well on my jetson nano. 
but when trying to use this tensorrt model with deepstream framework you put **yololayer.cu and yololayer.h** on <nvdsinfer_custom_impl_Yolo>. i think since i transfer model to tensorRT then we don't need to use **yololayer.cu and yololayer.h** any more.. pls explain me why to use **yololayer.cu and yololayer.h**..

**Comment by marcoslucianops** [comment]
I don't remember why, but I'm working now on native support for YOLOv5 in DeepStream 6.0.

**Comment by marcoslucianops** [comment]
Did it work without these files?

**Comment by ButlelyGuru** [comment]
Nope, without those files, it doesn't work due to Postprocessing layer.. In those files, it overrides custom layer function in tensorRT engine file, so it is essential to run yolov*.cu to run deepstream or tensorrt engine on your system.
