### ISSUE TITLE
Deepstream-6.0 support

### ISSUE THREAD

**Issue by shekarneo** [marcoslucianops/DeepStream-Yolo#95]
Hi,

happy to see this repo and is this supports deepstream 6.0.

i tried to make CUDA_VER=11.4 make -C nvdsinfer_custom_impl_Yolo it gave numerous errors

**Comment by marcoslucianops** [comment]
I finishing the update and I will update the repo in few days for the DeepStream 6.0

**Comment by shekarneo** [comment]
Thanks for the update

**Comment by marcoslucianops** [comment]
I've updated the repo, new features will be added soon.

**Comment by shekarneo** [comment]
Awesome, thanks for the update!
