### ISSUE TITLE
Make error: 'createReorgPlugin' was not declared in this scope; did you mean 'reorgPlugin'?

### ISSUE THREAD

**Issue by SimonRenu** [marcoslucianops/DeepStream-Yolo#98]
yolo.cpp:337:48: error: 'createReorgPlugin' was not declared in this scope; did you mean 'reorgPlugin'?
  337 |             nvinfer1::IPluginV2* reorgPlugin = createReorgPlugin(2);
         |                                              ^~~~~~~~~~~~~~~~~
         |                                              reorgPlugin
make: *** [Makefile:78: yolo.o] Error 1

**Comment by marcoslucianops** [comment]
Check the requirements in the README.md file.

**Comment by SimonRenu** [comment]
Thanks for answer.
For information, I was using the X86 docker images Deepstream 6 Triton. 
With the develop image, it is working.

**Comment by SimonRenu** [comment]
> Check the requirements in the README.md file.

With docker image L4T (for jetson), it doesn't seem to work ...

**Comment by marcoslucianops** [comment]
For the Triton image, you need to comment the lines 336 to 351 in the yolo.cpp file.

**Comment by shekarneo** [comment]
Hi could you tell exact line numbers, because those lines looks wrong 

```
                modelType = 2;
            }
            if (m_ConfigBlocks.at(i).find("new_coords") != m_ConfigBlocks.at(i).end()) {
                newCoords = std::stoi(m_ConfigBlocks.at(i).at("new_coords"));
            }
            if (m_ConfigBlocks.at(i).find("scale_x_y") != m_ConfigBlocks.at(i).end()) {
                scaleXY = std::stof(m_ConfigBlocks.at(i).at("scale_x_y"));
            }

            std::string layerName = "yolo_" + std::to_string(i);
            nvinfer1::Dims prevTensorDims = previous->getDimensions();
            TensorInfo& curYoloTensor = m_OutputTensors.at(outputTensorCount);
            m_NumClasses = curYoloTensor.numClasses;
            curYoloTensor.blobName = layerName;
            nvinfer1::IPluginV2* yoloPlugin
                = new YoloLayer(curYoloTensor.numBBoxes, curYoloTensor.numClasses, m_InputW, m_InputH,
```

**Comment by marcoslucianops** [comment]
@shekarneo, lines 371-397 in current repo version.

**Comment by JasonChao-yue** [comment]
Can you tell me the line number of the current version? I have the same problem

**Comment by marcoslucianops** [comment]
You need to comment/remove this part (lines 288-294)

```
nvinfer1::IPluginV2* reorgPlugin = createReorgPlugin(2);
assert(reorgPlugin != nullptr);
nvinfer1::IPluginV2Layer* reorg = network.addPluginV2(&previous, 1, *reorgPlugin);
assert(reorg != nullptr);
std::string reorglayerName = "reorg_" + std::to_string(i);
reorg->setName(reorglayerName.c_str());
previous = reorg->getOutput(0);
```

**Comment by JasonChao-yue** [comment]
@marcoslucianops  Thank you for your answer！
 I was using the X86 docker image deepstream:6.1.1-triton.
Used in yolov5.
